### ISSUE TITLE
Use of `with-out-str` with `println` omits certain newlines

### ISSUE THREAD

**Issue by cigitia** [bhauman/lein-figwheel#100]
The `cljs.core` macro `with-out-str` omits certain newlines when run while Figwheel is active.

    (with-out-str (println "A") (println "B"))

…will unexpectedly return `"AB"` instead of `"A\nB\n"`. When Figwheel is *not* running, the line above will expectedly return `"A\nB\n"` instead.

The omission only occurs for the extra newline that `println` adds and does not occur for `"\n"` that string arguments to `println` contain themselves.

    (with-out-str (println "A\n") (println "B\n")) ; returns `"A\nB\n"` when Figwheel is running
    (with-out-str (print "A\n") (print "B\n")) ; returns `"A\nB\n"` when Figwheel is running

This behavior was discovered while using `with-out-str` to capture text printed by `cljs.test/run-tests` while Figwheel was running.

**Comment by bhauman** [comment]
Are you running this inside of the REPL?

**Comment by cigitia** [comment]
Ah, thanks for the reply—I've tried it in both inside regular source code and inside the REPL. Are you having trouble reproducing it outside of the REPL? I can try making a project demonstrating the behavior.

**Comment by bhauman** [comment]
Can you do some testing to see if cljs.core/*print-newline* is set to false?  Also can you let me know what version of Figwheel you are using?

**Comment by bhauman** [comment]
That's `*print-newline*`
I'm on my phone

**Comment by cigitia** [comment]
Aha, yes, `cljs.core/*print-newline*` is `false`. This weirdly appears to be [due to the current behavior of `cljs.core/enable-console-print!`](https://github.com/clojure/clojurescript/blob/958580b5a6daf40e31f4e9f30bdb0ca333dab1be/src/cljs/cljs/core.cljs#L59), which, of course, my project is using. I’m using `figwheel 0.2.5-SNAPSHOT`.

Disabling newlines at the end whenever console printing is enabled—this appears to be a deliberate decision for ClojureScript itself, albeit one that puzzles me greatly, since it messes up `with-out-str`. Does this mean that this bug would be a ClojureScript problem and that it falls outside the scope of Figwheel?

**Comment by cigitia** [comment]
I’ve determined that this bug is a problem with ClojureScript itself rather than Figwheel; thank you.
