### ISSUE TITLE
Non-snapshot release

### ISSUE THREAD

**Issue by weavejester** [bhauman/lein-figwheel#101]
Is there a chance of a non-snapshot release? It would be nice to be able to be able to use a particular version of the lein-figwheel plugin without worrying about the code changing between uses.

**Comment by bhauman** [comment]
What a unreasonable request.  Just at so you know all previous SNAPSHOTs are stable.  But I will cut a 2.5.0 release. 

Seems like it's time.

**Comment by weavejester** [comment]
Why is it an unreasonable request?

Snapshots are designed to be mutable, unstable builds of a release in progress. You can continually update a snapshot without changing its version number, so a snapshot dependency may work one day, but not the next. By default, Leiningen automatically checks for new snapshots each day.

Non-snapshot releases are immutable, and cannot (easily) be updated after they've been committed to a package repository. So a non-snapshot release is guaranteed to work the same way one day to the next, and Leiningen will only download each release once.

If your previous snapshot releases are stable, then they don't need to be snapshots, they can just be normal releases. By marking them as snapshots you're telling people to expect the releases to change from day to day.

**Comment by bhauman** [comment]
OMG I was kidding, sorry about that.  I forgot the wink face.

I'm on vacation and responding from my phone.

**Comment by bhauman** [comment]
I absolutely agree.

**Comment by weavejester** [comment]
Ohh! Without the wink I completely misunderstood the tone of the message. Enjoy your vacation!

**Comment by bhauman** [comment]
Just released 0.2.5 release.
