### ISSUE TITLE
the SHA1 files for 2.5 seem wrong on clojars

### ISSUE THREAD

**Issue by ianphs** [bhauman/lein-figwheel#105]
SHA1 results:

lein-figwheel-0.2.5
    calculated: 5afe50f54e1f59ac5bd1f695a1b01d72701e3488
    on clojars: cc03b244fcb7f867a6d2917219a7400d28d6a2b5

figwheel-0.2.5
  calculated: f478b325d4c85b1ed2be7c98cf2c650b2e1638b7
  on clojars: a6dcd57241dbe12af02883a5f1a895b631e1af8e

**Comment by bhauman** [comment]
Yeah that was a bad deploy. I'm in a hotel with a horrible internet connection in the mountains of Utah.  I won't be able to release until the end of the week when I get home.

Sorry for the confusion.

**Comment by ianphs** [comment]
Not a problem. Thank you for all your work on figwheel.

**Comment by bhauman** [comment]
The bad deploy has been deleted from clojars.
