### ISSUE TITLE
NullPointerException when :id for build is not set?

### ISSUE THREAD

**Issue by ajoberstar** [bhauman/lein-figwheel#106]
Using 0.2.5, having a single element array of cljsbuild builds where that build doesn't have an :id, I get a NPE on `lein figwheel`. Adding an `:id` fixed it for me. I can try to put together some reproducible, if needed.

**Comment by bhauman** [comment]
Thanks, I'll look into it.  The system really needs the ids because of its capacity to build multiple builds at once.  I can either enforce their presence or generate temp-ids.

**Comment by ajoberstar** [comment]
Thanks for the quick response. I'm fine with either. This was my first use of cljs and figwheel so a NPE causes a lot of head scratching.

**Comment by bhauman** [comment]
There will be more for sure ;) Take it slowly, don't start with any frameworks.  Just write some code.  Pay attention to JavaScript inter-op. It's really worth the investment though.  

I do suggest learning React and writing React code straight (in cljs) and then using Sablono with it,  once that is working for you then look into Reagent or Om.

And when you are really getting into it read core.cljs: https://github.com/clojure/clojurescript/blob/master/src/cljs/cljs/core.cljs

Good luck!

**Comment by ajoberstar** [comment]
Thanks!

**Comment by bhauman** [comment]
Finally pushed a fix for this.

https://github.com/bhauman/lein-figwheel/commit/ba4b1a992b818cc0c04e27df96a1e316a5534209

**Comment by ajoberstar** [comment]
Cool. Thanks!
