### ISSUE TITLE
`(add-deps [reagent "0.5.0"])` causes compile error from missing cljsjs.react namespace

### ISSUE THREAD

**Issue by xeqi** [bhauman/lein-figwheel#109]
## Reproduction
```
$ lein new figwheel ex
$ cd ex
$ sed -i 's/-SNAPSHOT//' project.clj   #Use figwheel 0.2.5
$ lein figwheel
Wait for compile and connect browser

In figwheel cljs repl
> (add-dep [reagent "0.5.0"])

Edit src/ex/core.cljs and add (:require [reagent.core :as reagent])
```

## Output
Red info box:
```
clojure.lang.ExceptionInfo : failed compiling file:src/ex/core.cljs
clojure.lang.ExceptionInfo : No such namespace: cljsjs.react, could not locate cljsjs/react.cljs at line 2 file:/home/xeqi/.m2/repository/reagent/reagent/0.5.0/reagent-0.5.0.jar!/reagent/core.cljs
```

## Notes

Continues to occur with clojurescript version 0.0.3119.

**Comment by bhauman** [comment]
This means that straight up pomegranate add-dependency didn't work which happens quite often.  This is not surprising at all.  This problem is external to figwheel

**Comment by xeqi** [comment]
> pomegranate add-dependency didn't work which happens quite often

This surprises me.  I've never had pomegranate just fail silently before.  I would have expected it to be something related to the cljs compile and classloader (ala [CLJS-1036](http://dev.clojure.org/jira/browse/CLJS-1036)).

I'll be happy to look further into this one.

**Comment by bhauman** [comment]
It might not be failing silently. The output is probably going somewhere else.

**Comment by cichli** [comment]
Is it because `get-upstream-deps` is memoized [here](https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/closure.clj#L1221)?

**Comment by swannodette** [comment]
@cichli that's probably the problem, this is probably a good candidate for moving into one of the public `api` namespaces w/ no option to supply classloader (doing so is nearly always wrong) and extra argument to bypass cache.

**Comment by cichli** [comment]
Hmm, as far as I can tell neither figwheel nor clojurescript-build calls `get-upstream-deps` directly - would it be better to have a separate function for resetting the cache that figwheel could call after loading in the new dependency? Or if the bypass cache argument also caused the cache to reset, figwheel could call `get-upstream-deps` purely for that side effect. I'll create a JIRA ticket either way.

**Comment by swannodette** [comment]
@cichli not going to add any apis around cache invalidation. @bhauman will have to explain what figwheel needs, but this just seems like a case where figwheel should deal with upstream deps itself, supporting loading new JARs on the classpath on the fly is not in scope for ClojureScript itself.

**Comment by xeqi** [comment]
Ended up writing a standalone `build.clj` that exhibits the caching:: https://gist.github.com/xeqi/21fc5ab3e244d98d4199.

Upstream issue: [CLJS-1141](http://dev.clojure.org/jira/browse/CLJS-1141).

**Comment by bhauman** [comment]
I will comment here and on the upstream issue.

I don't see this as an urgent issue. More of a nice to have. There is apparently a work around for this along the lines of

https://github.com/cemerick/piggieback/commit/966c811ab817df0e818404943c473081337b286e

where we will just refresh the compiler env's `:ups-*` keys with data from `get-upstream-deps*` 

As far as the compiler is concerned
It may be nice to add an api method that takes a compiler env and updates the `:ups-*` keys.  This could be helpful for tool makers in the short term.  

@swannodette: 
But maybe instead of caching `get-upstream-deps` in memory we could cache it in the *compiler-env* thus keeping all compiler build based state in one place. Then invalidation is consistent destroy the compiler-env or remove `:ups-*` keys and you get fresh compile.  This incurs an initial cost for multiple builds, but not much at all.

**Comment by swannodette** [comment]
@bhauman fantastic idea to unify caching to leverage the same mechanism instead of doing things differently. Happy to take a patch that drops `memoize` completely for that :)

**Comment by bhauman** [comment]
I'll take a stab at it :)

**Comment by bhauman** [comment]
I created a pull request to CLJS to address this.

http://dev.clojure.org/jira/browse/CLJS-1141

I don't see it being a big priority. There are some issues with my implementation. I'm not happy with my use of resolve-ns to get around the a mutual dependency.  It works but ...

**Comment by ricardojmendez** [comment]
I believe I'm tripping this. Should it still be an issue? What's the workaround?

**Comment by lprefontaine** [comment]
I have it too with any release after 1.7.145 with every other dependencies up to date.
Not an emergency from my end. 145 works well.

**Comment by bhauman** [comment]
Sorry but this feature is going away.  I have excluded it from the 0.5.0-SNAPSHOT just too costs too much for such spotty convenience.  Maybe this will work better in the future but for now I'm excluding it.  

If you have a Clojure REPL you can rig this up readily.
