### ISSUE TITLE
Rails & Munging

### ISSUE THREAD

**Issue by JulianLeviston** [bhauman/lein-figwheel#113]
Is there any way to introduce a small time between when files are compiled and when the browser is told to reload them?

Using asset pipeline with Rails (sadly), figwheel and Reagent, I ocassonally see munged files which can be re-forced by recompiling a few times (hitting save a few times). This seems to be as a result of a mis-sync between figwheel thinking the file is ready (because it wrote it) and telling the browser, but Rails isn't  ready to serve it (because it hasn't preprocessed it and cached it yet, or something). This is just my guess though. If you understand what this issue might be, or if I'm doing or not doing something I should be, please let me know.

**Comment by bhauman** [comment]
Are you using :repl false in your :figwheel configuration?

**Comment by JulianLeviston** [comment]
no... should I be?

**Comment by bhauman** [comment]
No you shouldn't be. Now the asset pipeline copies files into place right? I've forgotten.

There is a delay parameter I think let me find it for you.

**Comment by bhauman** [comment]
Yeah :compile-wait-time its originally set at 10 milliseconds. You add it to the :Figwheel config.

**Comment by JulianLeviston** [comment]
I’m actually not sure what the asset pipeline does. It’s fairly opaque. I think it just serves them, but I think it’s getting them before figwheel has finished writing them or something. It’s very weird. I’m hoping setting a 1 or 2 second delay will just fix it, but I don’t understand what’s going on, or how to find out.

http://www.getcontented.com.au/ - You Need GetContented - Get Your Website On. :)

**Comment by JulianLeviston** [comment]
nice! that totally worked… 50 miliseconds. Thanks.. I *LOVE* figwheel by the way. 

http://www.getcontented.com.au/ - You Need GetContented - Now it's easy to run a website.

**Comment by bhauman** [comment]
Does your editor have auto save enabled?

**Comment by JulianLeviston** [comment]
No, no autosave...
