### ISSUE TITLE
Dependent namespaces not reloaded beginning in 0.2.5-SNAPSHOT

### ISSUE THREAD

**Issue by bhagany** [bhauman/lein-figwheel#114]
I've created a repository with a minimal repro here: https://github.com/bhagany/figwheel-dependent

There are two namespaces; `figwheel-dependent.dev` depends on `figwheel-dependent.debug`.  Under 0.2.4-SNAPSHOT, when you save debug.cljs, both debug.cljs and dev.cljs are reloaded.  Under 0.2.5-SNAPSHOT, only debug.cljs is reloaded.

I'm unsure if this is expected behavior, but it seems to me that the 0.2.4-SNAPSHOT behavior is correct, and the changelog doesn't indicate intentional changes to this post-0.2.4-SNAPSHOT.

**Comment by bhagany** [comment]
Okay, it looks like :recompile-dependents is being newly defaulted to false in figwheel.  Manually setting it to true in the cljsbuild config restores the 0.2.4-SNAPSHOT behavior.  I'm curious as to the reason for defaulting to false when the compiler defaults to true?

I'd close the issue, but I'm not entirely sure you'll see this question if I do.  Feel free.

**Comment by bensu** [comment]
For more info on Figwheel and `:recompile-dependents` look at #88 and #92. There you'll see the downsides of having it default to true.

**Comment by bhagany** [comment]
Okay, got it.  Looks like I started using Figwheel in earnest in the brief window after :recompile-dependents was added to Clojurescript, and before Figwheel changed the default, which made that behavior the baseline in my head.  Thanks!
