### ISSUE TITLE
How to work with multimethods?

### ISSUE THREAD

**Issue by sp3ctum** [bhauman/lein-figwheel#117]
I'd like to try setting up sente event handlers with multimethods.
Are they supported? I can see some changes if I `(def my-multi-method nil)`
before re-declaring the multimethod, but it seems both the old
multimethod and the new one being reloaded run.

Reloading my app's web page manually ends up only using the new
implementation, as expected.

Here's a snippet with something I'm trying out:

```lisp
(def chat-event-dispatcher nil)
(defmulti chat-event-dispatcher first)
(defmethod chat-event-dispatcher :default [event]
  (print "unknown server event" (:id event)))

(defmethod chat-event-dispatcher :server/send-new-messages
  [[_event-id {:keys [data]}] event]
  (print "old implementation")
  (swap! update-in app-state [:messages] #(concat % data)))

```

If I change "old implementation" to "new implementation" both
multimethods are ran with the file being saved.

**Comment by bhauman** [comment]
Mark more than likely you are adding new handlers to the channel events on
save.

Or you are passing the dispatch handler by value to sente.  Or a number of
things, but I can't tell anything from the code you have given me.

**Comment by sp3ctum** [comment]
Ah those are good suggestions. I'll review my code.
I take it multimethods are supported then?
27.3.2015 16.15 kirjoitti "Bruce Hauman" <notifications@github.com>:

**Comment by cichli** [comment]
`defmulti` has the same semantics as `defonce` - see [CLJ-900](http://dev.clojure.org/jira/browse/CLJ-900). I think you can just extract the implementation out into a separate function to make it reloadable.

**Comment by bhauman** [comment]
figwheel does nothing special for multimethods.  You have to be aware of their loading semantics.  They actually don't have `defonce` behavior right now.  http://dev.clojure.org/jira/browse/CLJS-1175

**Comment by sp3ctum** [comment]
Yep, looks like you guys were right. My problem was I had a sente-setup function to which I passed my chat-event-dispatcher. I removed the argument and hard coded the dependency to this specific function. Now it looks like I can just change the multimethod in place and figwheel reloads the new code immediately, like I expected it to.
Awesome! :)
