### ISSUE TITLE
Browser HUD and console don't display line numbers on compilation error

### ISSUE THREAD

**Issue by nicolashery** [bhauman/lein-figwheel#125]
Using:

```clojure
[org.clojure/clojure "1.6.0"]
[org.clojure/clojurescript "0.0-3058"]
[figwheel "0.2.6"]
[lein-cljsbuild "1.0.5"]
[lein-figwheel "0.2.6"]
```

I don't see the line number of the compilation error (and can't see the error in `figwheel_server.log` for that matter) in the browser:

![screen shot 2015-04-15 at 5 30 49 pm](https://cloud.githubusercontent.com/assets/1306536/7169633/582c31cc-e395-11e4-99be-63146d0754b8.png)

If I run `lein cljsbuild once` manually, the compilation error shows up as:

```text
...
Caused by: clojure.lang.ExceptionInfo: Map literal must contain an even number of forms {:column 23, :line 10, :file "/Users/nicolashery/Projects/outfolio-clj/src/cljs/outfolio/cards.cljs", :type :reader-exception}
...
```

Might it be the ClojureScript version I'm using having a different error format? I see the regex using "at line" in [support/src/figwheel/client/heads_up.cljs](https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client/heads_up.cljs):

```clojure
(defn file-and-line-number [msg]
  (when (re-matches #".*at\sline.*" msg)
    (take 2 (reverse (string/split msg " ")))))
```

**Comment by bhauman** [comment]
This is a bug.  I will happily take a patch for it.  Just haven't gotten around to it.

Also, I need to make sure these errors are getting printed to the figwheel_server.log as well.  Maybe file that as a separate issue.

On another note, I am going to be in Montreal for all of May.  Is there a local Clojure or FP, or JS group that would enjoy having me come speak? Thats great if there isn't, just want to make sure I'm doing my evangelism properly.

**Comment by nicolashery** [comment]
I'm quite the beginner in Clojure(Script), but if it's a small bug I may try to see if I can fix it...

Thanks for offering to speak here in Montreal! There is a small Clojure group (["Bonjure" mailing list](https://groups.google.com/forum/#!forum/montreal-clojure-user-group)), and we recently tried to expand it to a more general FP group ([Lambda Lounge Montreal](http://www.meetup.com/Lambda-Lounge-Montreal/)). I'm sure the members will enjoy hearing you speak! :) Feel free to drop a message on the mailing list or Meetup group, or I can do it for you if you'd like.
