### ISSUE TITLE
"undefined is not a function", using advanced compilation

### ISSUE THREAD

**Issue by arohner** [bhauman/lein-figwheel#126]
Using figwheel 0.2.6, with `:optimizations :advanced` results in "undefined is not a function". I was previously on 0.2.2-SNAPSHOT, which worked just fine. 

The line that fails, with :pretty-names turned on is:

`$cljs$core$constant$0keyword$0before_DASH_jsload$$,$cljs$core$constant$0keyword$0load_DASH_warninged_DASH_code$$,$cljs$core$constant$0keyword$0retry_DASH_count$$,$cljs$core$constant$0keyword$0autoload$$,$cljs$core$constant$0keyword$0url_DASH_rewriter$$,$cljs$core$constant$0keyword$0on_DASH_cssload$$],[!0,$figwheel$client$default_on_compile_warning$$,$figwheel$client$default_on_jsload$$,$figwheel$client$default_on_compile_fail$$,!1,!0,[$cljs$core$str$$("ws://"),$cljs$core$str$$($cljs$core$truth_$$($goog$$.$inHtmlDocument_$())?`

**Comment by bhauman** [comment]
Make sure you cleaned the builds by deleting the output files.

**Comment by arohner** [comment]
I did lein clean, and the issue persists. 

I'm using:

lein-figwheel, with figwheel as an explicit `:dependency`. I have a .cljs file with (:require [figwheel.client]). 

The issue appears between figwheel 0.2.2-SNAPSHOT, and 0.2.3-SNAPSHOT.

**Comment by arohner** [comment]
I'm using [org.clojure/clojurescript "0.0-3126"] if that's of any use.

**Comment by bhauman** [comment]
And you are saying that you have a :optimization none build that you are focusing on. And you are also auto building and advanced build as well?  

I think you probably need :recompile-dependents true on your advanced build.

**Comment by arohner** [comment]
`lein figwheel`, focusing on my :optimization none  build works just fine. When I `lein cljsbuild :once prod`, my :optimizations :advanced build fails with the error in the title. Changing the :dependencies [...[figwheel "0.2.6"]] to "0.2.2-SNAPSHOT" fixes it.

**Comment by bhauman** [comment]
Oh wait, you really shouldn't be trying to include the figwheel client into an advanced build. 

See this for an example:
https://gist.github.com/bhauman/cf5403efd142407355df

I haven't tried compiling figwheel.client in advanced mode lately. I will give it a try and see what I can do.

**Comment by bhauman** [comment]
Yeah,

I have put some time into this and while I can keep going.  Figwheel simply doesn't function in any other mode but `:none`.  If you do include it in an advanced build you shouldn't be calling `figwheel.client/start` because it just wont function.

I will continue looking into making it compile in advanced mode but for now see the gist I referred to above.

**Comment by arohner** [comment]
Thanks.

> If you do include it in an advanced build you shouldn't be calling figwheel.client/start because it just wont function.

In my experience, if figwheel.client was required in any namespace, even if that second namespace is never required, the advanced compilation build failed. 

I ended up working around this by using cljs modules:

```clojure
:modules {:dev {:output-to "resources/public/js/dev.js"
                                                         :entries ["figwheel.client"
                                                                   "foo.frontend.figwheel"]}
````

**Comment by bhauman** [comment]
Interesting use of modules. You shouldn't have to do this anymore with the latest release. The client script is embedded automatically in the compile. So you don't have to do `(fw/start ...)` anymore. 

The short of it is that you just need to put your client side compile config in your build config:

```clojure
:cljsbuild {
  :builds [{:id "dev" 
                :fighweel { :on-jsload "example.core/reload-callback" }
                :compile { ... }
               }]
 }
```

You can still do things the old way.

**Comment by lvh** [comment]
@bhauman Is this issue related to :advanced mode, or would it work in :whitespace mode? Asking because running tests under PhantomJS/SlimerJS requires optimization levels of at *least* :whitespace (to get everything into 1 file).
