### ISSUE TITLE
Still seeing double-reload in 0.2.7-SNAPSHOT

### ISSUE THREAD

**Issue by JulianLeviston** [bhauman/lein-figwheel#130]
When I save on either SublimeText 3 or Textmate 3, Figwheel reloads the file twice which seems to be causing the browser to load files that are only partly finished compiling.

Using:
OS/X 10.10(.3)
Safari 8.0.5 or Chrome 41.0.2272.118 (64-bit)

    org.clojure/clojure "1.7.0-alpha4"
    org.clojure/clojurescript "0.0-3058"
    org.clojure/core.async "0.1.346.0-17112a-alpha"
    reagent "0.5.0"
    figwheel "0.2.7-SNAPSHOT"
    secretary "1.2.1" ; <---- THIS is set to sense URL changes and adjust application state when that happens... 

    :figwheel {:repl false}

    (ns ^:figwheel-always gc.core ...

I'm also sadly using Rails as the backend which I get the feeling might be the culprit. Rails 4 with the asset cache set to have an additional custom location.

I have my fiwheel set up as follows:

    (fw/start {:websocket-url   "ws://localhost:3449/figwheel-ws"
      				 :on-jsload (fn [] (print "reloaded"))
      				 :load-warninged-code true
      				 :compile-wait-time 1000})

And I also regularly have multiple browser windows open (or multiple browsers) though this behaviour is exhibited irrespective of the windows I have open.

This behaviour has been identical in 0.2.7-SNAPSHOT and 0.2.6 and 0.2.5.

**Comment by JulianLeviston** [comment]
Actually, nevermind. I experimented with different compile-wait-time values and apparently 5000 "fixed" my issue. Not sure why that would fix double loading, though!

**Comment by JulianLeviston** [comment]
Sorry for the back and forth, but I jumped the gun - it just started working properly for a minute and now it's back to where it was again.

**Comment by bhauman** [comment]
Are you building multiple builds or just one?  

ie.  lein figwheel dev admin

**Comment by JulianLeviston** [comment]
Just one:
    lein figwheel

**Comment by JulianLeviston** [comment]
Oh... I just realised my plugin version was still set to 0.2.5... so I switched it to 0.2.7-SNAPSHOT, and re-ran lein figwheel and it downloaded and recompiled, then had this error:

       Exception in thread "main" java.lang.RuntimeException: No such var: ana/forms-seq*, compiling:(figwheel_sidecar/core.clj:173:21)

**Comment by JulianLeviston** [comment]
Ok, I just switched them both to 0.2.6, and now it only loads once. Don't I feel silly! :) Thanks man...

**Comment by JulianLeviston** [comment]
This is SO awesome now!
