### ISSUE TITLE
cljs repl - C-u C-c C-z to switch to buffer's ns, switches back to cljs.user after

### ISSUE THREAD

**Issue by dustingetz** [bhauman/lein-figwheel#132]
```
cljs.user>     ;; switch to cljs buffer and strike C-u C-c C-z to switch to repl buffer in that ns
pp-web.page> (+ 1 1)
2
cljs.user>    ;; it went back
```

To get a repl I did M-x cider-connect localhost 7888 (the figwheel nrepl v0.2.6); M-x nrepl-make-connection-default

I was unable to test on 0.2.7-SHAPSHOT as I couldn't get anything to compile. The bug exists in at least 0.2.5 also.

Using `(in-ns 'my.namespace)` to change the namespace seems to work fine.

**Comment by bhauman** [comment]
This is more than likely out of the scope of figwheel.  It is a rather an interaction between your emacs clojure package (Cider?) and the cljs.repl itself.
