### ISSUE TITLE
Strange interaction with react / quiescent?

### ISSUE THREAD

**Issue by magnars** [bhauman/lein-figwheel#136]
Hi! Thanks for making figwheel. I've only been using it a few days, and already I'm upset every time I have to reload the page. ;-)

I'm experiencing an issue that I can't properly explain. Maybe you can?

- I've got some React components created via `defcomponent` in Quiescent.
- On making changes to the file, the components are re-rendered and my changes are visibile.

So, everything is golden at this point. Then I move my component definitions into its own namespace, requiring them into my original page. This is when it turns weird:

- On making changes to the file, the components are not re-rendered.
- However, the file has been reloaded, so as soon as a state change triggers a re-render, the new changes are visible.

So, from what I can tell, when the components are included in the namespace where they are used, I can see the changes at once. When the components are required, the changes are reloaded, but they're not re-rendered until after a state change.

Any ideas? Thanks so much.

**Comment by bhauman** [comment]
Hey Magnar,

You need to force your system to rerender.  That is why figwheel has the
:on-jsload hook.
You can also put ^:figwheel-always in front of your main namespace to force
that file to reload on every change.

**Comment by magnars** [comment]
Hi Bruce, thanks so much for your quick response.

My figwheel setup looks like this:

```clj
(fw/start {:websocket-url "ws://localhost:3449/figwheel-ws"
           :on-jsload (fn [] (bus/publish :page-change))})
```

In which a `:page-change` event on the bus results in a new page render. I tried adding `^:figwheel-always` to the main namespace with no change in this behavior. I'll try to elaborate a bit:

- in my main namespace, I listen for changes to a state atom, which then re-renders the page with the given state.
- on-jsload triggers this render via a (basically noop) :page-change event.
- the rendering is done in a file `pages.cljs` by looking up the current page like this:

  ```clj
  (defn get-page-component [name]
    (case name
      :jars-page JarsPage
      :gateways-page GatewaysPage
      :gateway-page GatewayPage
      :images-page ImagesPage
      :migration-page MigrationPage))
```

  The result of this lookup is a Quiescent component. These pages are also defined in their own cljs-files.

So, when I make a change to (let's say) the MigrationPage and components defined in that namespace, the `on-jsload` triggers and reloads the page properly. However, if I extract some components out of the migration_page.cljs into another namespace, it no longer updates properly.

Could it be that the referred `MyComponent` used in `MigrationPage` points at the old definition? In that case, why is it suddenly correct when I force a re-render manually with a state change afterwards? 

Thanks again for taking the time to look at this, as it has me quite confused at this point.

**Comment by magnars** [comment]
Here's a new nugget - if I add `^:figwheel-always` to the `MigrationPage` namespace, it works as intended. So I could work around this issue by adding `^:figwheel-always` to all namespaces that have dependencies to some of my other code. Thoughts?

**Comment by bhauman** [comment]
This is interesting.  I haven't used Quiescent. 

I would maybe only put `^:fighweel-always` on your pages.cljs to keep the references up to date.

Or you can always do:
I would set `:recompile-dependents true` in your `:compile` options.

**Comment by magnars** [comment]
Adding `^:figwheel-always` to `my-project/pages` doesn't solve the issue, it has to be on `my-project/some-page`. Adding `:recompile-dependents true` does work nicely, and is the solution I am going for. Thanks so much for your help!

I'm not entirely convinced it is Quiescent specific, and I'd be happy to create a minimal example project, if you want to dig deeper.

**Comment by bhauman** [comment]
Actually a minimal example project would be very helpful :)

**Comment by magnars** [comment]
Hi again, Bruce. Finally had some time to cut down my project to some attempt at minimalism. :)

https://github.com/magnars/bug-examples/tree/lein-figwheel-136

Thanks for taking a look!

**Comment by bhauman** [comment]
So the solution here is to capture a reference to your page in pages.cljs.

:demo-page #'DemoPage 

Or 
:demo-page (fn [&args] (apply DemoPage args))

Pretty sure this will work.

**Comment by bhauman** [comment]
Darn the markdown killed my second example.
`(fn [&args] (apply DemoPage args)`

**Comment by magnars** [comment]
No, that doesn't solve it.

- `#'` gives `Uncaught SyntaxError: Unexpected token return`
- `(fn [&args] (apply DemoPage args)` exhibits the same symptoms.

I think I know what you are getting at, though, because I used to use a lookup-table like this:

```clj
(def page-components
  {:intro-page IntroPage
   :demo-page DemoPage})
```

But I fixed those issues going to this:

```clj
(defn get-page-component [name]
  (case name
    :intro-page IntroPage
    :demo-page DemoPage))
```
