### ISSUE TITLE
Cider autocomplete for aliased namespaces

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/lein-figwheel#138]
I just got fighweel to work with cider by following the wiki instructions and also removing weasel and piggieback from my project.cljs - newer versions like piggieback 2.0.0 seem to not work.

It works really great and loading a file with C-c C-k is so much faster than with weasel! Almost JVM like. Great work! 

Now the only thing in the way of using this repl in daily development is missing autocomplete on aliased namespaces in the current ns. Qualified ns do complete.

I'm using the bleeding edge of cider-0.9.0-SNAPSHOT -  Is this still expected behavior or should I downgrade to 0.8.2?

**Comment by bhauman** [comment]
Yeah I don't know of autocomplete working, but I'm out of the loop on this.

I'm gonna check this, this afternoon.  Maybe I can update that page and have a working nREPL.

**Comment by lgrapenthin** [comment]
FYI I this works for me after downgrading to Cider 0.8.2. 

It might be interesting for your wiki that I had to pull in the following dependencies to on Clojure 1.7 Beta 2 and Clojurescript 3211:
tools.namespace 2.10
tools.nrepl 2.10
tools.reader 0.9.1

**Comment by lgrapenthin** [comment]
I must add, that this only works sometimes. Often, when connecting, Emacs just blocks, and I have to C-g and kill the non-working repl buffer. I could not find a reliable way how I get it working yet.

**Comment by lgrapenthin** [comment]
The latter problem is apparently with Cider. One shouldn't use cider-connect when in a repl buffer, as a workaround. So with 8.2 and the above deps, everything works.

**Comment by bhauman** [comment]
very cool. I will try this out.

**Comment by Arcanum-XIII** [comment]
@lgrapenthin is there any alike issue with Cider 9, which is in beta ?

**Comment by lgrapenthin** [comment]
Not to my notice
