### ISSUE TITLE
rwrap doesn't seem to work

### ISSUE THREAD

**Issue by grav** [bhauman/lein-figwheel#141]
Starting figwheel with `rlwrap lein figwheel` (installed via homebrew) doesn't make any difference to my setup. Arrow keys and `ctrl+a` etc just prints escape codes. Something is probably messed up in my system, but all versions seem up to date:

```
Leiningen 2.5.0 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM
rlwrap 0.42
[org.clojure/clojurescript "0.0-3211"]
[lein-figwheel "0.2.9"]
[lein-cljsbuild "1.0.5"]

```

Any hints?

**Comment by bhauman** [comment]
are you running the command as
$ rlwrap lein figwheel

**Comment by grav** [comment]
Yes, exactly like that.

I've used rlwrap successfully with this tutorial btw:

https://github.com/clojure/clojurescript/wiki/Quick-Start

**Comment by grav** [comment]
Now I figured out the difference - I start leiningen using the [drip proxy](https://github.com/ninjudd/drip) (which 'caches' the jvm). If I disable drip in my `~/.lein/leinrc`, rlwrap works fine.

I'll close this issue, since it's not related to figwheel.
