### ISSUE TITLE
Logo in browser compile warnings obscuring logs

### ISSUE THREAD

**Issue by erikcw** [bhauman/lein-figwheel#142]
![screen shot 2015-05-04 at 5 42 50 pm](https://cloud.githubusercontent.com/assets/113129/7465446/1e58b976-f285-11e4-8c2c-d108affc45a4.png)

Looks like the z-index of the logo needs to be tweaked so that it sits behind the log text.

lein-figwheel 0.3.1
Chrome 42

**Comment by bhauman** [comment]
this is strange I'm willing to bet that you have CSS on the page that is
interacting with the logo poorly.  That being said the logo could have a
lower z-index.

The logo should be small in the upper left hand corner.

**Comment by erikcw** [comment]
You're right.  I had some CSS on page that was tweaking the SVG size....  Works correctly after name spacing the CSS properly.
