### ISSUE TITLE
Allow nrepl binding to non-localhost hostnames

### ISSUE THREAD

**Issue by nhusher** [bhauman/lein-figwheel#148]
I'm attempting to use figwheel and the provided nrepl hook to develop a client-side-only app with Figwheel that lives in a Docker cluster. This means that the nrepl host will be something other than localhost, which is disallowed by default.

[Here's a relevant stackoverflow that describes the issue](http://stackoverflow.com/questions/22422820/connecting-to-a-headless-nrepl-running-in-a-docker-container-from-another-contai). I'd like to be able to manually specify the hostname in my `project.clj`, which I don't think I can.

I believe the change can be added [here](https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L490-L495) with fairly little effort, but I'm not sure how to go about making/testing the change myself. I suspect it should look a bit like this:

```clojure
(defn start-nrepl-server [figwheel-options autobuild-options]
  (when (:nrepl-port figwheel-options)
    (nrepl-serv/start-server
     :port (:nrepl-port figwheel-options)
     :bind (or (:nrepl-host figwheel-options) "localhost")
     :handler (apply nrepl-serv/default-handler
                     (conj (map resolve cider/cider-middleware) #'pback/wrap-cljs-repl)))))
```

Willing to invest the time necessary to build this myself if I could get a quick primer on how to do so.

My [project.clj](https://gist.github.com/nhusher/16e0ef55b68efd54e730), if anyone is curious.

**Comment by nhusher** [comment]
I might have figured out how to install this thing locally -- pull request incoming later today or tomorrow.

**Comment by bhauman** [comment]
I will certainly accept a pull request for this.

**Comment by nhusher** [comment]
At your leisure: https://github.com/bhauman/lein-figwheel/pull/150
