### ISSUE TITLE
generated files in project directory

### ISSUE THREAD

**Issue by mhuebert** [bhauman/lein-figwheel#154]
When I run Figwheel, files like `0b21e194b30ecb571b267093ec0f129f5541677d-init.clj` are generated and put in my project directory. Is this expected? I reviewed the documentation and couldn't find any settings related to where these files should be saved.

**Comment by oskarth** [comment]
According to this issue: https://github.com/bhauman/lein-figwheel/issues/37 it seems as if the files come from running `lein cljsbuild auto`.

**Comment by bhauman** [comment]
I actually think that this comes from setting the env variable LEIN_FAST_TRAMPOLINE=y

**Comment by magnars** [comment]
I can confirm that LEIN_FAST_TRAMPOLINE is indeed the culprit. It also causes some issues where a clean doesn't fully clean stuff - you also have to remote the -init files. I've removed this from my settings now.
