### ISSUE TITLE
Too Awesome

### ISSUE THREAD

**Issue by JulianLeviston** [bhauman/lein-figwheel#155]
My major issue is that Figwheel is too awesome.

**Comment by JulianLeviston** [comment]
This was just my way of saying thanks for the great software, @bhauman :) It's a pity that you can't give "thanks" on github - seems a bit negatively geared. :)

Thanks!

**Comment by bhauman** [comment]
Thanks! I really appreciate it.

**Comment by minikomi** [comment]
:100: :+1:
