### ISSUE TITLE
Support readline commands in repl (^P, ^N, ^F, ^B, etc)

### ISSUE THREAD

**Issue by aaronjensen** [bhauman/lein-figwheel#156]
Currently, hitting any of the readline commands simply echoes them. It'd be nice if the REPL supported them.

**Comment by bhauman** [comment]
This is a much much larger issue, one that would take a significant about of dev time. 

But please see the notes about rlwrap in the Readme and Quick Start.

**Comment by aaronjensen** [comment]
Oh, wow, that's great, thanks! Might be helpful to put that closer to the top of the readme near the quick start--at least a link to that section.
