### ISSUE TITLE
CSS imported from the wrong location

### ISSUE THREAD

**Issue by matthewp** [bhauman/lein-figwheel#158]
If I change my `site.css` and import another css file:

```css
@import url("other.css");
```

It will correctly import `other.css`.  However when I then go edit other.css it tries to reload from: `http://localhost:3449/resources/public/css/other.css` which causes a 404.
 
It should be reloading from http://localhost:3449/css/other.css

**Comment by bhauman** [comment]
Sorry, this type of reloading isn't supported right now.  Only top level CSS files with link elements.

**Comment by bhauman** [comment]
also what version of figwheel are you using?
