### ISSUE TITLE
Build works with cljsbuild but not figwheel

### ISSUE THREAD

**Issue by yayitswei** [bhauman/lein-figwheel#159]
Here's the project.clj: https://gist.github.com/yayitswei/317dfec919d01e67fb4c

With `lein with-profile dev cljsbuild once` the project compiles successfully and the page loads correctly.

With `lein with-profile dev figwheel` I get a Uncaught ReferenceError: goog is not defined on page load.

Any tips on debugging this?

**Comment by yayitswei** [comment]
Turns out `lein with-profile dev figwheel` wasn't picking up the dev profile configuration. Not sure why, but I found a workaround for that.

Thanks to @bhauman for troubleshooting over #clojurescript

**Comment by bhauman** [comment]
Gonna keep this open as it is still an issue.

**Comment by dhruvbhatia** [comment]
@yayitswei Do you mind sharing the workaround you found?

**Comment by bhauman** [comment]
@dhruvbhatia It seems that @yayitswei has a project that wasn't merging the `:profiles` correctly into the cljsbuild config.

I tried to reproduce this non merging of the profiles and can't seem to do it.  It appears to work fine.

@dhruvbhatia is this the problem that you are having?

**Comment by yayitswei** [comment]
@dhruvbhatia I'm not using profiles anymore and instead have :prod and :dev cljs builds.

Here's my new project.clj: https://gist.github.com/yayitswei/3f79beab1c604973e1ca

**Comment by yayitswei** [comment]
@bhauman What version of leiningen are you using? I'm on 2.5.1 and I wonder if there were any changes that affected how profiles merged.

https://github.com/technomancy/leiningen/blob/master/NEWS.md

**Comment by dhruvbhatia** [comment]
@yayitswei Thanks - much appreciated! :+1:

**Comment by sthomp** [comment]
@dhruvbhatia Im getting this same error. Were you able to resolve this?
