### ISSUE TITLE
Unicode in CSS seems mangled

### ISSUE THREAD

**Issue by brandonbloom** [bhauman/lein-figwheel#160]
Something like this:

```
  content: '❯';
```

Seems to get served to my browser like this:

```
  content: 'â¯';
```

**Comment by bhauman** [comment]
You need to add a `<meta charset="UTF-8">` into the head of your document.

**Comment by brandonbloom** [comment]
Grumble grumble browsers. Thanks.

**Comment by brandonbloom** [comment]
(although, I don't recall having to do this in the past, my assumption was that this was an HTTP server behavior/configuration thing)
