### ISSUE TITLE
Instaparse version bump

### ISSUE THREAD

**Issue by conan** [bhauman/lein-figwheel#161]
I followed the [Usage](https://github.com/bhauman/lein-figwheel#usage) instructions to switch my project to use figwheel.  When running `lein figwheel` I get an arity error about StringReader, which seems to be because its arity has changed, and this broke instaparse.  Instaparse has updated to fix, so I had to add an explicit dependency on instaparse to use version 1.4.0; it'd be nice not to have to work through this when setting up a project.

Info [here](https://github.com/clojure-emacs/refactor-nrepl/issues/53).  I think instaparse comes from ring in a figwheel project, maybe ring could be updated for later Clojure versions?

**Comment by bensu** [comment]
What Clojure and ClojureScript versions are you using in the project?

**Comment by conan** [comment]
The same versions as listed in the Usage section of the readme:
```
[org.clojure/clojure "1.7.0-beta3"]
[org.clojure/clojurescript "0.0-3211"] ;; has to be at least 3211 or greater
```

**Comment by bensu** [comment]
The problem is that Instaparse < 1.3.4 doesn't work with Clojure 1.7. In Figwheel, Instaparse < 1.3.4 is pulled in by Compojure, via Clout. Upgrading Compojure to 1.3.4 might solve the problem.

**Comment by conan** [comment]
Ah that must be it.  Thanks.

**Comment by dark4eg** [comment]
thx)
