### ISSUE TITLE
Connection interrupted error in Firefox

### ISSUE THREAD

**Issue by brandonbloom** [bhauman/lein-figwheel#164]
Refreshing a Figwheel app in Firefox consistently produces this error message:

```
The connection to ws://localhost:3449/figwheel-ws/dev was interrupted while the page was loading.
```

From `socket.js:62:0`

**Comment by bhauman** [comment]
This doesn't affect development.  But its an interesting question as to wether you can declare a websocket as interuptable.  There is an `window.onbeforeunload` handler that we can shut down the socket with before the window is unloaded.
