### ISSUE TITLE
Code reloading causes key-press listeners to double-fire

### ISSUE THREAD

**Issue by juliangamble** [bhauman/lein-figwheel#165]
I've got a figwheel project here:
[https://github.com/juliangamble/figwheel-slides](https://github.com/juliangamble/figwheel-slides)

You start it with 
`lein figwheel`

You view it with 
[http://localhost:3449/#0](http://localhost:3449/#0)

To navigate between slides you use 
'Shift-right-arrow' and Shift-left-arrow'

This works fine until I modify the code, save and the code reloads. Then the key-listener double-fires and you jump two slides. 

I can't see what is going on. Is this a figwheel bug?

**Comment by pkillean** [comment]
https://github.com/juliangamble/figwheel-slides/blob/master/src/figwheel_slides/core.cljs#L162
You are calling init every time you reload that file, and it tacks on another event listener. Stuff you only want to happen once should be put in a (defonce ...) form and they'll be ignored on reload.

**Comment by juliangamble** [comment]
Thanks
