### ISSUE TITLE
Figwheel does not work with empty asset-dir 

### ISSUE THREAD

**Issue by borkdude** [bhauman/lein-figwheel#171]
Figwheel does not work with empty asset-dir 

Steps to reproduce:

- `lein new figwheel myproject -- --reagent`
- move assets from resources/public to resources
- replace string `resources/public` to `resources` in `project.clj`
- set `:asset-path` to `""` in `project.clj`
- set `:http-server-root` to `""` in `project.clj`
- lein figwheel
- browse to `http://localhost:3449`

Figwheel does not respond to code changes. Error message will be in the log files.
See also https://github.com/borkdude/figwheel-asset-problem

**Comment by bhauman** [comment]
This is more of an issue with setting `:output-dir`  "resources". It seems that the "resources" being on the resource path causes the compiler to find the output files.  So, I think this is in the compiler. 

My experiments show that an empty `:asset-path` works when the directory isn't "resources".

**Comment by bhauman** [comment]
There is an issue filed here:
http://dev.clojure.org/jira/browse/CLJS-1298
