### ISSUE TITLE
Figwheel heating up when exceptions are thrown in emacs REPL

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/lein-figwheel#172]
So figwheel works almost perfectly as my CLJS REPL for quite some time now. I don't use the REPL much, but having auto-complete and docstrings etc. in Emacs is awesome. However, when I use the actual REPL and an exception flies, the CPU starts heating up until I kill the figwheel JVM.

I am using nrepl 0.8.8.

**Comment by bhauman** [comment]
This is actually a long standing cider-nrepl issue.  It sends down trys to pprint whole repl-env when an error is thrown.  Been waiting for cider 0.9.0 to get out of SNAPSHOT.

Yes this is horrible and why I currently recommend inf-clojure if you are using Emacs.
