### ISSUE TITLE
Does figwheel support reloading :libs files?

### ISSUE THREAD

**Issue by doffltmiw** [bhauman/lein-figwheel#173]
Changes are detected, but nothing seems to happen. I had to manually run (clean-builds) and save the javascript file to restart the whole build.

**Comment by bhauman** [comment]
Right now figwheel does not support reloading :libs.

**Comment by bensu** [comment]
@bhauman Is it desirable?

Also, is it [here](https://github.com/bhauman/clojurescript-build/blob/master/src/clojurescript_build/core.clj#L192) where liibs should be picked up for changes?

**Comment by bhauman** [comment]
I'm currently working on this.

If you use 0.3.*-SNAPSHOT you will see that you can create GClosure style js libs right next to you cljs files. Just make sure you namespace them as you would your cljs files.

I still have to verify that the paths in `:libs` are being reloaded correctly.

I would love for you to give 0.3.8-SNAPSHOT a try.

The other big change is auto reloading of dependents instead separated from auto compiling dependents.

Autoloading is instantaneous and is the natural behavior that I think we are all wanting.

Dependencies are also being loaded in the correct order now.

**Comment by bhauman** [comment]
Actually `:libs` seems to work fine in 0.3.8-SNAPSHOT..

**Comment by bensu** [comment]
Great then! I'll try the latest version and report back.

**Comment by bhauman** [comment]
Seems like we can close this
