### ISSUE TITLE
reset-autobuild writes wrong content to app.js

### ISSUE THREAD

**Issue by hlship** [bhauman/lein-figwheel#175]
In my environment, I see the following when I execute (reset-autobuild) from the figwheel REPL.

The js/app.js file changes from:

```
if(typeof goog == "undefined") document.write('<script src="/merchant-portal/js/out/goog/base.js"></script>');
document.write('<script src="/merchant-portal/js/out/cljs_deps.js"></script>');
document.write('<script>if (typeof goog != "undefined") { goog.require("fan.merchant_portal.dev"); } else { console.warn("ClojureScript could not load :main, did you forget to specify :asset-path?"); };</script>');
```

to:

```
goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../reagent/interop.js", ['reagent.interop'], ['cljs.core']);
goog.addDependency("../reagent/debug.js", ['reagent.debug'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../reagent/impl/util.js", ['reagent.impl.util'], ['reagent.interop', 'cljs.core', 'reagent.debug', 'clojure.string']);
goog.addDependency("../reagent/ratom.js", ['reagent.ratom'], ['reagent.impl.util', 'cljs.core']);
...
```

and so forth.

**Comment by bhauman** [comment]
So what I belie is happening here is that Figwheel does a naive reload of your configuration and doesn't hanldle merging in profiles.

Am I right? If so you would need to make your main :cljsbuild more explicit.

Sorry but the intersection of all these tools is Complex to meet all needs.

**Comment by hlship** [comment]
Oh, yes, these tools are getting complex.  Makes me pine for Gradle, where you sort these things out a bit better.

I'm confused though, why would the module dependency data get written to app.js, even in the production build or default build or whatever?

**Comment by bhauman** [comment]
I "enhanced" reset to reload the config from 
Project.clj, so your cljsbuild config is dependent on a profile merge it may be missing the :main option.

**Comment by bhauman** [comment]
So this "feature" let's you change your build config at runtime.  But as it has some downsides I'm open to making it optional.

Any ideas?

**Comment by bhauman** [comment]
This can definitely cause confusion so I'm taking reload out of reset and making it explicit as `reload-config`:
https://github.com/bhauman/lein-figwheel/commit/aa82ef22c0df52ecb50b0dc650090a3aa5342ceb
