### ISSUE TITLE
Support for reloading macros

### ISSUE THREAD

**Issue by glittershark** [bhauman/lein-figwheel#177]
I don't know if this is already supported and there's a problem with my configuration somewhere, but I usually need to restart figwheel in order to properly reload clojure macro files. It'd be neat if I didn't have to!

**Comment by bhauman** [comment]
This is available, but the macro files have to be in the watched directories of the cljs build.
In other words, figwheel only watches the directories in the build `:source-paths` param.

Make sense?

**Comment by glittershark** [comment]
That makes sense. Is it idiomatic to have `:source-paths` overlapping between clj and cljs files?

**Comment by bhauman** [comment]
Not sure, it is idomatic to have macros that cljs sources use in cljs paths.

**Comment by bhauman** [comment]
I'm gonna close this if thats cool :)

**Comment by glittershark** [comment]
No worries!
