### ISSUE TITLE
Question: Figwheel has me wanting more from clojure

### ISSUE THREAD

**Issue by JulianLeviston** [bhauman/lein-figwheel#178]
I've wanted this for a while... since I heard about lisp and functional programming languages, actually (many moons ago)...

What if code was data, and modifying code was simply modifying data?

Then perhaps you could program from within the environment where your program lived. This is what I'd like to do... to have the "programming language" be injected into edited artefact... so that an editor was part of the live environment where I would grow my code, live. Cerating a deployable artefact would pretty much just be removing the editor functionality from the code "world".

This means that pulling out "source" would be a translation from data back into text... and that coding would simply be manipulating data. This would mean it'd be impossible to make syntax errors, because things are either created or not. But, perhaps it's not possible in clojure because it's not lazy enough... perhaps it'd involve reinventing haskell from within clojure, and that would be silly.

If code truly was data, macros wouldn't exist... because everything would lazy-eval, and things would be more like haskell. The trouble with Haskell, though, is that it's not dynamic... (as far as I know). Can you have dynamic, but typesafe (I really dislike the syntax of typed clojure, but maybe that's just a syntax thing and I should get over it). I really like Haskell's type inference.

I wonder if you've had thoughts about this... I tend to feel a REPL is a bad way to program, but that manipulating code/data from the REPL is a great idea, because it's live. It's just that a REPL isn't an editor. But why can't we have an editor that is live, rather than interpreting back and forth between text?

Happy to talk about this somewhere else if you're interested. If not, just close this. I'll understand :)

**Comment by bhauman** [comment]
Hey Julian,

First I would like point out some food for thought.
Data driven applications:
https://www.youtube.com/watch?v=BNkYYYyfF48
Out of the tar pit:
http://shaffner.us/cs/papers/tarpit.pdf

Secondly, I really understand this desire.

I think these ideas are great. The Wolfram language comes to mind. Is that along the lines of what you are talking about?

But, in general, this requires a declarative system/language to do things like this, right?  And so we are left with the trade-off that declarative systems offer, eh?  There are just things that a declarative system can't express.  Thus, you make the declarative system extensible (i.e. io monads, react components) and shove all the imperative stuff in there.  So, there is always going to be trade-off here, it's just where are we going to draw that line?

It's interesting though. This also makes me thing of .setScriptSource in the javascript remote debugger. if you could .getScriptSource as well, you could round trip the source as data.  It would be much better if the was an data and not just a string. This is how the live coding in the chrome dev tools works.

 
I'm including Brandon Bloom on this.
cc/ @brandonbloom

**Comment by JulianLeviston** [comment]
Hey! :) thanks for the thoughtful reply.

Quite familiar with the tar pit document, and also some of the work that is being done on Eve, and all of the work done by the STEPS people (alan kay et al), though it seems there might be better ways to do things than EVE. I'll watch that 'tube video you posted momentarily.

No, the wolfram language is different, I feel.

Is data different from code? What is a function? Is it a box I operate on, then close the lid and it runs? Or can I actually build the form up from nothing? Some of the form is built in to the hardware of the computer, or the low level virtual machine (whatever the "metal" is as the context of my evaluation), but each piece of data can mean an instruction, given a language and an interpreter (even if that language is ASM and the interpreter is the processor). At the base level, the computer sees no distinction between data and code, so why should we? We need to program on much higher levels than that, and with much more abstract blocks, because we understand patterns whereas computers don't (yet)... but the effect is the same, I feel. Code and data are just memory locations that have electricity held in them or not. Code is just data that can be executed or evaluated. So, what makes it alive? Is it when the effect can be directly manipulated? I feel so. When the representation of the thing is connected directly to the thing itself. When I don't have to have a process between the thing and the representation of it, and when the representation is still connected to the thing. A REPL has quite a close connection, but it's still not actually connected. Source editing is very indirect (many processes sit between our code and a live, running system).

It strikes me that a truly immutable language will be syntaxless, inasmuch as it is unrepresentable, therefore have *all* syntaxes. How to do that? By translating immutable definitions, I guess. A square function is the same square function all the world over, afterall, call it SUKUEERU (japanese), or maybe carré if you're french. Names are the immutable things. Whatever the process is, if the mathematical topology is the same, then it's the same function. We can communicate between languages by making use of these immutable definitions.

I'm not convinced that there are things that a declarative system can't express. What are those things? Perhaps we don't fully understand what it means properly? Time can quite easily be modeled as adjacent sets of declarations of identity transformations, afterall.

To bring a live "editor" where the thing being edited is data, and therefore also potentially live code, would involve these streams of declarations being explicitly modeled and communicated.

Anyway I'll go watch that video now :) I'm sure I should think more about this before talking about it more (though I *have* been thinking about it for well over 10 years).

**Comment by JulianLeviston** [comment]
Just wanted to add one more thing. This all came out of a complete and utter sickness of repeating myself, and the absolute irony that, as programmers, we are self-described masters of helping other people remove repetition from their lives, but can't seem to stop writing the same things over and over (how many times have you writte defn in the last year, for example? or how many times have you typed the 'a' key to mean the letter 'a'? for me it numbers in the thousands, I'd wager) ;-) Anyway, I'll stop here.

**Comment by JulianLeviston** [comment]
Ok so I watched the Paul deGrandis talk you mentioned, but what he's talking about there is data-driven functionality, assuming I'm understanding correctly: more like using a palette of previously built functionality, but you can't use the whole set of tools available to someone programming directly in the language. Effectively creating another world. I'm not interested in doing this, particularly. Actually, the opposite.

We need to learn from systems where the editor is the system like most Smalltalks offer (such as Squeek), but not take their crappy parts, such as the world being some separate golden perfect place, away from the "dirty" "everything else". A set of translators would allow this, and allow us to work on building a system that is more direct. This is the path that the VPRI / STEPS project went down (http://vpri.org) using a symbiotic meta-language called OMeta to translate between "worlds", or tiny meta-languages (I hesitate to use the word DSL here, they used the term POL: problem-oriented language).

If you haven't yet read the STEPS work, there is a wealth of information on their website under "writings". They're the "new" xerox-parc (given half of the people in it are directly from there, that would make sense - they're the old xerox parc too ;-)).

So, Haskell seems to solve this issue of "which is it? state or behaviour?" that we seem to chase our tail with. In Haskell, everything is a function - all values are thunks. But, all thunks don't seem to be data. THAT is the problem, because it means you can't just adjust them live... you have to recompile them. In clojure, there's a full separation, whereas haskell is slightly more pure.

What we ideally want is ONE single point of execution that the system automatically handles... which is what actually happens in reality - I mean, granted multi-core systems have multiple points of execution, but that's not really what we're talking about here. We're talking about the schema of the system.

Rather than create an artificial evaluation mechanism, why not use the actual one of the system? Things are all data. All things are also functions (ie lazy), and immutable. Things can be "mutated" by connecting a new single tree of things to the one mutable point in the system, and releasing the previous state from the system assuming backtracking isn't a requirement. Perhaps this is already how Haskell works, but I don't think so.

Anyway I need to get on with other things. :) Thanks for listening to me.

**Comment by bhauman** [comment]
Thanks for sharing your thoughts!! :)
