### ISSUE TITLE
nREPL doesn't work (doesn't install) refactor-nrepl?

### ISSUE THREAD

**Issue by lvh** [bhauman/lein-figwheel#180]
When I `lein figwheel`, connect my browser, and then connect to the nREPL server using CIDER, I get the following warning:

```
; CIDER 0.9.0 (package: 20150616.939) (Java 1.8.0_40, Clojure 1.7.0-RC1, nREPL 0.2.10)
WARNING: The following nREPL ops are not supported:
artifact-list artifact-versions clean-ns configure extract-definition find-debug-fns find-symbol find-unbound hotload-dependency rename-file-or-dir resolve-missing stubs-for-interface version warm-ast-cache
Please, install (or update) refactor-nrepl and restart CIDER.
You can mute this warning by changing cljr-suppress-middleware-warnings.
```

However, refactor-nrepl is in my `user` profile through `~/.lein/profiles.clj`:

```clojure
{:user {:plugins [[cider/cider-nrepl "0.9.0"]
                  [refactor-nrepl "1.1.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}
```

I can't tell if this is because the plugin is ignored, or if the nrepl support in figwheel simply doesn't support it...

**Comment by lvh** [comment]
OK, it's definitely not ignoring it; I added it manually to the `:plugins` vector in my `project.clj`, both in the `:dev` profile and in the global one; no change.

**Comment by lvh** [comment]
It also seems to ignore `:repl-options`:

```clojure
:repl-options {:init-ns figwheel-sidecar.repl-api
                        :init (figwheel-sidecar.repl-api/cljs-repl)}
```

Although I'm not sure if that's intentional...

**Comment by bhauman** [comment]
The middleware in the  Figwheel nRepl is hard wired.  It does not take LEIN configurations into account.

**Comment by lvh** [comment]
Cool; is that intentional, or would something that picks lein's brain re: repl configs be welcomed?

**Comment by bhauman** [comment]
I'm trying to keep lein out of the fIgwheel code.
You should probably be explicit and add the nREPL plugins in the :Figwheel config area. As that REPL is different.

**Comment by lvh** [comment]
Oh, I didn't realize that worked! Yes, I'd be perfectly happy to specify it for figwheel specifically. The only `:figwheel` configuration I could find, though, is `:http-server-root`, `:server-port`, `:css-dirs`, `:open-file-command`, and `:nrepl-port`. Is this something that is currently supported, or is that where you suggest I add that functionality?

**Comment by bhauman** [comment]
No that doesn't. That's the only way I'd consider adding it. Sorry for the confusion.

**Comment by sickill** [comment]
Just got this problem too. I'm a bit confused here. The doc https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl mentions CIDER several times, but the comments here say that CIDER connection isn't actually supported (If I got that correctly). Is this something that changed in recent CIDER versions?

**Comment by bhauman** [comment]
If you want to use figwheel with the newest cider-nrepl 0.9.0 do this: [lein-figwheel "0.3.3" :exclusions [cider/cider-nrepl]]  

figwheel 0.3.4 is coming out soon and it wont have this problem

**Comment by sickill** [comment]
I tried both `[lein-figwheel "0.3.3" :exclusions [cider/cider-nrepl]]` and `[lein-figwheel "0.3.5"]` and I'm getting the same result. Cider seems to be connecting now:

    nREPL: Establishing direct connection to localhost:7888 ...
    nREPL: Direct connection established
    cljr--assert-middleware: nrepl-refactor middleware not available! Did you remember to install it?

Still getting the above warning.

Now, when I try to eval a form with Cider (`<C-c><C-c>`) I'm getting this:

    CompilerException java.lang.RuntimeException: Unable to resolve symbol: *e in this context, compiling:(/private/var/folders/m4/ky3ycx6n0r3_kkll6h8z_v880000gn/T/form-init8192974437342477656.clj:1:1)

Here's the content of this tmp file:

    (.deleteOnExit (java.io.File. "/private/var/folders/m4/ky3ycx6n0r3_kkll6h8z_v880000gn/T/form-init8192974437342477656.clj")) (do (set! *warn-on-reflection* nil) (require (quote cljsbuild.crossover) (quote cljsbuild.util) (quote figwheel-sidecar.repl)) (try (do (clojure.core/letfn [(copy-crossovers__1413__auto__ [] (cljsbuild.crossover/copy-crossovers "/Users/sickill/code/asciinema/asciinema-player/target/cljsbuild-crossover" (quote [])))] (clojure.core/when (clojure.core/not-empty (quote [])) (copy-crossovers__1413__auto__) (cljsbuild.util/once-every-bg 1000 "copying crossovers" copy-crossovers__1413__auto__)) (figwheel-sidecar.repl/run-autobuilder {:figwheel-options {:resource-paths ["/Users/sickill/code/asciinema/asciinema-player/dev-resources" "/Users/sickill/code/asciinema/asciinema-player/resources"], :css-dirs ["resources/public/css"], :server-port 3449, :nrepl-port 7888, :http-server-root "public", :unique-id "player--0.1.0-SNAPSHOT"}, :all-builds [{:build-options {:output-dir "resources/public/js/test", :optimizations :none, :output-to "resources/public/js/test.js", :source-map "resources/public/js/test.js.map", :pretty-print false}, :parsed-notify-command {:shell ["phantomjs" "env/test/js/unit-test.js" "env/test/unit-test.html"]}, :id "test", :notify-command ["phantomjs" "env/test/js/unit-test.js" "env/test/unit-test.html"], :source-paths ["src/cljs" "test"]} {:build-options {:output-dir "resources/public/js/dev", :optimizations :none, :output-to "resources/public/js/dev.js", :source-map true, :pretty-print true}, :parsed-notify-command {:shell []}, :id "dev", :source-paths ["src/cljs" "env/dev/cljs"], :figwheel {:build-id "dev", :on-jsload "asciinema-player.main/reload"}}], :build-ids ["dev"]})) (java.lang.System/exit 0)) (catch cljsbuild.test.TestsFailedException e__1411__auto__ (java.lang.System/exit 1)) (catch java.lang.Exception e__1411__auto__ (do (.printStackTrace e__1411__auto__) (java.lang.System/exit 1)))))

**Comment by bhauman** [comment]
Please see the comments above.  The middleware in figwheel is hardwired, nrepl-refactor is not going to get picked up.  

Also try 0.3.7

Please see these new wiki pages:

https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL
https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-with-Emacs-Inferior-Clojure-Interaction-Mode

**Comment by ruiyang** [comment]
I also got the same issue with figwheel 0.3.7.
Message: cljr--assert-middleware: nrepl-refactor middleware not available! Did you remember to install it?

Looking at the comment above, I am still not sure how to manually add that refactor-nrepl middleware. Has someone worked around this?

Thanks

**Comment by otijhuis** [comment]
I'm looking into making the middleware configurable.

Just a few questions:
- What name would you recommend for the option? *:nrepl-middleware*?
- Leave cider and piggieback as default if the configuration doesn't exist and if it does you have to specify them both in the configuration as well? That would allow them to be overridden if needed.

**Comment by bhauman** [comment]
Yeah that sounds good. Go for it :)

**Comment by otijhuis** [comment]
I have a working version.

Example project.clj figwheel config
```clojure
:figwheel {
   :nrepl-port 7888
   :nrepl-middleware ["cider.nrepl/cider-middleware"
                                "refactor-nrepl.middleware/wrap-refactor"
                                "cemerick.piggieback/wrap-cljs-repl"]
}
```
Unfortunately I had to use strings, otherwise they are evaluated and the class can't be found.
Quoting doesn't work either.

Original function
```clojure
(defn start-nrepl-server [figwheel-options autobuild-options]
  (when (:nrepl-port figwheel-options)
    (let [middleware (if (require? 'cider.nrepl)
                       (map resolve (deref (resolve 'cider.nrepl/cider-middleware)))
                       (list))
          middleware (conj middleware #'cemerick.piggieback/wrap-cljs-repl)]
      (nrepl-serv/start-server
       :port (:nrepl-port figwheel-options)
       :bind (:nrepl-host figwheel-options)
       :handler (apply nrepl-serv/default-handler middleware)))))
```

Modified version
```clojure
(defn start-nrepl-server [figwheel-options autobuild-options]
  (when (:nrepl-port figwheel-options)
    (let [middleware (or
                      (:nrepl-middleware figwheel-options)
                      ["cider.nrepl/cider-middleware" "cemerick.piggieback/wrap-cljs-repl"])
          resolve-mw (fn [name]
                       (let [s (symbol name)
                             ns (symbol (namespace s))]
                         (when (require? ns)
                           (let [var (resolve s)
                                 val (deref var)]
                             (if (vector? val)
                               (map resolve val)
                               (list var))))))
          middleware (mapcat resolve-mw middleware)]
      (nrepl-serv/start-server
       :port (:nrepl-port figwheel-options)
       :bind (:nrepl-host figwheel-options)
       :handler (apply nrepl-serv/default-handler middleware)))))
```
If the middleware resolves to a vector it assumes it's a list of middleware.

Few things I'm not sure about:
- Leave the defaults in there hardcoded? Doesn't feel like the place for defaults.
- Right now there is no warning when one of them can't be loaded. Do we want warnings/exceptions? In the original version cider was silently ignored if it wasn't available. If piggieback is always available and should always be loaded, maybe remove cider from the defaults and throw if something can't be loaded?

Any other advice would be welcome too :)

If you rather have me do a pull request and discuss it there let me know. Haven't done that many contributions on github yet so not that familiar with the preferred workflow.

**Comment by bhauman** [comment]
Yeah go ahead and do a pull request! You can do it through github.

There are some other things I would like in this if you have time.

- I would probably remove piggieback in dependencies, so that folks don't
have to override versions eh?

- I would love to see some documentation in the readme. Including where
folks need to place the deps.

- Warning to stdout when the dep can't be found works fine.

Thanks for working on this!!  I should have done it long ago but I use
inf-clojure.

**Comment by bhauman** [comment]
One more thing: you can add stuff to the config.clj to turn those symbols
into strings so they can be serialized for lein if you want.  That file
keeps growing with exceptional cases.

**Comment by otijhuis** [comment]
It's my pleasure. Just glad I'm able to help. Figwheel is making things so much easier. So thanks to you :)

I'll remove the defaults. Then there are no assumptions of what is being loaded. I'll add some documentation as well on the nrepl page with an example of how to enable cider/refactor-nrepl/piggieback. Warnings will go to stdout then.

As for the piggieback dependency, besides the middleware, another function also depends on it. Looks like that will be the only part left that depends on piggieback.

```clojure
(defn repl
  ([build figwheel-server]
   (repl build figwheel-server {}))
  ([build figwheel-server opts]
   (let [opts (merge (assoc (or (:compiler build) (:build-options build))
                            :warn-on-undeclared true)
                     opts)
         figwheel-repl-env (repl-env figwheel-server build)]
     (if (thread-bound? #'nrepl-eval/*msg*)
       (cemerick.piggieback/cljs-repl
        :repl-env figwheel-repl-env
        :special-fns (or (:special-fns opts) cljs.repl/default-special-fns))
       (cljs.repl/repl* figwheel-repl-env (assoc opts :compiler-env (:compiler-env build)))))))
```

How do you want me to handle that part?

**Comment by otijhuis** [comment]
I'll leave the dependency in for now and will create a new issue to remove it as a dependency. That way things stay separate.

Will leave piggieback in the middleware defaults for now as well and only remove cider.

Until dependency is removed maybe upgrade piggieback to 0.2.1 from 0.1.5?

**Comment by bhauman** [comment]
I don't use piggieback but I remember piggieback 0.2.1 required a newer
release of nrepl.

Which would force folks to manually require nrepl 0.2.10 otherwise figwheel
won't launch?

I messed with this a bunch and it was pretty brittle back when I tried it
but the bottom line is that I think we should leave as 0.1.5 or get rid of
it.

I really want lien figwheel to work with earlier versions of lein so that
folks don't have a bad time of it.

**Comment by otijhuis** [comment]
Ah ok, didn't know that.

Do you want to get rid of piggieback completely in the code or make the user responsible for adding the dependency? Could do the *require?* "trick" with the remaining piggieback code but that means the user would have to add the dependency to make it work.

**Comment by bhauman** [comment]
Yeah, I think folks should have to explicitly add the dependencies for
their nrepl setup.  Too complex and the defaults just get in the way.
probably should do the same with cider. Huh?

**Comment by otijhuis** [comment]
Already removed cider from the defaults so only piggieback is left. I will mention in the readme how to add cider/refactor-nrepl and that they have to make sure themselves that they are on the classpath.

In case of the *repl* function mentioned a few comments above, what should happen when #'nrepl-eval/*msg* is bound? Could use *require?* to check if piggieback can be loaded and remove the hard dependency from the ns but don't know what to do when piggieback isn't available.

**Comment by otijhuis** [comment]
Created a pull request for the configuration/documentation part and created a new issue for the piggieback dependency. I'll look into that later.

**Comment by bhauman** [comment]
I guess we could just check if piggieback is there otherwise launch the regular cljs repl.

**Comment by bhauman** [comment]
Lets call this one fixed :)
