### ISSUE TITLE
Indicator doesn't escape (some) errors

### ISSUE THREAD

**Issue by JulianLeviston** [bhauman/lein-figwheel#183]
I just had the following error and the HTML seemed to be saying that the missing thing was blank. This was because I hadn't included the core.async "<!" function, but I think the HTML output isn't escaped, possibly. (The HTML output just said "Use of undeclared Var gc.block/")

         [Warning] Figwheel: Compile Warning - Use of undeclared Var gc.block/<! at line 485 src/gc/block.cljs (utils.js, line 58)

**Comment by bhauman** [comment]
Good catch!!!

**Comment by bhauman** [comment]
fixed with 
8a23e48f56519c7279f0433e38fb02596722817e
