### ISSUE TITLE
Is there a way for code to check whether it's running in a figwheel environment?

### ISSUE THREAD

**Issue by joebadmo** [bhauman/lein-figwheel#184]
Currently, I have separate `index.html` files for figwheel vs prod, and in the figwheel one I export a variable that I can check in code, but is there a less gross way to do this?

**Comment by bhauman** [comment]
You could check to see if `js/figwheel` is defined.  Is that helpful?

**Comment by joebadmo** [comment]
Yep, thanks, I should've thought of that!
