### ISSUE TITLE
Changes in .cljc files

### ISSUE THREAD

**Issue by mathpunk** [bhauman/lein-figwheel#185]
I am working my way through the Figwheel Quick Start by making it into an org-babel file that emits all the necessary files when I tell it to tangle. It seems to have led me to a response that might help distinguish between figwheel being happy and sad about the new .cljc extension.

If I tangle my source to a file called core.cljs, then lein figwheel works as intended. And if I make changes and re-tangle, figwheel recompiles and everything works. 

If, instead, I tangle my source to a file called core.cljc, lein figwheel still runs it with no problem. However, if I make changes and re-tangle, I get the following errors in the browser and the console:

in the browser:
Compile Error
java.io.FileNotFoundException : Could not locate hello_seymore/core__init.class or hello_seymore/core.clj on classpath: 

in the logs:
Compiling "main.js" from ["src"]...
Compiling "main.js" failed.
java.io.FileNotFoundException: Could not locate hello_seymore/core__init.class or hello_seymore/core.clj on classpath: 
 at clojure.lang.RT.load (RT.java:443)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojurescript_build.core$reload_lib.invoke (core.clj:40)
    clojurescript_build.core$handle_source_reloading_STAR_.invoke (core.clj:133)
    clojurescript_build.core$handle_source_reloading.invoke (core.clj:139)
    clojurescript_build.core$build_source_paths_STAR_.invoke (core.clj:151)
    figwheel_sidecar.auto_builder$default_build_options$fn__17650.invoke (auto_builder.clj:78)
    figwheel_sidecar.auto_builder$insert_figwheel_connect_script$fn__17683.invoke (auto_builder.clj:179)
    figwheel_sidecar.auto_builder$warning$fn__17647.invoke (auto_builder.clj:73)
    clojurescript_build.auto$time_build$fn__17443.invoke (auto.clj:55)
    clojurescript_build.auto$after$fn__17449.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__17449.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__17449.invoke (auto.clj:64)
    clojurescript_build.auto$error$fn__17452.invoke (auto.clj:71)
    clojurescript_build.auto$before$fn__17446.invoke (auto.clj:60)
    clojurescript_build.auto$make_conditional_builder$fn__17464.invoke (auto.clj:103)
    clojure.core$mapv$fn__6311.invoke (core.clj:6353)
    clojure.lang.ArrayChunk.reduce (ArrayChunk.java:58)
    clojure.core.protocols/fn (protocols.clj:98)
    clojure.core.protocols$fn__6057$G__6052__6066.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:60)
    clojure.core.protocols$fn__6031$G__6026__6044.invoke (protocols.clj:13)
    clojure.core$reduce.invoke (core.clj:6289)
    clojure.core$mapv.invoke (core.clj:6353)
    clojurescript_build.auto$autobuild_STAR_$fn__17550$state_machine__9177__auto____17551$fn__17556.invoke (auto.clj:186)
    clojurescript_build.auto$autobuild_STAR_$fn__17550$state_machine__9177__auto____17551.invoke (auto.clj:177)

I hope this is helpful.

**Comment by bhauman** [comment]
If changes to cljc files work with figwheel alone, is my primary consideration.  It's really hard to know how these other things affect the system.

Please let me know if this problem persists outside of org-babel.

I personally have no idea how an org-babel file and tangle work. Having never used them. I just looked at it and it looks really cool, though.

On a side note: I have put a lot of effort into cleaning up Devcards and making them into something that you can use easily right along with your code.  I'm going to work on the read me today. If you are interested I'd be happy to walk you through it.

**Comment by bhauman** [comment]
Actually after some reflection. I think that this isn't working because you are somehow not using the right version of clojure for the recompile somehow.  I bet that is it.  make sure you are using "1.7.0-beta3" or "1.7.0-RC2" etc.

**Comment by mathpunk** [comment]
I think that's exactly what wasn't working. I will check out Devcards next.
