### ISSUE TITLE
error with large websocket messages

### ISSUE THREAD

**Issue by noisesmith** [bhauman/lein-figwheel#194]
```
cljs.user=> @kingfisher.core/kingfisher
Wed Jul 01 13:00:12 PDT 2015 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Eval timed out!
```

This seems to be an issue with the http-kit version that is fixed with a newer http-kit?

https://github.com/http-kit/http-kit/issues/179

**Comment by bhauman** [comment]
just deployed 0.3.6.  Let me know it the http-kit bump fixes it for you.

**Comment by bhauman** [comment]
darn that was a miss deploy.  I will redeploy 0.3.7 shortly. :(

**Comment by noisesmith** [comment]
0.3.7 still has this issue. Oh, what a rabbit hole - maybe you need this workaround? https://github.com/http-kit/http-kit/issues/191 ? Bigger mess than I expected there. Thanks for being so responsive about this.

**Comment by dpetrovics** [comment]
Any progress here? I just ran into this issue

**Comment by thomas-morgan** [comment]
I'm also encountering this with 0.4.1 as well as today's 0.5.0-SNAPSHOT (2d7bf794e41f1bd1fb7be7863425cb46760a2072).

**Comment by conan** [comment]
I get this pretty regularly when trying to reference the app state of my reagent applications.  it generally seems to be to do with having multiple browser tabs connected to figwheel, which makes sense.  I'd really like to know whether there's any way back after it's occurred - at the moment i have to bounce figwheel, which is fairly painful.

**Comment by cvermilion** [comment]
I ran into this issue today, using figwheel 0.5.2. I could fix it by upgrading the `http-kit` dependency to either `[com.taoensso.forks/http-kit "2.1.20"]` or `[http-kit "2.2.0-alpha1"]` (and depending on `sidecar` with an exclusion: `[figwheel-sidecar "0.5.2" :exclusions [http-kit]]`.

**Comment by bhauman** [comment]
Did that fix it??  If so I'll update the dependency to 2.1.20

**Comment by hoeck** [comment]
I had the same issue, albeit with boot-cljs and weasel 0.7.0 (which pulls in http-kit for me). Upgrading http-kit to `[com.taoensso.forks/http-kit "2.1.20"]` solved it for me.

**Comment by Kaffeleif** [comment]
Same issue here, upgrading http-kit to [http-kit "2.1.21-alpha2"] fixed the issue for me.

**Comment by ingesolvoll** [comment]
Same thing happens in figwheel 0.5.4-SNAPSHOT when I try to `swap!` a huge state atom. Using latest alpha of http-kit removed it

**Comment by bhauman** [comment]
just waiting on http-kit to get to a non alpha release

**Comment by grav** [comment]
Seems `2.1.x` is now legacy. There's a `2.2.0` here: https://github.com/http-kit/http-kit#a-high-performance-event-driven-http-clientserver-for-clojure

**Comment by bhauman** [comment]
Looks like its finally time to integrate this.
