### ISSUE TITLE
Simple Cursive REPL integration wiki documentation?

### ISSUE THREAD

**Issue by swannodette** [bhauman/lein-figwheel#196]
Yesterday I discovered it's possible to run Figwheel as a simple REPL that Cursive can interact with (via the `clojure.main` option). It's far simpler to setup than the existing Cursive instructions. Would you be OK with me documenting this in the wiki?

**Comment by bhauman** [comment]
Please do!!!

**Comment by bhauman** [comment]
Do you have any strong feelings about #143?

**Comment by swannodette** [comment]
The basics are done. Feel free to tweak.

**Comment by swannodette** [comment]
@bhauman I don't! The community ClojureScript logo is great and I suspect there will never really anything more official than the Clojure one.
