### ISSUE TITLE
Figwheel Brand + Website

### ISSUE THREAD

**Issue by Prathyvsh** [bhauman/lein-figwheel#197]
First of all, thanks 1,000 figs for making Figwheel. I counted and by now, it has saved me more than a million seconds in reloading time and taking my apps to their correct state. It's payback time.

# Previous Conversation
Not sure if you remember, but we conversed on Twitter earlier and I showed you some [inferior work](https://twitter.com/prathyvsh/status/574275537335619585) with some Fig mascots. It was mostly me trying to distract myself from doing my dissertation, but now that's done and dusted and I'm back to my design+dev career. I loved Figwheel the very first time I encountered it;  I had already used a few different reloader frameworks by then and this was something substantially better. Yesterday, I finished watching your Clojure/West talk and was motivated to finish up this branding for a Figwheel that was laying around for a while now. Here's what I have built with my brother:

# Our work

![FGWL Brand](https://cloud.githubusercontent.com/assets/6199967/8509488/72490f24-229e-11e5-8d3f-bba762ce039f.png)

# Rationale

## Icon
We have gone for a pretty detailed look for the main icon and I think if you ever need to have a dock icon or a desktop icon, this one can be used and there's plans for a monochrome version if you approve this one.

## Palette
The colour palettes were mostly stolen off of some fig images on Google and Pinterest. Can make them more muted or vibrant as per your suggestion.

## Typography
Typeface chose is Avenir and we can help with grids and line widths if you think the typeface matches the feel you intend to have for the Brand. I think we can also go for some rounded/playful typefaces, if you so prefer.

## Mascot(s)
I named the mascot - Figgy. Totally open for a new name as I'm darn sure that one's way too cheesy. Lastly, those mascots that at the end are the new ones I have created and I have a few funny transitions from one to the other with color and mood change in my mind, but like all the above stuff, I need to get your green signal here as well. 

## Feedback
Almost everything shown here is tentative and we wanted to get your (@bhauman) opinion and also anyone else's on the initial vector. Any appreciation/critique/comments (preferably constructive criticism) are always welcome!

# Ideas for the Future
- Animate the mascots with SVG animation.
- Monochrome logo for various other contexts like favicon.
- When making the website, copy button copies the current Lein version to clipboard.
- Animate the main logo with a subtle spin on the inner juicy bits.
- Polish a lot of rough edges here and there that we are not entirely satisfied with.

P.S (More like shameless plug): That detailed version of Fig is created by my brother and all the rest is my work, we collectively go by the name of Prabros. You can check out our work [here](http://dribbble.com/pranav) and [here](http://dribbble.com/prathyush).

**Comment by bhauman** [comment]
This is really great work.  Thank you.  

I feel a bit uncomfortable though.  Even though I personally have put a lot of time into figwheel my main feeling is that it belongs to the community and I really don't want to brand in a direction that differentiates from the community.  In fact, I really don't want to brand at all.  

My overriding feeling is that as programmers we are all in this together. We all face and extremely tough uphill battle of creating things that actually solve problems and create value for others.

I understand the value that branding, PR, marketing brings to the table but for the most part I associate it with the concerns of a separate entity trying to differentiate itself and stand out from the crowd.

Figwheel's presentation to the world right now is simple and honest. It's not pretending to be more than it is.  I like that. I much prefer humility and honest growth.

If Figwheel does have a brand I want it to be joining a larger collective, say Clojure's and ClojureScript's, and not just differentiating itself.  Figwheel is literally nothing without the accumulation of the millions of good decisions that have manifested as Lisp, JVM, Clojure, ClojureScript, Google Closure, Reactjs and the absolutely incredible JavaScript engines etc. 

So yes I personally feel uncomfortable with this. Also, as figwheel is the result of a lot of personal effort, I may just be wanting a lot of personal control over how it is portrayed to the world. If I do want to set up a clean website, I think I'd like the opportunity to exercise my creativity and express it. 

I have gratitude for your appreciation and effort. And while it is attractive, fun and light hearted (all qualities I appreciate) my current position is to not use the branding above.  If in the future I do want to do some work with Figwheel's presentation, and you are willing, I'd love to chat.

Thank you soooo much for liking Figwheel enough to do this ...

**Comment by Prathyvsh** [comment]
Your concerns are legitimate and I appreciate the honesty and zero pretence nature of the stuff you said. I can totally understand when you say that you want it to be simple, straightforward and not alienate it from the community. No worries as this was much fun to do on it's own :) And about the presentation thing, do hit me up or send me a DM on Twitter when you prefer. Thanks again for helping a considerable amount of developers like me from keeping them away from doing the stuff that computers ought to do.

**Comment by skippednote** [comment]
@Prathyvsh Great work here.

**Comment by JulianLeviston** [comment]
@Prathyvsh could you close this now, please?
