### ISSUE TITLE
Compile error re-compiling cljc file

### ISSUE THREAD

**Issue by tdavis** [bhauman/lein-figwheel#198]
I'm having a pretty strange issue with figwheel. I have a project that includes mixed clj/cljs/cljc files. Figwheel works just fine when automatically recompiling cljs files that change. However, when recompiling cljc files, it fails. The strange part is, the stated error and line don't even exist in the source file anymore. If I stop and start figwheel, it compiles everything properly. I've tried `lein clean`, deleting the `target` directory, deleting the ``js/out`` directory...

I don't know if this is caused by figwheel or cljsbuild or what, or how I could possibly remove the phantom file or whatever is causing it. Has anyone seen this?

**Comment by bhauman** [comment]
Hmmm really not enough information here. Could you make a tiny example of this?

**Comment by tdavis** [comment]
So sorry, this was my error: I had an outdated file in another location assigned the same namespace which, for whatever reason, was picked up by the reload but not the original compile.
