### ISSUE TITLE
Deployment Guide

### ISSUE THREAD

**Issue by JulianLeviston** [bhauman/lein-figwheel#199]
Currently, to deploy I have to do a whole bunch of argy-bargy: comment out the figwheel NS require in my core.cljs file, ensure the figwheel start is commented out, deploy using my prod build, and then remove the dev tempfiles that were created on the dev branch. Then, to switch back to dev, I have to uncomment figwheel and kind of reverse that.

I'm pretty sure I've seen recommendations about how best to deploy around *some*where. Would it be possible to write a short deployment guide on best practices for ensuring an easy path to getting a deployment build without going through a 5 step procedure?

**Comment by bhauman** [comment]
Julian the latest versions of figwheel have a :figwheel true flag that you add to your dev build. You shouldn't be calling figwheel start explicitly anymore.  Please see the readme and the quick start.

**Comment by JulianLeviston** [comment]
Excellent! Thanks. I actually read the quickstart, but I obviously didn't read it well enough, did I! :)
