### ISSUE TITLE
Create a figwheel-noop version for production

### ISSUE THREAD

**Issue by pangloss** [bhauman/lein-figwheel#20]
I'd like to be able to compile releases without having to strip figwheel out of my sources beforehand. I think it would be possible to create a separate project to depend on for the release build that contains the same figwheel namespaces and public functions, but which simply does nothing. I'm not completely certain that would work, but I can't think of why it wouldn't.

**Comment by dchacke** [comment]
I don't think this works anymore as of today. What is the correct approach for this now?
