### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 414

### ISSUE THREAD

**Issue by smnirven** [bhauman/lein-figwheel#200]
I'm attempting to get figwheel setup & running, and am using the Quick Start page https://github.com/bhauman/lein-figwheel/wiki/Quick-Start

I'm able to get main.js to compile, and I'm loading my index.html page from the file system. With lein figwheel running in my project, I'm getting these errors in the Chrome Dev console:

```WebSocket connection to 'ws://localhost:3449/figwheel-ws/dev' failed: Error during WebSocket handshake: Unexpected response code: 414```

Here's my project.clj file. I'm using Clojure 1.7, figwheel 0.3.7, and clojurescript 3308

```(defproject pgtest "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "0.0-3308"]]
  :plugins [[lein-cljsbuild "1.0.5"]
            [lein-figwheel "0.3.7"]]
  :clean-targets ^{:protect false} [:target-path "out"]
  :cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]
              :figwheel true
              :compiler {:main pgtest.core}}]})```

**Comment by bhauman** [comment]
Hey can you tell me the OS and browser that you are using as well?

Sorry for not getting back to you sooner on this.

**Comment by smnirven** [comment]
Mac OSX 10.10.4 (Yosemite)
Chrome 43.0.2357.134 (64-bit)

**Comment by smnirven** [comment]
By the way - I think I figured out what the issue was. I had the Mac firewall enabled -- I just tried disabling the firewall and it seems to work now.

**Comment by smnirven** [comment]
Yep, confirming I'm all set now -- closing the issue
