### ISSUE TITLE
figwheel not loading a NS

### ISSUE THREAD

**Issue by ohlo** [bhauman/lein-figwheel#202]
Hi. I am on 0.3.7 figwheel with setup as recommended in README.

I have a ns which just contains a defmethod fn. when changed, i get 

'Figwheel: NOT loading these files '.  next line says 'not required ...'

keep up the good work.
Henry

**Comment by bhauman** [comment]
Not much info here but I'm guessing that you didn't require the namespace in your core namespace.  Figwheel doesn't load files that aren't required. 

By the tone of your request it might be possible that you are being snarky. I'm going to assume that isn't the case.

**Comment by ohlo** [comment]
Absolutely not being snarky! Figwheel has been a great help and I've been
using it from v.early on.

Also Thanks for info

**Comment by ohlo** [comment]
requiring worked a treat.

**Comment by bhauman** [comment]
Sorry for the misunderstanding it was early and have a negative bias in the morning :). 

Glad you were able to fix it.

**Comment by ftravers** [comment]
Another gotcha I've found is if you include a file that also adds the (ns ^:figwheel-always ...) metadata, only the included file will get reloaded by figwheel.  The includer will not get reloaded by figwheel.
