### ISSUE TITLE
cider/inf-clojure not working

### ISSUE THREAD

**Issue by xificurC** [bhauman/lein-figwheel#203]
Hi,

first of all thanks for this plugin! I'm having issues getting the figwheel repl working in emacs. Concentrating on the simpler, `inf-clojure` solution stated in the wiki I run into this error

    Exception in thread "main" java.io.FileNotFoundException: Could not locate figwheel_sidecar/repl_api__init.class or figwheel_sidecar/repl_api.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:(c:\home\code\cljs\hello_seymore\script\repl.clj:1:1)
	    at clojure.lang.Compiler.load(Compiler.java:7239)
	    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	    at clojure.main$load_script.invoke(main.clj:275)
        ...

This is my project.clj

    (defproject hello-seymore "0.1.0-SNAPSHOT"
      :dependencies [[org.clojure/clojure "1.7.0"]
                     [org.clojure/clojurescript "0.0-3308"]
                     [sablono "0.3.4"]]
      :plugins [[lein-cljsbuild "1.0.6"]
                [lein-figwheel "0.3.7"]]
      :clean-targets ^{:protect false} [:target-path "out"]
      :cljsbuild {
                  :builds [{:id "dev"
                            :source-paths ["src"]
                            :figwheel true
                            :compiler {:main hello-seymore.core}}]})

I'm following the steps described in [this](https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-with-Emacs-Inferior-Clojure-Interaction-Mode) wiki page and get this when running `M-x figwheel-repl` from the project file's buffer.

**Comment by bhauman** [comment]
Unfortunately that documentation is very advanced and makes a lot of assumptions.  I didn't write the documentation on that wiki page and haven't tried it.  That being said you have to have a directory of jars on you classpath for those instructions to work.  

It is probably going to be easier for you to use `inf-clojure` with the `lein figwheel` command.

**Comment by xificurC** [comment]
I see. I'd suggest doing something with the wiki pages then, either marking them incomplete/advanced or asking the author to go more in depth.

Thank you for the information!

**Comment by bhauman** [comment]
I just updated the wiki page. Much easier now.  Let me know if you have an issue.

**Comment by xificurC** [comment]
That was quick, thanks a lot!

**Comment by decoursin** [comment]
I think you're just missing a dependency on [figwheel-sidecar "0.5.0-SNAPSHOT"]. Not sure though.

**Comment by flexsurfer** [comment]
wiki/Running-figwheel-in-a-Cursive-Clojure-REPL doesn't work for me, have the same error

**Comment by leonfs** [comment]
Thanks @flexsurfer! restarting Intellij worked.

**Comment by flexsurfer** [comment]
I think the issue is the figwheel doesn't work with Intellij lein, so, you should manually reinit dependencies
