### ISSUE TITLE
sablono require documentation issue

### ISSUE THREAD

**Issue by chrismurrph** [bhauman/lein-figwheel#208]
From Quick Start tutorial. There was a problem with the require for sablono. I referred to this issue to fix it up:
https://github.com/r0man/sablono/issues/11
```clojure
(ns hello-seymore.components
  (:require [sablono.core :refer-macros [html]]))
```

**Comment by bhauman** [comment]
Hey Chris,

This works for me. For the versions supplied in the Quick Start.  ClojureScript does not require to explicitly require the macros if the core.cljs file of the lib requires the macros file. Its a trick but it works.

Please let me know the versions you are running. And please refer me to the example you are talking about.  

In the examples all the references to the `html` macro are prefixed as such: `(sab/html` and it should work like that.

Hope this helps.

**Comment by chrismurrph** [comment]
Hey Bruce, 
As an aside I'm looking at Clojurescript, actually coming from Scala.js.
My dependencies are straight from your document: 
```clojure
:dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-3211"]
                 [sablono "0.3.4"]] 
```
The exact example is hello_seymore when you have just split the code into core.cljs and components.cljs. I noticed as well that there's a requirement for sablono in core.cljs which is not necessary. I'll put my version up on Github soon, and get back to you here...
