### ISSUE TITLE
"quick start" build scripts

### ISSUE THREAD

**Issue by shaunlebron** [bhauman/lein-figwheel#209]
The build scripts found in the [CLJS Quick Start] perhaps represent the standard way for building ClojureScript projects now, whereas most projects are still using cljsbuild.  Oftentimes for reporting bugs, building with just these scripts helps rule out the possibility that cljsbuild may be interfering.  To see a popular template which omits cljsbuild, see [mies].

Some thoughts on integrating Figwheel with these build scripts:

1. __config__: build scripts use inline config whereas cljsbuild places them in project.clj. perhaps create a common `builds.edn` file at root?
1. __scripts__: we can probably omit the `watch` and `repl` scripts since figwheel takes care of these use-cases. the `build` and `release` scripts should have build parity with figwheel so they can be executed on their own (for build process visibility or for use in CI).

[mies]:https://github.com/swannodette/mies
[CLJS Quick Start]:https://github.com/clojure/clojurescript/wiki/Quick-Start

**Comment by bhauman** [comment]
Now these would go in the figwheel template right?

**Comment by bhauman** [comment]
figwheel could look for a clojurescript-builds.edn, project.clj and perhaps some other standard.

**Comment by bhauman** [comment]
I'm going to call this closed eh?
