### ISSUE TITLE
Configuration for figwheel not to start its internal server?

### ISSUE THREAD

**Issue by jakubholynet** [bhauman/lein-figwheel#211]
Is there a way to tell figwheel not to start its server? I serve the static html that includes my cljs code from my Node server and don't need another server running. Though it is of course a very minor thing. Thank you!

**Comment by bhauman** [comment]
The server that is being used is the web socket server that fig wheel is using to communicate that files have changed. So if the server doesn't run you don't get reloads.  :)

**Comment by jakubholynet** [comment]
Oh I see. Thank you!
