### ISSUE TITLE
debug figwheel from another computer, can't connect

### ISSUE THREAD

**Issue by jiyinyiyong** [bhauman/lein-figwheel#212]
I'm trying to run web page from another laptop but `socket.js` is keep connecting to `localhost:3449`. Is there a config that I can tell figwheel to change its websocket.url ?

**Comment by rasmuserik** [comment]
I had the same problem. Solved it by setting the `:websocket-host` in the `:figwheel` part of the `:cljsbuild`-section to the current IP-address, - which I find by `~(.getHostAddress (java.net.InetAddress/getLocalHost))` in project.clj. - it is a hack, but it works for me.

**Comment by jiyinyiyong** [comment]
I was following https://github.com/omcljs/om/wiki/Basic-Tutorial and currently found no `websocket-host ` in my project files.

**Comment by bhauman** [comment]
Hey please see this part of the figwheel readme.
https://github.com/bhauman/lein-figwheel#client-side-configuration-options

**Comment by rasmuserik** [comment]
You can open `project.clj`, and change the line saying

    :figwheel { :on-jsload "om-tut.core/on-js-reload" }

to

    :figwheel 
    {:on-jsload "om-tut.core/on-js-reload"
     :websocket-host ~(.getHostAddress (java.net.InetAddress/getLocalHost))}

and see if that works.

Disclaimer: I am not an expert in figwheel, - I just had the same issue, and found this workaround.

Maybe it would make sense to add a note about this in the documentation, or perhaps even connect to the public IP-address instead of localhost by default?

**Comment by jiyinyiyong** [comment]
Your solution works and thanks.

Actually I wrote configs to `/etc/hosts` to change the DNS settings. And `repo` is mapped to my IP.

```clj
:figwheel { :on-jsload "om-tut.core/on-js-reload"
            :websocket-host "repo"}
```
