### ISSUE TITLE
Support case-sensitive filesystems.

### ISSUE THREAD

**Issue by pepijndevos** [bhauman/lein-figwheel#214]
I'm getting 404 for the Closure library.

```
Request URL: http://localhost:3449/js/compiled/out/goog/net/XhrIo.js?zx=sr3bdn3l6dm9
Request Method: GET
Status Code: 404 Not Found
```

But the file is there alright.

```
$ ls resources/public/js/compiled/out/goog/net/
errorcode.js			jsloader.js			xhrio.js			xmlhttpfactory.js
eventtype.js			websocket.js			xhrlike.js			xpc
httpstatus.js			wrapperxmlhttpfactory.js	xmlhttp.js
```

And indeed `http://localhost:3449/js/compiled/out/goog/net/xhrio.js` loads just fine.

**Comment by bhauman** [comment]
Actually this is an error that is fixed in 0.3.8-SNAPSHOT, could you try
that out and see if it works for you?

**Comment by pepijndevos** [comment]
Works like a charm!

**Comment by bhauman** [comment]
Also in that version you can just create Google Closure js files right next
to your cljs files and work with them live.  It's pretty cool.
