### ISSUE TITLE
Error on cljs.test/run-tests

### ISSUE THREAD

**Issue by rhacker** [bhauman/lein-figwheel#215]
Hi,
Firstly, thank you for an amazing plugin. I'm playing around with it, trying to setup an auto testing environment with the `test-runner` like so : 
```
(ns router.test-runner
  (:require [cljs.test :refer-macros [is testing deftest run-tests]]
            [router.core :refer [slash-count]]
            [figwheel.client :as fw]))

(enable-console-print!)

(deftest slash-count-test
  (testing "Examples"
    (is (= true false))
    (is (= (slash-count "/test/something/") 1))))

(fw/watch-and-reload
 :websocket-url "ws://localhost:4449/figwheel-ws"
 :on-jsload #(run-tests))
```

But I got an error on the run-tests line like so 
```
Use of undeclared Var cljs.core/vswap! at line 15 test/router/test_runner.cljs
```

I'm confused what is the problem here ?

**Comment by bhauman** [comment]
You probably need to make sure you have cleaned your source by deleting
previously compiled artifacts. `lein clean` will help you with this, if you
have it configured to delete your compiled cljs.

Also this looks a lot like an older version of cljs is trying to mix with
code generated by a newer version of cljs or the other way around.

You also have to wait for things to compile before you initially load them
into the browser.

So make sure you have the latest cljs, the latest figwheel, and make sure
you have cleaned out previously compiled files.

**Comment by rhacker** [comment]
@bhauman thanks for the answer. I have setup the `lein clean` but it doesn't help me. Do you have any good example or template on setting up auto test properly. I have tried the code in your crashverse project.
