### ISSUE TITLE
quick start issue

### ISSUE THREAD

**Issue by pbaille** [bhauman/lein-figwheel#216]
Hello,

I'm following quick start tutorial and got this error:

$ lein figwheel
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: dev
Compiling "main.js" from ["src"]...
Compiling "main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: No such namespace: hello-seymore.core, could not locate hello_seymore/core.cljs, hello_seymore/core.cljc, or Closure namespace "hello-seymore.core" at line 1 target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)

Started Figwheel autobuilder

Launching ClojureScript REPL for build: dev
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (fig-status)                    ;; displays current state of system
          (add-dep [org.om/om "0.8.1"]) ;; add a dependency. very experimental
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when figwheel connects to your application

**Comment by pbaille** [comment]
I'm on osx yosemite and java build 1.8.0_60-b27

I've tried on another computer (mountain lion, java build 1.8.0_60-b27) and cannot reproduce the error.

i've got the same error when using: lein new figwheel my-project

Any help will be greatly appreciated

thanks

**Comment by bhauman** [comment]
Pierre,

Would love to help here.

Can you tell me where in the tutorial you got this error.  I'm thinking
that you may have named the file hello-seymore.cljs and not
hello_seymore.cljs.

But that is a guess can you push your failing project to github so I can
see what went wrong?

**Comment by pbaille** [comment]
Hi, 

thank you for your answer, here's a repository with my failing project https://github.com/pbaille/figquick

**Comment by pbaille** [comment]
I do not think it's faulty code, i should comes from elsewhere (maybe leiningen? yosemite?)
here's the error for this project: 

$ lein figwheel
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: dev
Compiling "main.js" from ["src"]...
Compiling "main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: No such namespace: figquick.core, could not locate figquick/core.cljs, figquick/core.cljc, or Closure namespace "figquick.core" at line 1 target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)

Started Figwheel autobuilder

Launching ClojureScript REPL for build: dev
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (fig-status)                    ;; displays current state of system
          (add-dep [org.om/om "0.8.1"]) ;; add a dependency. very experimental
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when figwheel connects to your application

**Comment by pbaille** [comment]
Leiningen 2.5.2 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM 
Yosemite 10.10.5

**Comment by bhauman** [comment]
So I  don't think it's java or lein or yosemite.  

Do you have a ~/.lein/profiles.clj  ?

If so remove it and try it again.

**Comment by pbaille** [comment]
here's my ~/.lein/profiles.clj:

{:user {:dependencies [[org.clojure/tools.namespace "0.2.3"]
                       [spyscope "0.1.3"]
                       [criterium "0.4.1"]
                       #_[com.gfredericks/debug-repl "0.0.6"]
                       #_[org.clojure/tools.nrepl "0.2.10"]
                       ]
        :injections [(require '(clojure.tools.namespace repl find))
                     ; try/catch to workaround an issue where `lein repl` outside a project dir
                     ; will not load reader literal definitions correctly:
                     (try (require 'spyscope.core)
                       (catch RuntimeException e))]
        :plugins [[lein-pprint "1.1.1"]
                  [lein-beanstalk "0.2.6"]
                  [lein-clojars "0.9.1"]
                  [lein-create-template "0.1.1"]
                  [lein-marginalia "0.7.1"]
                  [http-kit/lein-template "1.0.0-SNAPSHOT"]]}
        ;; :repl-options
        #_{:nrepl-middleware
          [com.gfredericks.debug-repl/wrap-debug-repl]}
        }

removing it doesn't change anything

**Comment by pbaille** [comment]
i've also tried to remove ~/.m2 just it case but same issue

**Comment by bhauman** [comment]
I will update my dependencies and see what happens. 

The profiles is the most likely candidate. I'm assuming you did a college try on that with a `lein clean` and everything?

**Comment by pbaille** [comment]
yes i've tried with lein clean and both empty profiles hash-map and no profiles.clj file, but it doesn't change the error, thank you.

**Comment by bhauman** [comment]
Well I have created a new release 0.3.9.  I have updated the Quick Start.  I'm hoping that if you are still interested that this will fix your issue.

**Comment by pbaille** [comment]
thank you a lot, I will try tomorow and let you know.

**Comment by pbaille** [comment]
unfortunately it doesn't change anything to my error.

**Comment by bhauman** [comment]
So I am on the same system that you are.

I'm using the repository you prodived to me.

How specifically is this failing?

**Comment by pbaille** [comment]
it is the same:

Compiling "main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: No such namespace: figquick.core, could not locate figquick/core.cljs, figquick/core.cljc, or Closure namespace "figquick.core"
 at clojure.core$ex_info.invoke (core.clj:4593)

thank you a lot for your time

**Comment by otijhuis** [comment]
If you're still running into the same issue, could you add all directories/files to your github repo? `target` is missing for instance. I'm running on pretty much the same system as well and can't reproduce it either.

**Comment by pbaille** [comment]
thank you, I will do so later today.

**Comment by pbaille** [comment]
Hi!

Finally i find where the issue comes from... classpath problem with leiningen, it comes from a folder name cointaning slash character...  thank you for all
