### ISSUE TITLE
No connection script for node

### ISSUE THREAD

**Issue by TerjeNorderhaug** [bhauman/lein-figwheel#217]
0.3.7 no longer generates a connection script for Node, failing to require "figwheel.connect". The cause is that require-connection-script-js explicitly bypass when target is nodejs. This flaw was introduced on Jun 26 in commit 9bc615b4d06b840506798b985d3a00c52003527f.

**Comment by bhauman** [comment]
Didn't know that Node worked :)

Just deployed the change to 0.3.8-SNAPSHOT

Now it works whether you are using `:main` or not.
