### ISSUE TITLE
Isomorphic Figwheel?

### ISSUE THREAD

**Issue by jcw** [bhauman/lein-figwheel#219]
It's probably a confusing term to use for this scenario, but is it possible to set up FW so it gets used for _simultaneous_ development in CLJS on both the server and the browser, i.e. two REPLs?

I'm looking for a reasonably robust and practical development workflow, mostly for a single Mac laptop setup, but possibly also with the server side running on a Raspberry Pi.

As far as I can tell, this will need four processes running:
* lein figwheel (i.e. jvm) for the server (based on malyn/figwheel-node-template)
* nodejs (i.e. v8) running the actual server code, i.e. as http + app server for browsers
* lein figwheel (a 2nd jvm) for client auto compiles and REPL
* a browser, such as Google Chrome or Safari (v8 or webkit)

Has anyone tried this? Any pointers?
Could this be simplified further, perhaps even to a single switchable REPL?

**Comment by bhauman** [comment]
The example project in the figwheel code base is isomorphic.  A single figwheel process can build and connunicate with multiple builds.  Figwheel does repl switching.

**Comment by bhauman** [comment]
The example project in the figwheel code base is isomorphic.  A single figwheel process can build and connunicate with multiple builds.  Figwheel does repl switching.

**Comment by jcw** [comment]
Aha! Thanks, I missed that - still in total noob mode. Does this mean I can start a single lein figwheel, and use "(switch-to-build id ...)" to direct it to either node.js or the browser? I'm not running these from the same area, was planning to make each a separate project with their own project.clj files.

Hm, wait, I think you've got it set up with a common project and then server and browser in different subdirs? Having a hard time wrapping my head around this, I'm afraid. With node as server, it needs to hot reload, but also serve application code & assets to the brower, which in turn also hot reloads?

I'll try out the various example modes, thx.

**Comment by TerjeNorderhaug** [comment]
I am working on a template supporting the use of figwheel for isomorphic development. Please check out my cljsnode repository. It runs figwheel concurrently on a nodejs server and your browser. Feedback appreciated.

**Comment by bhauman** [comment]
@jcw please please start small.  Do the quick start. Develop a small front end project first.  Understanding the ins and outs of a cljs figwheel node project is tough and there isn't a lot of guidance.  With experience it's very possible though.

**Comment by bhauman** [comment]
It would make a great blog post though ...

**Comment by jcw** [comment]
Yes, I am trying to start [really small](https://github.com/jeelabs/jet/tree/dev/hub) ...

Would love to blog about this, starting from the current CLJ 1.7.0 & CLJS 1.7.107. No doubt others are also pondering on how to find a way into all this stuff. But _first_ I need to figure it out myself. Will get there - one (baby) step at a time if need be!

@TerjeNorderhaug - that looks _really_ nice. Will examine your project in great detail, thx for the pointer.

**Comment by jcw** [comment]
@TerjeNorderhaug - your cljsnode setup is brilliant:
```
cljs.user=> (fig-status)
Figwheel System Status
----------------------------------------------------
Autobuilder running? : true
Focusing on build ids: app, server
Client Connections
	 server: 1 connection
	 app: 1 connection
----------------------------------------------------
```
Works really well!

**Comment by jcw** [comment]
_(In case anyone is interested in what I'm trying to do...)_

I know I'm aiming too high, but here's the usage scenario I'd love to get going at some point:

1. launch node server, with the intention to keep it running "forever"
2. launch browser to verify everything is working
3. launch figwheel, thus activating auto rebuild and hot reload mode for both
4. develop while staying maximally "in the flow", using Figwheel's hot reload
5. at some point: stop figwheel, close the browser, and get some sleep :)
6. resume at # 2 when ready to work on things some more

This appears to be the opposite way of doing things: server-side code stays up, dev mode merely attaches to it (or more accurately: allows periodic reconnect attempts from server to succeed).

The reason for this is that my server side needs to do data collection & logging & storage, even when no browser is connected. The less it gets restarted, and the less intrusive dev mode is, the better.

It's essentially a form of permanent live coding in a non-critical context. Maybe it's a pipe dream, but I think this sort of development could be nice for certain "tinkering-style" always-on projects.

**Comment by bhauman** [comment]
Yes Figwheel for some reason stops polling for connections on Node after
disconnect.  This isn't the case in the Browser. Not sure why this is.

**Comment by bhauman** [comment]
@jcw Clojure proper would work better for this server use case. If you embed an nREPL server into your server you will be able to connect and alter the code at runtime. 

But .... ya know this isn't the way to go.  Butter to have a rolling deploy that doesn't miss incoming data and dev offline.  You will probably miss more data by messing up the runtime env.

**Comment by jcw** [comment]
Thx - for now I'm just exploring options. I have no idea yet how the JVM and V8 compare, for example, in terms of memory consumption on a Raspberry Pi. One concern is that part of the logic is likely to be (user-contributed) JavaScript code anyway, so then JavaScript interop becomes unavoidable. Running _both_ Node.js _and_ a JVM is likely to be too tight for long-running processes.

I understand your point about not messing with a live server. Perhaps a mix is possible: develop new stuff on a local dev server (possibly getting a feed of the sensor data streams from the main server) - and then only push "reasonably stable" code to the main server. But all this staging does make the dev + deploy cases more complex, and maybe if the server side is fairly minimal occasional tweaks will be ok.

In terms of data loss, I tend to log raw data streams to (text) files anyway, with a replay facility to get back in sync after a restart. If this is done in an MQTT process, then a crash in "the server" is not so dramatic.

Besides: wouldn't it be _fun_ to try and tinker with an always-on system? (without having to use Erlang...)

**Comment by bhauman** [comment]
@jcw very cool, I would definitely use ClojureScript on RasberryPi,  will work much much better.

You know you could create a endpoint on your node server to call figwheel/start with the correct args.  

You could then connect to it with lein figwheel

No reason why that can't work. Not really secure or anything but ....

**Comment by jcw** [comment]
Alas, I'm still trying to wrap my head around who connects where & when in the world of figwheel and friends. Would it be an idea to create one ore more diagrams with [this tool](https://www.websequencediagrams.com/)?

**Comment by jcw** [comment]
Having doodled a bit more with all this, I'm now inclined to decouple things after all: one project with fighweel for a node-based server, and another one for the client. It's not so hard to keep a couple of processes going during development, and probably better matches an always-on-server scenario, while supporting the use of different client-side projects (or revisions).

**Comment by bhauman** [comment]
Cool closing this...
