### ISSUE TITLE
mention template in quick start docs

### ISSUE THREAD

**Issue by jcw** [bhauman/lein-figwheel#221]
It's a matter of personal preference, but would it be an idea to focus on using [figwheel-template](https://github.com/bhauman/figwheel-template) in the [quick start](https://github.com/bhauman/lein-figwheel/wiki/Quick-Start) wiki page?

There is a lot to take in when you get started with ClojureScript and Figwheel. A first success experience could be as quick as going through these three steps: "install leinigen", "lein new ... && cd ... && lein figwheel", "open your browser".

Or perhaps a tl;dr section at the top with this sort of suggestion.

Somewhat related: is there some way to support "+om" iso of "-- -om" for the lein new cmd?

**Comment by bhauman** [comment]
@jcw I here you here. But figwheel-template will only get you so far before you hit a much harder wall.  The history of questions I have received have all been from early users trying to understand how everything works together.

As you will see there is no quick way to do this. The template will hide many many things that folks need to know.  But as things are the template is mentioned in the Readme before the Quick Start.

I am open to a better introduction ... but in reality this is a completely different way of doing things and requires a bit of work.  Hard to get around it. If you would like to create another page about starting with the template I would be open to it for sure.  

The `-- --om` is how lein templates work, if folks are going to use lein its probably important to stick with the defaults to not confuse.

**Comment by jcw** [comment]
Fair enough. I'll close this issue before you beat me to it :)
