### ISSUE TITLE
repl error on using google closure function

### ISSUE THREAD

**Issue by rhacker** [bhauman/lein-figwheel#222]
I try this simple function in repl but it doesn't seem to work.
```
(require '[goog.string :as gstring])
(require 'goog.string.format)

(goog.string.format "%05d" 123)
```

Stack trace
```
#object[TypeError TypeError: goog.string.format is not a function]
          (resources/public/js/test/out/eval at figwheel$client$utils$eval_helper (figwheel/client/utils.js:110:13), <anonymous>:1:101)
          (resources/public/js/test/out/eval at figwheel$client$utils$eval_helper (figwheel/client/utils.js:110:13), <anonymous>:9:3)
          (resources/public/js/test/out/eval at figwheel$client$utils$eval_helper (figwheel/client/utils.js:110:13), <anonymous>:14:4)
         figwheel$client$utils$eval_helper (jar:file:/Users/namename/.m2/repository/figwheel/figwheel/0.3.7/figwheel-0.3.7.jar!/figwheel/client/utils.cljs:47:5)
```

I have tried the same thing on node repl, it seems to work well. I don't know what is the problem :-?

**Comment by bhauman** [comment]
As far as I can tell this is a general Clojurescript question please use clojurians on slack or #clojurescript on irc for questions like these.

In the example above you would use (gstring/format ...)

**Comment by rhacker** [comment]
hmm, I can see that figwheel does use the repl from clojurescript. I will investigate further to see if I can find anything.
gstring/format and goog.string.format both would work without any problem.

**Comment by bhauman** [comment]
This appears to be working now in the latest Figwheel.
