### ISSUE TITLE
is it possible to run fighweel on mobile safari ? 

### ISSUE THREAD

**Issue by jdkealy** [bhauman/lein-figwheel#224]
Loving the feedback loop, but I can't navigate to port 3449 on my mobile device. Has anybody been able to do this ?

**Comment by bhauman** [comment]
You will need to use the `:websocket-host` client config option and set it to your network ip address.


https://github.com/bhauman/lein-figwheel#client-side-configuration-options

**Comment by bhauman** [comment]
Actually there is an undocumented feature,  you can set `:websocket-host` to `:js-client-host`.

I'm going to document it right now.
