### ISSUE TITLE
Node.js repl

### ISSUE THREAD

**Issue by eneroth** [bhauman/lein-figwheel#225]
Is it possible to connect the REPL to a running Node.js instance? How? :-)

**Comment by bhauman** [comment]
Good question.  You literally just create a node project and configure to use figwheel the same way as you would a browser based set up.  You can do the quick start with :target :nodejs and using 

```
node output_to_file.js
```

Its trickier with node and you need to do a bunch of printing to the console. But it works.  

If you are feeling ambitious we really need a wiki page on this.
