### ISSUE TITLE
Pipe figwheel logs into REPL

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#227]
I'm not 100% certain this is possible, but it would be really nice to have figwheel logs be presented in the same terminal as the REPL so I don't need to open another terminal to tail `figwheel_server.log`. I looked at `sidecar/src/figwheel_sidecar/repl.clj` and it seemed like setting `{:repl false}` would allow me to get logs in my auto builder window, but it didn't seem to work.

Is this possible now, and if not, is it possible in the future?

**Comment by bhauman** [comment]
This is not possible now. There are REPL complications mainly involving redisplay of the prompt which can be very very confusing for folks, as it appears the the REPL has hung when in fact it is just waiting for input.  But also the volume of data is high.

That being said my next big push is to make scripting figwheel super friendly and making sure output isn't redirected to a log file will be trivial.

By the way you can do this now but it would require reading and understanding figwheel-sidecar source code.

**Comment by darwin** [comment]
`:repl false` definitely works for me when [specified in project.clj](https://github.com/binaryage/dirac/blob/master/project.clj#L191).

I tend to use [lein-cooper](https://github.com/kouphax/lein-cooper) to start multiple tasks in one terminal window. For example [here](https://github.com/binaryage/dirac-sample/blob/1e234b4937d61711c1e2b011c5e8a1b204a469a6/project.clj#L100) or [here](https://github.com/binaryage/dirac/blob/ec5a1cde1c22ce9823a0fd5d3831e21409998bf3/project.clj#L351-L357).

**Comment by vemv** [comment]
Is this possible yet?

Would be handy to me to know when does a recompilation finish (which can take a few seconds), so I know exactly when to leave from Emacs to Chrome.

Cheers - Victor

**Comment by bhauman** [comment]
Both `:repl false` and also `:server-logfile false` in top level `:figwheel` settings should give you the behavior you want.

**Comment by vemv** [comment]
Awesome, thank you!
