### ISSUE TITLE
Compilation error on Windows

### ISSUE THREAD

**Issue by conan** [bhauman/lein-figwheel#231]
I always get a compilation error when running figwheel on Windows:
```
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: app
Compiling "resources/public/js/app.js" from ["src/cljs" "env/dev/cljs"]...
Compiling "resources/public/js/app.js" failed.
java.lang.IllegalArgumentException: character to be escaped is missing
 at java.util.regex.Matcher.appendReplacement (:-1)
```
Compiling the same project on the same machine in a Linux VM works fine - shared folder, so same actual files.  It also works on other OSX machines (i.e. everyone else in my team).  I've had this problem with several different projects, my current one is quite large but also with small ones.

My plugin versions:
```
[lein-figwheel "0.3.9"]
[lein-cljsbuild "1.0.6"]
```
My clojure versions:
```
[org.clojure/clojure "1.7.0"]
[org.clojure/clojurescript "1.7.48"]
```
Any ideas?  I haven't yet managed to work out exactly what inclusion in the project causes the problem, if I create a brand new project using `lein new figwheel` then it works, but clearly something I'm doing breaks it.

**Comment by bhauman** [comment]
Hmmmm, a full stack trace would be helpful here.  I've seen this before.

Make sure that you are using Java 8 just in case.

**Comment by conan** [comment]
I'm not sure how I could get a stack trace out of figwheel here, is there some way I can get a log written?  I'm on Java 1.8.0_60.

**Comment by conan** [comment]
My only workaround now is to run figwheel in a linux VM, which is extremely slow in comparison.

**Comment by bhauman** [comment]
Have you tried the newer versions of Clojurescript?

Make sure you do a complete clean before you start Figwheel

**Comment by conan** [comment]
Yes, it seems to work with 1.7.122, thanks.
