### ISSUE TITLE
Clean builds on start.  

### ISSUE THREAD

**Issue by bhauman** [bhauman/lein-figwheel#232]
Should really clean the builds on start.  

This could be a painful slowdown if one is starting figwheel over and over again but it will prevent the countless errors that folks run into because they have assets on disk with a different compilation configuration.

Another approach is to record in a file the current config figwheel-version+cljs-version+build config and check that on start. But this is still no where near as good as just cleaning it all each time lein is invoked.

**Comment by calebsmith** [comment]
I'm a +1 on this for certain.

The increased startup time is undesirable of course, so it makes sense to weigh alternatives. However, to me, the price of that performance hit is worth the weird problems of correctness that occasionally require manual fixes.

I mostly run figwheel inside of a tmux session that stays running for days and days. Another workflow would obviously be a bit less friction-less with this change though.

**Comment by derekslager** [comment]
+1, time wasted fussing with "weird issues" > cumulative time wasted on additional startup time, at least for me. I don't need to restart figwheel very often. I think the referenced optimization is probably overkill.

**Comment by timgilbert** [comment]
+1 for me, I also tend to use a long-running figwheel process from within Cursive or my terminal, typically not restarting it unless my dependencies change or something.

**Comment by smahood** [comment]
+1 for clean on default. Is it easy to add in something like an -unclean flag or something to allow for the old behaviour?

**Comment by bhauman** [comment]
I'm thinking that this is best handled with yet another knob.

**Comment by bhauman** [comment]
Actually I think the best thing here is to write the checksum or hash of the project configuration to a temp-file.  

Then check this file on start.  If the configuration has changed then do a clean.  

This should do it.

**Comment by bhauman** [comment]
Addressed this here https://github.com/bhauman/lein-figwheel/commit/8e9ededc6ade50e41b9443cb2b1926a39a758333.  I'm basically cleaning on start when the classpath changes, or if some build sensitive config options change.
