### ISSUE TITLE
Required namespace not provided for <ns>

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#234]
I'm getting a sporadic error reloading a cljc namespace that shows up after a little while running figwheel. I am able to start the project and work for a while, reloading code as I go, but at some point I will get this error:

```
Figwheel: Compile Warning - Required namespace not provided for rethinkdb.query
```

I've already seen #129, but that seemed to end up being a dependency issue. I've created a small reproducible example at https://github.com/danielcompton/rethink-figwheel-test.

To reproduce the test case, start `lein figwheel`, add some code to trigger reloads for ~30 seconds, then leave it for 10 minutes, then come back and make some more changes to trigger a reload. If the debugging gods are smiling on us then you should get that error. If not, try leaving it in the background for longer, it should show up eventually.

The version of clj-rethinkdb I'm running corresponds to [this](https://github.com/apa512/clj-rethinkdb/tree/7567e4d248b019b3912ee3b9b1458331629970f8). The only thing that I could think might possibly be causing this is [these lines](https://github.com/apa512/clj-rethinkdb/blob/7567e4d248b019b3912ee3b9b1458331629970f8/src/rethinkdb/query.cljc#L22-L23) or this [`:use-macros`](https://github.com/apa512/clj-rethinkdb/blob/7567e4d248b019b3912ee3b9b1458331629970f8/src/rethinkdb/query.cljc#L15) command, although I don't think this is the case because it was able to be reloaded many times before the issue showed up.

**Comment by danielcompton** [comment]
Are there some more figwheel debugging steps I could do to help narrow this down, e.g. enabling more verbose logging?

**Comment by bhauman** [comment]
This is interesting.  Could you find out if this is a ClojureScript bug by eliminating figwheel.  Perhaps use cljsbuild auto or the cljs-repl :watch method found in the ClojureScript quick start.  I think this is an underlying issue that is outside of figwheel

**Comment by danielcompton** [comment]
I've been trying to reproduce this with figwheel, and it hasn't come up again after my initial report. The bug seems to be extremely sporadic so I haven't had a chance to test if it's a bug in ClojureScript yet. Will keep trying though.

**Comment by danielcompton** [comment]
Closing for now, haven't seen this in a long time.
