### ISSUE TITLE
Uncaught TypeError: goog.constructNamespace_ is not a function

### ISSUE THREAD

**Issue by bilus** [bhauman/lein-figwheel#236]
This is what I'm getting with version 0.3.8 (0.3.9 seems to have the same code):

```
Uncaught TypeError: goog.constructNamespace_ is not a function
figwheel$client$file_reloading$bootstrap_goog_base @ file_reloading.cljs:196
(anonymous function) @ file_reloading.cljs:210
figwheel$client$file_reloading$patch_goog_base @ file_reloading.cljs:210
(anonymous function) @ client.cljs:326
debug.cljs:15 (Channel opened)
```

Relevant dependencies:
`[lein-cljsbuild "1.0.5"]`
`[org.clojure/clojure "1.7.0"]`
`[org.clojure/clojurescript "0.0-3211"]`
`[lein-figwheel "0.3.8" :exclusions [org.clojure/clojure org.codehaus.plexus/plexus-utils]]`

**Comment by bilus** [comment]
It's only after pasting dependencies that I noticed that we failed to upgrade ClojureScript in this particular project. I'm tentatively closing the issue. I'm sorry for raising a false alarm.

**Comment by bhauman** [comment]
Yeah you the newer version of cljs
