### ISSUE TITLE
Allow Figwheel to act as proxy server?

### ISSUE THREAD

**Issue by kamn** [bhauman/lein-figwheel#239]
I really like using Clojure(script) as a general programming language and I think Clojurescript has a lot to offer for frontend development in terms of conciseness, simplicity and ease of refactor. However Clojurescript became really attractive to me with demos of Figwheel. It just felt like a key missing piece of front-end development.

By necessity Figwheel has to have it's own server which can then link up to a Clojure backend. That would be ideal but I think it is easier to sell an alternative javascript language than an alternative backend language. I think a solution to allow a non-Clojure backend with Figwheel would go a long way in advocating Clojurescript.

One potential solution is to setup a proxy server that Figwheel could use. Any request that the server does not recognize would be forwarded to another non-Clojure server. That way Figwheel serves as a light shim when developing and a release version of the CLJS would easily integrate into a non-Clojure server. The routes would be the same and during development you are actually using the non-Clojure server.

This would be easiest to use for a SPA and an APIish server. There would still have to be some glue in place still. The main route would have to be duplicated in both the dev Figwheel and the non-Clojure server. I am sure several other issues would arise but I think a simple implementation could go a long way.

I got a quick and dirty example working just to make sure I can do the basics. It is just a modified Luminus server to forward unrecognised routes. I was wondering if there is any desire for something like this to be integrated into Figwheel itself? The setup could just be additional options in the project.clj like so.

``` Clojure
;;...
:figwheel {
  :proxy-server       true
  :proxy-server-ip    "0.0.0.0"
  :proxy-server-port  8080
}
;;...
```
This could be fairly complex and it might be outside of the scope of what Figwheel as a dev tool wants to be. If you would like something like to to be a part of Figwheel (or just see an example of it), I can fork a branch and work on it. Else I will probably start a separate project. Maybe even just a template.
 
Thoughts?

**Comment by bhauman** [comment]
There is absolutely no requirement for figwheel to have a Clojure backend at all.  

I often write Ruby servers.

That is just how these various templates use figwheel.  

Please see the figwheel QuickStart.  Where figwheel is used in conjunction with an app served from the filesystem.  

You can literally use figwheel with any application server you want.

**Comment by bhauman** [comment]
Thanks for offering to work on this.

**Comment by kamn** [comment]
Thanks for the response! I am still new with CLJS and Figwheel in general so sorry about my ignorance about this. I will look thought the Quick Start again.

I quick summary of what solution I was looking for in case I was not clear. 

If I have Figwheel running on `localhost:3449` I want to code on it as if it is a PHP server because the cljs will be complied and put onto a PHP server in production. So the PHP server has a route `api/user/register`. I want to be able to put the following in my code...
```clojure
   ;;...
    (POST "api/user/register"
      {
        :response-format :json
        :keywords? true
        :params info
        :handler handler
        :error-handler error-handler
      })
```
and call `localhost:3449/api/user/register` and have that call be my real PHP server while still using the live reloading from the Figwheel server.

Is this already possible?

Sorry to take up your time with these questions but I really appreciate the responses.

**Comment by bhauman** [comment]
You don't have to serve your App HTML or make your requests to the figwheel-server localhost:3449. That server only is mainly a websocket server for communication purposes, it serves HTML and assets as a development convenience. You can easily serve you HTML and assets from php.

Please take your time and do the Quick Start. There is a lot to learn.

**Comment by kamn** [comment]
Looked at the Quick Start again. I guess the first time I didn't really comprehend the importance of the loading from the file system and I didn't really understand the way Figwheel worked. I played around with a PHP server and using figwheel on that and it worked great!

Thanks for the comments and taking the time to educate me. You really have done a great job with Figwheel!

**Comment by ccfontes** [comment]
@kamn your issue and solution proposal is exactly what I was thinking. Thanks for going through all the trouble of writing it.

@bhauman `lein-figwheel` is too awesome and the Quick Start explains well how to get `figwheel` up and running, but I still couldn't easily understand how to develop with `figwheel` from HTML and assets served from an external server.

For people going through the same understanding issue, this is what you may need to pay attention to:
> The last line of main.js loads the code that will connect to the Figwheel server. This is what enables the Figwheel server to communicate with the application, which is running in the browser.
... 
and load the index.html in the browser from the filesystem. The location bar in your browser should have a file://<...>/hello_seymore/index.html url in it.
Change back to the terminal where Figwheel is starting and when it finishes you should see a REPL prompt.

`figwheel` will connect to your app running in the browser, whether the app was loaded from `file://<...>/hello_seymore/index.html` or `http://localhost` (the latter available through an external server). When the HTML is loaded in the browser, `main.js` is loaded too, and the following code is responsible for connecting back to the `figwheel server`:

```javascript
if(typeof goog == "undefined") document.write('<script src="out/goog/base.js"></script>');
document.write('<script src="out/cljs_deps.js"></script>');
document.write('<script>if (typeof goog != "undefined") { goog.require("hello_seymore.core"); } else { console.warn("ClojureScript could not load :main, did you forget to specify :asset-path?"); };</script>');
document.write("<script>if (typeof goog != \"undefined\") { goog.require(\"figwheel.connect\"); }</script>");
```

**Comment by karneaud** [comment]
very hard to understand indeed
