### ISSUE TITLE
quoted value for `:main` inside cljsbuild config breaks figwheel

### ISSUE THREAD

**Issue by dqdinh** [bhauman/lein-figwheel#246]
I had the following bug below while using figwheel and cljsbuild. I found a workaround but wanted to get your feedback on why this happened.
```
 $ lein clean; lein figwheel 
java.lang.ClassCastException: clojure.lang.PersistentList cannot be cast to clojure.lang.Named
 at clojure.core$name.invoke (core.clj:1524)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    ...
```
After several hours of leiningen config trial and error, it turned out that Figwheel will specifically error out if it sees `:main 'app.core`.  So of the three ways to specify `:main`:

1. `:main 'app.core`
2. `:main app.core`
3. `:main "app.core"`

only options 2 and 3 will work. The error only occurs when specifying `:main 'app.core` inside `:cljsbuild {:builds {:build-id {:compiler ...}` and calling `lein figwheel`. All other cljsbuild commands work.

This is my current working project.clj for reference.
```
(defproject frontend "0.1.0"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.48"]
                 [reagent "0.5.1-rc3"]
                 [re-frame "0.4.1"]
                 [environ "1.0.0"]
                 [prismatic/schema "1.0.1"]
                 [prismatic/plumbing "0.4.4"]
                 [figwheel "0.4.0"]
                 [cljs-ajax "0.3.14"]]

  :plugins [[lein-environ "1.0.0"]
            [lein-figwheel "0.4.0"]
            [lein-cljsbuild "1.0.6"]
            [lein-doo "0.1.5-SNAPSHOT"]
            [codox "0.8.13"]]

  :source-paths ["src"]

  :codox {:language :clojurescript
          :exclude clojure.string}

  :profiles {:dev {:env {:dev? true
                                    :cors? true}

                           :cljsbuild {:builds {:client {:figwheel {:on-jsload "frontend.core/mount-root"}
                                                                   :compiler {:main "frontend.core"
                                                                        :source-map true
                                                                        :source-map-timestamp true
                                                                        :optimizations :none
                                                                        :output-dir "resources/public/js/out"
                                                                        :asset-path "js/out"}}}}}}

  :clean-targets ^{:protect false} [:target-path
                                    :compile-path
                                    "resources/public/js"
                                    "../public/frontend-dev"
                                    "../public/frontend-prod"]

  :cljsbuild {:builds {:client {:source-paths ["src"]
                             :compiler {:output-to "resources/public/js/main.js"}}

                       :browser-test {:source-paths ["src" "test"]
                                      :compiler {:output-to "resources/public/js/browser_tests.js"
                                                 :main "frontendtest.browser"
                                                 :optimizations :none}}}}

  :figwheel {:css-dirs ["resource/public/css"]
             :server-port 3333
             :repl false})
```

**Comment by dqdinh** [comment]
https://github.com/bensu/doo/issues/26

**Comment by bhauman** [comment]
Yeah this is crap. I need to look into this more, ... but to be clear I recommend the use of strings over symbols and quoted symbols.  Yes `lein` is promiscuous this way but there is a problem where we have to cross a serialization boundary with arbitrary data. And so I have to constantly add tweaks to how we process that data before sending it across the boundary.


This line is where we pass the options across the boundary:
https://github.com/bhauman/lein-figwheel/blob/master/plugin/src/leiningen/figwheel.clj#L62

So I have to pre-process lots of situations that don't work.

**Comment by dqdinh** [comment]
Thanks for the feedback.

**Comment by bensu** [comment]
I agree, this is crap. The reason `doo` is supporting `'foo.core` is because people copy paste example from the QuickStart, which are scripts, which need to be quoted. `doo` is no longer dependent on cljsbuild to parse the lein project. 

If you are interested, I could extract the relevant bits from Figwheel into a micro utility and use it also from `doo`, so they are always parsing things in the same way for the compiler.

**Comment by bhauman** [comment]
This is an interesting idea. A library that makes the cljs build config serializable.
Somehow cljsbuild seems to not suffer from this but I can't figure out how.

**Comment by bhauman** [comment]
I just committed a fix for this. I found out how cljsbuild avoids all these issues and it is so silly that I missed it. @bensu hit me up and I'll show you can fix this in doo.
