### ISSUE TITLE
Add new middleware policy as commented prompt in figweel lein template

### ISSUE THREAD

**Issue by voland62** [bhauman/lein-figwheel#248]
It's not a bug, just suggestion.
It will be good to add middleware configs from [here](https://github.com/bhauman/lein-figwheel#middleware) in form of comments to the figwheel template. I spend couple of hours to upgrade cider/figwheel based workflow to the new lein2.5.3/cider 0.10.0-snapshot/cider-nrepl 0.10.0-SNAPSHOT/nrepl 0.2.11/fiwheel 0.4.0. It was pretty confusing to find in which layer was the issue. So any such prompt would be a grace.

Thx for the great stuff, Bruce.

**Comment by bhauman** [comment]
If you would like to do this, I'd really appreciate it  :)

**Comment by bhauman** [comment]
Actually on second thought. I really don't want to encourage folks to use nREPL for CLJS development.  It's a constant source of pain and is absolutely where everyone's frustration comes from.

**Comment by voland62** [comment]
Ok.
