### ISSUE TITLE
Figwheel fails to load on change due to weird "net::ERR_CONNECTION_REFUSED"

### ISSUE THREAD

**Issue by jakubholynet** [bhauman/lein-figwheel#249]
I have this weird problem with Figwheel that I don't know how to troubleshoot (using my own Node.js to serve the files at port 3000):

Chrome console:
```
Figwheel: notified of file changes
jsloader.js:197 GET http://me:3000/js/compiled/out/oops/core.js?zx=thddqnh5f9km net::ERR_CONNECTION_REFUSED
Figwheel: Error loading file http://me:3000/js/compiled/out/goog/../oops/core.js(anonymous function)
GET http://me:3000/js/compiled/out/oops/devcards.js?zx=ysgrlxcenf0s net::ERR_CONNECTION_REFUSED
utils.cljs:36 Figwheel: NOT loading these files 
utils.cljs:38 not required: (nil "/oops/devcards.js")
```
The same problem happens in FF. However it works upon reload / initial load or if I paste the URL into the browser address bar. Any idea why Figwheel could be getting this error? Why connection refused?!

Thanks for any tips!

**Comment by bhauman** [comment]
I have no idea. Definitely seems like a server configuration. Maybe the extension is fouling your server up?

**Comment by jakubholynet** [comment]
I do not know. Could it possible be some timing issue, Figwheel asking for it before the file is there? But then I'd expect 404 not connection refused :(

**Comment by bhauman** [comment]
Could it be a CORS problem? Have you tried to access the urls directly with your browser?

**Comment by jakubholynet** [comment]
BTW Sometimes it works sometimes not. That would indicate it could really be a timing issue.

**Comment by bhauman** [comment]
OK you can set a `:figwheel {:compile-wait-time ...millis... }` at the root level of your project.clj with your other server level config options.  

This sets the time to wait after compile before sending a message.  The default is 10 milliseconds.

**Comment by bhauman** [comment]
Try 500 millis to see if it works better. 

By the way you could just serve the static assets with the figwheel server and the problems will just go away. You don't need to do any config to do this.

**Comment by jakubholynet** [comment]
Thank you! I will try that.

I cannot use fg server since the page is dynamic, containing some JavaScript generated by Node that my client-side code needs :(

**Comment by jakubholynet** [comment]
Hi, it seems the problem was caused by using `nodemon` to run my server resulting in a restart whenever the files changed (and the request from the browser likely coming before the server was fully up). If the problem does not show up again, we can close this in a few days.

Sorry for troubling you and thanks for the `:compile-time-milis` tip!

**Comment by bhauman** [comment]
Cool we'll close this then :)
