### ISSUE TITLE
figwheel not working

### ISSUE THREAD

**Issue by piranha** [bhauman/lein-figwheel#25]
When I clone flappy-bird-demo repository and run `lein figwheel` there, I get an error:

```
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve var: reader/*alias-map* in this context, compiling:(cljs/analyzer.clj:1499:11)
```

I obviously can provide full one, it's really long though. I found out that this could be old version of tools.reader, but as far as I see I have `0.8.3` required by cljs and nothing else, so everything should be ok. Any ideas?

**Comment by mmower** [comment]
@piranha I just hit the exact same problem `'figwheel' is not a task` and had to rename my `profiles.clj` file to get it working again. Did you raise the failure with the `lein-ancient` folks? If not is there any more info about how it's conflated with figwheel?

**Comment by piranha** [comment]
Totally forgot about this one. I'm still using `lein-ancient` and `figwheel`, but without lein plugin, just as a library (`figwheel-sidecar`). Never raised this problem in ancient's github, maybe it's worth it if it's still a problem.
