### ISSUE TITLE
node js support is currently not working on Windows

### ISSUE THREAD

**Issue by JacobGood1** [bhauman/lein-figwheel#251]
AGH, I screwed this issue up by accident...

I keep getting an error when trying to run node like it says in the wiki:

Error: Cannot find module 'C:\Users\jacobgood1\figwheel4node-server\target\server_out\target\server_out\goog\bootstrap\nodejs.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\jacobgood1\figwheel4node-server\target\server_out\figwheel4node_server_with_figwheel.js:6:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

I tried searching for a solution on google which led me to setting some env variables but I still cannot get it to work.  Any suggestions?

**Comment by bhauman** [comment]
Yes there is currently a problem with Windows.

**Comment by bhauman** [comment]
See the end of this thread: https://github.com/bhauman/lein-figwheel/issues/187

**Comment by bhauman** [comment]
@frankhale Just calling you in here.  

We can fix this issue today, my suspicion is that forward slashes do work for requires on windows.  Can you check this out for straight Node?

So the problem is that the paths are inconsistent?

Can I see a diff of your changes?

**Comment by frankhale** [comment]
I can run a quick check now.

**Comment by bhauman** [comment]
Thanks!!

**Comment by frankhale** [comment]
I pasted my changes on https://github.com/bhauman/lein-figwheel/issues/187 because the error reported above doesn't quite look like the one I was encountering. This may be something different.

**Comment by frankhale** [comment]
Just tested forward slashes and they work for requires in Windows. I should have known this but it's okay to test it again. =)

**Comment by bhauman** [comment]
Could you eliminate the parts of your fix that that are redundant then.  It looks like it's only the root.

**Comment by frankhale** [comment]
I'm trying to come up with a simpler fix now.

**Comment by bhauman** [comment]
@JacobGood1 Sorry for all the noise here. I believe that your problem is that you have an `:asset-path` in your build config?  Is that correct?

**Comment by JacobGood1** [comment]
Here is my lein profile...
(defproject figwheel4node-server "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.122"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [figwheel-sidecar "0.4.0"]]
  :plugins [[lein-cljsbuild "1.1.0"]]
  :clean-targets ^{:protect false} ["target"]
  :cljsbuild {
              :builds [{:id "server-dev"
                        :source-paths ["src"]
                        :figwheel true
                        :compiler {:main figwheel4node-server.core
                                   :output-to "target/server_out/figwheel4node_server_with_figwheel.js"
                                   :output-dir "target/server_out"
                                   :target :nodejs
                                   :optimizations :none
                                   :source-map true }}]}
  :figwheel {})

**Comment by JacobGood1** [comment]
@bhauman I am new to these things, by build config you were referring to lein right?

**Comment by bhauman** [comment]
Yeah thanks for sending me your project.clj. Thats helpful.

**Comment by bhauman** [comment]
@frankhale OK can you try this:

```clojure
(defn windows? []
  (re-matches #"win.*" js/process.platform ))

(def reload-file*
  (condp = (utils/host-env?)
    :node
    (let [sep (if (windows?) "\\" "/")]
      (fn [request-url callback]
        (dev-assert (string? request-url) (not (nil? callback)))
        (let [root (string/join sep (reverse (drop 2 (reverse (string/split js/__dirname #"[/\\]")))))
              path (str root sep (fix-node-request-url request-url))]
          (aset (.-cache js/require) path nil)
          (callback (try
                      (js/require path)
                      (catch js/Error e
                        (utils/log :error (str  "Figwheel: Error loading file " path))
                        (utils/log :error (.-stack e))
                        false))))))

    :html (fn [request-url callback]
            (dev-assert (string? request-url) (not (nil? callback)))  
            (let [deferred (loader/load (add-cache-buster request-url)
                                        #js { :cleanupWhenDone true })]
              (.addCallback deferred #(apply callback [true]))
              (.addErrback deferred #(apply callback [false]))))
    (fn [a b] (throw "Reload not defined for this platform"))))

```

**Comment by frankhale** [comment]
Thanks that is much more succinct than my crude code. LOL! I'll definitely try it.

**Comment by bhauman** [comment]
@frankhale actually can you check this in the cljs console

=> js/require.cache

**Comment by bhauman** [comment]
I need to know the shape of the object properties so I can delete them

**Comment by frankhale** [comment]
Sure, I will check that before I try out the code above.

**Comment by frankhale** [comment]
Sorry that took longer than usual. I had to figure out how to get that data out of the Windows command prompt where it was a jumbled mess. 

Here is my js/require.cache:

https://gist.github.com/frankhale/b6267890031ca2f60091

**Comment by bhauman** [comment]
Cool it looks like the code should work then

**Comment by frankhale** [comment]
I'm going to try your code from above in just a few minutes to see if it resolves the issues.

**Comment by frankhale** [comment]
I used your rewritten reload-file* and the errors go away. Looks good!

**Comment by bhauman** [comment]
Can you try this as well?

```
(def reload-file*
  (condp = (utils/host-env?)
    :node
    (let [sep (if (re-matches #"win.*" js/process.platform ) "\\" "/")]
      (fn [request-url callback]
        (dev-assert (string? request-url) (not (nil? callback)))
        (let [root (string/join sep (reverse (drop 2 (reverse (string/split js/__dirname #"[/\\]")))))
              cache-path (str root sep (fix-node-request-url request-url))]
          (aset (.-cache js/require) cache-path nil)
          (callback (try
                      (js/require (string/join "/" ["." ".." request-url])) ; <-- this line changed
                      (catch js/Error e
                        (utils/log :error (str  "Figwheel: Error loading file " path))
                        (utils/log :error (.-stack e))
                        false))))))
    
    :html (fn [request-url callback]
            (dev-assert (string? request-url) (not (nil? callback)))  
            (let [deferred (loader/load (add-cache-buster request-url)
                                        #js { :cleanupWhenDone true })]
              (.addCallback deferred #(apply callback [true]))
              (.addErrback deferred #(apply callback [false]))))
    (fn [a b] (throw "Reload not defined for this platform"))))
```

**Comment by bhauman** [comment]
You may want to also check that reloads are actually happening.

**Comment by frankhale** [comment]
I just tried your new code, I think there is a typo. 

In the following line you are using path but it's not defined. Should it be cache-path?

```
(utils/log :error (str  "Figwheel: Error loading file " path))
```

Additionally, while errors are gone and reloading is happening (eg. I can see the messages in the console). When I change code it's not changing after reload. I'm sure I am doing something wrong.

I tried your code here for an express app:

https://gist.github.com/bhauman/c63123a5c655d77c3e7f

It's probably a misunderstanding on my part but it would be nice to have a reference project that demonstrates that gist so there is no ambiguity in testing to see if everything is working. I'll try the code I have on Linux later tonight to see if it's just Windows that is having problems or if it's just me. LOL!

**Comment by bhauman** [comment]
I think I've fixed this now.

This should do it.

```clojure
(def reload-file*
  (condp = (utils/host-env?)
    :node
    (let [path-parts #(string/split %  #"[/\\]")
          sep (if (re-matches #"win.*" js/process.platform ) "\\" "/")
          root (string/join sep (pop (pop (path-parts js/__dirname))))]
      (fn [request-url callback]
        (dev-assert (string? request-url) (not (nil? callback)))
        (let [cache-path
              (string/join
               sep
               (cons root
                     (path-parts (fix-node-request-url request-url))))]
          (aset (.-cache js/require) cache-path nil)
          (callback (try
                      (js/require (string/join "/" ["." ".." request-url]))
                      (catch js/Error e
                        (utils/log :error (str  "Figwheel: Error loading file " cache-path))
                        (utils/log :error (.-stack e))
                        false))))))
    
    :html (fn [request-url callback]
            (dev-assert (string? request-url) (not (nil? callback)))  
            (let [deferred (loader/load (add-cache-buster request-url)
                                        #js { :cleanupWhenDone true })]
              (.addCallback deferred #(apply callback [true]))
              (.addErrback deferred #(apply callback [false]))))
    (fn [a b] (throw "Reload not defined for this platform"))))

```

**Comment by frankhale** [comment]
You did it! It's working like a charm. Thank you!

**Comment by JacobGood1** [comment]
Should we close this now?

**Comment by bhauman** [comment]
yep!

**Comment by JacobGood1** [comment]
fixed by bhauman aka the pod man
