### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by piranha** [bhauman/lein-figwheel#253]
My app, when running in development mode, constantly eats 10-12% of CPU. Today in the morning I decided to track what's going on, and disabling figwheel drops usage to 0. I have two simultaneous builds going on, and disabling one of them drops usage somewhat, but not really noticeably (by ~2%).

I'm not exactly sure how to track this further. Maybe figwheel does polling for changes rather than using FSEvents/whatever?

**Comment by piranha** [comment]
I've just looked and saw you're using watchtower, which polls for changes! I guess that could explain the problem.

I used [hawk](https://github.com/wkf/hawk) with great success, I guess I'll try to do a pull-request for that.

**Comment by bhauman** [comment]
I don't use watchtower for cljs changes but I do poll for changes.  It is a CPU hit but it is much faster.  The FSEvent Stuff has a significant lag.  

That doesn't mean its a bad idea, just that there is a price. Instantaneous speedy feedback is really hard to let go of.  I'm going to be re-architecting this over the next couple of weeks. Maybe then there will be an option to have one watcher or another.

**Comment by piranha** [comment]
Ah, I see. Well, I use hawk right now to auto-reload my server components, and, to be honest, I don't really notice significant lag there. Though there is some, of course.

It's just figwheel drains my battery and makes my fan work all the time, so I'm worried about that. But by no means I want to degrade experience, fast reloading is really useful. :-)

**Comment by bhauman** [comment]
I think this should be an option.  Right now I'm doing some simplifying of figwheel arch. I'm going to get rid of clojurescript-build and move towards component for system management.  I'm hoping to make a more composable system so that folks can easily script there own stuff. 

Don't know how far I'll get.  But I'm gonna try..

**Comment by piranha** [comment]
Hehe, that's gonna be cool. :) Ok, so I have to wait a bit for your changes until jumping in. :)

**Comment by bhauman** [comment]
The next release of figwheel uses hawk. So I'm going to call this closed.

**Comment by piranha** [comment]
Woohoo! Thank you!
