### ISSUE TITLE
(cljs-repl)  is just redirecting I/O from the shell

### ISSUE THREAD

**Issue by JvJ** [bhauman/lein-figwheel#254]
I am currently able to run figwheel-sidecar.repl-api/cljs-repl, from within the cider window, I am only able to type input in stdin, and see input from stdout, just like on the command line.  I'm not getting the full nrepl experience.

Is this a bug, or are some other steps necessary?

**Comment by bhauman** [comment]
You are using nREPL
https://github.com/bhauman/lein-figwheel#editor-repls-and-nrepl
