### ISSUE TITLE
Minor heap issue

### ISSUE THREAD

**Issue by fdserr** [bhauman/lein-figwheel#256]
I'm tempted to stfu since figwheel/devcards is such an awesome, really useful piece of software, but making sure you're aware of this is stronger.

Something seems to fastly and constantly produce garb on the heap while fig is idle:

![image](https://cloud.githubusercontent.com/assets/3100658/10392985/284ea868-6e8c-11e5-9e18-a25296afb4fe.png)

Then later (completely idle):

![image](https://cloud.githubusercontent.com/assets/3100658/10393605/a5fdfc28-6e91-11e5-8f8e-041387667bf8.png)

When the gc enters all is reclaimed and more heap is allocated. Not an issue but I read you're on your way for an arch rehaul, so you may wish to look into this too.

**Comment by bhauman** [comment]
Thanks for the graphs, this is most certainly the same issue as #253.  
Awesome graphs!!
Gonna close this.

**Comment by fdserr** [comment]
`jvisualvm` if you've got jdk installed.

**Comment by bhauman** [comment]
I was in the middle a big refactor that includes this.
