### ISSUE TITLE
Heads-up display does not find body?

### ISSUE THREAD

**Issue by Jarzka** [bhauman/lein-figwheel#257]
Hi

When I'm using Figwheel (0.4.1) with heads-up display I get the following error:
TypeError: document.body is null heads_up.js:207:1

Looks like heads_up.js does not find the body element even it is there (I can see the whole web page before this error shows up in the console). I still wonder if this has something to do with the fact that Figwheel's JS files are included in the head section in HTML before the body section is fully loaded? Also, the HTML file is completely built on the server side (it's not a static file served directly from the file system) but this probably does not matter.

If I turn heads-up display off, Figwheel works perfectly.

**Comment by bhauman** [comment]
What browser are you using?
Are you mounting your application to body?

**Comment by Jarzka** [comment]
I'm using Firefox but Chrome gives me the same kind of error:
Uncaught TypeError: Cannot read property 'appendChild' of null (heads_up.cljs:71)

My project is currently a very simple HTML file that is constructed on the server side using hiccup and returned in HTTP response. So I guess I'm not mounting my app to body. :P

**Comment by bhauman** [comment]
You probably don't have a body element then.

**Comment by bhauman** [comment]
any more news here?
