### ISSUE TITLE
figwheel nrepl server doesn't create .nrepl-port file

### ISSUE THREAD

**Issue by malchmih** [bhauman/lein-figwheel#258]
It makes impossible for CIDER (for example) to suggest port for connection. More info here: clojure-emacs/cider#1367 Is it possible to add this to figwheel?

**Comment by bhauman** [comment]
There is contention over this one file apparently

https://github.com/bhauman/lein-figwheel/pull/115

**Comment by malchmih** [comment]
Sorry, didn't find that issue. Probably we can add optional parameter to figwheel config? I'm only using `lein figwheel` as a nREPL server so I'd like to have this file.

**Comment by malchmih** [comment]
Actually I'm using figwheel's [scripting support](https://github.com/bhauman/lein-figwheel#scripting-figwheel), so it's not a problem for me anymore. And thanks for that @bhauman, it is awesome!
