### ISSUE TITLE
start-figwheel! fails to compile cljs source if there's "/" in the path

### ISSUE THREAD

**Issue by voins** [bhauman/lein-figwheel#259]
Hi,

Here I've created a minimal example exposing the problem. Everything is fine when I run `lein cljsbuild once` or `lein figwheel`, but if I start `lein repl` (please note `:init` in `:repl-options`) it fails to compile the source with that error:
```
Caused by: clojure.lang.ExceptionInfo: No such namespace: cljsmin.app, could not locate cljsmin/app.cljs, cljsmin/app.cljc, or Closure namespace "cljsmin.app"
```
But if I replace "src/cljs" with just "cljs" in `:source-paths` (and move correspoding source file to new location) it all compiles smoothly. Just as mentioned in issue #216. I don't think though, that this is a leiningen's problem. It happens only when `start-figwheel!` is used.

I'm trying to investigate it myself, but you could do it faster. :)

Oh, and that's linux, 64bit openjdk 1.8.0_60-b24.

Thanks.

**Comment by bhauman** [comment]
This is most certainly a class path issue. And it has everything to do with how you are launching your repl or script. 
src is the default classpath 
Lein repl does not add your cljs soure-paths to the source path.   

I guess I need to update the scripting instructions.

**Comment by voins** [comment]
"src" is the default classpath, but "cljs" isn't. And somehow it works.

**Comment by bhauman** [comment]
Then it must be in the classpath right? The only way the clojurescript
compiler can find a file is if it is on the classpath.

This is very simple to solve just add the `:source-paths` from your
cljsbuild to the
`:source-paths` at the top level of the project.clj.

**Comment by bhauman** [comment]
So this isn't a figwheel issue.

Please go to clojurians.slack.com for help :)

http://clojurians.net/

**Comment by voins** [comment]
Yes, that did help. Thanks a lot. :)

**Comment by bhauman** [comment]
You're welcome :)
