### ISSUE TITLE
Piggieback REPL doesn't use :output-dir build option

### ISSUE THREAD

**Issue by weavejester** [bhauman/lein-figwheel#268]
I was using Piggieback 0.2.1 with Figwheel 0.4.1 and I was attempting to use `figwheel-sidecar.repl/repl` to start a REPL in an existing nREPL session. It worked, but whenever I used the function I saw an `out` directory appear.

I eventually tracked it down to Piggieback, as the problem didn't occur with the default ClojureScript REPL. I confirmed the `:output-dir` was correctly set in the `:compiler-env` options, but Piggieback still used the `out` directory instead of the one in `:output-dir`.

The [Piggieback README](https://github.com/cemerick/piggieback#usage) kinda implies that `:output-dir` needs to be passed as an explicit option, and when I tried it, it seemed to solve the problem:

```clojure
;; In figwheel-sidecar.repl/start-cljs-repl :nrepl
(cljs-repl figwheel-env :special-fns special-fns :output-dir (:output-dir opts))
```

Not sure if this is an issue with Piggieback or Figwheel, or if I've simply done something wrong.

**Comment by bhauman** [comment]
Hmmmm is the `out` directory empty?

This is really strange.  Makes me wonder if the compiler-env is being used at all.

**Comment by weavejester** [comment]
Nope, the `out` directory contains cljs and js files:

```
out
├── cljs
│   ├── core.cljs
│   ├── core.js
│   ├── core.js.map
│   ├── repl.cljs
│   ├── repl.cljs.cache.edn
│   ├── repl.js
│   └── repl.js.map
└── goog
    ├── array
    │   └── array.js
    ├── asserts
    │   └── asserts.js
    ├── base.js
    ├── debug
    │   └── error.js
    ├── dom
    │   └── nodetype.js
    ├── object
    │   └── object.js
    └── string
        ├── string.js
        └── stringbuffer.js
```

It only occurs with Piggieback. The default REPL seems to use the `:output-dir` option.
