### ISSUE TITLE
Conditional :websocket-url

### ISSUE THREAD

**Issue by galdolber** [bhauman/lein-figwheel#270]
I'm using figwheel with reactnative and I'm having the following issue: the iOS simulator needs a different :websocket-url than the android emulator, and this has to be resolved on runtime.

Something like this would be great to have:

{:websocket-url '(if (= (.-OS (.-Platform js/React)) "android")
                             "ws://10.0.3.2:3449/figwheel-ws"
                             "ws://localhost:3449/figwheel-ws")}

**Comment by bhauman** [comment]
do in this case I would call figwheel.client/start manually for now.  Basically look at the generated connect script in target/figwheel-temp/:build 

That script is only there while figwheel is running.

Copy it and use it directly while removing :figwheel from your build config.  This will allow you to customize to your hearts content.  

Also only modify websocket-host  not websocket-url

**Comment by bhauman** [comment]
Did you give this a whirl?

**Comment by galdolber** [comment]
Yes! worked great. I tried to patch the lein plugin, but lein is complaining when I pass a quoted list as an argument for some reason.
As figwheel generates the connect clojurescript file, passing around a snippet of code like the one above and just inject it on the generated code seems arbitrary. 
I'll give it another try when I have time.

**Comment by twashing** [comment]
I got this kind of working. But I had to take a different path. From the figwheel server side, I do the following. 
  1. [Figwheel server-side config](https://github.com/bhauman/lein-figwheel#figwheel-server-side-configuration) takes the `server-ip` I give it.
  2. Then I run `(start-figwheel!)` (the *Figwheel: Starting server at http://localhost:3449* message erroneously hardcodes *localhost*, when that's not Figwheel server's actual host value)

Now, I'm developing my application from a vagrant VM. And I can't get figwheel's client side connect script to point to a configured URL. That connect script is being [generated here](https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/build_middleware/injection.clj#L67). But I can't see in the config, where to pass in that host value.
  * The `js/out/figwheel/connect.js` that gets generated, still has **ws://localhost:3449/figwheel-ws** (a hard coded *localhost* for the ws URL). Any ideas here?
```
goog.provide('figwheel.connect');                                                                                                                                                                                                                                         
goog.require('cljs.core');                                                                                                                                                                                                                                                
goog.require('figwheel.client');                                                                                                                                                                                                                                          
goog.require('figwheel.client.utils');                                                                                                                                                                                                                                    
goog.require('codepair.core');                                                                                                                                                                                                                                            
figwheel.client.start.call(...,"ws://localhost:3449/figwheel-ws"], null)); 
```
  * Also, not sure this is figwheel's fault. But my **main.js** that gets generated, still has a **resources/public/** string prefix in the URI, which shouldn't be there. I know this doesn't happen when I use raw cljsbuild. Any ideas on how to exclude it?
```
...
if(typeof goog == "undefined") document.write('<script src="resources/public/js/out/goog/base.js"></script>');
document.write('<script src="resources/public/js/out/cljs_deps.js"></script>');
document.write("<script>if (typeof goog != \"undefined\") { goog.require(\"figwheel.connect\"); }</script>");
...
```

Thanks :)

**Comment by twashing** [comment]
Ok, solved this problem for a cider / sidecar setup. For my future and anyone else's reference.

1. The websocket url for the generated `js/out/figwheel/connect.js`, can be configured via an external [figwheel.edn config](https://github.com/bhauman/lein-figwheel/tree/master/sidecar#figwheel-sidecar). Or it can be done through your leiningen config. In **project.clj**, what worked for me was putting the `:websocket-url` config under the path **:cljsbuild/:builds[]/:figwheel** (see below).

2. Removing the **resources/public/** string prefix, was indeed a matter of setting the `:asset-path` [compiler option](https://github.com/clojure/clojurescript/wiki/Compiler-Options#asset-path) (see below). In **project.clj**, I set my `:asset-path` under the path **:cljsbuild/:builds[]/:compiler** (see below). I'd previously just put it in the wrong location.
```
  :cljsbuild {:builds [{:id "main"
                                :source-paths ["src/cljs/"]
                                :figwheel {:build-id "main"
                                                :websocket-url "ws://172.28.128.3:3449/figwheel-ws" }
                                :compiler {:main "codepair.core"
                                                 :output-to "resources/public/js/main.js"
                                                 :output-dir "resources/public/js/out"
                                                 :source-map "resources/public/js/out.js.map"
                                                 :asset-path "js/out"
                                                 :optimizations :none
                                                 :pretty-print true}}]} 
```
