### ISSUE TITLE
Show clj macro error stacktraces in heads-up display or console

### ISSUE THREAD

**Issue by aaronc** [bhauman/lein-figwheel#274]
This should be a pretty easy one. I can see in the websocket packets figwheel sends that the full exception info and stacktrace's are sent when an exception occurs on the clojure side of things (i.e. in a macro or in the compiler). Would it be possible to show the stacktrace in the head's up display or at least console.log it? Not having this info was driving me crazy, but at least I can now manually extract it from the websocket packets.

**Comment by bhauman** [comment]
This stacktrace should be in the figwheel_server.log

**Comment by aaronc** [comment]
Great! Good to know. Is there a way to get println's from clj to show up
there as well?

**Comment by bhauman** [comment]
This is highly dependent on your set up... Looking into clojure io and logging will answer this for you.
