### ISSUE TITLE
auto reload ring-handler in figwheel server

### ISSUE THREAD

**Issue by razum2um** [bhauman/lein-figwheel#275]
Hi Bruce, currently I tried to use your master again and get application's ring handler do reloads via like this:

```
(require '[ring.middleware.reload :refer [wrap-reload]])

(defroutes app-routes
  (GET "/test" req "<html><body><h1>change this text</h1></body></html>"))

(def app (wrap-reload app-routes))

(defn dev-system []
  (component/system-map
   :figwheel (sys/figwheel-system (-> (sys/fetch-config)
                                      (assoc-in [:figwheel-options :ring-handler] 'my.core/app)))))
```

although this doesn't reload until I stop-start the full system.

this way also doesn't work
```
(def app (wrap-reload app-routes))
(assoc-in (sys/fetch-config) [:figwheel-options :resolved-ring-handler] app))
```

Hopefully you remember my patch submitted recently, where I *already got it done* in following way:

1) allow to pass `:httpless` option to `FigwheelServer` which prevents http-kit from start. The component needed only export it's handlers
2) use figwheel's component in some `App` component which composes final ring handler

the final result looked like this https://github.com/razum2um/figwheel-example/blob/master/src/clj/figwheel_example/core.clj#L30L32

Questions:
1) do you like the idea of decompose figwheel from http server
2) do you like handler dependency: not figwheel uses application, but application uses figwheel and starts http server (of course, it's optional and default behaviour will remain the same)

**Comment by razum2um** [comment]
Hm, want to say that way work
```
(def app (wrap-reload #'app-routes))
(assoc-in (sys/fetch-config) [:figwheel-options :resolved-ring-handler] app))
```

maybe it will help someone later
but anyway what do you think on the subject

**Comment by bhauman** [comment]
I can't expect people to be running httpkit as their application server which they would be forced to do if they wanted to include an figwheel endpoint

please think of figwheel's communication with the client as a separate connection like a repl
and think of the ring-handler and serving static assets as a very short term convenience

please see my comments on this here https://github.com/bhauman/lein-figwheel/pull/272#issuecomment-153219400

If I only had a httpkit websocket connection for figwheel tooling I think this would be less confusing.
Figwheel's connection is first class and independent like weasel or the CLJS browser repl the fact that it is an HTTP connection is incidental
