### ISSUE TITLE
:server-port option for cljsbuild?

### ISSUE THREAD

**Issue by YottaSecond** [bhauman/lein-figwheel#277]
I like the idea of figwheel so much that I want to try doing my server-side (node.js, not a clojure server) and client-side development in it at the same time! 

The :cljsbuild configuration allows for separate build ids - I guess the mindset for this is so that you can run with different configurations in your different environments; turn off compiler optimizations in development or turn off debugging stuff in prod, that sort of thing.

I'd like to configure one cljsbuild for my client-side code, and one for the server, and I was picturing that I could do something like this:

[{:id "client-dev"
    :source-paths ["client-src"]
    :figwheel {        
             :server-port 3000}}
{:id "server-dev"
    :source-paths ["server-src"]
    :figwheel {
            :server-port 3450}}]

That :server-port option is ignored, so I can't run a "lein figwheel server-dev" and "lein figwheel client-dev" at the same time.

I suppose I could just have my server and client code in separate projects, maybe that would be cleaner. But I'm curious about what other people think.

**Comment by bhauman** [comment]
Brian Fay this already works. I do it all the time.

Both builds can connect to the same port.  Figwheel dispatches messages on build-id.

You can run `lein figwheel server-dev client-dev` and both builds will build and the changes will be sent to the correct clients.

**Comment by YottaSecond** [comment]
Oh, that's excellent! I assumed that you needed to run two separate figwheel servers, but running both builds in one is even better. Thanks, Bruce!
