### ISSUE TITLE
Don't exit with compiler errors on start

### ISSUE THREAD

**Issue by rosejn** [bhauman/lein-figwheel#278]
Hi,
  When starting 'lein figwheel' on a project that doesn't compile figwheel chokes on a compiler error and exits, rather than just printing a message and watching for changes like it does once you've gotten it to compile at least once.  This is especially painful when porting a library to CLJS, where it might take a while until you can get it to compile correctly.  Could get figwheel to stay alive when there is an initial compiler error?

Once you get used to the live style of figwheel development it's painful to have it any other way.  Thanks!

**Comment by bhauman** [comment]
Just pushed a commit to fix this :)

**Comment by rosejn** [comment]
Awesome, thanks!
