### ISSUE TITLE
quick start seems inconsistent with observed behavior

### ISSUE THREAD

**Issue by gonewest818** [bhauman/lein-figwheel#279]
I'm walking through the quick start for the first time and I've reached the point where like-seymore is refactored into a separate components.cljs file.  I am expecting (based on the description in the text) that changes to components.cljs will no longer trigger a (render!). In practice, however, I'm seeing my changes to the literal "Seymore's popularity" in components.cljs are immediately visible in the browser.   In Chrome's javascript console I see 'Figwheel: Loaded these files ("../hello_seymore/components.cljs" "../hello_seymore/core.js")' even when all I have changed is components.cljs.

**Comment by bhauman** [comment]
Yes the behavior has moved and the Quick Start needs to be updated.

**Comment by gonewest818** [comment]
Ok, well at least that confirms it. I'll just keep going then.

**Comment by bhauman** [comment]
Yeah man sorry about that. Things have changed recently when it comes to
the speed of compiling of dependents.  I will fix this today.

**Comment by bhauman** [comment]
updated quick start

**Comment by gonewest818** [comment]
Thank you
