### ISSUE TITLE
Compilation issue with CojureScript 1.7.170 / cljsbuild 1.1.1

### ISSUE THREAD

**Issue by ricardojmendez** [bhauman/lein-figwheel#280]
Getting a compilation issue with the latest ClojureScript and cljsbuild on figwheel 0.4.1, which I've managed to reproduce on the flappy bird demo.

```
clojure.lang.ExceptionInfo: No such namespace: cljsjs.react, could not locate cljsjs/react.cljs, cljsjs/react.cljc, or Closure namespace "cljsjs.react" {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:568)
```

To reproduce:

```
git clone https://github.com/bhauman/flappy-bird-demo.git
```

Then upgrade dependencies to:

[org.clojure/clojurescript "1.7.170"]
[org.clojure/core.async "0.2.371"]
[sablono "0.4.0"]
[lein-cljsbuild "1.1.1"]
[lein-figwheel "0.4.1"]

And run `lein figwheel` to get the exception at compile time. `lein cljsbuild once` works as expected (both on my test case and on flappy bird demo).

If you just upgrade to:

[org.clojure/clojurescript "1.7.122"]
[lein-cljsbuild "1.1.0"]
[lein-figwheel "0.4.1"]

Then you do not get an exception when running figwheel.

**Comment by otijhuis** [comment]
You probably need to use `0.5.0-SNAPSHOT`. I know there were some changes needed for clojurescript 1.7.170 in several libraries, including figwheel and cljsbuild. I saw a tweet from David Nolen that those changes were already made in figwheel and others. `0.4.1` has been out for a while so it won't contain those changes.

**Comment by ricardojmendez** [comment]
Thanks for the tip @otijhuis, but just tried it on the flappy-bird demo and I get the same error.

**Comment by bhauman** [comment]
I think the flappy bird error was a `lein clean` thing.  I just updated the flappy bird demo for modern expectations and it works fine.

**Comment by pkpkpk** [comment]
I'm having a problem on a windows box, getting

clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/uti
ls.clj:1:1)

builds fine without fw

**Comment by byronm** [comment]
@bhauman I'm experiencing the same issue as @pkpkpk in both the flappy-bird-demo project and my own app. Both are on figwheel `0.5.0`, cljs `1.7.170`, and lein-cljsbuild `1.1.1`. Running `lein figwheel` yields the error

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/utils.clj:1:1)
```

I've tried running `lein clean` in both but the problem persists. As an aside, a simple compile with `lein cljsbuild` does work fine.

Happy to provide a more complete stack trace or help in any other way that's useful. Thanks!

**Comment by byronm** [comment]
@bhauman @pkpkpk I was able to solve the problem by upgrading leiningen itself. I was previously on leiningen `2.5.0`; bumping to `2.5.3` solved the issue.

**Comment by pkpkpk** [comment]
@byronm yes this works, thankyou

**Comment by sherpc** [comment]
@byronm thank you!
