### ISSUE TITLE
Subproject :scm option incorrect

### ISSUE THREAD

**Issue by weavejester** [bhauman/lein-figwheel#281]
Currently the `:scm` option on the subprojects looks like:

```clojure
  :scm {:name "git"
        :url "https://github.com/bhauman/lein-figwheel"
        :dir "support"}
```

But the `:dir` option is relative to the current directory, so it should instead be:

```clojure
  :scm {:dir ".."}
```

Everything else should be pulled from git automatically by Leiningen, as far as I know. You just need to point it to the repository root.

**Comment by bhauman** [comment]
Thanks!!
