### ISSUE TITLE
:analyze-path option missing from REPL

### ISSUE THREAD

**Issue by weavejester** [bhauman/lein-figwheel#282]
The `cljs-repl` function should be given an `:analyze-path` option pointing to the `:source-paths` given in the options in [repl.clj line 113](https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L133). So instead of:

```clojure
(cljs-repl figwheel-env :special-fns special-fns :output-dir output-dir)
```

It should also have an extra option:

```clojure
(cljs-repl figwheel-env :special-fns special-fns :output-dir output-dir :analyze-path (:source-paths opts))
```

This will stop the warnings that occur whenever the user tries to refer to a predefined var from the REPL. Possibly the same is true of the default REPL as well.

**Comment by bhauman** [comment]
Interesting, did this really change behavior for you?

I'm sharing a compilation environment between the compiler and the repl.  I'm populating the compiliation environment first by compiling the project once before starting the repl and the autobuilder it.


So all analysis should have taken place.  There could be a race condition that occurs if the repl launches before compilation is finished I guess. But first build should be blocking.

How are you using the launching the repl?  Is the initial build occurring before its launch?

Adding the :analysis-path will force analysis right?

**Comment by weavejester** [comment]
Yeah, without it, whenever I referred to a var through the REPL, I got a warning printed out. The value still worked as expected, but adding the `:analyze-path` option fixed the warning.

[This blog post](http://blog.fikesfarm.com/posts/2015-06-10-analyze-path-ftw.html) covers the behavior in detail.

**Comment by bhauman** [comment]
Well after sleeping on it I realized the Compiler env isn't getting passed into the piggieback repl at all!

And that would explain this behavior :) Thanks for taking th Erie to point this out!
