### ISSUE TITLE
add-repl-print-callback! erroneously assumes print callback won't change

### ISSUE THREAD

**Issue by weavejester** [bhauman/lein-figwheel#283]
The [add-repl-print-callback!](https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L61) function currently looks like:

```clojure
(defn add-repl-print-callback! [{:keys [browser-callbacks]}]
  (let [pr-fn (resolve-repl-println)]
    (swap! browser-callbacks assoc "figwheel-repl-print"
           (fn [args] (apply pr-fn args)))))
```

But this assumes that the print function never changes during a session. At least in Piggieback it does, which leads to errors when trying to print in a Figwheel Piggieback-based REPL. So instead, it should look more like:

```clojure
(defn add-repl-print-callback! [{:keys [browser-callbacks]}]
  (swap! browser-callbacks assoc "figwheel-repl-print" 
         (fn [args] (apply (resolve-repl-println) args))))
```

**Comment by bhauman** [comment]
Ahhhh, thanks for this. I'll look into it more.  

As you can see I rarely use Piggieback so any help I can get is welcomed.

**Comment by weavejester** [comment]
As far as I know, the two REPL issues I've reported are the only remaining problems with Piggieback REPLs. I've already fixed them in [duct-figwheel-component](https://github.com/weavejester/duct-figwheel-component), and I've yet to find any other problems during my usage of it.

**Comment by weavejester** [comment]
For reference, I opened issue https://github.com/cemerick/piggieback/issues/69 before I realized the problem was with the print callback in Figwheel.
