### ISSUE TITLE
Live reload of sass/scss files

### ISSUE THREAD

**Issue by DanBurton** [bhauman/lein-figwheel#284]
It's delightful how figwheel live reloads CSS. I wish I could rename a `.css` file to `.scss` and have it work the same way. This would require hooking a sass compilation step into the live reload process.

**Comment by DanBurton** [comment]
Related to #46.

**Comment by bhauman** [comment]
You should look at this:  
https://github.com/bhauman/lein-figwheel/tree/master/sidecar

You can create a component that compiles your sass files into the css directory and then viola!

**Comment by otijhuis** [comment]
The wiki now contains an example of a SassWatcher in the scripting section.

**Comment by DanBurton** [comment]
For the lazy, here's a link to what @otijhuis was talking about: https://github.com/bhauman/lein-figwheel/wiki/SASS-watcher

**Comment by cemerick** [comment]
Landed here first when I was looking for how to best address this; I appreciate the flexibility that the sidecar offers if and when I need it, but if I might suggest…just run:

```
sass --watch <PATHS> &
lein figwheel
```
and tweak your `:css-dirs` config appropriately. Might be a reasonable addition / preface to the wiki page.

**Comment by bhauman** [comment]
Added preface to the Wiki page and a CSS Precompiler section in the README

**Comment by cemerick** [comment]
lein-cooper looks darn handy, thanks for mentioning that.
