### ISSUE TITLE
CLJ dependency figwheel reloading

### ISSUE THREAD

**Issue by thwg** [bhauman/lein-figwheel#291]
Hello,

I am using figwheel in combination with CLJ and CLJS files.  The CLJ files are used for calculation of some known values at compile time, rather than having each client re-calculate them every runtime.

When I edit a CLJS file, both that module and any that depend on it are reloaded by figwheel.  However, when editing CLJ files, only the single CLJ module is re-evaluated (dependent CLJS modules are as well).  Would it be possible to have figwheel automatically reload CLJ modules that depend on the modified CLJ module?

For reference, I've created a minimal example of the problem in a repository, using the hello-world template: https://github.com/thwg/figwheel-reload-example

Notice that whenever `secondary.cljs` is modified, both `secondary.cljs` and `core.cljs` are re-evaluated, because `core.cljs` requires `secondary.cljs`.  However, whenever `secondary.clj` is modified, `core.clj` is not re-evaluated (and the wrong value appears in the DOM), even though `core.clj` requires `secondary.clj` and `core.cljs` requires macros from `core.clj`.

**Comment by bhauman** [comment]
So the figwheel clj reloading is currently pretty simple.   And while this is on the roadmap it's not coming soon :)
