### ISSUE TITLE
Cursive REPL: custom build id

### ISSUE THREAD

**Issue by honzabrecka** [bhauman/lein-figwheel#294]
Hi,

I followed the instructions in https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL and it works great! But I have two builds specified in my project.clj file, and I want to be able to choose, which one should be used by figwheel/REPL (it uses the first one by default). Is it even possible?

I'm using this repl.clj script:

```clojure
(use 'figwheel-sidecar.repl-api)
(start-figwheel!)// ??
(cljs-repl)
```

Thank you!

**Comment by bhauman** [comment]
Pass the build-id to (cljs-repl "example")

**Comment by honzabrecka** [comment]
Thank you!

**Comment by honzabrecka** [comment]
Hello again. I followed your advice, but it doesn't work as I would expect. I want to use figwheel with "server-dev" build target, but figwheel picks up "browser-dev" build target, just because it's defined first. When I switch the order of the targets ("server-dev", "browser-dev"), then it works. Is there a way how can I specify which build figwheel should pick? Thanks

```clojure
; project.clj

;...
:dependencies [
 [org.clojure/clojure "1.7.0" :scope "provided"]
 [org.clojure/clojurescript "1.7.170" :scope "provided"]
 [figwheel-sidecar "0.5.0-1"]
]
;...
:cljsbuild {:builds [
 {:id "browser-dev"
  :figwheel true
  ;...
 }

 {:id "server-dev"
  :figwheel true
  :target :nodejs
  ;...
 }]}
;...
```

```clojure
(use 'figwheel-sidecar.repl-api)
(start-figwheel!)
(cljs-repl "server-dev")
```

```
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - browser-dev    <----- this is wrong, should be server-dev
````

**Comment by honzabrecka** [comment]
Great, thank you again!
