### ISSUE TITLE
Figwheel server accidentally kills whole JVM process

### ISSUE THREAD

**Issue by rkworks** [bhauman/lein-figwheel#296]
Hi

I'm using figwheel component by embedding it into my system.
My problem is that figwheel kills the whole process via System/exit when I accidentally launch multiple figwheel instances with same port.
https://github.com/bhauman/lein-figwheel/blob/29037d64dac7a8815530411f29160eee8bfcd9c8/sidecar/src/figwheel_sidecar/components/figwheel_server.clj#L124

This behaviour may not be problematic when figwheel is used as a leiningen plugin. However, it might be better to delegate exception handling to figwheel users when it is used as a library.

**Comment by bhauman** [comment]
Yeah this line needs to go.

But please don't tell me you are creating 2 Figwheel systems in the same Clojure process?

**Comment by bhauman** [comment]
just committed a fix for this
https://github.com/bhauman/lein-figwheel/commit/c19a4cfde88d05e6103678cb339a10e0c44b7a0c

**Comment by rkworks** [comment]
Great, thanks!

Ah, I didn't mean I created servers in one project.
I'm recently working with multiple projects including leiningen template at the same time.
So sometimes I forget to change a port of figwheel, and this kills one of my cider repl sessions.

Especially, leiningen template project tends to cause such a mistake because I manually test a generated fresh project including figwheel component, and I occasionally forget to kill a process of previously generated project.
