### ISSUE TITLE
using reagent-template from cursive

### ISSUE THREAD

**Issue by pbaille** [bhauman/lein-figwheel#297]
Hi,

I'm trying to adapt a project generated by reagent-template to work in cursive (repl) 
Can't have it to work while following the "Running figwheel in a Cursive Clojure REPL" instructions
the repl stay stuck on "Prompt will show when Figwheel connects to your application" 

Any help welcome

**Comment by jumarko** [comment]
@pbaille did you solve this issue?
I suffer from pretty much the same.
Following https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL for project generated by "figwheel" template works just fine, but for project generated by "reagent" template I'm not able to properly connect browser with nREPL - If I open html page I get the message
```
Figwheel Server: Resource not found

Keep on figwheelin'
```
