### ISSUE TITLE
Support or replace `:notify-command`?

### ISSUE THREAD

**Issue by eyelidlessness** [bhauman/lein-figwheel#304]
It appears support for `:notify-command` has gone back and forth over several revisions of Figwheel, and it was explicitly removed with the removal of `cljsbuild` in 0.3.8. Unfortunately, this removes functionality which isn't obvious how to reproduce.

Is there a clear or canonical way to run arbitrary commands (either CLI or CLJ will do) when Figwheel's watchers detect a change?

**Comment by bhauman** [comment]
Hey I'm just letting you know I saw this and I am meditating on it.  

There is a way to do this currently with a custom-build function.  But this is not obvious in any way.

**Comment by eyelidlessness** [comment]
Thanks @bhauman.

For what it's worth, I managed to cobble something together that approximately meets my needs, using the instructions for file watching. But it isn't exactly the same behavior as `:notify-command` (most notably the watcher fires before compilation is complete, which I've just hacked around with a brief sleep) and it's fairly involved.

I'd be happy to see if I can put together a PR, I have a feeling that addressing the compilation time problem would need to happen within figwheel.

**Comment by eyelidlessness** [comment]
Oh, I should add, the most involved part was actually getting the command's output to appear in the terminal running the fighweel repl. I quite hackily solved that by sending the output to the client and calling `figwheel-repl-print`. I have to imagine that is uh... not optimal.

**Comment by bhauman** [comment]
Have you considered testing in another tab in the browser?  Its a really nice workflow.

**Comment by eyelidlessness** [comment]
I'm open to it (and seeing it in one of your videos definitely piqued my interest), but I ultimately also want to continue to run tests in phantomjs as it will be used in CI.
