### ISSUE TITLE
Null line, file, column when :refer points to non-existent symbol

### ISSUE THREAD

**Issue by zentrope** [bhauman/lein-figwheel#308]
Suppose you have something like the following:

```clojure
(ns my.app
  (:require [my.app.lib :as l :refer [ljks]]))
```

and that `my.app.lib` exists, figwheel doesn't report the line, file or column (just the file is helpful).

Instead:

    ANALYSIS ERROR: Referred var lattice-client.partner.icons/ksksks does 
    not exist on file null, line null, column null

Cljsbuild provides:

```clojure
clojure.lang.ExceptionInfo: failed compiling file:src/lattice_client/partner/PartnerUI.cljs 
{:file #object[java.io.File 0x6167a456 "src/lattice_client/partner/PartnerUI.cljs"]}
```

Dnolen may have added something helpful:

https://github.com/clojure/clojurescript/commit/16d5f2abcb3a8fde284124348795ca28e62f32b4

(We discussed it a bit on IRC.)

Couple of stack trace examples (cljsbuild and figwheel):

    https://gist.github.com/zentrope/7ac91655e29e784ff0cd

**Comment by zentrope** [comment]
You (or at least I) can reproduce this any time just by adding a fake var to any :refer vector in a code base being auto-compiled by figwheel.

**Comment by bhauman** [comment]
Yep, this is real. The way warnings are handled needs to be looked at again.

**Comment by bhauman** [comment]
Fixed as of this commit:
https://github.com/bhauman/lein-figwheel/commit/fd61b9a88519bc4099b699ba7b29aea9f9d37779
