### ISSUE TITLE
Multiple output files

### ISSUE THREAD

**Issue by ilja903** [bhauman/lein-figwheel#310]
*I am new to ClojureScript

I am planning to create a cljs project with a few pages. However, I discovered, that there could be only one main per build. How can create each main for each page without the need for multiple profiles?

Something like this:

:compiler     {:main  [hello-world.main hello-world.about]
                               :asset-path           "js/compiled/out"
                               :output-to            ["resources/public/js/compiled/main.js"
                                                           "resources/public/js/compiled/about.js"]
                               :output-dir           "resources/public/js/compiled/out"
                               :source-map-timestamp true}

Is figwheel only suitable for SPAs?

**Comment by danielcompton** [comment]
@ilja903 You should be able to use [modules](http://swannodette.github.io/2015/02/23/hello-google-closure-modules/) to do this. I'm not sure how Figwheel handles this, although you could have multiple figwheel configs, one for each module?

**Comment by bhauman** [comment]
This is mainly a ClojureScript question. Multiple builds is normally the solution for this and figwheel allows you to work on more than one build at the same time.

ClojureScript can be used for SPAs or not.

Please join the slack at http://clojurians.net/

Many helpful folks are there to help with your ClojureScript questions.
