### ISSUE TITLE
Error message regression between 0.3.7 and 0.5.0-2

### ISSUE THREAD

**Issue by dmohs** [bhauman/lein-figwheel#311]
Our project is currently running version 0.3.7 of Figwheel. I created a new project as kind of a playground and started with version 0.5.0-2. I got all the way to the point of connecting successfully, but when I changed a file, nothing happened.

`lein cljsbuild auto` recompiled on changes, so it appeared that the watching mechanism of Figwheel was broken.

So, I downgraded to 0.3.7. When I did a clean build, I noticed warnings. It turns out that I had used underscores in my namespace names instead of hyphens (my_project instead of my-project). Beginner mistake.

I wonder if there is a way we can get these warnings back. This would be a tough situation to debug for someone who is new to ClojureScript and Figwheel.

We depend heavily on Figwheel for day-to-day development, so I would be more than happy to put time and energy into helping out with this. Please let me know if there is anything I can do. As a first step, I could provide a code snippet to reproduce the problem if that would be helpful.

Thank you for such an amazing development tool.

**Comment by bhauman** [comment]
Gonna work on this right now.

**Comment by dmohs** [comment]
Yikes! This seems to have either been fixed or my original steps to reproduce were incorrect. I was just trying to put together a test case and found that when I compiled with 0.5.0-3, I got the following error:

```
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - client
Compiling "target/compiled.js" from ("src/cljs" "src/cljs-dev" "src/cljs-figwheel")...
{:tag :cljs/analysis-error}
ANALYSIS ERROR: Could not locate my_project/utils__init.class or my_project/utils.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name. in file src/cljs/my-project/utils.cljs on file null, line null, column null
```

This is a great error message—it even correctly points out the possible problem with underscores.

I'm going to upgrade my projects now. So sorry for the noise.

**Comment by bhauman** [comment]
You probably upgraded Cljs Compiler and got a better message.
