### ISSUE TITLE
UTF8 issue with figwheel

### ISSUE THREAD

**Issue by zachcp** [bhauman/lein-figwheel#314]
Hi Bruce,

Great work on Figwheel.

I just encountered an error using cljsjs.d3 in figwheel. The error (see below) is related to the use of UTF-8 characters in d3.js that is normally addressed  by  [specifying UTF-8 ](https://github.com/mbostock/d3/issues/1195) in `<meta>` or `<script>`. However, I could not resolve this issue using either route. If, however, I use `cljsbuild` and serve the static file, everything works fine.  

I'm hoping there might be an easy way to force UTF-8 detection in figwheel's server and would appreciate any pointers on how to make it work.

![image](https://cloud.githubusercontent.com/assets/1260667/12060547/3fffa0e4-af40-11e5-9f7f-de8b8753e169.png)

thanks,
zach cp

**Comment by darwin** [comment]
I believe the problem is in slurp call on this line:
https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L94

Slurp should be provided with `:encoding` parameter, in your case "UTF-8" (or `:utf-8`).

I think the best solution would be to introduce figwheel server config key to be used there, which would default to `:utf-8`. Or if we wanted to do some extra work, an `:auto` value could do some content-based encoding detection.

**Comment by bhauman** [comment]
@darwin yeah that needs to be addressed, but not certain this is the cause yet

@zachcp could provide a small example to reproduce this?

**Comment by zachcp** [comment]
Thanks @darwin & @bhauman. 

I'm having trouble recreating the issue.  With a vanilla install of the re-frame template, loading and using D3 seemed to work fine. I copied the dependencies from my trouble-repo with the issue and started having problems. So perhaps its a versioning issue? On the other hand, when I put the previous dependencies back I can't seem to restore the correct behavior - so maybe a caching problem? I have been using `lein clean; lein figwheel` each time.

[test figwheel repo](https://github.com/zachcp/figwheelerrortest)
to recreate just lein figwheel and you should encounter the same character issue I was running into.

thanks,
zach cp

**Comment by bhauman** [comment]
Thanks for giving it a try.

**Comment by zachcp** [comment]
@bhauman I may have given the wrong impression: the linked repo does recreate the problem. I was just trying to logic out the source.

zcp

**Comment by bhauman** [comment]
@zachcp copied your repo and I'm not able to reproduce

**Comment by zachcp** [comment]
thanks for looking into this @bhauman. I will close this until/if I can get a reproducible error.
