### ISSUE TITLE
lein figwheel not honouring LEIN_OFFLINE env flag (clojars.org is down)

### ISSUE THREAD

**Issue by retrogradeorbit** [bhauman/lein-figwheel#316]
cljsbuild and figwheel both timing out when connecting to clojars:

$ DEBUG=true lein figwheel
Leiningen's classpath: /home/crispin/.lein/self-installs/leiningen-2.5.2-standalone.jar
Applying task figwheel to []
Jan 03, 2016 12:04:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://clojars.org:443: Network is unreachable
Jan 03, 2016 12:04:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://clojars.org:443
...

$ DEBUG=true lein cljsbuild once min
Leiningen's classpath: /home/crispin/.lein/self-installs/leiningen-2.5.2-standalone.jar
Applying task cljsbuild to [once min]
Compiling ClojureScript...
Jan 03, 2016 12:09:00 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://clojars.org:443: Network is unreachable
Jan 03, 2016 12:09:00 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://clojars.org:443
...

However, once LEIN_OFFLINE mode is set cljsbuild begins working, but figwheel continues to try and clontact clojars.org:

$ LEIN_OFFLINE=true DEBUG=true lein cljsbuild once min
Leiningen's classpath: /home/crispin/.lein/self-installs/leiningen-2.5.2-standalone.jar
Applying task cljsbuild to [once min]
Compiling ClojureScript...
Compiling "resources/public/js/compiled/ld34.js" from ["src"]...
WARNING: update already refers to: cljs.core/update being replaced by: ld34.flies/update at line 29 /home/crispin/dev/clojure/ld34/src/ld34/flies.cljs
WARNING: Use of undeclared Var infinitelives.pixi.macros/canvas at line 115 /home/crispin/dev/clojure/ld34/src/ld34/core.cljs
Successfully compiled "resources/public/js/compiled/ld34.js" in 21.447 seconds.

$ LEIN_OFFLINE=true DEBUG=true lein figwheel
Leiningen's classpath: /home/crispin/.lein/self-installs/leiningen-2.5.2-standalone.jar
Applying task figwheel to []
Jan 03, 2016 12:14:16 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://clojars.org:443: Network is unreachable
Jan 03, 2016 12:14:16 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://clojars.org:443

figwheel version: 

:plugins [[lein-cljsbuild "1.1.1"]
            [lein-figwheel "0.5.0-1"]]

$ lein -v
Leiningen 2.5.2 on Java 1.7.0_79 OpenJDK 64-Bit Server VM

**Comment by bhauman** [comment]
This is working for me. Leiningen is strange about some things. Plugin resolution and dependencies seems to take a different path.

However the in your case may be that you don't have a resolved dependency in the figwheel case? Figwheel has different deps than cljsbuild.  

This would need to be demonstrated with a minimal case.  A case where all the deps are available for the build to actually run offline. A case where they aren't.  But I think this is ultimately a leiningen thing.

**Comment by retrogradeorbit** [comment]
I will do that, make sure all the deps are available, then take clojars offline locally and test. Will report back what I find.
