### ISSUE TITLE
Figwheel with dynamic handler definition

### ISSUE THREAD

**Issue by emanjavacas** [bhauman/lein-figwheel#317]
I'd like a setup where I can use figwheel awesomeness to reload my cljs front-end. I define the routes handler is dynamically inside a Stuart Sierra's component.
To handle figwheel integration, I encapsulate figwheel as a component itself and start it with figwheel-sidecar.repl-api as shown [in the docs](https://github.com/bhauman/lein-figwheel#scripting-with-component)
However, I keep getting a 404 on localhost:3449 and the repl never connects to the application.
I guess it must be some configuration related issue. I am posting this here, because I think I could help documenting that bit if I manage to get it working.

This is my current configuration.

    (def figwheel-config
       {:figwheel-options
        {:css-dirs ["resources/public/css"]}    
         :build-ids ["dev"]   ;; <-- a vector of build ids to start autobuilding
         :all-builds          ;; <-- supply your build configs here
         [{:id "dev"
           :figwheel {:on-jsload "cleebo.core/mount-root"
                           :websocket-host :js-client-host}
           :source-paths ["src/cljs"]
           :compiler
           {:main "cleebo.core"
            :output-to "resources/public/js/compiled/app.js"
            :output-dir "resources/public/js/compiled/out"
            :asset-path "js/compiled/out"
            :source-map-timestamp true}}]})

    (defrecord Figwheel []
      component/Lifecycle
      (start [component]
        (f-repl/start-figwheel! component)
        (f-repl/cljs-repl)
        component)
      (stop [component]
        (f-repl/stop-figwheel!)
        component))

There is also this [stackoverflow question](https://stackoverflow.com/questions/30418172/how-to-use-figwheel-with-a-ring-handler-thats-a-component) with a related issue.
I'd be very grateful for any kind of hint in the right direction

**Comment by emanjavacas** [comment]
Finally I got this working with the following work-around, which consists of basically hardcoding the web socket url.
In my client code:

    (require '[figwheel.client :as figwheel])
    (figwheel/start {:web socket-url "ws://localhost:3449/figwheel-ws"})

and then in my server code I add the following key-value pair to the client configuration in "figwheel-config"

    :figwheel {:on-jsload "cleebo.core/mount-root"
               :websocket-host :js-client-host
               :web socket-url "ws://localhost:3449/figwheel-ws"}

The entire server and client code is in [here](https://github.com/emanjavacas/cleebo/blob/e0a867b88e924994f76a505057658f25f0b1c948/src/clj/cleebo/figwheel.clj) and [here](https://github.com/emanjavacas/cleebo/blob/e0a867b88e924994f76a505057658f25f0b1c948/src/cljs/cleebo/core.cljs).

I am wondering if there is nicer solution.

**Comment by bhauman** [comment]
Looks like you can just leave :websocket-host and :websocket-url completely out of the configuration.

**Comment by emanjavacas** [comment]
Hey! thanks for your comment. I just tried updating :figwheel to
    :figwheel {:on-jsload "cleebo.core/mount-root"
    ;           :websocket-host :js-client-host
    ;           :websocket-url "ws://localhost:3449/figwheel-ws"
    }

but now I keep getting "WebSocket network error: The operation couldn’t be completed. Connection refused"

I should mention that the server is actually a remote machine (which means that I actually pass the server ip instead of localhost to the urls). Could that be an issue?

**Comment by bhauman** [comment]
yes that is an issue :) 
There is no way for the client to know what it is supposed to connect to.
So you will have to pass the :websocket-url parameter.

**Comment by emanjavacas** [comment]
that makes perfect sense :-), I was a bit lost debugging and forgot about the simplest thing.

Anyway, what took most time for me to find the solution was that I wasn't aware of the :websocket-url parameter, which is not mentioned explicitly in the README. Perhaps it could help others doing so.
In any case, this issue can now be closed.

best!

**Comment by bhauman** [comment]
actually you can just use the websocket-host: "ip-address"
