### ISSUE TITLE
vanilla setup fails

### ISSUE THREAD

**Issue by ftravers** [bhauman/lein-figwheel#322]
* did a lein new figwheel with a reagent flavour option.
* have tools.nrepl-0.2.12, cider-nrepl-0.11.0-SNAPSHOT, figwheel 0.5.0-2, lein 2.5.3
* followed along this page instructions
* I don't have any ~/.lein/profiles.clj

Here is the project: 
https://github.com/ftravers/hello-world

However when I try to start figwheel after pulling in repl-api tonnes of text just scrolls by.

**Comment by bhauman** [comment]
See https://github.com/bhauman/lein-figwheel/issues/320

I've already committed a fix for this.  But it's strange that in the SystemMap is being printed out. Component defines a print-method that is supposed to prevent this from happening.  

Is there a particular Cider setting that may be causing this?

**Comment by bhauman** [comment]
To get around this for now 

```
(do (start-figwheel!) nil)
```

**Comment by ftravers** [comment]
Thank you Bruce!  That did the trick!

**Comment by bhauman** [comment]
I have just deployed a new version that should no longer have this problem.
