### ISSUE TITLE
File change detection fails when running in docker (works in 0.3.7)

### ISSUE THREAD

**Issue by dmohs** [bhauman/lein-figwheel#325]
Running Figwheel like so:
```
docker run --name figwheel --rm -it -w /w -v "$PWD":/w -v "$HOME"/.m2:/root/.m2 -p 3449:3449 clojure lein do resource, figwheel
```
and serving files like so:
```
sudo ruby -run -ehttpd target -p80
```
works great on 0.3.7 and 0.5.0-3 (see attached examples). On 0.3.7, this:
```
touch src/cljs/my_project/core.cljs
```
causes Figwheel to detect the change and reload. This does not work on 0.5.0-3 (the change is silently ignored). `cljsbuild auto` works on both versions and this works on 0.5.0-3:
```
docker exec -it figwheel touch src/cljs/my_project/core.cljs
```

We generally run Figwheel in docker, so this prevents us from upgrading since file saves do not trigger a hot reload. Any ideas?

[figtest-0.3.7.zip](https://github.com/bhauman/lein-figwheel/files/88116/figtest-0.3.7.zip)
[figtest-0.5.0-3.zip](https://github.com/bhauman/lein-figwheel/files/88117/figtest-0.5.0-3.zip)

**Comment by dmohs** [comment]
```
diff figtest-0.3.7/project.clj figtest-0.5.0-3/project.clj 
5,8c5,8
<    [org.clojure/clojurescript "1.7.48"]]
<   :plugins [[lein-cljsbuild "1.0.6"]
<             [lein-figwheel "0.3.7" :exclusions [org.clojure/clojure
<                                                 org.codehaus.plexus/plexus-utils]]
---
>    [org.clojure/clojurescript "1.7.228"]]
>   :plugins [[lein-cljsbuild "1.1.2"]
>             [lein-figwheel "0.5.0-3" :exclusions [org.clojure/clojure
>                                                   org.clojure/tools.reader]]
11,13c11
<                                   [devcards "0.2.1-2" :exclusions [cljsjs/react
<                                                                    org.clojure/clojurescript
<                                                                    org.clojure/tools.reader]]]
---
>                                   [devcards "0.2.1-2" :exclusions [cljsjs/react]]]
```

**Comment by bhauman** [comment]
I would create a minimal project with lein new figwheel. 

The difference in 0.5.0 is that I'm using the Hawk library to detect file change events.  So I would like their if I were you.

**Comment by dmohs** [comment]
Indeed, Hawk does not detect the change in this scenario. I filed an issue:
https://github.com/wkf/hawk/issues/10

**Comment by bhauman** [comment]
Happy to integrate a :watching-method option into the :figwheel config once you confirm the hawk fix is working. 

BTW thanks for contributing, it means a lot to me.

**Comment by dmohs** [comment]
@bhauman, Hawk 0.2.8 has a `:polling` option (see the above issue for syntax). I can't see any Figwheel user needing to adjust the sensitivity to anything other than the default `:high`, so if there were a `:watching-method` option of `:polling` in Figwheel's config, I'm confident it would solve my use case (and any other similar ones) perfectly.

My contribution was a small thanks for an awesome piece of software. You rock.

**Comment by dmohs** [comment]
Is there anything in your way of pushing a release for this? I'm really excited to upgrade to the latest version in our project.

**Comment by bhauman** [comment]
Pushed 0.5.0-5

**Comment by dmohs** [comment]
Just to close the loop on this, we've updated our project and everything is working nicely. I'm working with the author of the [Clojure docker image](https://github.com/Quantisan/docker-clojure) to get rlfe included for a nice Figwheel REPL.

Reloads are much slower in the docker environment than when running Leiningen locally, but it's nice to have the zero-install option available, especially for developers who just want to experiment.

Thank you so much for adding this.
