### ISSUE TITLE
Structure Request: Alter cljs-autobuild to align more code paths with figwheels' approach

### ISSUE THREAD

**Issue by aredington** [bhauman/lein-figwheel#329]
Really loving figwheel and have been building a bigger tower on top of it at https://github.com/apraxis/apraxis

We're building an asset pipeline where it would be advantageous to be able to trigger a cljs build off the modification of a non-cljs resource, e.g. when this html file used in a kioo template is modified, trigger a rebuild so the kioo template can pick up the changes.

This is totally achievable now because of the nice construction of figwheel! A lot of the implementation is folded into the body of https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/components/cljs_autobuild.clj#L96, specifically: extraction of the log-writer, extraction of the cljs-build-fn, and the callback executed when watching detects a file change. By having to replicate this logic ourselves we introduce the opportunity for divergence from figwheel's implementation. If more of the body was extracted from the start impl in partially applied functions it would serve as a means to ensure consistency across impls going forward. As a straw man implementation I would:

- Extract the callback to a new fn 'execute-build' to be partially applied to the the CLJSAutobuild record.
- Relocate log-writer extraction to the new 'execute-build' fn.
- Extract 'cljs-build-fn' computation to its own fn 'extract-cljs-build-fn'

This would allow us to use the exact same impl as figwheel going forward for these concerns, but does increase the surface area of coupling points in figwheel going forward.

If you'd find these changes amenable I can go ahead and issue a PR implementing them.

**Comment by bhauman** [comment]
Sounds good to me. PR away!!
