### ISSUE TITLE
IE and Edge SecurityError

### ISSUE THREAD

**Issue by stephenway** [bhauman/lein-figwheel#336]
Figwheel works great on all browsers I test in except for Internet Explorer and Edge, generally I just get a console error like this on IE:
``` shell
SCRIPT5022: SecurityError
File: socket.js, Line: 62, Column: 1
```
Clicking on socket.js takes me to [this line](https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client/socket.cljs#L53)

On Edge I get something more like:
```shell
Figwheel: trying to open cljs reload socket
figwheel/client/utils.js (94,1)
SCRIPT12017: WebSocket Error: SECURITY_ERR, Cross zone connection not allowed
```
Clicking on utils.js brings me to [this line](https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client/utils.cljs#L38)

Thanks

**Comment by bhauman** [comment]
Don't really understand why IE consistently stays out of step with the rest of the ecosystem. 

If you find a way around this let me know.  
Perhaps you have a local browser setting that is making things extra strict? Or you can loose this restriction.

Until then if its possible to serve your application from the figwheel server things should work.

**Comment by stephenway** [comment]
Yea looks like turning off "Protection Mode" and lowering the policies to the lowest setting opens that up. However I might suspect that other users of figwheel are running on default settings for browser policies. I'm on a VM just for the browser so I don't care, but might be a bad idea for people on physical boxes.

I can't remember but there's a reason I can't run from figwheel server. This workaround works for me for the time being. Thanks for the help!

**Comment by bhauman** [comment]
AFAIK not much I can do about this.  Figwheel has to use CORS.

If IE has its own special CORS requirements that figwheel isn't meeting I'm going to have to rely on a motivated community member to find this and make the appropriate fixes.

**Comment by stephenway** [comment]
@bhauman This keeps popping up for me and it doesn't seem to be getting easier to get around. Is it possible to add in a P3P policy to get around this issue?
Source: http://stackoverflow.com/questions/20198696/cors-request-with-ie11
