### ISSUE TITLE
Callback before figwheel reloads?

### ISSUE THREAD

**Issue by Engelberg** [bhauman/lein-figwheel#337]
on-js-reload is invoked after the code is reloaded.  Is there any callback that is invoked before the code is reloaded?

My use case is that I'm working with a highly stateful javascript library.  Before figwheel reloads, I'd like to capture the important stateful information in a defonce'd Clojure atom and then copy that information back into the state after reload.

**Comment by bhauman** [comment]
There are currently two client side configuration options
https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client.cljs#L298

https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client/file_reloading.cljs#L25

**Comment by Engelberg** [comment]
Thanks.  That looks easy enough to hook into and do what I want.

**Comment by arichiardi** [comment]
@bhauman sorry to write in a closed issue, but is there some custom hook I can use right after having compiled the new artifacts? I would use it to force a sync-to-file-system for `boot`.
