### ISSUE TITLE
programmatically force reload of code from sidecar or client api

### ISSUE THREAD

**Issue by sleexyz** [bhauman/lein-figwheel#341]
Is there any way to programmatically force a reload of a script's own code via the client api?

Toy example:

Suppose I click on a button in the browser. I want it to force figwheel to reload the clojurescript code containing the button.

If not, is there away to programmatically force a reload of a certain script via sidecar?

**Comment by sleexyz** [comment]
_Actual motivating example:_


Suppose I have a compile-time clj macro that slurps `text.md` and spits out the context as a string. 

ie. [this macro](https://gist.github.com/noprompt/9086232)


So whenever my cljs code is compiled, `(slurp "text.md")` will expand to  a string, ie. `"# this is some markdown..."`

Out of the box, Figwheel recompiles my cljs file (and therefore reslurps text.md) when my cljs file changes.


However, when I change `text.md`  directly *without* changing its respective cljs code, figwheel has no way of knowing that my text has changed!


My workaround would to be put all "volatile(compile-time)" assets (like `text.md') assets in a directory, ie `./hot`, and use a file-system-watcher component to force a reload to a script that depends on a changed "volatile(compile-time)" asset.

I'm stuck on how to implement that component, any hints would be gladly appreciated!

**Comment by bhauman** [comment]
https://github.com/bhauman/lein-figwheel/wiki/HTML-watcher-including-browser-reloading

**Comment by sleexyz** [comment]
yeah, I've been following that to implement a watcher component, but I'm looking for to force a file recompilation, as opposed to a browser refresh.

ie. instead of 
```clojure
(fig/add-message-watch
 :some-watcher
 (fn [{:keys [msg-name] :as msg}]
   (when (= msg-name :some-files-changed)

     (.reload js/window.location true) ; browser refresh

     (println "Figwheel: Some file(s) changed. Reloaded page."))))
```

can we do 

```clojure
(fig/add-message-watch
 :some-watcher
 (fn [{:keys [msg-name] :as msg}]
   (when (= msg-name :some-files-changed)

     (reload-this-very-file) ; .cljs reload

     (println "Figwheel: Some file(s) changed. Reloaded page."))))
```
where `reload-this-very-file` triggers figwheel to force a recompilation of that file?

**Comment by bhauman** [comment]
Hmmm good question. I should be able to expose a function to do that if one doesn't already exist.

**Comment by bhauman** [comment]
Alright `figwheel.client.file-reloading/figwheel-require`  it takes a munged-namespace and you will want to provide true as a second arg to force reload.

```
(figwheel-require "example.my_routes" true)
```

**Comment by sleexyz** [comment]
I tried running `figwheel-require`, both in my cljs code and also just in the figwheel REPL and it seems like a no-op; no error, no print-out, no anything. The javascript console made no indication that new code was reloaded, and neither did the page reload anything. My suspicion is that `figwheel-require` only *completes* the loading of the new code pushed to client. Or not, I'm new to clojure!

My current understanding of figwheel is that code updates are exclusively *pushed up* through the figwheel server into the figwheel client, and it is up to functions like `figwheel-require` on the client side to accept these upstream changes. 

I'm however looking for a way to the client to *pull* changes from the server (by forcing a recompilation)

**Comment by bhauman** [comment]
Oh duh, sorry.  Just touch the source file to force a reload.

 Or if you want to get fancy look up "mark file for recompile" or something like it in the cljs.build.api

**Comment by bhauman** [comment]
Did you come to a conclusion on this?

**Comment by alex-dixon** [comment]
I'm looking for a way to do this as well. Have tried using `cljs.build.api/mark-cljs-ns-for-recompile!`
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/build/api.clj#L39
Doesn't seem to do the trick. :/
