### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by IwanKaramazow** [bhauman/lein-figwheel#343]
Coming straight from a webpack-background, I've become quite fond of code splitting and dynamically loading modules at runtime.
I managed to create two builds, one classic, one with `:modules` and `:optimizations` for code-splitting and dynamic module loading. The second build does it job (modules get dynamically loaded), although my repl connection breaks & auto-reloading vanishes. Seems I have to put the `.js` bundle from the first build back into my `index.html` to get those back. Switching between those build also requires me to comment/uncomment specific code to make the dynamically module loading possible.

I'm pretty new to figwheel, I'm not sure if it's possible to have to full figwheel experience with my second code-split build? The first build also feels redundant because it hasn't got the module loading aspect...
I guess code-splitting/dynamically requiring modules isn't supported? (yet?)

There isn't much to find on Google about this topic..

**Comment by bhauman** [comment]
Figwheel only works for optimizations :none

There are really good reasons for this. Speed being of primary importance. Fast reload times are important.  From a semantics perspective you change a file and that file gets loaded.  

As long as Google isn't using closures for modules I suppose we could support simple modules at some point. But right now this goes against the grain of what figwheel is.

Look at https://github.com/clojure/clojurescript/wiki/Compiler-Options#closure-defines
If you need build conditional client side execution.

**Comment by IwanKaramazow** [comment]
Thanks for the clarification. I'll try and automate everything into a dev/prod flag.
