### ISSUE TITLE
Only serve index.html for SPAs?

### ISSUE THREAD

**Issue by jakehow** [bhauman/lein-figwheel#344]
Working on a Clojurescript single page application using HTML5 History.

If I visit http://host/mypath, I would like to serve index.html no matter what.  Is this possible currently?

**Comment by bhauman** [comment]
You can create a :ring-handler that will do this.  You can also just create a simple server in whatever language you feel most comfortable with.

**Comment by jakehow** [comment]
@bhauman thanks for the response!

Do you know of any link to an example/hello-world app that has a sample custom ring handler working that I can look at?

I have just playing around with this project so sorry for the naive question(s).

Here is what I tried, but which does not work:

In `./src/clj/<my-app>/server.clj` I copied the contents of https://github.com/bhauman/lein-figwheel/blob/master/example/src/example/server.clj

In my `project.clj` I changed the `:figwheel` section of the `:cljsbuild` key to be:

```clojurescript
:figwheel {
                          :on-jsload "<my-app>.core/mount-root"
                          :ring-handler <my-app>.server/handler
                        }
```

I also tried:

```clojurescript
:figwheel {
                          :on-jsload "<my-app>.core/mount-root"
                          :ring-handler <my-app>.server/static-server
                        }
```

I also saw that in some of your code you had `:ring` declared as a top level key so tried it there as well but no luck.  This is a `re-frame` app if that matters. Thanks for your help!

**Comment by bhauman** [comment]
Jake I would refer these questions to the Clojurians Slack sign up at
clojurians.net

**Comment by mjg123** [comment]
I'm sure slack is great but if someone like me comes here from google with the exact same question, the answer isn't here :(

**Comment by mjg123** [comment]
By the way I use a quick and dirty fix, which is to specify a handler in `:figwheel :ring-handler` that ignores all details of the incoming request and just returns index.html off the classpath:

```
(defn handler [request]
  {:status 200
   :headers {"Content-Type" "text/html"}
   :body (slurp (clojure.java.io/resource "public/index.html"))})
```

**Comment by carrete** [comment]
We also serve static assets, so we make sure everything get's compiled under `resources/public/static` like:

```clojure
  :cljsbuild {:builds {:dev
                       {:source-paths ["src"]
                        :compiler {:optimizations :none
                                   :closure-defines {"villarrica.frontend.devtooler.enable" true}
                                   :main "villarrica.frontend.core"
                                   :asset-path "/static/js/dev"
                                   :output-dir "resources/public/static/js/dev"
                                   :output-to "resources/public/static/js/villarrica-frontend.js"
                                   :source-map true
                                   :source-map-timestamp true}}
```

Repeat as necessary for other environments, and then:

```clojure
(ns frontend.ring
  (:require [clojure.string :refer [starts-with?]]
            [compojure.core :refer [defroutes]]
            [compojure.route :as route]
            [ring.middleware.defaults :refer [site-defaults wrap-defaults]]))

(defn- wrap-default-index [next-handler]
  (fn [request]
    (next-handler
     (if-not (starts-with? (:uri request) "/static/")
       (assoc request :uri "/index.html")
       request))))

(defroutes routes
  (route/resources "/"))

(def handler (wrap-defaults (wrap-default-index routes) site-defaults))
```

**Comment by mjg123** [comment]
Amazing, thanks @carrete

**Comment by carrete** [comment]
> Amazing, thanks @carrete

No problem. I'm happy it was helpful.

**Comment by mjg123** [comment]
By the way, I'm not using compojure so I ended up with:

```clojure
(ns reag-sec.server
  (:require [clojure.string :refer [starts-with?]]
            [ring.middleware.resource :refer [wrap-resource]]))

(defn- wrap-default-index [next-handler]
  (fn [request]
    (next-handler
     (if (or (starts-with? (:uri request) "/css/")
             (starts-with? (:uri request) "/js/"))
       request
       (assoc request :uri "/index.html")))))  ;; Just left wrap-resource find index.html for us

(def handler
  (-> (fn [_] {:status 404 :body "static asset not found"})
      (wrap-resource "public")
      wrap-default-index))
```

**Comment by arichiardi** [comment]
Cool stuff, this should go in the wiki! Thanks.

**Comment by quangv** [comment]
Thanks @jakehow for opening this issue, @carrete, @mjg123 and everyone else that contributed to this thread.

I was able to use @mjg123 example, as well as https://github.com/bhauman/lein-figwheel/tree/master/examples/using-ring-handler to get 1/2 of html5 history nav (no hash required) for figwheel dev server. Thanks!

**Comment by alex-dixon** [comment]
Note this doesn't seem to support paths apart from things like "/user". I wasn't able to get ones like "/user/" "/user/foo" to work without further changes.

In particular I had to change the default script path in index.html to reference "/js ..." instead of "js" and change :asset-path in project.clj to "/js" instead of "js" as well.

I've opened a PR to https://github.com/quangv/re-frame-html5-routing. Hope this helps.

**Comment by faisalhasnain** [comment]
We can use more generic, flexible and simplified middleware variant - which simply returns `index.html` whenever there is 404 - not found:

```clojure
(ns my-app.server
  (:require
   [ring.middleware.resource :refer [wrap-resource]]))

(defn- wrap-default-index [handler]
  (fn [request]
    (let [response (handler request)]
      (if (not= (:status response) 404)
        response
        (handler (assoc request :uri "/index.html"))))))

(def handler
  (-> (fn [_] {:status 404 :body "index.html file found"})
      (wrap-resource "public")
      wrap-default-index))
```
