### ISSUE TITLE
Hidden error when Sidecar cannot load Piggieback

### ISSUE THREAD

**Issue by stuartsierra** [bhauman/lein-figwheel#347]
In Figwheel Sidecar, trying to start a ClojureScript REPL via nREPL and Piggieback:

At [figwheel_sidecar/repl.clj line 143](https://github.com/bhauman/lein-figwheel/blob/a364ac2eb77a98bbd15bd483267c4f3f97cb5767/sidecar/src/figwheel_sidecar/repl.clj#L143) the actual exception thrown when trying to load Piggieback is not shown or accessible, making it difficult to diagnose the cause of the problem.

The fallback behavior, starting the `:default` ClojureScript REPL, does not work in some environments. For example, in the [Cursive IDE](https://cursive-ide.com/) nREPL client, this results in a REPL buffer which will not accept any input.

I ran into this issue trying to run Figwheel Sidecar in Cursive IDE via nREPL, in a Leiningen project which was missing the [Piggieback nREPL middleware](https://github.com/cemerick/piggieback/blob/440b2d03f944f6418844c2fab1e0361387eed543/README.md#installation) configuration.

**Comment by bhauman** [comment]
Thanks for the report Stuart.  I'll take a look.
