### ISSUE TITLE
WebSocket broken in Nginx HTTP2 sites

### ISSUE THREAD

**Issue by jiyinyiyong** [bhauman/lein-figwheel#348]
HTTP/1.1 is very slow in loading a lot of small files so I tried to use HTTP2:
http://frp.im/mvc-works/respo/resources/public/

It loads slow the first time but the caching works good. `304` codes are returned in one request and much better than it was in HTTP/1.1 

However, WebSocket it down:
```
socket.cljs:54 Mixed Content: The page at 'https://frp.im/mvc-works/respo/resources/public/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://frp.im:3449/figwheel-ws/web-dev'. This request has been blocked; this endpoint must be available over WSS.figwheel$client$socket$open @ socket.cljs:54(anonymous function) @ client.cljs:372
socket.cljs:54 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

Need some advice please. Have anyone configured this before?

My machine is running Ubuntu and Nginx 1.9.11 .

**Comment by bhauman** [comment]
You can only use HTTPS with figwheel if you are using a tunneling proxy like https://github.com/jugyo/tunnels

**Comment by jiyinyiyong** [comment]
I believe we will lose the benefit from HTTP2 after using a proxy.
