### ISSUE TITLE
Fully configurable server root

### ISSUE THREAD

**Issue by arichiardi** [bhauman/lein-figwheel#349]
Hey Bruce, I am reporting here a request from Slack that I could take care of myself:

> let's say I am creating a library, replumb for instance, and I don't want to include in my jar the `resources` folder...what I do is `:resource-paths []` in my `project.clj` root. But now figwhell does not see it anymore. An idea would be to add `:resources-paths` to figwheel. Summoning @bhauman :smile:
> [12:48] 
> (maybe there is another more obvious solution but I can't see it now)

So I am forced to have my `:resource-paths` empty but at the same time I would like to still use figwheel.
I dug in the code and it boils down to change [this line](https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/components/figwheel_server.clj#L111) to something like `(route/files "/" {:root (str "resources/" http-server-root)})` and of course pass an option.

To avoid changing `:http-server-root` semantic we could add the figwheel option `:http-server-path` and read that piece from there.

I got it almost working already here, would you be open to such a patch?

Peace!

**Comment by bhauman** [comment]
I think you may be looking at this backwards?  

If you use the leinigen profiles you can add a resource path that you only use in :dev 

See the devcards project.clj 
https://github.com/bhauman/devcards/blob/master/project.clj#L70

**Comment by arichiardi** [comment]
It is exactly my case! If in a case like the one you linked I do not put an explicit `resource-paths []`, my `resources ` finishes in the jar (using either lein uberjar or lein deploy clojars).
I am using leiningen 2.6.1 where they might have changed this. It kind of makes sense, because resource-paths defaults to that folder and if present it will be included in the final artifact.
I will try to add it in `:dev` and see what happens, not sure it is a figwheel issue. Nonetheless I guess the patch was needed by a lot of people and I decided to push it.

By the way the validation stuff in `0.5.1-SNAPSHOT` is pretty neat!

**Comment by bhauman** [comment]
@arichiardi So I think you might not be seeing the pattern.

The pattern is that you add a **new** directory to resources that **isn't** the default directory.

Above I use "example-resources". I only add "example-resources" to the `:dev` build.  This way those resources only available in a dev build.

The trouble you are experiencing is that the "resources/" path itself is in every build by default.  

There is also a built in "dev-resources" functionality in lein. So you could just move you resources to "dev-resources/" and that should also work fine. 

The pull request you offered breaks the magic of using resources and will most assuredly break many existing builds.

**Comment by arichiardi** [comment]
Yes I did not see that, you are right. I am trying that solution as we speak and I will probably close the PR thereafter ok?
Thanks a lot!

On February 29, 2016 12:09:55 PM PST, Bruce Hauman <notifications@github.com> wrote:
>@arichiardi So I think you might not be seeing the pattern.
>
>The pattern is that you add a **new** directory to resources that
>**isn't** the default directory.
>
>Above I use "example-resources". I only add "example-resources" to the
>`:dev` build.  This way those resources only available in a dev build.
>
>The trouble you are experiencing is that the "resources/" path itself
>is in every build by default.  
>
>There is also a built in "dev-resources" functionality in lein. So you
>could just move you resources to "dev-resources/" and that should also
>work fine. 
>
>The pull request you offered breaks the magic of using resources and
>will most assuredly break many existing builds.
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bhauman/lein-figwheel/issues/349#issuecomment-190362222

-ar

**Comment by arichiardi** [comment]
Works like a charm! I should have checked `devcards` before.
