### ISSUE TITLE
Figwheel requires Java 1.8.0 at least

### ISSUE THREAD

**Issue by roti** [bhauman/lein-figwheel#353]
Hi,

I'm running IntelliJ with java 1.7 and `lein figwheel` with java 1.8, and I get an assertion error:

```
/opt/java/jdk1.8.0_71/bin/java -Dfile.encoding=UTF-8 -Dmaven.wagon.http.ssl.easy=false -Dmaven.wagon.rto=10000 -Didea.launcher.port=7532 -Didea.launcher.bin.path=/opt/idea-IC/bin -classpath /home/razvan/.lein/self-installs/leiningen-2.5.3-standalone.jar:/opt/idea-IC/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain clojure.main -m leiningen.core.main figwheel
System Assertion: Java >= 1.8.0 - Figwheel requires Java 1.8.0 at least. Current version  1.7.0_95
  Please install Java 1.8.0 at least.
Subprocess failed

Process finished with exit code 1
```

I looks like figwheel is taking the java version from the Intellij JVM, not the leiningen one.

Cheers,
Răzvan

**Comment by bhauman** [comment]
So here is the line in question 
https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/config.clj#L23

(System/getProperty "java.version") is reporting 1.7.0_95 ...

**Comment by roti** [comment]
I found something even stranger: Running IntelliJ with Java 1.8, `lein figwheel` with Java 1.8, but in the OS java 1.7 is the default (i.e. it's in the PATH) and I still get this error. So I had a look at the processes and found that `lein figwheel` starts another jvm with the command line:
```
java -classpath <...long list...> -Dfile.encoding=UTF-8 -Dclojure.compile.path=null -D.version=null -Dclojure.debug=false clojure.main -i /tmp/form-init5095939309223899558.clj
```

which is taking the default jvm on the OS (in my case the wrong one). Is this coming from leiningen or figwheel?

**Comment by bhauman** [comment]
That would be leinigen
