### ISSUE TITLE
support secure websocket

### ISSUE THREAD

**Issue by wilkerlucio** [bhauman/lein-figwheel#365]
I'm trying to use Figwheel to hot-reload code while developing a Chrome Extension. The code runs injected on pages, as a content script. While developing locally we mostly use insecure HTTP; content scripts are likely to run on HTTPS pages. The problem is that when we try to connect to the socket the browser refuses because of protocol mismatch. Here is an example exception got from Chrome:

```
Mixed Content: The page at 'https://inbox.google.com/u/0/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://localhost:3449/figwheel-ws/chrome'. This request has been blocked; this endpoint must be available over WSS.
```

Supporting WSS would enable Figwheel to connect to secure pages, allowing hot-reload for browser extensions in those cases.

**Comment by bhauman** [comment]
Have you tried tunnels?

https://github.com/jugyo/tunnels

**Comment by wilkerlucio** [comment]
@bhauman that works great! thank you :)

**Comment by fasiha** [comment]
@wilkerlucio could you share how this worked? I see you can configure figwheel's port, but then figwheel-generated JS will just point to that port. Presumably you were able to get your browser to look for a `wss` server on port N, which tunnels was listening to and proxying data to port M, which unencrypted figwheel was listening on, but the specifics of how that was configured is eluding me. Thanks!
