### ISSUE TITLE
Figwheeling a mobile device on the LAN

### ISSUE THREAD

**Issue by aiba** [bhauman/lein-figwheel#368]
If you're figwheeling a device on your LAN, but not using figwheel to serve the javascript, then you need to manually set the `:websocket-host` to something like your ip address or `mymachine.local`.  Since that value can change based on which machine you're running it on, I use this in my project.clj:

```
:figwheel {:websocket-host ~(.getHostAddress (java.net.Inet4Address/getLocalHost))}
```

...which is a bit of a hack.

Would it make sense to have `:websocket-host` always default to this?  Or perhaps we could have another special value, analogous to `:js-client-host`, something like `:local-ip`.  So I would set `{:websocket-host :local-ip}` rather than the inlined call to getHostAddress().

Happy to submit a PR if the project maintainers like either of these ideas.

**Comment by bhauman** [comment]
Yeah send on a PR, this sounds good
