### ISSUE TITLE
Popping the ClojureScript repl with C-c M-J works, but doesn't serve the app

### ISSUE THREAD

**Issue by brianmingus** [bhauman/lein-figwheel#370]
As seen in the images below, I can get C-c M-J to pop a ClojureScript repl, but it hangs on waiting to connect to the app. On visiting localhost:3449, it prints "Page not found." Would be really great to get this working..

![screenshot from 2016-04-04 11-21-43](https://cloud.githubusercontent.com/assets/3188728/14256694/6e536fe0-fa57-11e5-8268-4a5574e56c97.png)

![screenshot from 2016-04-04 11-17-28](https://cloud.githubusercontent.com/assets/3188728/14256635/31b721b2-fa57-11e5-813d-7598b77d6d82.png)

**Comment by bhauman** [comment]
You haven't included any information about your situation.  

You need to load a page that hosts your clojurescript application, into the browser.  

If I were a betting man I'd say that might be localhost:3449/index.html but that is making a lot of assumptions.

You should definitely read the figwheel Quick Start.

Please also join the clojure slack 
http://clojurians.net

**Comment by brianmingus** [comment]
Hey Bruce - I'm about to give this a shot, but it works when I run `lein figwheel` and then do C-c M-c and connect to localhost:5555 and visit localhost:3449 in my browser.

**Comment by brianmingus** [comment]
@bhauman I sent you a message on the clojurians slack - should make it easier for me to send you info.
