### ISSUE TITLE
What is the recommended way to turn off fighweel in nodejs production

### ISSUE THREAD

**Issue by naartjie** [bhauman/lein-figwheel#373]
I am using figwheel on NodeJS with Express as per this [gist](https://gist.github.com/bhauman/c63123a5c655d77c3e7f). It is working pretty nicely.

I was wondering what is the recommended way to disable figweel for a production build, the example has `(fw/start { })` in the `core.cljs`, so it always runs. Should I use envs, and have 2 different entry points into the app, one with `fw/start` (and figwheel as a dependency) and another one without?

**Comment by bhauman** [comment]
The main way to do this is to have a build with :figwheel true and a :compiler :main in development.  And a production build which leaves out the :figwheel true option.  

The fighweel true option injects the figwheel/start call into the generated loading script.

Please see:
https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel

**Comment by naartjie** [comment]
Great, thanks @bhauman.

I had `(fw/start { })` explicitly in my code - I copied it from the express [gist](https://gist.github.com/bhauman/c63123a5c655d77c3e7f).

I noticed that `cljsbuild` doesn't inject any figwheel code for a `dev` build with `:figwheel true` set, but that does require a `lein clean` so probably safest to have 2 separate builds, `dev` and `prod`.

Thanks!!
