### ISSUE TITLE
:resource-paths and running Figwheel REPL inside Cursive

### ISSUE THREAD

**Issue by AlexHill** [bhauman/lein-figwheel#377]
I'm trying to run a Figwheel REPL for a Reagent/http-kit app inside of Cursive. Everything works fine running `lein figwheel` from the terminal.

I've followed the instructions from the wiki with a few modifications and Figwheel is using my handler. My CSS is served correctly but I get 404s trying to access my JS.

My JS is compiled to "target/cljsbuild" whereas the CSS lives in "resources". I'm guessing when I run from the script, `resource-response` can't find my JS because `:resource-paths` is a Leiningen thing and we're bypassing Leiningen? How else can I get "target/cljsbuild" onto the classpath?

**Comment by AlexHill** [comment]
Well, I added
```
<sourceFolder url="file://$MODULE_DIR$/target/cljsbuild" isTestSource="false" />
```
to my project .iml file, and that made Cursive add to the classpath, and now the resources are served. Success!

This seems like a bit of a hack - is there a "proper" way to make this happen? I'd like to do it in Cursive's run configuration screen but you can only set the classpath, not add to it.

**Comment by bhauman** [comment]
Unfortunately I don't use Cursive so ...
