### ISSUE TITLE
Can't set nrepl-host option.

### ISSUE THREAD

**Issue by tvaughan** [bhauman/lein-figwheel#378]
nrepl-host appears to be a configuration option. https://github.com/bhauman/lein-figwheel/search?utf8=✓&q=nrepl-host. But when I set it I get:

```
------- Figwheel Configuration Error -------

Found unrecognized key :nrepl-host at path [:figwheel]

  :figwheel {
    :nrepl-host "0.0.0.0"
    ^ key :nrepl-host not recognized
  }
```

**Comment by tvaughan** [comment]
This is in the same place where I've set nrepl-port so I'm pretty sure it's in the right place.

**Comment by bhauman** [comment]
Shoot, missed that!  Will fix.

**Comment by bhauman** [comment]
Just fixed this with commit 
fd058b887931a03461353d7cbc486ef15d647416

**Comment by tvaughan** [comment]
That was fast! Thanks!
