### ISSUE TITLE
Add configuration for :launch-commands

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#383]
When we start Figwheel, we always need a browser to go with it. As far as I can tell, there is no automated way to force Figwheel to open a browser, or do other commands once building has finished. We currently use lein-shell to open a browser before figwheel runs, but that means that the browser is opened before there is a web server and we get an error page.

Apologies if this is covered in some other way that I haven't realised.

**Comment by bhauman** [comment]
Actually, I'm thinking about a more specific `:open-url` that opens the given url on launch.

**Comment by bhauman** [comment]
Let's make that :open-urls []
