### ISSUE TITLE
How do I control where files are reloaded from

### ISSUE THREAD

**Issue by Whoops** [bhauman/lein-figwheel#384]
Hello,

We are currently using Cordova combined with Clojurescript to develop a mobile app. We've been using Figwheel for code reloading, but at some point this broke on the device and simulator. Basically the problem is that when running via Cordova, the page isn't actually loaded through figwheel, instead being served from the local filesystem, so when we modify a file it reloads it from `file://` instead of the figwheel server, and of course the local copy hasn't been modified.

We were working around this by using `:url-rewriter` to redirect it to the figwheel server, however it looks like this option has been removed. Is there a new way to accomplish this? I see there is a `before-jsload` hook, but based on my reading of the code it doesn't look to me like it provides a way to actually modify what's about to be loaded.

Thanks for the great resource!

**Comment by bhauman** [comment]
Look at the :figwheel -> :websocket-host parameter.  

Or in dev mode you may want to load the code initially from figwheel (localhost:3499), If you do that then everything should work properly.  But you may be prevented for some reason (cross-origin). 

Also setting up :main and :asset-path properly should help as well.

Please let me know how this goes for you.

**Comment by Whoops** [comment]
Damn, now I feel dumb. It never occurred to me that `asset-path` didn't need to be relative. Sure enough when I change it too `:asset-path "http://localhost:3449/js/out/app"` everything works. 

It's a bit hinky since the port forwarding requires an attached debugger to work, so I have to start the app, it fails to load because it can't find the files, attach the debugger and reload the app, but it does the job. I'll fool with it and see if I can find a way to make it a bit more smooth, but one way or another this does the job.

Thanks!

**Comment by bhauman** [comment]
Glad to help!
