### ISSUE TITLE
Automatically set ":source-map-timestamp true" ?

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#386]
I think all (almost all?) Figwheel users would be well served by having `:source-map-timestamp true` in their CLJS compiler options. Is it worth automatically adding it to the compiler options if it's not present? People that want to opt out could provide `:source-map-timestamp false`.

I'm a bit wary of updating CLJS compiler options, but I'm not sure if you do it elsewhere already.

What are your thoughts?

Relates to #385, #51.

**Comment by bhauman** [comment]
I have worked to make sure that compiler options just flow through to the compiler un-altered. 

However, I do understand that in this case it seems appropriate for several reasons and apparently has zero downsides.

The more I think about it, this should be the one exception.  Gonna mull on it a bit more.

**Comment by danielcompton** [comment]
This has been [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=438251#c47) in Chrome Canary on Jan 22. I think that [slates it](https://www.chromium.org/developers/calendar) for Chrome 66 with an estimated release date of April 17.
