### ISSUE TITLE
:websocket-host :js-client-host overrides port

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/lein-figwheel#387]
Apparently the client tries to connect on 8080 even though the server port is 3449.

Using 0.5.2.

**Comment by bhauman** [comment]
hmmm, there is a name behavior miss-match here.  The behavior of 
`:websocket-host :js-client-host` actually means that it will try to connect to the the same location that the page was loaded including the port.  

So really bad naming here.

**Comment by lgrapenthin** [comment]
Then the documentation lies or is at least truly misleading: https://github.com/bhauman/lein-figwheel/wiki/Configuration-Options#client says 

> Configure a websocket **host**. Figwheel **already knows the port**. This is helpful if you want to broadcast to devices. If you set it to :js-client-host, it will set the host based on the js/location.host param of the browser. This is helpful for multiple device settings where you are using fighweel to serve your app. Default: localhost

**Comment by bhauman** [comment]
Darn! Really bad documentation. Alright I'll look at this today.
