### ISSUE TITLE
IE problem with CustomEvent

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/lein-figwheel#388]
Apparently Figwheel uses a customevent constructor that is not supported by Internet Exploder.

The line in question is client.utils:22 which throws a strange exception.

The current workaround is this polyfill https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

It might shine light on how to work around in this project without depending on it.

**Comment by bhauman** [comment]
fixed this in a recent commit https://github.com/bhauman/lein-figwheel/commit/8b381051f9f1b2e0607fb3ced7f603441785e99b
