### ISSUE TITLE
"Quick Start" suggestions

### ISSUE THREAD

**Issue by kennytilton** [bhauman/lein-figwheel#391]
First, the Quick Start is one of the best I have come across trying to get going on Clojure.

I may be wrong on this, but I think there are a few issues in the section "Auto-reloading CSS".

1. Where we are directed to edit the project.clj, a comment points out one addition (the :figwheel/css-dirs bit) but there is a second :builds/:figwheel addition that could use pointing out for those of us not just copying in the whole wodge.

2. The index.html shown lacks the mount point: `<div id="app"></div>`

3. I did not get css auto-loading after restarting Figwheel until I also re-opened the new version of index.html. I guess that is obvious but I was just following step by step and did not think of it right away.

Thanks again for a great tutorial.

**Comment by bhauman** [comment]
Great feedback I will check it out.

**Comment by bhauman** [comment]
I think I found and addressed all these issues.  Thanks again for the feedback, it was very helpful.

**Comment by kennytilton** [comment]
No problem! I only spoke up because the tutroial was so great. (And I am slogging thru a ton these days getting up to speed on clojure, so I should know <g>.)
