### ISSUE TITLE
Compilation exceptions and warnings need nREPL messages

### ISSUE THREAD

**Issue by bhauman** [bhauman/lein-figwheel#406]

**Comment by darwin** [comment]
Not an easy task I think. This comment might be relevant:
https://github.com/bhauman/lein-figwheel/pull/309#issuecomment-163801038

This is current state of sniffer in Dirac:
https://github.com/binaryage/dirac/blob/master/src/nrepl/dirac/nrepl/driver.clj

The code was intially copied from my original lein-figwheel fork:
https://github.com/darwin/lein-figwheel

I'm curious if you could find a better solution. Please share it here.

**Comment by bhauman** [comment]
Going to table this.
