### ISSUE TITLE
Node w/ recent figwheel/cljs

### ISSUE THREAD

**Issue by jimrthy** [bhauman/lein-figwheel#425]
I haven't done a thorough analysis to track down the actual version where this problem started.

Today's my first time dabbling with node.js, so I might have missed something obvious.

I started with the basic `lein figwheel new` template, then made the conversions that seem appropriate to get it working with node.js (based upon the wiki page here, from the "node.js needs documentation" issue...that one seems done to me).

My node.js app shows the initial "Update me to see reloading in action" message, followed by:

...target/headless/cljs/core.cljs:4711
    (assoc m k (f (met m k)))))
                      ^

ReferenceError: location is not defined
   at .../target/headless/figwheel/client.js:1552:98
   at .../target/headless/cljs/core.cljs:4711:18
   at Function.cljs.core.update_in.cljs$core$IFn$_invoke$arity$3 (.../target/headless/cljs/core.cljs:4711:17)
   at cljs$core$update_in (.../target/headless/cljs/core.cljs:4702:1)
   at figwheel$client$fill_url_template (.../target/headless/figwheel/client.js:1551:28)
   at [object Object]._onTimeout (.../target/headless/figwheel/client.js:1693:56)
   at Timer.listOnTimeout (timers.js:89:15)

So, I went back to swannodette's "clojurescript quickstart" minimal implementation. When that was working fine, I added the basic pieces from the figwheel wiki to use node.js.

Using clojure 1.7.0, clojurescript 1.7.107, and lein-figwheel 0.3.9, it seems to work fine.

When I switch to clojure 1.8.0, clojurescript 1.8.51, and lein-figwheel 0.5.3-2, that error comes back.

Based on the "node.js needs documentation" issue, I made sure to set my cljsbuild's :asset-path. 

If it would help, I can binary sort versions to try to narrow down where the problem actually appears, but it seemed like it might be more efficient to just ask here. (I'd ask on IRC, but our corporate overlords have blocked it).

**Comment by bhauman** [comment]
Yes this has been fixed in snapshot
Try 0.5.4-SNAPSHOT

**Comment by jimrthy** [comment]
Sorry for the delay. Verifying that it does seem to be fixed.

You rock! Thank you.
