### ISSUE TITLE
Figwheel crashes trying to parse profiles

### ISSUE THREAD

**Issue by yogthos** [bhauman/lein-figwheel#427]
I'm updating Luminus to use the latest version of Figwheel, and I notice that it's not compatible with the profiles as seen in this [project.clj](https://gist.github.com/yogthos/ba12313f40fb9e35cb4306738261fc4b). I see the following trace trying to run `lein figwheel`. However, when I remove profiles, then Figwheel starts up correctly. Note that all the ClojureScript/Figwheel configuration is outside the profiles.

```
Figwheel: Cleaning because dependencies changed
Figwheel: Cutting some fruit, just a sec ...
java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.util.Map$Entry
 at clojure.lang.APersistentMap$KeySeq.first (APersistentMap.java:166)
    clojure.lang.RT.first (RT.java:667)
    clojure.core$first__4339.invokeStatic (core.clj:55)
    clojure.core$concat$cat__4448$fn__4449.invoke (core.clj:720)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:688)
    clojure.core$next__4341.invokeStatic (core.clj:64)
    clojure.core$some.invokeStatic (core.clj:2592)
    clojure.core$some.invoke (core.clj:2583)
    leiningen.figwheel$profile_merging_QMARK_.invokeStatic (figwheel.clj:119)
    leiningen.figwheel$profile_merging_QMARK_.invoke (figwheel.clj:112)
    leiningen.figwheel$create_config_source.invokeStatic (figwheel.clj:168)
    leiningen.figwheel$create_config_source.invoke (figwheel.clj:167)
    leiningen.figwheel$run_figwheel.invokeStatic (figwheel.clj:185)
    leiningen.figwheel$run_figwheel.invoke (figwheel.clj:177)
    leiningen.figwheel$figwheel_main.invokeStatic (figwheel.clj:413)
    leiningen.figwheel$figwheel_main.invoke (figwheel.clj:411)
    leiningen.figwheel$eval875$fn__876.invoke (figwheel.clj:423)
    clojure.lang.MultiFn.invoke (MultiFn.java:238)
    leiningen.figwheel$figwheel.invokeStatic (figwheel.clj:523)
    leiningen.figwheel$figwheel.doInvoke (figwheel.clj:439)
```

**Comment by bhauman** [comment]
Thanks for the report, looking at this now.

**Comment by yogthos** [comment]
fantastic thanks!

**Comment by bhauman** [comment]
This commit fixes it in simple-lein-profile merge.

https://github.com/bhauman/simple-lein-profile-merge/commit/141acb4a94d64dfad50db6621ebcf60785e975ce

**Comment by yogthos** [comment]
perfect, just ping me when you have it up and I'll let you know if it works

**Comment by bhauman** [comment]
slimple-lein-profile-merge "0.1.1-SNAPSHOT" deployed

**Comment by yogthos** [comment]
Unfortunately, I still see the same issue. [Here's](https://github.com/yogthos/figwheel-test) a complete project I'm using to test.

**Comment by bhauman** [comment]
you have a typo `slimple-lein-profile-merge` is wrong it's `simple-lein-profile-merge`

**Comment by bhauman** [comment]
Ahh but you can't exclude the plugin deps ...

**Comment by bhauman** [comment]
Also a big note here is that you should never include [lein-figwheel ] in your `:dependencies`, if you pull in lein-figwheel you are pulling in leiningen-core and that's not a good idea. This is true for all plugins.

If you need figwheel in the repl include [figwheel-sidecar] in your dependencies.

**Comment by yogthos** [comment]
Ah yeah I'll definitely update that.

**Comment by bhauman** [comment]
OK deployed lein-figwheel 0.5.4-1

**Comment by yogthos** [comment]
Yup, can confirm figwheel is starting up ok. I'm going to do a bit of testing around using the nREPL and stuff.

**Comment by yogthos** [comment]
OK can confirm the nREPL is working well. I think we can close this one.

**Comment by yogthos** [comment]
and thanks for getting this resolved so fast :)
