### ISSUE TITLE
figwheel not serving the app.js

### ISSUE THREAD

**Issue by yogthos** [bhauman/lein-figwheel#428]
I'm updating the Reagent template and I ran into a problem where Figwheel 0.5.4 will not server the `app.js` file from `target/cljsbuild/public/js/app.js`. This works correctly in 0.5.3-2. Here's a sample [project.clj](https://gist.github.com/yogthos/3d011bc04c7ddeb8a13e34271f3d6881) file.

**Comment by bhauman** [comment]
looking at this now

**Comment by bhauman** [comment]
I traced this to your ring handler stack, your call to `(resources "/")` is not working and passing through to `(not-found "Not Found")`.  When I comment that out it falls through and gets to my `(resources "/" {:root "public"})` call which picks up the file. Soooo ...

**Comment by bhauman** [comment]
The :resource-paths and class path are all correct.  I have no idea why your call to `resources` isn't working.

**Comment by bhauman** [comment]
actually think I may have found it

**Comment by yogthos** [comment]
good to hear, let me know if you want me to do more testing

**Comment by bhauman** [comment]
man actually this is super funky ... it works and then it doesn't work, think it may be something else in the ring stack because the Figwheel stack works on its own with compile targets in the "target". Maybe reloader is doing it I don't know.

**Comment by bhauman** [comment]
Yeah there is definitely something in your wrap-middleware that is messing with the state when I remove that .  The figwheel-server ring stack hasn't changed at all in this release.

**Comment by yogthos** [comment]
Hmm, yeah that's pretty weird because it was working consistently with the last release. [This](https://github.com/reagent-project/reagent-template/blob/master/resources/leiningen/new/reagent/env/dev/clj/reagent/middleware.clj) is the only middleware being used too. It's just ring-defaults, wrap-exceptions, and wrap-reload.

**Comment by bhauman** [comment]
@yogthos you bumped up `ring-defaults` and `ring` at the same time you bumped up figwheel. I think the action is there.

**Comment by yogthos** [comment]
Yeah it does look like it's the interplay between them. Would make sense for Figwheel to work with the latest ring-defaults though. :)

**Comment by bhauman** [comment]
There is nothing fishy going on inside the Figwheel server.

https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/components/figwheel_server.clj#L156
This hasn't changed.

If you see a safer way to do it let me know.

**Comment by yogthos** [comment]
I'm still not sure what cause the issue in the new ring-defaults. Unfortunately, I haven't had much time to dig into this yet. I'll let you know if I figure it out though.

**Comment by bhauman** [comment]
I'm going to look at this again.  It occurs to me that I can make this much simpler and get rid of the compojure dep.  Which would be a good thing.

**Comment by yogthos** [comment]
Sweet! :)

**Comment by yogthos** [comment]
Awesome, I'll push out a new reagent-template with the latest

**Comment by yogthos** [comment]
I did a bit of testing with the latest and I still see the issue unfortunately. It doesn't appear to be related to middleware, I've tried just using the `defroutes` defined handler as `:ring-handler` and also failed to load Js.

However, this doesn't happen every time either. Is it possible that there's some race condition in loading the resource paths that's happening. The cljs build config is set as follows [here](https://github.com/reagent-project/reagent-template/blob/5bf255cc6f82a4b9daf767d6d7fdbc079e5d0a1c/resources/leiningen/new/reagent/project.clj#L65).

```clojure
{:main "{{name}}.dev"
              :asset-path "/js/out"
              :output-to "target/cljsbuild/public/js/app.js"
              :output-dir "target/cljsbuild/public/js/out"
              :source-map true
              :optimizations :none
              :pretty-print  true}
```

Not sure if that helps, but I'll keep looking to see if I can narrow this down.

**Comment by bhauman** [comment]
So you tested against the snapshot?

**Comment by bhauman** [comment]
I haven't deployed this change to clojars yet.

**Comment by yogthos** [comment]
Ah my bad, I saw a new version show up on Clojars after the issue getting closed and assumed it had the change. Just did a local install for the snapshot and can confirm everything is looking good. Sorry for the noise. ;)

**Comment by lvh** [comment]
I ran into a similar issue trying to do the same; although it's not clear that it's exactly the same thing yet, because I'm still seeing it with the current release, which does come after that commit.

**Comment by lvh** [comment]
I don't know if this is related, but, I'm seeing:

> # Figwheel template
> Checkout your developer console.

... despite having configured a ring handler that doesn't show that page.

**Comment by lvh** [comment]
Downgrading to 0.5.3-2 does indeed resolve the issue.

**Comment by smogg** [comment]
Similar issue - ring handler no longer shows my page, but an index.html is displayed trying to load `http://localhost:3449/js/compiled/reason.js`

**Comment by lvh** [comment]
@smogg Can you add the exact versions where the problem started?

**Comment by smogg** [comment]
`0.5.4-4` is the first versions where the problem appears

**Comment by lvh** [comment]
`0.5.4-3` does not have the same issue? Have you been able to narrow this down to a commit?

**Comment by smogg** [comment]
No issues on `0-5.4-3`. Not sure which commit introduced the issue exactly

**Comment by smee** [comment]
I used to have a similar problem. The reason was a transitive dependency in my class path with an "index.html" in the jar. Depending on the order of loading, this (wrong) index.html got loaded instead of the one provided by figwheel. As soon as I got rid of this dependency everything went back to working perfectly.

**Comment by smogg** [comment]
@smee Did it also triy to load `reason.js`? Do you happen to remember what dependency was that?

**Comment by smee** [comment]
See https://github.com/keechma/forms/issues/2
Keechma/forms and lein-doo

**Comment by smogg** [comment]
@smee Yeah, it looks like that's it - one of the packages I'm using has index.html in public folder. Thanks!

**Comment by smogg** [comment]
So do I understand it correctly - now every package that has `resources/public/index.html` file will always override the handler in my app? That doesn't sound right imho

**Comment by smee** [comment]
Not always, no. It depends on the order of dependencies in your classpath / the loading order as implemented by the classloaders utilized. My understanding is, that if you just use the classloader to load resources from the classpath, you may experience the error you observed. The only two ways to prevent this are to avoid having other public/index.html files on your classpath or patch figwheel so it manually traverses all dependencies, identifies its own public/index.html and loads that (with special code to handle exploded/packaged cases...), not very feasible.

**Comment by lvh** [comment]
@smee Thanks, that was very insightful. Would it be helpful to short-circuit the index.html-manually-loading logic if a ring handler is provided? (My understanding is that that's how figwheel used to work.)
