### ISSUE TITLE
Error thrown by Figwheel 0.5.4

### ISSUE THREAD

**Issue by rationalism** [bhauman/lein-figwheel#429]
Figwheel 0.5.4 and higher throw this exception on startup:

---begin error message---
ExceptionInfo 
------- Figwheel Configuration Error -------

The key :server-port is most likely in the wrong place in your config.

  :cljsbuild {
    :builds [{
      :figwheel {
        :server-port 3450
        ^ key :server-port is on the wrong path
      }}]}

It should probably be placed here:

  :figwheel { :server-port 3450}

-- Docs for key :server-port --
An integer that the figwheel HTTP and Websocket server should bind.
Default: 3449

:server-port 3000

clojure.core/ex-info (core.clj:4617)
---end error message---

This is my ClojureScript build configuration, in project.clj:

  :cljsbuild {:builds
              [{:id "dev"
                :source-paths ["src/project_cljs" "src/project_cljc"]
                :figwheel {:websocket-url "wss://localhost:3450/figwheel-ws"
                           :server-port 3450}
                :compiler {:main "project_cljs.init"
                           :asset-path "/js/main"
                           :output-dir "resources/public/js/main"
                           :output-to "resources/public/js/main.js"
                           :optimizations :none
                           :pretty-print true}}]}

This configuration seems to work fine for me with Figwheel 0.5.3-2. Is it wrong somehow? Or is this a new bug in Figwheel? Thanks.

**Comment by bhauman** [comment]
You configuration is wrong as error states.

Configuration validation for start-figwheel  was added in 0.5.4 that's why you are seeing it now.
