### ISSUE TITLE
Add a :websocket-port option to go with :websocket-host

### ISSUE THREAD

**Issue by px0** [bhauman/lein-figwheel#432]
I have experienced flakiness with using the fighweel-provided static file server (which is probably worth its own issue) and 'solved' it by using a different httpd for it.
Now I have my own httpd running on port 8080, and the websocket connection is still on 3449. This is as it should be, except that my client is a mobile phone, so I was using `:websocket-host :js-client-host` in the configuration so as not to have to specify my development machine IP address. Unfortunately that breaks the websocket connection as the figwheel script now (I assume) tries to get a websocket connection on `:js-client-host` port 8080. This setup works if I explicitely specify a ` :websocket-url "ws://$my-hardcoded-ip:3449/figwheel-ws"`, but then I have to redefine the IP every time it changes. The most straight-forward way of fixing this (short of fixing the actual flakiness) that I can think of is adding a `:websocket-port` option which tries to establish the websocket connection to `:websocket-host` port `:websocket-port`

**Comment by bhauman** [comment]
Its worth taking a look at the :websocket-host docs in the readme

**Comment by bhauman** [comment]
actuallly i meant the :websocket-url docs :)

**Comment by mgerlach-klick** [comment]
Oh, cool! I looked for that but didn't see it until you pointed it out.
So would the right solution be:
`:websocket-url "ws://[[server-ip]]:3449/figwheel-ws"`
and leave the `:websocket-host` totally out of it?

**Comment by bhauman** [comment]
Yep! :)

**Comment by mgerlach-klick** [comment]
You have thought of everything! Thank you so much, Bruce, you're awesome!




Thursday, June 16, 2016, 17:37 -0400 from notifications@github.com  <notifications@github.com>:
>Yep! :)
>
>Sent from my iPhone
>

**Comment by bhauman** [comment]
Glad that helped :)
