### ISSUE TITLE
alternate browse-url support

### ISSUE THREAD

**Issue by davidsiefert** [bhauman/lein-figwheel#435]
When I try to run `lein figwheel` it invoked java.awt.Desktop.browse which is not supported on my platform.  It would be nice to have an option that lets me avoid this call and spawn the browser of my choice directly.

**Comment by davidsiefert** [comment]
It looks like this just delegates to ``clojure.java.browse/open-url`` so I'm thinking this is best solved in the clojure library itself.  Thoughts anybody?

**Comment by bhauman** [comment]
So this is actually in java.awt.desktop.  And it's a feature I just added to figwheel.  I'm not so certain of its value yet.  I personally turn it off because I end up with too many windows open.  It is ok for first user experience, which is why it was added.

**Comment by bhauman** [comment]
I'm going to close this for now, as it's not a feature that is going into the queue.
