### ISSUE TITLE
JavaScript hot reloading no longer default?

### ISSUE THREAD

**Issue by lambdahands** [bhauman/lein-figwheel#438]
Hi, I've been trying to get a `css-modules` setup much like [this one][cljs-css-modules] working. I have everything setup, and the CSS reloads as usual, but the JavaScript files I reference through `:foreign-libs` no longer seems to hot reload.

I noticed that project is using a `0.4.x` version of Figwheel, and when I run it locally, the dependencies reload as expected. As of `0.5.x` I haven't had any luck getting the same behavior. Is there configuration I'm not passing in correctly? I know it's possible to pass in a custom `cljs-build-fn`, but I'm a bit lost as to how that's accomplished.

Thanks for the awesome work here. I hadn't touched ClojureScript for a while, and coming back to Figwheel has been a joy, especially with the huge strides it's made. 😊 

[cljs-css-modules]: https://github.com/dhruvbhatia/clojurescript-css-modules-demo/

**Comment by bhauman** [comment]
I'll check into it.  Its easy for something like this to regress.  I would really appreciate a minimal example though.  If you could reproduce this with a `lein new figwheel hello-world` project that would be very helpful.

**Comment by bhauman** [comment]
Don't worry about the example... This is real and I'm looking into it.

**Comment by lambdahands** [comment]
Whoa, that was quick! Thanks for the fix. 💃

**Comment by bhauman** [comment]
deployed 0.5.4-5-SNAPSHOT if you need it right away

**Comment by lambdahands** [comment]
Just pulled down the `SNAPSHOT`, and everything is working great. Thanks so much again!
