### ISSUE TITLE
`lein do clean, figwheel` does not serve resources from target/

### ISSUE THREAD

**Issue by tonsky** [bhauman/lein-figwheel#439]
Might be related to #428, might be not. I still see this behaviour in 0.5.4-4, although 0.5.3 is fine. Here’s what happens:

```clj
:resource-paths ["target/js"]
:cljsbuild {
...
          :output-to            "target/js/main.js"
          :output-dir           "target/js/none"
... }
:figwheel {
    :http-server-root "."
    ...
}
```

Now, if I do `lein do clean, figwheel`, it won’t serve `/main.js`
If I stop that and run `lein figwheel` (no cleaning this time), it suddenly starts to work.
Strangely, `lein clean && mkdir target && mkdir target/js && touch target/js/main.js && lein figwheel` doesn’t work though.

Seems to be broken in 0.5.4 (all `0.5.4-*` are affected). 0.5.3 works fine.

My guess there’s a check somewhere that checks if folder exists and excludes it from resource path. Do you remember adding something like that between 0.5.3 and 0.5.4?

**Comment by tonsky** [comment]
It ends up classloader not seeing the resource:

```clj
(let [cl (.getContextClassLoader (Thread/currentThread))]
  (doseq [url (java.util.Collections/list (.getResources cl ""))]
    (println (str url))))
```

0.5.3:

```
$ lein do clean, fw
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid. Starting Figwheel ...
file:/Users/prokopov/Dropbox/ws/cognician/Insights/dev/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/src/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/target/js/             <----------
file:/Users/prokopov/Dropbox/ws/cognician/Insights/resources/
Figwheel: Starting server at http://0.0.0.0:4000
...
```

0.5.4-4:

```
$ lein do clean, fw
Figwheel: Cleaning because dependencies changed
Figwheel: Cutting some fruit, just a sec ...
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid :)
file:/Users/prokopov/Dropbox/ws/cognician/Insights/dev/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/src/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/resources/
Figwheel: Starting server at http://0.0.0.0:4000
...
^C
$ lein fw
Figwheel: Cutting some fruit, just a sec ...
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid :)
file:/Users/prokopov/Dropbox/ws/cognician/Insights/dev/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/src/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/target/js/               <-------------
file:/Users/prokopov/Dropbox/ws/cognician/Insights/resources/
Figwheel: Starting server at http://0.0.0.0:4000
...
```

There’s definitely something fishy going on, but I can’t figure out what yet.

**Comment by bhauman** [comment]
where are you placing that code?

**Comment by bhauman** [comment]
I'm going to look into this more

**Comment by tonsky** [comment]
In my handler. Looks like I can't serve these resources from my handler as
well. Only as files

**Comment by bhauman** [comment]
Actually this is a bad test

````
(let [cl (.getContextClassLoader (Thread/currentThread))]
  (doseq [url (java.util.Collections/list (.getResources cl ""))]
    (println (str url))))
```

This will only respond if the directories exist. You would need to add a file to the directory and then call this.

Are you by chance using the `:open-urls` thing?

**Comment by tonsky** [comment]
No

**Comment by bhauman** [comment]
I found it ... the figwheel validation used to run in the figwheel plugin and it *ensured* the existence of the :output-dir directories BEFORE the figwheel process started. 

A rule :: A resource-path must exist before a process starts.

We never ran into this before because figwheel was ensuring the existence of these directories, BTW it did this because earlier versions of the compiler would error on their absense.

So bottom line ... its important to know that if a resource-path isn't there at launch it doesn't get included in the resource paths.

I'm reintroducing this behavior into the plugin but it needs to be pointed out that figwheel is doing something exceptional here which is not the rule for other plugins [lein-ring etc] ... this could be confusing if you move to a different setup, where you launch your own server in a different lein process, which happens to start when the target path was blown away.

This seems to point to having the target path as a resource path as a brittle setup ...

https://github.com/bhauman/lein-figwheel/issues/428
@yogthos
@tonsky

**Comment by yogthos** [comment]
Ah that makes sense. I noticed a similar problem the other day, where I would need to start figwheel before doing `lein run` after deleting the target folder, or the path to Js assets wouldn't exist and the server wouldn't see the compiled Js once figwheel started.

I think the behavior makes sense in this case as I can't see why you wouldn't want the path to be created.

Having resource path as a target path is important conceptually as these are generated assets and should not be part of the sources/resources paths.

**Comment by bhauman** [comment]
I reinstated this directory creation behavior here:

https://github.com/bhauman/lein-figwheel/commit/5c5caa436c9dda5656e56c300bf469c4f79b06b4

**Comment by bhauman** [comment]
This should be fixed ...

**Comment by yogthos** [comment]
👍

**Comment by yogthos** [comment]
If you're really worried about this being an implicit behavior, perhaps a log might be a good compromise. Figwheel could say "creating resource path for ...".

**Comment by tonsky** [comment]
Wait, that doesn’t explain why `lein clean && mkdir target && mkdir target/js && touch target/js/main.js && lein figwheel` won’t serve my resources

**Comment by tonsky** [comment]
```
$ lein clean && mkdir target && mkdir target/js && lein fw
Figwheel: Cleaning because dependencies changed
Figwheel: Cutting some fruit, just a sec ...
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid :)
file:/Users/prokopov/Dropbox/ws/cognician/Insights/dev/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/src/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/resources/
Figwheel: Starting server at http://0.0.0.0:4000
```

**Comment by tonsky** [comment]
Oh. It probably does. If I just create empty dirs, `Figwheel: Cleaning because dependencies changed` kicks in, and it probably deletes all the directories I’ve created

**Comment by tonsky** [comment]
Yep. That fixed it. Thanks a lot, that was probably not easy to figure out :)

```
$ lein do clean, fw
Figwheel: Cleaning because dependencies changed
Figwheel: Cutting some fruit, just a sec ...
Retrieving figwheel/figwheel/0.5.4-5-SNAPSHOT/figwheel-0.5.4-5-20160623.192821-1.pom from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.4-5-SNAPSHOT/figwheel-sidecar-0.5.4-5-20160623.192838-1.pom from clojars
Retrieving figwheel/figwheel/0.5.4-5-SNAPSHOT/figwheel-0.5.4-5-20160623.192821-1.jar from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.4-5-SNAPSHOT/figwheel-sidecar-0.5.4-5-20160623.192838-1.jar from clojars
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid :)
file:/Users/prokopov/Dropbox/ws/cognician/Insights/dev/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/src/
file:/Users/prokopov/Dropbox/ws/cognician/Insights/target/js/           <----
file:/Users/prokopov/Dropbox/ws/cognician/Insights/resources/
Figwheel: Starting server at http://0.0.0.0:4000
```
