### ISSUE TITLE
Update Sidecar README

### ISSUE THREAD

**Issue by brw31415** [bhauman/lein-figwheel#440]
hi, i am stepping through the initial instructions on the web site, when i get to 
(require '[figwheel-sidecar.system :as sys])
i  get:

 java.lang.RuntimeException: No such var: ana/forms-seq*, compiling:(figwheel_sidecar/utils.clj:49:21)

**Comment by bhauman** [comment]
Oh sorry you will want to ensure you are using the a later version of ClojureScript.  

Which instructions are you following and which version of ClojureScript are you using?

**Comment by bhauman** [comment]
Oh sorry you were reading the sidecar README.  Thats pretty out of date.  I will update it.

**Comment by stevebuik** [comment]
I've also just used the sidecar component/docs and found a problem. 

I needed to use (sys/figwheel-system (:data (sys/fetch-config))) to make it work i.e. needed to extract the map from the record using the :data key to make it load the system with valid config.

Happy to log a new issue, let me know if you prefer that.

**Comment by isaksky** [comment]
I had that problem too. Thanks @stevebuik .
