### ISSUE TITLE
Introduce :non-interactive-validation config tweak

### ISSUE THREAD

**Issue by darwin** [bhauman/lein-figwheel#444]
I'm aware of `:validate-config` option to disable config checks. I would still like to use config validation but I don't want interactive resolution because I'm using `lein figwheel` as part of other scripts (via lein-cooper).

I would propose a new tweak `:non-interactive-validation` which would be `false` by default.
When set to `true`, validation errors would be still printed, but figwheel would auto-resolve them with "(s)tart Figwheel anyway?". 

Additionally this tweak could have a string value, which would match:
* (f)ix
* (q)uit
* (s)art
* ...

**Comment by bhauman** [comment]
Let's make it :validate-interactive (true, false, :fix,:quit)

**Comment by darwin** [comment]
Is the documentation out-of-sync with the spec in 0.5.6? Looks like `:start` is not supported.

```
------ Figwheel Configuration Error ------

The key :validate-interactive at (:figwheel) has a non-conforming value: :start
It should satisfy one of: boolean? | #{:fix :quit}

  {:figwheel
   {:server-port 7100
    :server-logfile ".figwheel_dirac.log"
    :validate-interactive :start
    ^---- The value at key :validate-interactive doesn't conform
    :repl false}}

-- Docs for key :validate-interactive --
Because build startup time is significant Figwheel offers the
opportunity for you to fix you configuration problems interactively.
In some develeopment environments this is not desirable. In this case
you can just set :validate-interactive to false

Other options are:
:fix   - don't ask if you want to watch and fix, just start watching
:quit  - just quit on a validation error, same behavior as false
:start - ignore any configuration errors and start figwheel anyway

Default: true

  :validate-interactive false

------------------------------------------
```

**Comment by bhauman** [comment]
this is a problem with the spec itself... just fixed it...  
https://github.com/bhauman/lein-figwheel/commit/11655e7fd1dee2f68a8d40b68484d006e6c23bd0
