### ISSUE TITLE
Does not work with cljs-devtools custom options

### ISSUE THREAD

**Issue by ariofrio** [bhauman/lein-figwheel#445]
See https://github.com/binaryage/cljs-devtools/releases/tag/v0.7.2:

> ClojureScript newly supports :preloads compiler option which allows you to require namespaces prior your :main namespace. Now you can use this feature to add cljs-devtools support to your project without modification of your code. You simply add devtools.preload into the :preloads list.
>
> [...]
>
> You may specify additional configuration options under your compiler options. 
For example cljs-devtools expects its custom config under :tooling-config > :devtools/config.
> 
> For example:
> 
> ~~~
:tooling-config {
  :devtools/config {
    :features-to-install    [:sanity-hints]
    :fn-symbol              "F"
    :print-config-overrides true}}
~~~

In particular, the error shown is:

~~~

ExceptionInfo 
------- Figwheel Configuration Error -------

Found unrecognized key :tooling-config at path [:cljsbuild :builds 0 :compiler]

  :cljsbuild {
    :builds [{
      :compiler {
        :tooling-config { :devtools/config { ... } }
        ^ key :tooling-config not recognized
      }}]}

  clojure.core/ex-info (core.clj:4617)
~~~

**Comment by darwin** [comment]
Set `:figwheel` > `:validate-config` to `false`. AFAIK that is the only way around that.

The `:tooling-config` name is not set in stone yet. We should discuss it with @bhauman and come up with a more general name.

**Comment by bhauman** [comment]
`:external-config` is a real thing and it's in 0.5.4-5

**Comment by ThomasDeutsch** [comment]
i use a figwheel.clj script file where i preload the devtools `:preloads [devtools.preload]` as a compiler option.

```clj
(require '[figwheel-sidecar.repl :as r]
         '[figwheel-sidecar.repl-api :as ra])

(ra/start-figwheel!
  {:figwheel-options {:css-dirs ["resources/public/css"]}
   :build-ids ["dev"]
   :all-builds [{:id "dev"
                 :figwheel true
                 :source-paths ["src/myproj/main"]
                 :compiler {:main 'myproj.main.core
                            :asset-path "dev/out"
                            :output-to "resources/public/dev/main.js"
                            :output-dir "resources/public/dev/out"
                            :verbose true
                            :preloads [devtools.preload]}}
            ]})

(ra/cljs-repl)
```

but i get **this error**:
`
Exception in thread "main" java.lang.ClassNotFoundException: devtools.preload, compiling:(C:\myproj\script\figwheel.clj:4:1)`

i use
```clj
:dependencies [[org.clojure/clojure "1.9.0-alpha7" :scope "provided"]
               [org.clojure/clojurescript "1.9.88" :scope "provided"]
               [figwheel-sidecar "0.5.4-5" :scope "test"]]
```

**Comment by bhauman** [comment]
you are having a Regular clojure error.

See how your 'myproj.main.core is quoted? It needs to be that way otherwise Clojure needs to find its value, which is not available.  Try unquoting that symbol and you will see your error change to that symbol.

Now you just need to make sure that all unquoted symbols are quoted. 

ie.
```
['devtools.preload]
```

but its even easier to just quote the whole thing (after unquoting all your symbols)

```
(start-figwheel! '{...}) ;; if you do this you can't have quoted symbols
```
