### ISSUE TITLE
Don't fire a reload event if figwheel-no-load is on the namespace

### ISSUE THREAD

**Issue by Hendekagon** [bhauman/lein-figwheel#446]
Figwheel has ^:figwheel-no-load to prevent reloading of a namespace, however it still reloads the page on changes to that namespace's file. It would be nice if there were an option to make Figwheel completely ignore changes to a namespace's file and not reload the page on changes to it.

**Comment by bhauman** [comment]
Hmmm, this looks like a regression.

**Comment by bhauman** [comment]
Nice tensegrity ...

**Comment by Hendekagon** [comment]
Thanks! My brother & I designed the system, it's carbon-fibre tubes with elastic loops running through & around them, and the tensegrity is constructed by looping the ends of the tubes in the elastic to form knots. Ken Snelson is one of my favourite artists.

**Comment by bhauman** [comment]
Hmmmm ... I *finally* get what you are saying here is figwheel-no-load shouldn't fire any events on file change.  Took me long enough to get it. This is a good point.

**Comment by bhauman** [comment]
And added benefit would be that you can easily exclude .cljc namespaces, etc.

**Comment by bhauman** [comment]
Note to self: this is best done client side.
