### ISSUE TITLE
Cursive with checkouts

### ISSUE THREAD

**Issue by metasoarous** [bhauman/lein-figwheel#450]
In the [Cursive wiki page](https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL), it is mentioned that the setup there breaks checkouts. Is this still the case? Or has this been fixed? If not, what's the issue and is there a way around it?

**Comment by bhauman** [comment]
I have no idea as "I don't use Cursive yet"™ and that page is maintained by others.

Might want to check check the #cursive channel on clojurians.slack.com
