### ISSUE TITLE
Ring server *out* not printing (flushing) to terminal

### ISSUE THREAD

**Issue by comamitc** [bhauman/lein-figwheel#456]
I see at least where the logic switch occurs: https://github.com/bhauman/lein-figwheel/blob/c346a65ad3d170ebe21b2f47e8b4b24f1d7f1df5/sidecar/src/figwheel_sidecar/components/figwheel_server.clj#L357-L361

Toggling the `repl` on gets the `server-logfile` to capture output. If `repl = false`, `(print ...` statements don’t get flushed from the ring server.  

If I randomly define and use: 

``` clj
(defn print-ln [s]
  (.println System/out s))
```

**after** serval print statements, all are flushed and printed.

**Comment by bhauman** [comment]
I'm going to need more info about your environment and how you are running figwheel.

**Comment by bhauman** [comment]
I'm looking into this but when I run figwheel with `:repl false` I get output from my ring handlers to the terminal..

Also are you using the latest version of figwheel?

**Comment by bhauman** [comment]
I made some changes, see if 0.5.5-SNAPSHOT changes your experience

**Comment by IwanKaramazow** [comment]
I'm experiencing the same issue, `println` doesn't print to my cider-repl in emacs.

Apparently it has something to do with fighweel, whenever I run figwheel on version `"0.5.3-2"` `println` gets flushed to the terminal. Newer version of figwheel lose the ability to println code in my ring handler.

I'm using the chestnut template with the following config:

```clojure
:figwheel {
             :css-dirs ["resources/public/css"]  ;; watch and update CSS
             :ring-handler user/http-handler
             :server-logfile "log/figwheel.log"}
```

```clojure
;; user.clj
(ns user
  (:require [bp.server]
            [ring.middleware.reload :refer [wrap-reload]]
            [figwheel-sidecar.repl-api :as figwheel]))
(set! *warn-on-reflection* true)
(set! *unchecked-math* :warn-on-boxed)
(def http-handler
  (wrap-reload #'bp.server/http-handler))

(defn run []
  (figwheel/start-figwheel!))

(def browser-repl figwheel/cljs-repl)
```

**Comment by IwanKaramazow** [comment]
Update running your own server, instead of using the `:ring-handler` config hook, is a pretty easy workaround.

**Comment by bhauman** [comment]
This is solved if you set `:server-logfile false`
