### ISSUE TITLE
Compilation reports misleading source paths

### ISSUE THREAD

**Issue by TerjeNorderhaug** [bhauman/lein-figwheel#458]
When compiling, Figwheel reports the source paths it supposedly uses:

    Compiling "resources/public/js/out/app.js" from ["src/browser" "src/cljs"]...

**However, the reported source paths are not those actually used for compilation.**

Verify by modifying a project so the :source-paths of a build is split into a new build definition:

    {:builds {:app {:source-paths ["src/browser" "src/cljs"] ...}}}
    =>
    {:builds {:app {:source-paths ["src/browser"] ...} :bogus {:source-paths ["src/cljs"] ...}}}

Running `lein do clean, figwheel app` will still complete yet fail to report it is still using sources in "src/cljs":

    Compiling "resources/public/js/out/app.js" from ["src/browser"]...

Confusingly, the build is instead compiled based on a union of all source paths from the the project, which may lead to surprises including conflicts when different builds have modules in the same namespace.

**For consistency, Figwheel should report the source paths it actually uses for compilation. Preferably, when compiling Figwheel should use only the source paths for the current build rather than the union of source paths from all builds.**

**Comment by TerjeNorderhaug** [comment]
Moreover, a build will still compile even with nothing but an empty directory `mkdir src/bogus` as `{:source-paths ["src/bogus"] ...}` while reporting:

    Compiling "resources/public/js/out/app.js" from ["src/bogus"]...

**Comment by bhauman** [comment]
I'm going to need a little more information.  A more detailed project.clj would be helpful along with wether you are using cljc

**Comment by TerjeNorderhaug** [comment]
I have verified the issue can be replicated using this clojurescript project (no cljc): 

    git clone https://github.com/TerjeNorderhaug/cljsnode

Edit project.clj commenting out "src/cljs" from the :source-paths of the :app build, as in:

    :cljsbuild {:builds {:app {:source-paths ["src/browser" #_"src/cljs"] ... }}}

Then run figwheel to compile:

    lein do clean, figwheel app

The compilation will complete as expected despite the missing source path, while reporting:

    Compiling "resources/public/js/out/app.js" from ["src/browser"]...

Yet the output has still been compiled using sources in "src/cljs":

    ls resources/public/js/out/app
    ls src/cljs/app

**Comment by bhauman** [comment]
Are you sharing an :output-dir between build configurations?

**Comment by TerjeNorderhaug** [comment]
No sharing of `:output-dir`:

    :cljsbuild 
    {:builds                                                                                           
              {:app                                                                                             
               {:source-paths ["src/browser" #_"src/cljs"]                                                                   
                :compiler {:output-to "resources/public/js/out/app.js"                                          
                           :output-dir "resources/public/js/out"                                                
                           :asset-path "js/out"                                                                 
                           :main app.start                                                                      
                           :optimizations :none}}                                                               
                                                                                                                
               :server                                                                                          
               {:source-paths ["src/node" "src/cljs"]                                                           
                :compiler {:target :nodejs                                                                      
                           :output-to "main.js"                                                                 
                           :output-dir "target"                                                                 
                           :main server.core                                                                    
                           :optimizations :none}                                                                
                }}}

**Comment by TerjeNorderhaug** [comment]
Potentially related to issue #169.

**Comment by bhauman** [comment]
So this is complex ...

The classpath *is* the union of all the cljs source paths... This is the
way that both cljsbuild and figwheel behave ...

So if you require a namespace that is on the classpath the compiler will
look it up and pull it in ...

The cljs build config :source-paths key indicates the directories that are
both watched and added to the classpath...

Your source code is requiring files that are on the classpath and thus they
are included in the build, this is precisely how source files are pulled
out of dependency jars. (they are on the classpath)

You have also explicitly added the top level :source-paths ["src/cljs"] to
the classpath as well.

If you want to stop this behavior

set the top level `:source-paths []` exclude the default ["src"]

and set the following`:figwheel-load-all-builds false` which will only add
the source path of the builds that are supplied on the command line.

**Comment by bhauman** [comment]
And I may add that the only reason to do this is to have a namespace that serves two different purposes ...

This violates the idea that a namespace is an identity which is the expectation in Clojure programming ...

**Comment by TerjeNorderhaug** [comment]
*The issue here is that figwheel gives misleading feedback during compilation*, creating the impression that the specific source-paths from a build definition in the project is used for compilation. For example, when building :app from the project above, figwheel will report to the developer:

    Compiling "resources/public/js/out/app.js" from ["src/browser"]...

Yet the compilation is based on the union of the source paths: ["src/browser" "src/node" "src/cljs"]. Figwheel should avoid misunderstandings by rather inform the developer about the actual source paths used for the compilation:

    Compiling "resources/public/js/out/app.js" from ["src/browser" "src/node" "src/cljs"]...

I dug into the figwheel code to take a closer look at what causes figwheel to report misleading source-paths during compilation. Apparently `leiningen.figwheel/run-local-project ` starts a new figwheel process with the union of all :source-paths, merged by `make-subproject`. Yet `figwheel-sidecar.components.cljs-autobuild/figwheel-start-and-end-messages` misleadingly reports to the user only the source-paths of the current build.

**Comment by bhauman** [comment]
I hope that you're emphasis is intended to clarify... but rest assured I'm trying to be helpful here.

I am taking the time to clarify what is going on ...

The classpath is a completely different thing than the source paths that are passed to the compiler.  The message is completely accurate about which source paths are being sent to the compiler.  The compiler looks at every file on those source paths and then tries to resolve any missing required namespaces via the classpath.  

So we have two different meanings here the source paths passed to the compiler and the classpath.

Figwheel is correctly reporting which source paths are being directly given to the compiler... and that is precisely what this compilation message is intended to clarify.

I understand that you are finding this to be false advertising. But I assure you that there is a different intent for that message than what you are interpreting it to be. It is very important to know which :source-paths the compiler is *directly* examining.  If you don't require namespaces from the classpath they will not show up in the output.

Figwheel is behaving in the exact same way as cljsbuild and this is for the reason mentioned above.

**Comment by bhauman** [comment]
Well that was pretty repetitive... its late over here on the east coast.

**Comment by TerjeNorderhaug** [comment]
Perhaps Figwheel could make this behavior more transparent for the user? Such as reporting the actual class path used by the compilation, or alternatively the union of the source-paths as a proxy.

As the :source-paths of a build can be even just a bogus empty directory, it is not apparent that knowing the source-paths from the build definition makes a significant difference. If the distinction actually is very important, how can this be communicated better than the current compilation feedback?

**Comment by TerjeNorderhaug** [comment]
> The compiler looks at every file on those source paths and then tries to resolve any missing required namespaces via the classpath.

**Comment by bhauman** [comment]
The only reason it is building with an empty :source-paths is because source is being injected into the build via `:figwheel true`.

Figwheel true creates and injects a single source file which in turn requires the :main option 'app.start.  And the compiler then looks for 'app.start on the classpath because its not in the supplied source files.

So there is magic going on...

I could report the local directories that are on the classpath ...

But the classpath is vast and it includes local resource directories target directories etc ... 
So an understanding of the environment and lein is absolutely necessary, there is no way around this especially if you want to have an identity (namespace, module) on the classpath mean two different things.  This, by the way, is not recommended at all.

If you experiment you will see that including and excluding paths from :source-paths does in fact determine exactly what gets compiled.

If you want do something like using a single namespace to do two different things (again, not recommended), you will need to manage the classpath.

**Comment by TerjeNorderhaug** [comment]
Using a single namespace for two modules that do the same thing for different platforms seems acceptable. The [Clojure 1.7 Reference ](http://clojure.org/reference/reader#_reader_conditionals) states that:

> The primary mechanism for managing platform-specific code is to isolate that code into a minimal set of namespaces, and then provide platform-specific versions (.clj/.class or .cljs) of those namespaces.

The [announcement of Clojure 1.7](http://blog.cognitect.com/blog/2015/6/30/clojure-17) from last year contains similar language, noting that:

> It is now common to see a library or application targeting multiple Clojure platforms with a single codebase.

The [Clojure Wiki](http://dev.clojure.org/display/design/Reader+Conditionals) discusses platform specific namespace overrides:

>This allows the opportunity to override a platform-agnostic file with a platform-specific implementation of a namespace.

How can we better support using a single namespace for two clojurescript implementations of the same functionality targeting respectively nodejs and the browser in an isomorphic app?

**Comment by bhauman** [comment]
All of the references are referring to a single file the behaves differently in u

**Comment by TerjeNorderhaug** [comment]
I presume you're referring to a single file the behaving differently depending on platform due to the use of Reader Conditionals. That would be a secondary mechanism for managing platform-specific code, with platform-specific versions of namespaces being the primary mechanism for managing platform-specific code.

> To support cases where is not feasible to isolate the varying parts of the code, or where the code is mostly portable with only small platform-specific parts, 1.7 provides Reader Conditionals.

> In cases where is not feasible to isolate the varying parts of the code, or where the code is mostly portable with only small platform-specific parts, 1.7 also introduced reader conditionals, which are supported only in cljc files and at the default REPL. Reader conditionals should be used sparingly and only when necessary.

**Comment by bhauman** [comment]
There is so much to communicate here.  

First off it is possible to overload namespaces.  But in ClojureScript this is much much trickier.  

And I will refer to the the forums for more conversation on that.  

The platforms here are very similar so load time conditionals are a great choice to make short work of this...


(defn node-env? [] (not (nil? goog/nodeGlobalRequire)))

(def my-fun 
  (if (node-env?) 
     (fn [a b] (+ a b))
     (fn [a b] (- a b))))


  




The platform difference in this case is negligible.  And thus the way I handle differences

**Comment by bhauman** [comment]
Darn I'm on my phone and it formatted the code as a markdown link

**Comment by bhauman** [comment]
If you look in the figwheel support/src/figwheel/client/utils.cljs there are predicates for detecting the platform

**Comment by bhauman** [comment]
Please refer to clojurians.net to get more help ...

**Comment by TerjeNorderhaug** [comment]
I am not looking for help - I've been managing platform-specific implementations in isomorphic clojurescript by overloading namespaces for a while.

Using separate platform-specific implementations can be a good solution when a namespace :require a library that is distributed as [CLJSJS](http://cljsjs.github.io/) for the browser and [NPM](https://www.npmjs.com/) for Node. Typically the implementations will have different namespace declarations, e.g. `(ns app.shim (:require [cljsjs.pubnub]))...` for the browser vs `(ns app.shim (:require [cljs.nodejs :as nodejs]))...` for node.

Clojure's [reader conditionals] (http://clojure.org/guides/reader_conditionals) address platform-specific components in namespace declarations, but cannot (yet) distinguish between browser- and node-specific clojurscript. The predicates in figwheel/client/utils.cljs are no substitute.

Anyway, this is a bit of a detour from the issue I reported, although it may give you some insight into why figwheel should play well with overloading namespaces.  I'll bump it up to the next level. Thank you for taking the time considering it.
