### ISSUE TITLE
Suppressing print statements when using figwheel-sidecar.repl-api

### ISSUE THREAD

**Issue by aamedina** [bhauman/lein-figwheel#459]
Hello! 

I was wondering if it was possible to suppress printed messages which look like:

"Compiling ... from [...]"

and 

"notifying browser that file changed: ...".

The use case is when I embed the Figwheel process using the REPL API, I would like to be able to edit code without seeing these messages. 

Thank you!

**Comment by bhauman** [comment]
Specifically how are you starting the repl?  I need to know all the options that you are passing as well.

**Comment by aamedina** [comment]
I'm using CIDER. I just create a project REPL, and then start a system (via com.stuartsierra.component) which uses a Figwheel component.

**Comment by aamedina** [comment]
Here's the config: https://github.com/aamedina/om-cljs/blob/master/src/leiningen/new/om_cljs/dev/user.clj#L8

**Comment by bhauman** [comment]
get rid of the :repl false and you are good

**Comment by aamedina** [comment]
Woohoo! Thanks :)

**Comment by bhauman** [comment]
Woohoo! :)  Lovin it ...
