### ISSUE TITLE
Debugging slow reloading

### ISSUE THREAD

**Issue by aamedina** [bhauman/lein-figwheel#462]
Hello there!

I can reproduce this behavior using the example flappy-bird-demo project.

From the logs:
[Compiling "resources/public/js/flappy_bird_demo.js" from ["src"]...
[Successfully compiled "resources/public/js/flappy_bird_demo.js" in 10.364 seconds.
notifying browser that file changed:  resources/public/js/out/goog/deps.js
notifying browser that file changed:  resources/public/js/out/cljs_deps.js
notifying browser that file changed:  out/flappy_bird_demo/core.js

Every rebuild takes around the same time, which leads me to think that something is introducing ten seconds of overhead somewhere in the pipeline.

I've tested Hawk on its own to see if it was some sort of file watching issue, but Hawk seems to detect changes immediately so the delay doesn't seem to be there.

I've also started the lein-cljsbuild autobuilder for the same project and recompilation takes around 100-150ms.

Since I was able to reproduce this delay across multiple projects, including the flappy-bird-demo example, I was wondering if you had any ideas for how I could debug and solve this? 

Thanks!

**Comment by bhauman** [comment]
Is this on every incremental build?

**Comment by bhauman** [comment]
Or is it just on the initial build??

**Comment by aamedina** [comment]
Every incremental build.

**Comment by bhauman** [comment]
so you are on Linux or windows?

**Comment by aamedina** [comment]
Mac OS X

**Comment by bhauman** [comment]
And you are using the checkout of flappy-bird demo?

**Comment by aamedina** [comment]
I cloned the repository and then ran `lein figwheel`. But this is happening with my other Figwheel projects as well, I just did that to make sure it wasn't anything local to a specific project.

**Comment by bhauman** [comment]
Please note if you have anything strange about your environment, docker, vagrant strange filesystem, remote file system?

**Comment by aamedina** [comment]
Nothing like that, but I am using macOS Sierra. Both Hawk and lein-cljsbuild seem to be unaffected though.

**Comment by bhauman** [comment]
Well that is worth noting for sure, I run on osx and my incremental builds for the demo are 0.249s seconds.

So if it's an iNotify thing you can try polling and see if that fixes things...

project.clj > :figwheel > :hawk-options {:watcher :polling}

**Comment by aamedina** [comment]
I tried that actually with all supported :watcher values. No change in incremental compilation time.

**Comment by bhauman** [comment]
And you are using the latest figwheel?

**Comment by aamedina** [comment]
Yes, I also tried the snapshot version and the previous release.

**Comment by aamedina** [comment]
All of this does make me suspect macOS Sierra... But I would have thought a problem there would manifest in Hawk.

**Comment by bhauman** [comment]
So the compiler checks the timestamp of the previously compiled files with the timestamp of the source files, to decide wether to recompile...

It's strange that cljsbuild works and figwheel doesn't though...  That makes me think that there is a filesystem api change.  Oh wait OSX Sierra has a brand new filesystem.

**Comment by aamedina** [comment]
Just tested figwheel-sidecar.watching/watch!.

Looks like changes are being propagated almost immediately there. So it doesn't seem to be the file watching infrastructure itself. 

Is there a facility to perform an incremental build for your project from the REPL? I'll test that next, and if it takes 10+ seconds, I'll try to instrument it to see what's taking the time.

**Comment by bhauman** [comment]
So it wouldn't be hawk be cause the compile starts. It's got to be that the compilation output-dir is getting blown away each time...

Does it say "Figwheel: Cleaning build dev" for each build iteration in the figwheel server log?

**Comment by aamedina** [comment]
No, just exactly what I posted in the original issue.

**Comment by bhauman** [comment]
I can't imaging trying it in the REPL would make any difference but yes that exists:

https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

**Comment by bhauman** [comment]
I really think the directory is getting cleaned each time around.

**Comment by aamedina** [comment]
Sorry I was unclear, I meant that I want to programmatically start an incremental build, so I can get a sense of where to profile.

**Comment by aamedina** [comment]
Just confirmed the output-dir is not being cleaned. It's only modifying the specific files changed after the incremental build has completed.

**Comment by bhauman** [comment]
Yes, that page will help you programmatically start an incremental build ...

**Comment by aamedina** [comment]
Can you think of anything about figwheel-sidecar.build-middleware.injection/hook that could be causing this?

**Comment by bhauman** [comment]
Given that I'm not on your system I really don't know, if the filesystem is actually behaving differently anything could be causing it.

You can remove that middleware by commenting out the build config's > :figwheel key

and then run lein figwheel

**Comment by aamedina** [comment]
More context for you: figwheel-sidecar.build-middleware.injection/add-connect-script! is the specific call that is taking the 10 seconds.

**Comment by bhauman** [comment]
Thank you for being persistent and tracking this down! Good work.

**Comment by bhauman** [comment]
Let's see

**Comment by aamedina** [comment]
No problem, I love using Figwheel when developing ClojureScript. :) 

I'm looking through the source of add-connect-script! now, will report back if I find anything more specific.

**Comment by bhauman** [comment]
Well this could be moot, because I was going to remove the file system based connect script and do it all in memory.

**Comment by bhauman** [comment]
But it would be good to know exactly whats going on.

**Comment by bhauman** [comment]
.deleteOnExit could hang while waiting for a system resource

**Comment by bhauman** [comment]
And, that is the only call to that method in the whole codebase.

**Comment by aamedina** [comment]
Wow, prepare to have your mind blown for this one.

It's figwheel-sidecar.config/fill-websocket-url-template. 

(java.net.InetAddress/getLocalHost) is blocking for ten seconds.

**Comment by aamedina** [comment]
Actually five seconds, but it's called twice. :P

**Comment by aamedina** [comment]
So, if I had to speculate here, something to do with macOS Sierra has changed which is impeding java.net.InetAddress's ability to introspect the local network without blocking.

**Comment by bhauman** [comment]
Dang! And your are not even using that feature.

**Comment by aamedina** [comment]
More to the point, I do not think that interpolation is necessary if you're just using localhost, right? I'm thinking I'll just `lein install` a modified version of Figwheel for the time being which elides that call. Perhaps by the time Sierra is released, Java will have a solution to this problem. I can't imagine I'm the first to notice it.

**Comment by bhauman** [comment]
Still that call shouldn't be made if the template isn't being used.

**Comment by aamedina** [comment]
That's true. An even easier solution then would be to check to see if any of those regexes are in the url before replacing them. I can make a patch for this if you want.

**Comment by bhauman** [comment]
almost done with a commit

**Comment by aamedina** [comment]
Awesome! Thanks.

**Comment by bhauman** [comment]
I can deploy the snapshot in a bit

**Comment by aamedina** [comment]
No rush, I'll `lein install` in the meantime. Really appreciate your help here!

**Comment by aamedina** [comment]
Closing the issue since we figured it out and the practical issue has been addressed in https://github.com/bhauman/lein-figwheel/commit/c8fdb663711b6cc483269ce09a7ab06a52223c04.

**Comment by bhauman** [comment]
Alrighty redeployed the 0.5.5-SNAPSHOT

**Comment by nikitapecasa** [comment]
Hi, 
I was searching for the same problem, and found this page, so here is
a workaround for making getLocalHost faster on sierra - http://stackoverflow.com/questions/39636792/sbt-test-extremely-slow-on-macos-sierra/39698914#39698914

**Comment by drcode** [comment]
@nikitapecasa Thanks, your fix worked for me as well.

**Comment by iconara** [comment]
Any chance of making a release with this fix? It's probably going to bite everyone who upgrades to macOS Sierra. I've been using the latest release (0.5.4-7) and have been frustrated for a couple of weeks. I didn't think of looking at closed issues initially, perhaps this shouldn't be closed until the fix is released so that it's easier to find?

I changed to 0.5.5-SNAPSHOT and it looks like my build times went from 10+ seconds to around half a second.

**Comment by bhauman** [comment]
0.5.8 is the latest release

**Comment by iconara** [comment]
Apologies, [0.5.4-7 is marked as the latest release in the GitHub releases tab)[https://github.com/bhauman/lein-figwheel/releases/tag/v0.5.4-7], but I see now that it says 0.5.8 in the README.
