### ISSUE TITLE
sidecar README doesn't clarify purpose of sidecar

### ISSUE THREAD

**Issue by mars0i** [bhauman/lein-figwheel#465]
Figwheel is great!  I used it, starting the default 'lein new figwheel' configuration, in a couple of projects now.  figwheel-sidecar is a mystery, though.  It's included in the default project.clj, and so I assume that I am benefiting from it.  The README.md for sidecar begins with "Let's start with a sketch of how we can use the components in Figwheel Sidecar." and proceeds from there.  I'm lost already. It would be helpful if the README began with a sentence or two just stating what sidecar's overall purpose is.

**Comment by bhauman** [comment]
The sidecar readme is for advanced users.  The basic use of sidecar is explained the top level readme under 

https://github.com/bhauman/lein-figwheel#scripting-figwheel

**Comment by mars0i** [comment]
Thanks.  But from that page I can infer certain things about sidecar through careful reading and reading between the lines, but it's still not clear what sidecar does.  There's nothing there that states clearly what sidecar is--what it does in general.  I was looking at the sidecar README.md here because I was trying to understand the figwheel README.md.  "Figwheel has a Clojure API that makes it easy to start, stop and control Figwheel from Clojure."  Is the point that sidecar is that api?  If so, I suggest adding something like: ", called sidecar, " after "API".  Again, thanks for figwheel!
