### ISSUE TITLE
cannot find fighwheel.connect if project contains hyphen (after upgrade to 0.5.5)

### ISSUE THREAD

**Issue by odrevet** [bhauman/lein-figwheel#468]
This is probably due to 'the generated connect code has a unique namespace depending on the build id' (c.f. CHANGES.md) and the fact that hyphens are corece to undercores in file names.

**Comment by bhauman** [comment]
Is figwheel not starting for you? 

And you think it's a coercion issue??

**Comment by bhauman** [comment]
I deployed 0.5.6-SNAPSHOT with this fix
