### ISSUE TITLE
CSS watcher doesn't like it if the :css-dirs path doesn't exist at startup

### ISSUE THREAD

**Issue by cemerick** [bhauman/lein-figwheel#469]
This can happen easily if one is e.g. using sass, but hasn't started the sass watcher, and just did a `lein clean` before starting figwheel.

Thanks for the solid piece of kit, @bhauman. :-)

**Comment by bhauman** [comment]
There is no straightforward way around this, besides throwing a more descriptive Error, which sure wouldn't hurt.

**Comment by bhauman** [comment]
Wait, I ingested some sugar, there is a straightforward solution.

**Comment by cemerick** [comment]
I figured, the java watcher service can notify on file/directory creation, etc. Never used it through hawk though, so I didn't have any concrete suggestions.

**Comment by bhauman** [comment]
yeah that would require watching a level lower, and that gets crazy...

But just making the directories before launching the service makes sense...

**Comment by bhauman** [comment]
Conj???
