### ISSUE TITLE
CSS isn't reloading properly

### ISSUE THREAD

**Issue by iand675** [bhauman/lein-figwheel#47]
I've got the following in the project.clj file that I'm trying to use figwheel with.

```
:figwheel {:css-dirs ["resources/assets/css"]}
```

This is what I've got in the cljs app:

```
(fw/watch-and-reload
  :websocket-url "ws://localhost:3449/figwheel-ws"
  :jsload-callback (fn [] (do
                            (update-ui!))))
```

Whenever CSS files are changed, it tries to reload the CSS with the following URL:

```
<link rel="stylesheet" media="" href="//localhost:3449resources/assets/css/app.css?rel=1414087417074">
```

The issue appears to be that there's not a / after 3449 in the URL.

**Comment by dsvensson** [comment]
Reading about CORS here, and here:

https://github.com/bhauman/lein-figwheel/blob/ce39ac0bcb046a9a5626cdb3f5565939a13e2c37/sidecar/src/figwheel_sidecar/components/figwheel_server.clj#L115

...I get the impression that figwheel should do CORS out of the box when I type "lein figwheel", I still get "XMLHttpRequest cannot load...No 'Access-Control-Allow-Origin' header is ..." when trying to do CORS. What am I missing?
