### ISSUE TITLE
Figwheel cleaning clean-targets while rebuilding.

### ISSUE THREAD

**Issue by BartAdv** [bhauman/lein-figwheel#470]
When starting figwheel after switching a branch, it performs `Cleaning, because dependencies changed`. This seems to use leiningen's clean, which means it also cleans other artifacts built by potential other plugins (in my case less compiler). 

It means that in such case I need to manually rebuild those. Is it possible to specify what should be cleaned in such situations?

**Comment by bhauman** [comment]
This is a good question.  I think it may be best to allow you to turn the auto cleaning feature off if you are finding that you're dependencies are in flux and its destroying assets.
