### ISSUE TITLE
figwheel.connect.dev.js not emitted on nodejs for fw >= 0.5.5

### ISSUE THREAD

**Issue by pkpkpk** [bhauman/lein-figwheel#474]
seeing  `goog.require could not find: figwheel.connect.dev` , no target/figwheel/connect*.js file present. The same build config works with 0.5.4-7

**Comment by bhauman** [comment]
Update: This is indeed a problem and I'm looking at this right now.

**Comment by bhauman** [comment]
I have tracked this to a bug in the CLJS compiler that doesn't output inline code for node js targets under certain circumstances.  This is unfortunate as I will need to revert to outputting source files for connect scripts for the node js targets.

**Comment by bhauman** [comment]
Here is the JIRA issue:
http://dev.clojure.org/jira/browse/CLJS-1806

**Comment by pkpkpk** [comment]
Ok thankyou

**Comment by ykomatsu** [comment]
This patch seems to fix this issue but I do not know why.

ykomatsu/clojurescript@fc986467e66e6a628dc8f0e8a2ef2b30f715fd23

**Comment by pkpkpk** [comment]
@ykomatsu Did you want to submit a patch to JIRA?  I'd like to try to get this fixed this week
