### ISSUE TITLE
Fix or document inconsistency between `lein cljsbuild` and `lein figwheel`

### ISSUE THREAD

**Issue by ncalexan** [bhauman/lein-figwheel#475]
I got very confused yesterday about what I see as an inconsistency, but it might be that I don't really understand what's happening.  What I observe is a `goog.require("figwheel.connect");` line at the end of my `:output-to` file when it is built using `lein figwheel BUILDID`, but _not_ when it is built using `lein cljsbuild once BUILDID`.  Is that expected?  If it is, could we document it?  It surprised me, and I spent an hour rolling back changes until I figured out that `lein cljsbuild` wasn't the issue.

I am using
```
  :plugins
    [[lein-figwheel "0.5.4-7"]
      [lein-cljsbuild "1.1.3" :exclusions [[org.clojure/clojure]]]]
```

Thanks!

**Comment by pkpkpk** [comment]
When you `$lein figwheel` , fw wraps your app with its own [client  code ](https://github.com/bhauman/lein-figwheel/tree/master/support) so it can manage reloading & the [build process ](https://github.com/bhauman/lein-figwheel/tree/master/sidecar).  Building with cljsbuild is just building your app. Note that the `lein figwheel` is invoking a *leiningen plugin*, which is different than having figwheel components as dependencies in your project.

**Comment by ncalexan** [comment]
> When you $lein figwheel , fw wraps your app with its own client code so it can manage reloading & the build process . Building with cljsbuild is just building your app. Note that the lein figwheel is invoking a leiningen plugin, which is different than having figwheel components as dependencies in your project.

OK, I understand this (now!) but I found it confusing that a cljsbuild configured with a `:figwheel` section didn't do the wrapping, while the figwheel plugin did.  Is that just my error?  Is it worth calling this out in the documentation?  (Is it already called out?)

**Comment by pkpkpk** [comment]
The figwheel key is just where figwheel looks to find your per-project figwheel configurations while it manages its own build process. lein-cljsbuild does not care to look at this info. figwheel was originally build on top of lein-cljsbuild, though you can now use it in other ways.

**Comment by bhauman** [comment]
Closing this ... This is explained at the beginning of the quick start.
