### ISSUE TITLE
figwheel-sidecar needs piggieback in :dependencies?

### ISSUE THREAD

**Issue by the-kenny** [bhauman/lein-figwheel#479]
For some reason our project needed `[com.cemerick/piggieback "0.2.1"]` in its `:dependencies` in order to use `figwheel-sidecar.system/cljs-repl`.

Without it, we get the following exception when trying to evaluate anything (including `:cljs/quit`) in the cljs-repl:

```
cljs.user> 42
----  Exception    ----



----  Exception Stack Trace  ----

java.lang.NullPointerException: null
 at clojure.core$deref_future.invokeStatic (core.clj:2290)
    clojure.core$deref.invokeStatic (core.clj:2310)
    clojure.core$deref.invoke (core.clj:2296)
    cljs.analyzer$get_namespace.invokeStatic (analyzer.cljc:502)
    cljs.analyzer$get_namespace.invoke (analyzer.cljc:498)
    cljs.analyzer$get_namespace.invokeStatic (analyzer.cljc:500)
    cljs.analyzer$get_namespace.invoke (analyzer.cljc:498)
    figwheel_sidecar.repl$eval_cljs.invokeStatic (repl.clj:223)
    figwheel_sidecar.repl$eval_cljs.invoke (repl.clj:218)
    figwheel_sidecar.repl$catch_warnings_and_exceptions_eval_cljs.invokeStatic (repl.clj:248)
    figwheel_sidecar.repl$catch_warnings_and_exceptions_eval_cljs.invoke (repl.clj:240)
    figwheel_sidecar.repl$catch_warnings_and_exceptions_eval_cljs.invokeStatic (repl.clj:242)
    figwheel_sidecar.repl$catch_warnings_and_exceptions_eval_cljs.invoke (repl.clj:240)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.Var.invoke (Var.java:388)
    cljs.user$eval86690.invokeStatic (form-init4259833278772319339.clj:1)
    cljs.user$eval86690.invoke (form-init4259833278772319339.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6977)
    clojure.lang.Compiler.eval (Compiler.java:6940)
    clojure.core$eval.invokeStatic (core.clj:3187)
    clojure.core$eval.invoke (core.clj:3183)
    clojure.main$repl$read_eval_print__9952$fn__9955.invoke (main.clj:242)
    clojure.main$repl$read_eval_print__9952.invoke (main.clj:242)
    clojure.main$repl$fn__9961.invoke (main.clj:260)
    clojure.main$repl.invokeStatic (main.clj:260)
    clojure.main$repl.doInvoke (main.clj:176)
    clojure.lang.RestFn.invoke (RestFn.java:1523)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__37687.invoke (interruptible_eval.clj:87)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:657)
    clojure.core$with_bindings_STAR_.invokeStatic (core.clj:1963)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1963)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic (interruptible_eval.clj:85)
    clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:55)
    clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__37732$fn__37735.invoke (interruptible_eval.clj:222)
    clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__37727.invoke (interruptible_eval.clj:190)
    clojure.lang.AFn.run (AFn.java:22)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)

nil
```

**Comment by bhauman** [comment]
Yes you need piggieback in order to use the Figwheel REPL from nREPL.  But it isn't a dependency because you can use a figwheel without nREPL.

**Comment by bhauman** [comment]
This is explained 
https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

**Comment by the-kenny** [comment]
I understand that this figwheel is usable without piggieback, but wouldn't it be nice to have a better error message telling the user that he likely want to add piggieback to his project?

**Comment by bhauman** [comment]
Well this is interesting:

https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L158

According to this function the REPL should fail to launch and print a message.

And this function is used to test if the repl is launched in an nREPL env:

https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/repl.clj#L158

Maybe that function is failing to detect the presence of nREPL.
You are using the latest figwheel?

**Comment by the-kenny** [comment]
I think so - I'm using 0.5.8 here.

**Comment by bhauman** [comment]
Well I'm going to need more specifics of your system to figure this out.

**Comment by darwin** [comment]
I can see one possible issue. There might be `cemerick.piggieback` on class-path but it is not configured to be present in nREPL middleware.

Just my $0.02

**Comment by bhauman** [comment]
Ah, that makes sense ...  so ideally I would really need to check if it's in the middleware stack.

**Comment by darwin** [comment]
Right, but I don't think there is an easy way to do that. Maybe sending some specially crafted message "eval" and observing side-effects which would be caused only if piggieback was present.

**Comment by bhauman** [comment]
Fun

**Comment by darwin** [comment]
an unrelated note: I have unintentionally became an "nREPL expert". Feel free to ask. Got my hands dirty lately when working on a massive rewrite of Dirac middleware (which started as a piggieback fork):
https://github.com/binaryage/dirac/commits/master/src/nrepl/dirac/nrepl

This will allow "the holy grail setup" for me. Having dirac using figwheel's compiler environment (which is being auto-reloaded in the background). Of course, if figwheel's sidecar is present in the nREPL server. Something like this:

https://dl.dropboxusercontent.com/u/559047/dirc-with-figwheel-sneak-peek.png

**Comment by bhauman** [comment]
Cool I will certainly check it out.

On Thu, Oct 6, 2016 at 1:02 PM, Antonin Hildebrand <notifications@github.com

**Comment by darwin** [comment]
I was just searching through NREPL JIRA tickets, looking why bencode is pretty much crippled, and see what I found:
http://dev.clojure.org/jira/browse/NREPL-77

To adopt proposed solution in the comments, you would have to fork piggieback and introduce a new nREPL operation for identifying piggieback presence. That is what I have in dirac middleware as well: https://github.com/binaryage/dirac/blob/edfff70c3551f090c63a307dc62d4b5de6a5d59f/src/nrepl/dirac/nrepl.clj#L22

**Comment by bhauman** [comment]
Unfortunately this is far far to complex for the marginal convenience. I have added a much more detailed error message.
