### ISSUE TITLE
Make stamp-and-clean accept absolute files

### ISSUE THREAD

**Issue by arichiardi** [bhauman/lein-figwheel#482]
Hello Bruce!

I am trying to make `boot-figwheel` work in an idiomatic way and therefore compile stuff in boot's `~/.boot` folder, by configuring `boot-figwheel` accordingly.

At the moment I am getting an error in `stamp-and-clean`:

```
java.lang.IllegalArgumentException: /home/kapitan/.boot/cache/tmp/home/kapitan/git/booma/f8n/-tkisbw/division.out is not a relative path
                                   clojure.java.io/as-relative-path/invokeStatic               io.clj:  414
                                               clojure.java.io/file/invokeStatic               io.clj:  426
                                               clojure.java.io/file/invokeStatic               io.clj:  418
                                                            clojure.java.io/file               io.clj:  418
                                                                             ...                           
       figwheel-sidecar.build-middleware.stamp-and-clean/stamp-file/invokeStatic  stamp_and_clean.clj:   21
                    figwheel-sidecar.build-middleware.stamp-and-clean/stamp-file  stamp_and_clean.clj:   20
figwheel-sidecar.build-middleware.stamp-and-clean/create-deps-stamp/invokeStatic  stamp_and_clean.clj:   46
             figwheel-sidecar.build-middleware.stamp-and-clean/create-deps-stamp  stamp_and_clean.clj:   45
                       figwheel-sidecar.build-middleware.stamp-and-clean/hook/fn  stamp_and_clean.clj:   55
```

The problem is [here](https://github.com/bhauman/lein-figwheel/blob/e47da1658a716f83888e5a5164ee88e59b2d8c1e/sidecar/src/figwheel_sidecar/build_middleware/stamp_and_clean.clj#L20)  and it is clear to me, I need to be able to make it accept the absolute path I am passing as `output-dir`.

I am opening this issue and relative PR to ask you if you think I should avoid that, if there is anything I am not thinking about and therefore I don't want to make that change :smile:.

**Comment by bhauman** [comment]
What if we make cleaning optional? Boot doesn't need cleaning right? This is also a solution for #470

**Comment by arichiardi** [comment]
Ah, yes maybe it is the best option, it is just that I need to touch many more places for that while the patch for the absolute thing is a one liner, I can look into that definitely.

**Comment by bhauman** [comment]
OK I get it now, are you sending a patch?

**Comment by arichiardi** [comment]
Yep, soon-ish, trying now.

**Comment by bhauman** [comment]
merged
