### ISSUE TITLE
Warn when CLJ compilation fails in a CLJC file

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#484]
When working in a cljc file, if you type (say) `js/window` then you will get a compilation error in the logs:

```
java.lang.RuntimeException: No such namespace: js, compiling:(my/cool/file.cljc:1:205)
```

This prevents the compilation from proceeding any further, or that code being reloaded, but Figwheel doesn't show this error in the browser, so it is possible that you could miss it (as I have in the past).

It would be great if it was possible for these errors to be caught and sent to the browser like other compilation errors?

**Comment by bhauman** [comment]
Hmmmm, interesting so you are wanting the hud to display clj errors when cljc files are dynamically loaded into the Clojure runtime by figwheel.  

When cljc files are interpreted/analyzed by the CLJS compiler their errors get propagated to the HUD.

This seems like a good idea.  I just wanted to add some detail and verify what you were describing.

**Comment by bhauman** [comment]
This was a hard one but its a pretty nice feature, thanks for the suggestion.

**Comment by danielcompton** [comment]
Thanks!
