### ISSUE TITLE
Creating new folders does not make inotify watch the folder

### ISSUE THREAD

**Issue by vans163** [bhauman/lein-figwheel#496]
If you create a new folder, you need to restart the REPL fully in order for inotify to track the new folder.

Inotify returns a bitmask if the created file was a folder, if this returned mask is checked, newly created folders can be added to inotify watch as they are created.

**Comment by bhauman** [comment]
Figwheel relies on Hawk 
See this issue:
https://github.com/wkf/hawk/issues/16

**Comment by bhauman** [comment]
@vans163 can you override hawk with this new version and see if this fixes the behavior for you, if it's working for you I'll update it and test it some more

**Comment by vans163** [comment]
@bhauman I am pretty new to clojurescript let me see if i can figure out how to do that.

**Comment by bhauman** [comment]
@vans163 actually if you are using the plugin that could be challenging.  Let me just fix it and deploy a snapshot.  I'll let you know.

**Comment by bhauman** [comment]
@vans163 Alright try out the 0.5.9-SNAPSHOT

**Comment by vans163** [comment]
@bhauman 

So its working for the most part.  The broken test case was when I mv a folder, it did not watch it.  But creating subfolders in subfolders works now.
