### ISSUE TITLE
uWebSockets as an alternative for ws

### ISSUE THREAD

**Issue by jiyinyiyong** [bhauman/lein-figwheel#501]
I noticed now we have a faster WebSocket implementation, it Figwheel willing to try it? https://github.com/uWebSockets/uWebSockets

Almost a drop-in-replacement, except for package name, BTW.

**Comment by bhauman** [comment]
Not really worth the change yet. The speed up is negligible compared to the time it takes to compile something.

Thanks for pointing it out.
