### ISSUE TITLE
Option to disable the dev server

### ISSUE THREAD

**Issue by mhuebert** [bhauman/lein-figwheel#503]
It would be nice to have an option to disable the development server. Figwheel is awesome, and I often use it to work on multiple projects simultaneously. But I usually run my own dev servers, to support things like pushstate routes.

Prior to the resolution of issue #407, conflicting server-port errors were ignored (with a warning), but now one must add a unique server-port even to projects that do not use the server, otherwise Figwheel will not compile if there is a conflict.

An alternative would be to increment the server-port until an open port is found; this is the behavior of the dev server provided by the Firebase cli tools.

**Comment by bhauman** [comment]
The dev-server isn't optional. Its required for communicating with the client.  The websocket that the repl and reload messages use is on that port.

**Comment by mhuebert** [comment]
Ah, I see. In that case - I've just pushed a minimal ring handler to use with figwheel that falls back to `index.html`, to play well with pushstate routes: https://github.com/mhuebert/figwheel-pushstate-server
