### ISSUE TITLE
Append timestamps to sourcemap paths

### ISSUE THREAD

**Issue by glenjamin** [bhauman/lein-figwheel#51]
I've been running into this a bit, as I edit my code, new JS gets loaded, but they all point to the same source map path, which gets cached early and then ends up pointing to the wrong locations.

Is this something that could be in scope of figwheel?

**Comment by bhauman** [comment]
One thing to note is that recent versions of the compiler enable these timestamps with :source-map-timestamp true build option

**Comment by danielcompton** [comment]
Just to clarify the above: to force browsers to update their source maps when Figwheel reloads code, add `:source-map-timestamp true` to your `:compiler` options in your cljsbuild config.
