### ISSUE TITLE
Custom http-kit configuration

### ISSUE THREAD

**Issue by frerom** [bhauman/lein-figwheel#513]
It should be possible to specify custom http-kit options. For example, if I want to post larger files than 8M to the server I need to set the :max-body http-kit option. This isn't possible right now.

I suggest a :http-kit with a map in the config that is simply merged with the http-kit options.

**Comment by bhauman** [comment]
So my standard answer here is that you can/should run your own http-kit server to serve your application.  You will still run `lein fighweel` to build/watch and serve cljs changes.

**Comment by frerom** [comment]
Sounds like the right approach, thanks!
