### ISSUE TITLE
Consider relaxing :closure-defines spec

### ISSUE THREAD

**Issue by christianromney** [bhauman/lein-figwheel#519]
I use `:closure-defines` to define some variables for my app. In some contexts, a blank string is a perfectly legitimate application value to use for some of these variables. However, upon starting Figwheel an exception is thrown from an internal spec saying that:

```
It should satisfy one of: Number | NonBlankString | boolean?
```

Would you consider changing the spec to use`string?` rather than `NonBlankString` for this value? 

Thanks for your work on Figwheel.

**Comment by bhauman** [comment]
Yes that absolutely makes sense.  The spec is so large that things are still shaking out of it.

**Comment by christianromney** [comment]
Completely understandable. Would you like me to take a stab at a pull request.
