### ISSUE TITLE
Ring handler not working

### ISSUE THREAD

**Issue by wnederhof** [bhauman/lein-figwheel#523]
For some reason, when I set the `:figwheel` / `:ring-handler` in Figwheel `0.5.2`, my custom HTTP handler is picked up by Figwheel correctly. However, when I use version `0.5.4-4` or `0.5.9`, the dependency of Figwheel to version 0.5.4-4 or 0.5-9, the `:ring-handler` seems to be ignored by Figwheel.

**Comment by bhauman** [comment]
I'm sure there is a simple reason for this.  

Can you send me your config and your handler?

This is the current ring stack:
https://github.com/bhauman/lein-figwheel/blob/master/sidecar/src/figwheel_sidecar/components/figwheel_server.clj#L208
