### ISSUE TITLE
Reload ordering with Nodejs + CLJS >= 1.9.473

### ISSUE THREAD

**Issue by pkpkpk** [bhauman/lein-figwheel#525]
The new CLJS node changes remove user namespaces from [js/goog.dependencies_.requires ](https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client/file_reloading.cljs#L109). This means that [figwheel.client.file-reloading/get-all-dependents](https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/client/file_reloading.cljs#L150) will return reload files in the wrong ordering, because they have been ignored by the topo-sort.

Simplest case, 2 files:
```clojure
(ns ^:figwheel-always app.core
  (:require [app.child]))

(println "core loaded")
```
```clojure
(ns app.child)

(println "child loaded")
```
If you save app.child, as of CLJS 1.9.473 the ~~child~~ core will reload first, then child

**Comment by bhauman** [comment]
Thanks for the report :)

**Comment by wildermuthn** [comment]
It looks to me like the only file reloaded is the file you change — none of its dependent namespaced reload either. Basically broken. Would love to help however I can.

**Comment by bhauman** [comment]
Just want to provide an update here:

The issue has been found and reported:
https://dev.clojure.org/jira/browse/CLJS-2151

And a fix should be in place soon.
