### ISSUE TITLE
Missing required key :entries at path ... :modules :cljs-base

### ISSUE THREAD

**Issue by jtkDvlp** [bhauman/lein-figwheel#527]
Hi guys

I got the following error on figwheel startup:
```edn
ExceptionInfo ------ Figwheel Configuration Error ------

Missing required key :entries at path (:cljsbuild :builds 0 :compiler :modules :cljs-base)

  {:cljsbuild
   {:builds
    [{:compiler
      {:modules
       {:cljs-base
        {:output-to "resources/public/js/compiled/base.js"
         :entries ...
         ^---- The required key :entries is missing
         }}}}]}}
```

Further more I got the following warning:

> Spec Warning:  missing an :output-to option - you probably will want this ...

What I'm doing wrong or aren't modules supported?

**Comment by bhauman** [comment]
Your going to want to direct this question to the Clojurians slack. 

Sign up:
http://clojurians.net
Sign in:
http://clojurians.slack.com

Channels of interest to this topic:
#clojurescript

**Comment by jtkDvlp** [comment]
Thx. I'm going to do so.
