### ISSUE TITLE
Running in a Cursive REPL does not load dependencies

### ISSUE THREAD

**Issue by feifanzhou** [bhauman/lein-figwheel#528]
Following the [instructions here](https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL), Lein dependencies don't seem to be picked up — I get "No such namespace" errors in the build, and adding garbage dependencies do not trigger a "Could not find artifact" error at startup. However, using the `lein-figwheel` plugin and running as `rlwrap lein figwheel` behaves as expected ("Could not find" garbage artifacts, and the build completes successfully with (real) additional dependencies). 

I'm sure this is user error, but I'm not familiar enough with the tooling stack to where the discrepancy is coming from …

Screenshot: Cursive REPL in background. "No such namespace" after build. Same project using `rlwrap lein figwheel` in Terminal builds fine. 
<img width="608" alt="screen shot 2017-02-18 at 19 02 12" src="https://cloud.githubusercontent.com/assets/3407996/23098841/6f99c590-f60d-11e6-9fac-c9bb9ed3a8db.png">

**Comment by bhauman** [comment]
Your going to want to direct this question to the Clojurians slack. 

Sign up:
http://clojurians.net
Sign in:
http://clojurians.slack.com

Channels of interest to this topic:
#clojurescript #cursive

**Comment by feifanzhou** [comment]
Ultimately this was my bad for not reading the [Cursive docs](https://cursive-ide.com/userguide/leiningen.html) — I needed to manually refresh Lein deps after updating `project.clj`.
