### ISSUE TITLE
warnings key ignored

### ISSUE THREAD

**Issue by joerupen** [bhauman/lein-figwheel#529]
Is it possible to control CLJS compiler settings? When I pass the :warnings key to the cljs compiler configuration, it has no effect, e.g.

````
 :compiler    {:main                 foo.core
                    :output-to            "resources/public/js/compiled/app.js"
                    :output-dir           "resources/public/js/compiled/out"
                    :asset-path           "js/compiled/out"
                    :warnings {:redefs false}
                    :source-map-timestamp true}}
````

Redeclaring a function in a namespace brings up a compiler warning which I'd like to suppress.

**Comment by bhauman** [comment]
I have just checked and the `:redef` warning option is making it through to the CLJS compiler.

Next steps for you: 
Try this without figwheel 
https://github.com/clojure/clojurescript/wiki/Quick-Start

And ask on the #clojurescript slack channel as this is behavior found the the ClojureScript compiler.

**Comment by kanaka** [comment]
For future travelers using shadow-cljs, here is how I was able to squelch redef warnings in `shadow-cljs.edn` (note that it's `:redef` and under `:compiler-options`):
```clojure
 :builds {:foo {:compiler-options {:warnings {:redef false}}}}
```
