### ISSUE TITLE
node.js development with Figwheel for version 0.5.9

### ISSUE THREAD

**Issue by jiangts** [bhauman/lein-figwheel#534]
I'm going through the tutorial for figwheel on node.js [here](https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel) and am trying fw version 0.5.9.

everything works up until the "Node.js module development with figwheel" section, where on the new version of fw I get that cannot find property exports of undefined -- aka `js/module` can't be found.

Not sure what the changes were between figwheel 0.3.9 and 0.5.x that made this break, but it'd be awesome if this could be patched for fw 0.5.x.

**Comment by pkpkpk** [comment]
you can use "0.5.10-SNAPSHOT" with cljs 1.9.293. The recent cljs node module changes are not supported in figwheel at this time.

**Comment by jiangts** [comment]
got it, thanks!
