### ISSUE TITLE
Evaluate a cljs string within the browser's console

### ISSUE THREAD

**Issue by vemv** [bhauman/lein-figwheel#538]
Hi!

This might be bit of an odd request but it also seems easy to answer.

What JS invocation should I perform within the browser console so I get a string evaluated as clojurescript?

I'm looking for something like `figwheel.client.foo.bar.call("(+ 3 2)")` that gets me `5` in return.

I know that clojurescript has some proper self-hosting alternatives, but given that I already have FW set up, this seems handy occasionally.

Cheers - Victor

**Comment by bhauman** [comment]
This doesn't exist. :)

**Comment by vemv** [comment]
Alright! It surprises me a bit. I was hoping there would be some hack-ish way to make a roundtrip (console -> figwheel process -> console) that was initiated from the console itself.
