### ISSUE TITLE
Checkouts deps stopped working

### ISSUE THREAD

**Issue by vemv** [bhauman/lein-figwheel#539]
I have a "checkout deps" setup, which has worked correctly since day 1 for weeks.

I had it set up by setting `:source-paths` to `["src" "checkouts/foo/src" "checkouts/bar/src" "checkouts/baz/src"]`, and actually having that tree structure via symlinks.

But now it stopped working for no apparent reason... I have made no changes, have tried `lein clean` / `git clean -fd`, etc

This is the error message:

![image](https://cloud.githubusercontent.com/assets/1162994/23959647/000900c2-09a6-11e7-8c75-b760286fbf89.png)

I have seen this error described in https://github.com/bhauman/lein-figwheel/issues before (one must use different output-dir value per builds) but this case seems to be different. It has to do with checkouts rather than with multiple builds.

Any idea of what is causing the issue? The most suprising aspect is that I'm getting the error all of a sudden, without changes from my side.

Cheers - Victor

**Comment by vemv** [comment]
Two things:

* Error coordinates say `[:cljsbuild :builds 1 :compiler :output-dir]`. Notice the `1`. I assume it means that it supposedly refers to the _second_ item of the :builds vector. But I left just one item (position 0), so how come the problem is reported at position 1?

* It would help to show project.clj's full path instead of just "project.clj". That way I'd now for sure which project to lool at

**Comment by bhauman** [comment]
I would need to see your configuration. To shed any light on this.

**Comment by vemv** [comment]
Can't do that (not my copyright). In any case I had the feeling that checkout deps were working by mere chance as they are not a documented feature

Will resort to something else

**Comment by bhauman** [comment]
I would first trust that the error is pointing out something real and that
you have two builds in your config with the same output directory.
