### ISSUE TITLE
Instructions on figwheel and inf-clojure don't work

### ISSUE THREAD

**Issue by yatesco** [bhauman/lein-figwheel#543]
Hi, I followed https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-with-Emacs-Inferior-Clojure-Interaction-Mode but when I run `M-x figwheel-repl` I get `Symbol's function definition is void: run-clojure`.

My `init.el` is:
``` lisp
(use-package clojure-mode)
(use-package inf-clojure)

(defun figwheel-repl ()
  (interactive)
  (run-clojure "lein figwheel"))

(add-hook 'clojure-mode-hook #'inf-clojure-minor-mode)
```

I can load `inf-clojure` fine. Have I missed a precondition?

(and thanks, `figwheel` is wonderful!).

**Comment by bhauman** [comment]
For some reason that alias was removed. It looks like you can use `inf-clojure` instead of `run-clojure`. Can you check to see if that works?

**Comment by yatesco** [comment]
Will do once I return from my sunny hols ;-).



On Sun, 9 Apr 2017, at 07:15 PM, Bruce Hauman wrote:

> For some reason that alias was removed. It looks like you can use inf-
> clojure instead of run-clojure. Can you check to see if that works?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/bhauman/lein-figwheel/issues/543#issuecomment-292802404

**Comment by yatesco** [comment]
Yep, works for me. I will update the documentation and issue a PR.

**Comment by bhauman** [comment]
Thanks!
