### ISSUE TITLE
Accept quoted maps

### ISSUE THREAD

**Issue by vemv** [bhauman/lein-figwheel#544]
Hi!

I have an entry like this in my project.clj:

`:compiler '{:closure-defines {'foo.common.env/env "dev"}}`

The quoting is needed so `lein doo` doesn't fail with a Java ClassNotFound exception (it tries to load foo.common.env as a Clojure namespace).

So, lein doo passes, but lein figwheel doesn't:

```
The key :closure-defines at (:cljsbuild :builds 0 :compiler) has a non-conforming value: 
  '{foo.common.env/env "dev"}
It should be a Map
```

According to clojure, (= {} '{}), so complaining about quoted maps feels pedantic to me?

If I remove the quoting, figwheel will pass but doo will fail.

Looks like https://github.com/bhauman/strictly-specking could be modified so quoted literals are accepted (maybe in some cases only)?

Cheers - Victor

**Comment by bhauman** [comment]
For the most part this is a bug in `lein-doo`

`lein-doo` is breaking a leiningen convention where you need to quote project derived data to allow for raw symbols.

`lein-cljsbuild` follows this convention here:
https://github.com/emezeske/lein-cljsbuild/blob/master/plugin/src/leiningen/cljsbuild.clj#L110

`lein-figwheel` follows this convention here:
https://github.com/bhauman/lein-figwheel/blob/master/plugin/src/leiningen/figwheel.clj#L151

`lein-doo` is not quoting the `compiler` config here:
https://github.com/bensu/doo/blob/master/plugin/src/leiningen/doo.clj#L215
and this is why you have to quote the symbols for lein-doo

@bensu ^^

**Comment by vemv** [comment]
Nice, thanks for the precise anaylisis!

Yes, I realised most part of the fault lies in doo, and opened https://github.com/bensu/doo/issues/133 after opening this issue.

Anyways finally I was able to come up with a workaround (conditional quoting depending on env var) so I don't depend on quick resolution.
