### ISSUE TITLE
Programmatic "connect" function for client

### ISSUE THREAD

**Issue by johnmn3** [bhauman/lein-figwheel#545]
Is there a function anywhere in figwheel I can require from client code in order to control when and where the client connects to the server?

**Comment by bhauman** [comment]
While figwheel is running look in `target/figwheel_temp/dev/figwheel/connect/dev.clj` where `dev` is your build `:id`.

This is injected into your build when the `:figwheel` key in your cljsbuild has a truthy value.

If you remove the `:figwheel` key you can connect manually as demonstrated in the script.

Something like:
```
(ns figwheel.connect.dev
  (:require [fighweel.client]))

(figwheel.client/start {:build-id "dev" :websocket-url "ws://localhost:3449/figwheel-ws"})
```

**Comment by johnmn3** [comment]
Thank you! I now have the goodness of figwheel while connected to a Webworker :) Weasel worked, but it was not nearly as capable and pretty as figwheel. I'm running multiple repls from multiple workers in the same browser at the same time though, so as to test message passing between them. Is there a way to run multiple figwheel repls with only one doing the watch/compilation? Thanks Bruce!

**Comment by bhauman** [comment]
you just do `lein figwheel build-id1 build-id2 build-id3`

**Comment by johnmn3** [comment]
I mean, I need a repl on 3449, 3500, 3501, etc. So that each worker instance has a unique repl to connect to.

**Comment by johnmn3** [comment]
In any case, this specific issue is resolved.

**Comment by johnmn3** [comment]
So, what I am doing right now is launching the first repl. Updating my project.clj with a new :server-port. Launching figwheel again in another shell in the same directory. My UI thread is connecting to 3449 and the first worker is connecting to 3450. Perhaps being able to provide :server-port at the command line would alleviate having to change the project config while the first figwheel is still running?

At the moment, I cannot tell that the two figwheel instances are conflicting with each other. When I save a source file, the page immediately updates and both repls continue running smoothly. Seems to be working fine.

**Comment by johnmn3** [comment]
Scratch that. Only one repl at a time appears to be able to call user namespaces without spurious warnings. And derefing a dereferable object using '@' causes a java.lang.NullPointerExeption, failing to send the form to the browser. It isn't a matter of whether the repl is connected to a Webworker or not. It depends on the sequence in which the repls were started. If anyone smells a root cause, let me know - I'll keep exploring.

**Comment by bhauman** [comment]
You can connect all of your workers to the same figwheel repl endpoint
(3449 for instance). But then you are required to switch between the
different repls. by quiting the repl with cljs/quit and choosing which repl
to switch to.

This set up works pretty well. You can run this all with one server I
promise :)

**Comment by Nolan330** [comment]
Apologies to bring this back up, but I believe I'm trying to solve a similar problem, and can't quite gleam what I need from this exchange.

I have N (say 2) client connections to the same build ('dev'). Is there a way to have each connection have it's own state and switch between them within the repl? I apologies if I missed switching between connections in the docs. I essentially want to be able to "act" as 2 different people, and issue commands/mutate state independently on the same build.

If this is unsupported and something you see as possible, let me know where I can start!

**Comment by johnmn3** [comment]
Nolan,

You'll want to launch figwheel, then change the figwheel server port in the
project.clj config to another port. Then start another figwheel in another
shell.

If you're using multiple workers, state between them can get hairy when
they're all using the same build id. So I'll usually give each one a
different build id, but then have each worker pull from the same dev build
folder.
