### ISSUE TITLE
serving stale js files even after clean and rebuild

### ISSUE THREAD

**Issue by Sophia-Gold** [bhauman/lein-figwheel#546]
Figwheel seems to be serving old builds even after cleaning and even manually deleting old resources. I'm using Leiningen 2.6.1 on NixOS, but heard the same issue from someone using 2.7.1 on OS X.

This issue is reproducible by cloning [this project](https://github.com/Sophia-Gold/Lazy-Henderson). It's a library that draws to the canvas element with tests at the bottom. Commenting the current one out and uncommenting others still displays the same image after a manual reload. 

Furthermore, Figwheel looks for the same source file in _all_ of my projects. In other words, if I launch it from a different project it will fail to load as it cannot find the src file from the project linked above.

**Comment by danielcompton** [comment]
I've observed stale files being loaded as well. I'm not sure if they're being cached by Chrome though, because doing a clean Chrome reload seems to fix it in every case I remember. Do you have any info that could help determine whether it's Chrome or Figwheel that's serving the cached file? It very may well be Figwheel, but I can't imagine a mechanism that would cause it to cache files across different projects.

**Comment by Sophia-Gold** [comment]
I'm fairly certain it's not Chrome because this is the first time I've launched any of these projects on this machine. Someone else reporting this issue suggested that, but said it didn't resolve it for him either.

**Comment by Sophia-Gold** [comment]
So, I just fired up Figwheel to see if I could diagnose this a bit more and...lo and behold...it's now working as expected with no changes made on my part. I'm not sure what to say about this. Given the number of people who have reported it as an occasional issue with no standard solution, I'd prefer to keep this open in case anyone is able to shed light on the underlying cause.

**Comment by pesterhazy** [comment]
@Sophia-Gold I'm seeing a similar issue in Chrome 58, which loads stale files from its disk cache, rather than re-requesting.

I think this PR should fix this particular issue (not sure if the same as yours): https://github.com/bhauman/lein-figwheel/pull/464

**Comment by Sophia-Gold** [comment]
Frequently clearing browser cache has always been just a reality of using Figwheel for me. This issue was not opened to address that, but rather Figwheel itself very rarely serving stale cached files even after a clean and rebuild. I don't follow Figwheel development enough to know whether that bug can be fixed without disabling caching entirely, but I don't see any reason why that would be the case. As it stands, the problem seems to be just that no one has been able to consistently reproduce the bug.
