### ISSUE TITLE
:npm-deps compiler option support

### ISSUE THREAD

**Issue by async-cl** [bhauman/lein-figwheel#552]
As documented here

https://anmonteiro.com/2017/03/requiring-node-js-modules-from-clojurescript-namespaces/

**Comment by ballad89** [comment]
is there a release of figwheel out which supports this feature ?

**Comment by chbrown** [comment]
@ballad89 yep, Bruce just released `[lein-figwheel "0.5.11"]` which adds this compile option; see https://github.com/bhauman/lein-figwheel/blob/master/CHANGES.md#0511-new-cljs-compiler-options

**Comment by esseswann** [comment]
Is there any documentation\examples on how to use `:npm-deps` option in figwheel? I mean overall setup

**Comment by chbrown** [comment]
@esseswann it's not really a figwheel option; the recent change is only in passing it through to the cljs compiler. See:

* https://cljs.github.io/api/compiler-options/npm-deps
* https://anmonteiro.com/2017/03/requiring-node-js-modules-from-clojurescript-namespaces/
* https://clojurescript.org/news/2017-07-12-clojurescript-is-not-an-island-integrating-node-modules

**Comment by LeaveNhA** [comment]
I really can't get figwheel to work on my project since I was add npm module in it.
Is this supported or not ?
