### ISSUE TITLE
add support for headless chrome

### ISSUE THREAD

**Issue by bhurlow** [bhauman/lein-figwheel#555]
now that chrome is supporting a `--headless` mode, figwheel support for this feature could open up some interesting possibilities including:

- running your tests in a real chrome context without opening a new window 
- having REPL access to a real live DOM
- tests?

Though this may not be too much of a gain for local development (how hard is it to open a browser window?), this is something I might use in a CI environment where it's not possible to click and navigate to a browser window and another js context like Node/Nashorn does provide a full picture.

Thoughts?

**Comment by pkpkpk** [comment]
Does  fw need to add anything to support this? driving the chrome process i think is out of scope. fwiw you can get the same effect in electron, but not that this is __*spectacularly unsafe*__

**Comment by bhauman** [comment]
As far as I know nothing needs to be done to support this

**Comment by bhauman** [comment]
Going to close this until it is known that we need to do something specific to support headless chrome.
