### ISSUE TITLE
emoticon prevents paredit mode

### ISSUE THREAD

**Issue by dpsutton** [bhauman/lein-figwheel#568]
This is a rather silly issue, but when i try to turn on paredit-mode in an inf-clojure figwheel repl I am prevented by the following otherwise charming output:

    Figwheel: Configuration Valid :)

I think fundamental to paredit is that it can only work if delimiters are balanced and this happy face really makes it sad. Is this properly a paredit mode issue or is this something that could be addressed here?

**Comment by bhauman** [comment]
Well to me its "critical" to fix this while maintaining its charming nature. ;)

Can we think of more balanced ways of expressing this perhaps `:smiley-face:`?

**Comment by glenjamin** [comment]
😀

**Comment by danielcompton** [comment]
Not sure whether paredit mode detects comments, but adding a `;` could work. Alternatively a real smile emoji would be cool.

**Comment by dpsutton** [comment]
it seems to handle the emoticon in a comment just fine. I was thinking a smile emoji but i'm not sure of the terminals and other locations people use this and if that might break them more than a simple unbalanced `)`.

**Comment by bhauman** [comment]
The simplest solution is `;)` An emoji is an interesting solution but having garbage output after a "Configuration valid" message could be confusing, even if part of me enjoys the irony.
