### ISSUE TITLE
Implement suspendable?

### ISSUE THREAD

**Issue by featheredtoast** [bhauman/lein-figwheel#570]
Would you be open to adding the [Suspendable API](https://github.com/weavejester/suspendable) to the figwheel system?

I'm attempting to reload a system (using [reloaded.repl](https://github.com/weavejester/reloaded.repl)) with figwheel's component, using `(figwheel-system)`. On a reset/reload of the system, existing cljs repls are lost, forcing a user to run a `:cljs/quit`, followed by a call to `(cljs-repl)`. Ideally, cljs-repl connections should persist across system reloads.

I'm looking at options to address some issues that are cropping up with integrating component + merging figwheel into the Chestnut lein template, specifically - any pointers or suggestions would be appreciated!

[Having the implementation be something like this would be ideal for me](https://gist.github.com/featheredtoast/eaca83c7be850cb751942a7d526d3021#file-figwheel-suspendable-clj-L22-L27) - under a workflow like reloaded.repl, calling a reset won't break existing cljs connections.

**Comment by featheredtoast** [comment]
I'm closing this out. This probably isn't a figwheel issue -- I didn't realize that everything still works even if I extend a protocol outside of the declared namespace, so I'm going to go down that route instead. Sorry for the noise!

**Comment by featheredtoast** [comment]
After discussing a potential PR with Chestnut for these changes, this kind of functionality would still be ideal for Figwheel directly - so I'm going to re-open the ticket here. Would you be open to extending the figwheel-system?

**Comment by bhauman** [comment]
I would take a PR with the changes you have discussed above.
