### ISSUE TITLE
Add support for new `:checked-arrays` compiler option and `:invalid-array-access` warning

### ISSUE THREAD

**Issue by mfikes** [bhauman/lein-figwheel#574]
The next version of the ClojureScript compiler will include a `:checked-arrays` compiler option that can contain either some `false`-y value, or `:warn` or `:error`, and a new `:invalid-array-access` warnings.

This hasn't been released yet, but just logging this ticket as a reminder. Here is the draft PR that updates the ClojureScript site documentation about the feature: https://github.com/clojure/clojurescript-site/pull/100

**Comment by mfikes** [comment]
News post about the new feature: https://clojurescript.org/news/2017-07-14-checked-array-access

**Comment by bhauman** [comment]
Can you let me know when this get documented on the Compiler Options page? So that I can add docs in?

**Comment by mfikes** [comment]
@bhauman This is now in ClojureScript 1.9.854
https://clojurescript.org/reference/compiler-options#checked-arrays
