### ISSUE TITLE
:checked-arrays allows true

### ISSUE THREAD

**Issue by mfikes** [bhauman/lein-figwheel#579]
The spec used for the new `:checked-arrays` option allows the user to pass `true` which doesn't work. (While developing the feature I did this several times myself, as intuitively seems that it would turn it on, but `true` is not an allowed value). See https://github.com/bhauman/lein-figwheel/commit/a6f4909325c28c62be4d1502a5330baa9b9077d8#commitcomment-23148786

**Comment by bhauman** [comment]
gotcha
