### ISSUE TITLE
Error accessing localStorage when checking autoload?

### ISSUE THREAD

**Issue by jeaye** [bhauman/lein-figwheel#581]
I'm currently getting this sporadically:

![figwheel-error](https://user-images.githubusercontent.com/1057635/28485679-0030fee4-6e30-11e7-8d9f-5dd864a2d99c.png)

It happens typically in one of two cases:

1. Startup
2. Reloading after files changed

When inspecting it, in the debugger, I can see that `localStorage` is non-nil, but it doesn't have a `getItem` function on it. I'm not sure **why** this happens, and what it just started happening, but it's a blocker.

The relevant CLJS, as shown in the image is here: https://github.com/bhauman/lein-figwheel/blob/48eba2f7e481be4079fdfc4b606d3eb52217a891/support/src/figwheel/client/utils.cljs#L132

Looks like this issue might be related to: https://github.com/bhauman/lein-figwheel/issues/313 and perhaps the fix for #313 was incomplete.

**Comment by jeaye** [comment]
What's your release schedule for clojars? I'm currently running on a modified local install of this, with the fix, but would like to get it to my other teammates.

**Comment by bhauman** [comment]
I can push a snapshot out until the next release

**Comment by jeaye** [comment]
Sounds good to me, thank you!

**Comment by bhauman** [comment]
I just deployed it a bit ago 0.5.12-SNAPSHOT

**Comment by jeaye** [comment]
Cheers!
