### ISSUE TITLE
Symbolically linking index.html into resources/public broken on 0.5.11

### ISSUE THREAD

**Issue by dmohs** [bhauman/lein-figwheel#584]
I use a symlink to place my source index.html into the resources/public folder so it gets updated when I change the file:
```bash
ln -s src/static/index.html resources/public/index.html
```
This works in versions 0.5.8 through 0.5.10 (I tested each one). It no longer works on 0.5.11, even if I explicitly request the file (e.g. at `http://localhost:3449/index.html` rather than `http://localhost:3449/`).

**Comment by bhauman** [comment]
Well this must be a result of updating `ring` from 1.5.0 to 1.6.1
We use `ring.util.response/resource-response` to handle this.

**Comment by dmohs** [comment]
@bhauman Beautiful.
