### ISSUE TITLE
Broken with new Closure library

### ISSUE THREAD

**Issue by Deraen** [bhauman/lein-figwheel#594]
Next ClojureScript updates Closure-library version

New version removed deprecated jsloader load function: https://github.com/google/closure-library/commit/988ff900886e959a888485ee56d1540d1bf2f29d

https://github.com/bhauman/lein-figwheel/blob/48eba2f7e481be4079fdfc4b606d3eb52217a891/support/src/figwheel/client/file_reloading.cljs#L208

Instead, one needs to use `goog.html.legacyconversions` to create `safeUrl` and use `safeLoad` function instead.

Same fix at Boot-reload: https://github.com/adzerk-oss/boot-reload/commit/025dfbc1ecb772d0193060430a5ea45c6563ba84

**Comment by bhauman** [comment]
Updated fix here
https://github.com/bhauman/lein-figwheel/commit/9e8e6d4504c807f8a41767075bf86cbab67df6d1

**Comment by TerjeNorderhaug** [comment]
Work-around until the next release restores figwheel's ability to reload compiled files:

    (set! js/goog.net.jsloader.load
        #(goog.net.jsloader.safeLoad
            (goog.html.legacyconversions/trustedResourceUrlFromString %1)
            %2))

**Comment by bhauman** [comment]
This has been released already.
