### ISSUE TITLE
Too many global items with ":optimizations :advanced"

### ISSUE THREAD

**Issue by shrimpy** [bhauman/lein-figwheel#595]
When compile with code with ":optimizations :none",  there are around ~300 global items on "window" object (which is ideal) after loading all js file into browser

However, when compile code with ":optimizations :advanced", there are ~10K global items (functions and objects).

Seems like minification strategy is making everything global. Is there a way to change its behavior?

**Comment by danielcompton** [comment]
This isn't a figwheel specific issue, this is from the ClojureScript compiler (I think?)

**Comment by shrimpy** [comment]
Thanks! Move question to SO https://stackoverflow.com/questions/45830636/too-many-global-variables-functions-with-optimizations-advanced
