### ISSUE TITLE
Some files still being cached (perhaps CLJC related?)

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#597]
From https://groups.google.com/d/msg/clojure/ON12TDD8tOQ/1-ah7ib-AQAJ

> Isn't that change already active in I noticed the change in 0.5.13? I actually tried that release, but it did not make a difference for me. I still need to have the DevTools visible, with "Disable cache" flagged in the Network Panel, to avoid situations where a modification that was correctly picked up by Figwheel, would suddenly get lost again when I perform a hard refresh of the page. (I never fully investigated this issue, because I assumed that it was perhaps linked to the fact that I have to disable the "reload-clj-files" for CLJC-files, to avoid that a single change in a CLJC would cause a full recompile of all CLJS files — which is unmanageable if half your codebase consists of CLJC files...).

**Comment by mtruyens** [comment]
I'm the person who initially made the comment above.

I have now performed a deeper investigation, and noticed that the new "no-cache" flag is only relevant for Figwheel's built-in dev server. As my project uses its own dev server, the comment has become irrelevant. This issue can therefore be closed

Nevertheless, this sparked the idea of adding the no-cache flag to my own dev server, which (so far) seems to resolve the issue. So thanks!

**Comment by bhauman** [comment]
Great!
