### ISSUE TITLE
Looking for a `:build-to-focus` option?

### ISSUE THREAD

**Issue by au-phiware** [bhauman/lein-figwheel#600]
I note this comment:

> choosing which build for the repl to focus on is a bit tricky

[sidecar/src/figwheel_sidecar/system.clj#L525](https://github.com/bhauman/lein-figwheel/blob/bddbcc0fe326ea1e4aafb649a0b95c9113377611/sidecar/src/figwheel_sidecar/system.clj#L525)

May I propose a simple config setting (along side `:builds-to-start`) that directs figwheel to choose a specified build to focus on during startup?

I have tried all sorts of things to influence the first build that is chosen when the figwheel repl starts. I have resorted to using a sorted map in my `project.clj` and renaming my build id to `:!start`, this signifies and ensures that it is the first (as opposed to `:app`).

Perhaps a new config setting is too verbose, perhaps the order of the build ids in `:builds-to-start` could be respected. I.e. whilst in [`choose-repl-build-id`](https://github.com/bhauman/lein-figwheel/blob/bddbcc0fe326ea1e4aafb649a0b95c9113377611/sidecar/src/figwheel_sidecar/system.clj#L529) the first id is chosen from a filtered `:builds-to-start` vector (although this seems to be the case already in [`narrow-builds*`](https://github.com/bhauman/lein-figwheel/blob/bddbcc0fe326ea1e4aafb649a0b95c9113377611/sidecar/src/figwheel_sidecar/config.clj#L126)).

    Leiningen 2.7.1 on Java 1.8.0_131 OpenJDK 64-Bit Server VM
      [lein-figwheel "0.5.13"]
      [figwheel-sidecar "0.5.13"]

**Comment by bhauman** [comment]
Yes this makes sense.    If you use an vector for the builds instead of a map then the first build is known.  This should work for maps as well unless you have a lot of builds. 

However a `:build-to-focus` param does make sense.

**Comment by au-phiware** [comment]
If I use a vector, will leiningen's profiling still work? I had assumed not, but I didn't actually try...

**Comment by bhauman** [comment]
Good assumption, profiles won't work

**Comment by bhauman** [comment]
Actually the order in builds to start should be respected as you suggest, and the first one should be the focus build.

**Comment by bhauman** [comment]
The first build in :builds-to-start will become the focused build for the REPL
