### ISSUE TITLE
Windows: Can't overwrite file while compilation error dialog open

### ISSUE THREAD

**Issue by philip-healy** [bhauman/lein-figwheel#604]
I'm using lein-figwheel v0.5.13 running on Windows Subsystem for Linux on Windows 10.

I'm editing my source files using IntelliJ/Cursive running as a Windows app.

Figwheel works as normal if I save a source file with no compilation errors. If I save a file with compilation error, the "Compilation Error" dialog appears in my browser.  While this dialog is open I can't save the file again in IntelliJ - I need to close the dialog first.

Is Figwheel holding a lock on the source file while the "Compilation Error" dialog is open?

**Comment by bhauman** [comment]
Figwheel does a `slurp` to read the source of the file and `slurp` uses `with-open` which simply reads the file. No lock required.  I think your env might be the suspicious outlier in this case. The compiler writes to files but not Figwheel.

**Comment by bhauman** [comment]
There is another windows 10 filesystem related issue in here somewhere ...

**Comment by philip-healy** [comment]
Thanks for responding so quickly Bruce. I'll try the same workflow with the Windows version of Leiningen and see if the issue still crops up.

**Comment by philip-healy** [comment]
It seems to be working fine with Leiningen running natively under Windows. So, this appears to be a WSL compatability issue. I think we can close this as WSL is in beta. A supported version of WSL will be shipping with the upcoming Fall Creators Update. I'll check again once I have updated to the supported version.
