### ISSUE TITLE
Figwheel is caching project.clj somehow

### ISSUE THREAD

**Issue by aaronc** [bhauman/lein-figwheel#61]
When I change my project.clj, figwheel does not pick up the changes. It is caching the old project.clj somewhere! The old source paths are reported.

This applies to `0.2.0-SNAPSHOT`. If I go back to `0.1.7-SNAPSHOT`, the problem goes away and figwheel sees my changes.

**Comment by Bost** [comment]
I just found out figwheel also uses the $HOME/.cljs as a cache and when I deleted its content the `ReferenceError: foo is not defined` was gone. Could we document it somewhere / somehow?

**Comment by bhauman** [comment]
This is the new behavior by the most recent version of ClojureScript, this behavior will soon be turned off by default.

**Comment by bhauman** [comment]
@Bost so I would downgrade from using clojurescript 1.10 until the official release comes out...
