### ISSUE TITLE
cljs-base support

### ISSUE THREAD

**Issue by rosejn** [bhauman/lein-figwheel#611]
When compiling into multiple modules the Clojurescript compiler now has a concept of the cljs-base module, which gets all namespaces not explicitly placed in other modules.  The documentation recommends a module specification that only includes an :output-to setting to specify where the module should be written to, but Figwheel complains with an error saying that modules require an :entries key.  Hitting 's' to start anyway moves on and everything works fine, but the error checker should probably take this into account now.

**Comment by bhauman** [comment]
https://github.com/bhauman/lein-figwheel/issues/608

already implemented in 0.5.14-SNAPSHOT

**Comment by rosejn** [comment]
Awesome, thanks!
