### ISSUE TITLE
Configure initial namespace

### ISSUE THREAD

**Issue by pesterhazy** [bhauman/lein-figwheel#614]
The lein clojure REPL provides a `{:repl-options {:init-ns foo.bar}}` to change the initial namespace.

Is it possible to configure the namespace that the figwheel's terminal repl prompt starts with? It defaults to `cljs.user`. I'd like to set it to the same namespace that `:main` is set to as per https://gist.github.com/bhauman/cf5403efd142407355df

**Comment by bhauman** [comment]
Wow after looking into this there is no easy way to do this at all.  The complexity required to do this leads me to think that this would need to be corrected/added to the ClojureScript repl itself.

You should be able to bind `cljs.analyzer/*cljs-ns*` to set the initial namespace but it seems the initialization code overrides it?? I'm not sure but it doesn't work.

**Comment by pesterhazy** [comment]
Thanks for looking into this. The obvious workaround is to name your repl/util namespace `cljs.user` and to require `cljs.user` somewhere in your code. This works for me, except that namespace aliases `(:require [clojure.string :as string])` don't take an effect until I reload `cljs/user.cljs` for the first time. This works ok for me so I'll close this one for now.
