### ISSUE TITLE
Add ability to choose which build hosts repl when multiple builds are running

### ISSUE THREAD

**Issue by nbardy** [bhauman/lein-figwheel#615]
Currently figwheel only connects the repl on one build when running multiple builds e.x. `figwheel dev devcards` Allow an option for selecting which build should host the repl. 

API Idea:
`lein figwheel dev +devcards`

**Comment by bhauman** [comment]
This is an interesting idea, but it is intended that the first on is the one that gets the REPL. It is possible that this doesn't work anymore?

**Comment by sonwh98** [comment]
I have a need for this as well. currently i have a build for an admin and another for the client app. when i connect to the repl on two different browsers i only get the state of one browser. it would be nice if i can change which browser i'm connected to so i can debug both the admin and the client app

**Comment by nbardy** [comment]
The first one makes sense. Currently that is not working for me. I not sure how it selects the build. But I just tested and it's not the first build option.

**Comment by bhauman** [comment]
OK so I'm going to make it so that the first build gets the REPL. That was a regression.

**Comment by bhauman** [comment]
The first build on the command line will become the focused build for the REPL
