### ISSUE TITLE
React Native reloading broke

### ISSUE THREAD

**Issue by jeaye** [bhauman/lein-figwheel#616]
I'm using `0.5.14`, but I'm seeing this: https://github.com/drapanjanas/re-natal/issues/99

Based on my research, this commit broke reloading in ReactNative: https://github.com/bhauman/lein-figwheel/commit/a3938056c7aad62b588b4b0826c6b20746b6f71a

React Native is no longer supported in `reload-file*`: https://github.com/bhauman/lein-figwheel/blob/381ed0ccb3de66c6f4cbf8bb9ccc48c093694baa/support/src/figwheel/client/file_reloading.cljs#L264-L274

Is this intentional, or am I missing something? I'm, unfortunately, unable to do any live reloading now.

**Comment by bhauman** [comment]
You need to use the latest version of re-natal with figwheel 0.5.14

**Comment by bhauman** [comment]
Specifically the changes that are in figwheel bridge.

**Comment by jeaye** [comment]
Thanks for the quick reply. I'm on `0.7.0`, as per:

```bash
$ re-natal --version
0.7.0
```

Looks like there's a `0.7.1` though, so I'll upgrade to that and report back.

**Comment by jeaye** [comment]
Updating to `0.7.1.` didn't change the error I'm seeing. That is, `"Reload not defined for this platform"` being thrown when a file changes.

My suspicion, since re-natal changes were required for this fix, is that the re-natal config layout changed in a way which doesn't progress old users forward. So I may be stuck with some baggage from the time before this fix. Just a guess, right now.

**Comment by jeaye** [comment]
Matching my suspicion, it looks like I didn't run the upgrade procedure documented here: https://github.com/drapanjanas/re-natal/blob/ac78028655a55c98c6f8b6f381450929995fcfef/README.md#upgrading-re-natal-cli-version

After upgrading, I'm still seeing this issue.

```bash
$ re-natal --version
0.7.1
$ re-natal use-android-device "192.168.0.12"
Using development host IP: '192.168.0.12'
Please run: re-natal use-figwheel to take effect.
$ re-natal upgrade
upgraded .re-natal
upgraded files in env/dev and env/prod 
upgraded figwheel-bridge.js
To upgrade React Native version please follow the official guide in https://facebook.github.io/react-native/docs/upgrading.html
$ re-natal use-figwheel
Cleaning...
index.ios.js was regenerated
index.android.js was regenerated
Host in RCTWebSocketExecutor.m was updated
Dev server host for iOS: localhost
Dev server host for Android: 192.168.0.12
```

The `figwheel-bridge.js` diff appears now: https://gist.github.com/jeaye/ba9513abcbe1d0ca0014af8e2a878fb4

I still can't reload though.

**Comment by jeaye** [comment]
Gah, found it. After the upgrade, I also needed to run `react-native run-android` to install a new version on there. I'll mention this in the re-natal ticket, so the docs can be updated. Apologies for the noise; hopefully this serves as documentation for anyone else in this pickle.

Thanks for the help.
