### ISSUE TITLE
:global-exports not supported

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/lein-figwheel#617]
See description in title

**Comment by bhauman** [comment]
As far as I can tell from the non descriptive issue, These issues have been resolved already please make sure you are using the latest figwheel SNAPSHOT.

And please feel free to check recent issues, the commit log and the change log as these issues may have been resolved recently.

If the issues haven't been resolved please give me something to go on.

**Comment by lgrapenthin** [comment]
Hi Bruce, no offense intended - just wanted to be as brief as possible.
I haven't found anything at the places you mentioned, but have also not tried out SNAPSHOT yet.
(Talking about :global-exports for https://clojurescript.org/reference/compiler-options#foreign-libs)
I'll try SNAPSHOTS now and let you know.

**Comment by lgrapenthin** [comment]
The key is supported in the latest SNAPSHOT.
