### ISSUE TITLE
cljc reloading not working

### ISSUE THREAD

**Issue by skbach** [bhauman/lein-figwheel#633]
I've added :reload-clj-files {:clj true :cljc true} to my root figwheel config, but changes to the cljc files do not trigger a figwheel reload.

Are there any workarounds?

**Comment by bhauman** [comment]
The `cljc` files have to be in a watched directory i.e. in the specific builds ':source-paths'

**Comment by skbach** [comment]
Thanks Bruce.

I had the source-paths correct in the parent config but not in the dev build profile.
