### ISSUE TITLE
Enhancement: Development of Service Worker

### ISSUE THREAD

**Issue by orolle** [bhauman/lein-figwheel#642]
Hi,
I develop a service worker for my progressive web app (PWA) in cljs. Currently my work flow is to run `lein build once min-service-worker` after each change and hitting F5 in the browser afterwards. I guess figwheel can do better and I believe there are 2 options to solve the issue (and to be a head of the PWA hype).

**Problem**
The core problem is that cljs is compiled to non-optimized javascript-code and contains <script>-tags. But in a service worker runtime environment no DOM is present, which causes the service worker execution to fail. If the service worker cljs code is compiled with optimization advanced on, no <script>-tags are present and the service worker works just fine.   

**Example PWA Project**
Here is an example PWA in cljs project, I based my work on:
PWA in cljs repo: https://github.com/gja/pwa-clojure
PWA in cljs video: https://www.youtube.com/watch?v=atUdVSuNRjA

**Option 1**
Use importScript() instead <script>-tag when generating javascript code from service-worker marked cljs code. The service worker marker can be added to project.clj. 

**Option 2**
Allow for `:optimizations   :advanced` when running figwheel (`lein figwheel dev-service-worker`). During optimization, <script>-tags will be removed and the cljs service worker can execute. I am not an expert in figwheel (or else I implemented the solution myself), but maybe then hot-swaping of code will not work?

**Comment by bhauman** [comment]
Does this help? https://github.com/bhauman/lein-figwheel/wiki/Using-Figwheel-with-Web-Workers
