### ISSUE TITLE
Add Etag to static file responses

### ISSUE THREAD

**Issue by danielcompton** [bhauman/lein-figwheel#664]
## Problem

I've noticed some caching issues with Figwheel under `:optimizations :none`, even after #586. I think it's due to the way modified dates are calculated on compiled files (by the ClojureScript compiler?). It looks like the last modified date is copied from the source file to the compiled file.

This will work correctly when that cljs file is changed, but doesn't detect changes in compiled output due to changes in macros from other namespaces. This may also impact other code too.

The way this can manifest is:

1. Page loads with version 1 of ns `a`, served by Figwheel
2. Change macro code in `b` used by `a`, causing recompile of `a`. Figwheel pushes version 2 of `a.js` (with cache busting query string)
3. Reload the page, requesting a.js with the last `If-Modified-Since` matching the `Last-Modified` sent in 1. `a.js` hasn't changed, so Figwheel returns a 304.

## Solution?

I think the way forward here is to calculate and use an [ETag](https://en.wikipedia.org/wiki/HTTP_ETag) when serving the static files. This is a much more reliable way to ensure files are up-to-date than based on file modification time.

I'll have to do some tests and check the caching specs, but I think we can still provide Last-Modified and use the union of the two to determine cache freshness.

**Comment by danielcompton** [comment]
I took a crack at this, and I think it's going to be a bit more tricky to solve properly. ClojureScript compiles are not deterministic (think gensyms), so we can't set an Etag based on either the content of the length of the JS file being served. One way to solve this would be to set the last modified date for a file to match the last modified date of that file, or any of the files that could affect its output (only macro files?).

**Comment by kommen** [comment]
Thanks for bringing this up. We're running into the same issue, especially with Safari not reloading files. And I also noticed the ClojureScript behavior of not always setting last-modfied on the out files, even if they changed.
Concrete example: We upgraded the ClojureScript version in our project, which resulted on all files being re-compiled (easy to see because the ClojureScript version is included in the resulting .js files). But the last-modied time stamps we're still from before the upgrade, leading to weird issues due to Safari using cached .js files which actually already have been changed.

I wonder if the ClojureScript behaviour is desired. Maybe this commit is also related? https://github.com/clojure/clojurescript/commit/a0b952129a087a724fc6f89cb9b1a5960426dfd6

**Comment by danielcompton** [comment]
Sleeping on this overnight, I think it is perfectly acceptable to send a new response if the file has changed, this is the point of caching headers. It is possible that the ClojureScript compiler will produce semantically identical JavaScript which checksums differently because of gensyms, but there is not a lot we can do about that.

After a quick spike on adding an ETag I was still seeing incorrect caching behaviour by Figwheel which led me to open https://github.com/ring-clojure/ring/issues/322 to fix the 304 behaviour when an ETag and Last-Modified header are both provided.

**Comment by bhauman** [comment]
I'm think I'm seeing this too.  We probably should never cache any files that are compiled from the source-paths and we should not ever cache *:output-to*'s. This should solve the problem for good.

**Comment by danielcompton** [comment]
I think it's OK for us to cache files as long as we calculate a checksum for each file and use that instead. There are lots of files in Google Closure which are always the same, so we benefit from not starting with an empty cache on each page load. On a TodoMVC based project I see 2.3s to DOMContentLoaded with empty cache vs. 1.5-1.7s with checksum based 304's. 

I've opened #667 which adds an a checksum based ETag for efficiently detecting file changes.
