### ISSUE TITLE
Could not locate cljs/analyzer__init.class or cljs/analyzer.clj 

### ISSUE THREAD

**Issue by p-b-west** [bhauman/lein-figwheel#670]
This issue seems to have cropped up at times in the past.  Maybe I'm doing something wrong.

Leiningen 2.8.1 on Java 1.8.0_161 Java HotSpot(TM) 64-Bit Server VM

Simplest example:
$ lein new figwheel whatever
$ cd whatever
$ lein figwheel

Lots of stacktrace, including
Caused by: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath:

**Comment by bhauman** [comment]
So this has to be an environment thing. This means that your clojurescript dep is being met with something that doesn't have cljs.analyzer in it.  This means your .m2/repository, .profiles etc is mucking things up.

**Comment by p-b-west** [comment]
# Have been tinkering with shadow-cljs
$ rm -rf ~/node_modules
$ rm -rf ~/.yarn*
$ rm -rf ~/.npm
# I had clojure 1.9 installed with brew.
$ brew uninstall --force clojure
$ cd ~/.m2/repository
$ rm -rf clj* clojure* lein*
$ cd Projects
$ lein new figwheel ozehealth
$ cd ozehealth
$ lein figwheel

Same result.  Any other suggestions?

**Comment by bhauman** [comment]
did you check your .lein/profiles?

**Comment by bhauman** [comment]
Also you would really need to get rid of or move your whole m2 repository to check this.

**Comment by p-b-west** [comment]
Nope, I forgot about them.  Had a clojure 1.6.0 from 2015, which shows how long it's been since I used lein.  Thank you for your patience.
