### ISSUE TITLE
Need to execute a command before figwheel starts ?

### ISSUE THREAD

**Issue by metacritical** [bhauman/lein-figwheel#671]
I need to execute a command say ```# electron .``` in a separate subprocess before figwheel starts  is there a possibility one could use :eval-fn key to execute say a ```clojure.java.shell```?   or maybe other clever way in figwheel?

**Comment by danielcompton** [comment]
If you want a particularly custom lifecycle you can [use Component](https://github.com/bhauman/lein-figwheel#scripting-with-component) to coordinate things in just the right way. I don't quite understand the context, but could you also just run something like this?

```console
$ ./run-my-command.sh && lein figwheel
```

**Comment by metacritical** [comment]
Thanks., can you give an example how to use :eval-fn key?

**Comment by danielcompton** [comment]
I don't think [:eval-fn](https://github.com/bhauman/lein-figwheel/blob/db2cd28d7a0719ac3065421336e70cd62c218ff2/support/src/figwheel/client/utils.cljs#L75-L78) is what you want, that seems more for customising the eval command that the browser client is going to run, not for running arbitrary functions. I think this is more of a usage question than a feature request that might get more responses in the #lein-figwheel channel on Clojurians Slack?
