### ISSUE TITLE
Unrecognized VM Option 'OmitStackTraceInFasThrow'

### ISSUE THREAD

**Issue by alexnixon** [bhauman/lein-figwheel#681]
I'm using Windows 10, these plugins:

```
  :plugins [[lein-cljsbuild "1.1.7"]
            [lein-ring "0.12.4"]
            [lein-figwheel "0.5.15"]]
```
```
>lein figwheel
Figwheel: Cutting some fruit, just a sec ...
Unrecognized VM option 'OmitStackTraceInFasThrow'
Did you mean '(+/-)OmitStackTraceInFastThrow'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Note the typo. I haven't made any local changes that I'm aware of. I've checked out the source from github for leiningen, lein-cljsbuild and lein-figwheel and cannot find this misspelled string anywhere.

Given I see some Figwheel output before the error I assume it's figwheel's fault so I'm filing here. Happy to debug myself if someone can give me some pointers.

**Comment by bhauman** [comment]
This should not be figwheels fault as it doesn't do any thing with VM args. This would have to something to do with lein and or some global settings for your JVM

**Comment by alexnixon** [comment]
Thanks - I'll close this then and let the mystery continue elsewhere. Apologies for the false alarm.
