### ISSUE TITLE
Error on every refresh

### ISSUE THREAD

**Issue by conan** [bhauman/lein-figwheel#692]
Every time figwheel reloads code, I get the following error dumped to the console:
```
connect.cljs?rel=1526298312396:9
Uncaught TypeError: Cannot read property 'init' of undefined
    at G__56805__delegate (connect.cljs?rel=1526298312396:9)
    at Function.figwheel.connect.start.cljs.core.PersistentArrayMap.G__56805.cljs$lang$applyTo (connect.cljs?rel=1526298312396:9)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$2 (core.cljs:3891)
    at cljs$core$apply (core.cljs:3883)
```
It doesn't cause any problems that I am aware of, but I'd like to get rid of it.  Unfortunately I have no idea where to start looking.  Any clues?

Here's a snapshot of my console with more info:

![image](https://user-images.githubusercontent.com/3037019/40844813-d05364ee-65ac-11e8-9030-d750d665ac2a.png)

**Comment by conan** [comment]
I load the application in my `index.html` by calling my `init` function, I'm guessing it's something to do with that; the problem only occurs on figwheel reloads though, not on initial load of the application.

**Comment by bhauman** [comment]
it looks like it can't find the "hanabi" namespace

I'm pretty sure that it's this line thats causing the error.

Is your init function getting called?

**Comment by bhauman** [comment]
forgot to paste the line
https://github.com/bhauman/lein-figwheel/blob/master/support/src/figwheel/env_config.clj#L29

**Comment by conan** [comment]
The init function is called in the `index.html` file like this:
```
<div id="app"></div>
<script src="js/compiled/app.js?cache_buster=<cache_buster>"></script>
<script>hanabi.core.init();</script>
```

**Comment by conan** [comment]
it gets run correctly because that's what kicks off the application fine, or at least it gets run on first load; it's possible it isn't being run on subsequent loads because of this error, but the application has already started up

**Comment by conan** [comment]
I figured this out, I had an `:on-jsload` option in my figwheel config in my `project.clj` that was looking for `hanabi.user/init` instead of `hanabi.core/init`.
