### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by whodidthis** [bhauman/lein-figwheel#70]
So I'm getting this weird error that I have no idea where it's coming from because the stack trace is lost. I did however try adding this following line:
https://github.com/whodidthis/lein-figwheel/blob/master/support/src/figwheel/client/heads_up.cljs#L76
and whenever figwheel reloads I get `setting style! null` which sounds there could be something in there(?)

Project I tested on is here: https://github.com/whodidthis/flow-testing

**Comment by whodidthis** [comment]
Right when I walked out of the house i realized what I had done. Anyways if someone goes this route (replaces the entire document.body along with figwheels new information panels) maybe a little warning message wouldnt hurt, heh

**Comment by bhauman** [comment]
Yeah I will create a guard for this situation.

**Comment by bhauman** [comment]
I really think part of this is fixed.  

Letting people know that mounting an app to `<body>` is a bad idea is an interesting issue.

**Comment by darthdeus** [comment]
I just ran into this, fortunately managed to google this issue almost immediately, but a small warning or assertion would be nice in this case :)

**Comment by bhauman** [comment]
You tried mount your app to body?

**Comment by darthdeus** [comment]
Yes
