### ISSUE TITLE
figwheel repl does not connect to browser 

### ISSUE THREAD

**Issue by dpsutton** [bhauman/lein-figwheel#703]
This is an issue I've had since the cider/piggieback update.  When using `cider/piggieback` 0.3.5 and `lein-figwheel` and `figwheel-sidecar` 0.5.16 the repl never connects. It just hangs at 

```
Prompt will show when Figwheel connects to your application
```

However, 0.5.14 and cemerick/piggieback 0.2.2 work just fine. In order to diagnose the differences, I had to backport checks for cider/piggieback to 0.14 and then bisect until it would no longer connect.

I've found that for our principal application 
`8f2ced4 * | include eval-fn in the hook protection` [commit](https://github.com/bhauman/lein-figwheel/commit/8f2ced40d1e4c5847e33dd154d5ce464f03d1aec) works just fine but that the next commit `9bff797 Merge branch 'refactor-injection2` [commit](https://github.com/bhauman/lein-figwheel/commit/9bff7971b427c40925aeb5ed5b36d3c76761738c) leaves the repl in this pending state.

I'm still investigating what are the breaking changes for us in this but wanted to put this out there.

**Comment by bhauman** [comment]
So this will have nothing to do with piggieback and everything to do with figwheel switching to preloads to inject its repl connecting code.

**Comment by dpsutton** [comment]
Yeah. There were so many moving parts with lein-figwheel, sidecar, piggieback and CIDER it was tough to narrow it down. I'm gonna read through and see if i can understand what's going on. I went through a bit of the figwheel codebase at first and there were a lot of moving parts. I'll see if i can spot anything.

**Comment by dpsutton** [comment]
> Another thing to check is to see if figwheel.preload or figwheel.connect is in the sources that your page is fetching. And if they actually get downloaded.

That's exactly it! This also explains why when I was bisecting if I didn't close the tab it would work but wouldn't work on a fresh tab. I should have put that together sooner. There are zero figwheel resources on 0.5.16.

Thanks for the help so far!

**Comment by dpsutton** [comment]
```

**Comment by dpsutton** [comment]
build info before the add connect script function
```clojure
{:output-dir "target/raw/jib_out/js",
 :cache-analysis true,
 :language-out :ecmascript5,
 :optimizations :none,
 :warnings
 {:protocol-multiple-impls false, :single-segment-namespace false},
 :output-to "target/raw/jib_out/js/jib.js",
 :source-map-timestamp true,
 :source-map true,
 :libs
 ["src/breeze/client/models/growth.js"
  "src/breeze/client/models/cptPrices.js"
  "src/breeze/orderedB64.js"],
 :devcards true,
 :language-in :ecmascript5}
```
and after:
```clojure
{:output-dir "target/raw/jib_out/js",
 :cache-analysis true,
 :language-out :ecmascript5,
 :optimizations :none,
 :warnings
 {:protocol-multiple-impls false, :single-segment-namespace false},
 :preloads [figwheel.preload],
 :output-to "target/raw/jib_out/js/jib.js",
 :source-map-timestamp true,
 :source-map true,
 :libs
 ["src/breeze/client/models/growth.js"
  "src/breeze/client/models/cptPrices.js"
  "src/breeze/orderedB64.js"],
 :devcards true,
 :external-config
 #:figwheel{:config
            {:on-jsload "breeze.jib.main/rerender!",
             :build-id "raw",
             :websocket-url
             "ws://[[client-hostname]]:3000/figwheel-ws"}},
 :language-in :ecmascript5}
```

**Comment by dpsutton** [comment]
So I've seen that the necessary ( i think) goog.addDependency but I'm not quite clear on what causes the browser to fetch these and who should serve them:

```
goog.addDependency("../figwheel/client/utils.js", ['figwheel.client.utils'], ['goog.userAgent.product', 'goog.string', 'cljs.core', 'goog.object', 'goog.string.StringBuffer', 'cljs.pprint', 'goog.async.Deferred', 'clojure.string', 'cljs.reader']);
goog.addDependency("../figwheel/client/file_reloading.js", ['figwheel.client.file_reloading'], ['goog.string', 'goog.net.jsloader', 'goog.Uri', 'cljs.core', 'goog.object', 'cljs.core.async', 'clojure.set', 'goog.html.legacyconversions', 'figwheel.client.utils', 'goog.async.Deferred', 'clojure.string']);
goog.addDependency("../figwheel/client/socket.js", ['figwheel.client.socket'], ['cljs.core', 'goog.object', 'figwheel.client.utils', 'cljs.reader']);
goog.addDependency("../figwheel/client/heads_up.js", ['figwheel.client.heads_up'], ['goog.dom', 'goog.string', 'cljs.core', 'goog.dom.dataset', 'goog.object', 'cljs.core.async', 'cljs.pprint', 'figwheel.client.utils', 'figwheel.client.socket', 'clojure.string']);
goog.addDependency("../figwheel/client.js", ['figwheel.client'], ['goog.userAgent.product', 'goog.Uri', 'cljs.core', 'goog.object', 'cljs.core.async', 'figwheel.client.file_reloading', 'figwheel.client.utils', 'cljs.repl', 'figwheel.client.heads_up', 'figwheel.client.socket', 'clojure.string', 'cljs.reader']);
goog.addDependency("../figwheel/connect.js", ['figwheel.connect'], ['cljs.core', 'figwheel.client']);
goog.addDependency("../figwheel/preload.js", ['figwheel.preload'], ['cljs.core', 'figwheel.connect']);
```

**Comment by dpsutton** [comment]
I think I have found the source of the problem. We had our own `:ring-handler` specified.

In the past it "just worked" (TM) and I'm not exactly sure where the figwheel init call was made. Now that doesn't happen. Previously it would just emit a goog.require(our-app.main) but now it needs to include the `";goog.require('figwheel.preload');goog.require('breeze.jib.main');"`.

It's been a fun journey :)

Can you chime in with your thoughts about whether we are being dumb or if this contract is not documented somewhere?

**Comment by bhauman** [comment]
Darn I should have noticed you are not using `:main`

Since you are not using the `:main` option along with the resulting `:output-to` main script all bets are off.  I highly recommend you revert to using main and the resulting `:output-to` script.  When you don't use `:main` you won't get Closure defines, or preloads. You can literally slurp it into the index html in your ring server if you want.

Otherwise you have to use the `figwheel.preload` but this is only going to work for so long.  David is really pushing to all parameterization to `goog-define`'s, which means that you will need to ensure that the Clojure Defines are available.

**Comment by dpsutton** [comment]
Thanks @bhauman for taking the time to look over this. I'll run this by coworkers on Monday.

**Comment by bhauman** [comment]
Sorry this was such a pain.  Figwheel used to account for this by adding extra lines to the `:output-to` when `:main` wasn't configured. Perhaps I need to return to doing this.

**Comment by bhauman** [comment]
Thanks very much for the donation and the shout out, I'll be sure and use it for something fun this summer :)

**Comment by dpsutton** [comment]
Let me chat with coworkers. We might be doing some wonky things that are no longer necessary. We had a cordova build that introduced a bunch of complexity that has gone away. It would be nice if we could make our build and serve process a bit more simple.

You're very welcome. Your software makes my day to day life easy and pleasurable. Please have some fun on me :)

**Comment by bhauman** [comment]
Also, figwheel-main is coming along nicely you may want to take it for a whirl soon.
