### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by galdolber** [bhauman/lein-figwheel#705]
I'm getting a strange error only on figwheel. It doesn't fail when compiling directly with cljs.main. This is the smallest failing test case I found:

deps.edn
```
{:paths ["src"]
 :deps
 {org.clojure/clojure {:mvn/version "1.9.0"}
  org.clojure/clojurescript
  {:git/url "https://github.com/clojure/clojurescript"
   :sha "9a8196ebfe4265feda88a06de84affb9df469012"}  
  com.rpl/specter {:mvn/version "1.1.1"}
  com.bhauman/figwheel-main {:mvn/version "0.1.3"}
  com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}}}
```

bug.cljs.edn
```
{:target :nodejs 
 :infer-externs true
 :optimizations :none 
 :main figwheel.bug}
```

bug.cljs
```
(ns figwheel.bug
  (:require [com.rpl.specter :include-macros true :refer [path LAST must]]))

(def PROGRAM (path (must :state/programs) LAST))
```

<img width="933" alt="screen shot 2018-06-26 at 11 29 19 pm" src="https://user-images.githubusercontent.com/963214/41949821-6e8642bc-7999-11e8-9de5-bd67b94a88d8.png">

**Comment by galdolber** [comment]
After more investigation, this seems to be a bug in specter introduced after this clojurescript commit https://github.com/clojure/clojurescript/commit/9a8196ebfe4265feda88a06de84affb9df469012
Not sure why it only happens on figwheel

**Comment by mfikes** [comment]
FWIW, this was also manifesting itself outside of Figwheel (when running Specter's unit tests with ClojureScript master). It was reported and fixed in Specter: https://github.com/nathanmarz/specter/issues/261
