### ISSUE TITLE
No matching ctor found for class org.httpkit.server.HttpServer

### ISSUE THREAD

**Issue by t3chnoboy** [bhauman/lein-figwheel#71]
Hi!
I was using figwheel 1.3 and 1.4. Everything was working like a charm!
After upgrading to 2.2-SNAPSHOT when I run ```lein figwheel``` I'm getting this error: ```No matching ctor found for class org.httpkit.server.HttpServer```
I've tried to create clean project using [figwheel template](https://github.com/bhauman/figwheel-template) and got the same error. [This example](https://github.com/bhauman/lein-figwheel/tree/master/example) doesn't work either. Same problem present in 2.0.
Here's [full stack trace](https://gist.github.com/t3chnoboy/6d97db370d102dd5aa07)

OS X 10.10. Leiningen 2.5.0 on Java 1.8.0_20-ea Java HotSpot(TM) 64-Bit Server VM

**Comment by bhauman** [comment]
It really seems like you are getting either a previous version of http-kit or class compiled from a previous version of HttpKit.  

Try to do a lein clean and see where that gets you.

Also if that isn't working try a lein deps :tree and see if you have any interesting conflicts

**Comment by t3chnoboy** [comment]
I have already tried ```lein clean``` without any luck.
Looks like there are many conflicts. [ lein deps :tree](https://gist.github.com/t3chnoboy/c6e4137f213629dfc6a5)

**Comment by t3chnoboy** [comment]
Removing [[refactor-nrepl "0.3.0-SNAPSHOT"]](https://github.com/clojure-emacs/refactor-nrepl) from ~/.lein/profiles.clj resolved the issue!
Thank you!
