### ISSUE TITLE
:ring-handler does not alert when it can not find the given namespace

### ISSUE THREAD

**Issue by diegovdc** [bhauman/lein-figwheel#714]
I spent a looong while to figure out this was the error in my config.  Due to my inexperience I was not locating my ring handler in the right place, once I figured out the right naming and folder structure it worked. 

It would be nice for beginners like me to have some kind of error message on this.

Thanks

**Comment by bhauman** [comment]
see https://github.com/bhauman/lein-figwheel/pull/713

**Comment by bhauman** [comment]
this is available in the latest SNAPSHOT
