### ISSUE TITLE
error trying to require a Javascript module with an @ character

### ISSUE THREAD

**Issue by carocad** [bhauman/lein-figwheel#717]
I am using the figwheel bridge together with the Expo template for a react native app.

I just migrated to node.js compilation target and started using js interop for requiring modules through the namespace form.

Everything seems to work fine for "standard" requires (those with simple names like react, react-native, expo) but if I try something like below then figwheel complains it cannot read it.

<img width="394" alt="screen shot 2018-11-05 at 14 00 34" src="https://user-images.githubusercontent.com/10408729/47999863-14ce8e00-e104-11e8-9a2e-92c5e3369544.png">

**Comment by bhauman** [comment]
This is ClojureScript issue

**Comment by carocad** [comment]
@bhauman sorry for the poorly explained issue. You are right that the issue is from Clojurescript, however, the issue that I wanted to point out is that it is not possible to know what went wrong on the repl since figwheel doesnt show it.

The feedback simply says `message from client couldnt be read`, which of course could mean a lot of things.

Would it be possible to improve that? I would be willing to help if possible :)

**Comment by bhauman** [comment]
I think this is fixed in figwheel-main.  I'm suggesting that folks move over as the improvements are many.

**Comment by bhauman** [comment]
When I say fixed I mean that the message is a tad clearer.
