### ISSUE TITLE
scss reloading not being triggered

### ISSUE THREAD

**Issue by diegovdc** [bhauman/lein-figwheel#728]
I am not sure what is going on here, but when I modify files that are not the my `main.scss` file, then `figwheel` does not seem to detect the changes. 

If, after making the change on `somefile.scss` I save `main.scss` or the compiled `main.css` in the `public` directory, then the changes are successfully applied.

I recall css reloading to be working properly, but I recently moved from `gulp 3` to `gulp 4` for my sass compilation,  so maybe it has something to do with how the new `gulp-sass` is working.

**Comment by danielcompton** [comment]
There’s not enough actionable information here for anyone to be able to help at this point. It’s also not clear if the issue is with Figwheel, or something else. I’d suggest rolling back to your Gulp 3 build and trying to isolate more clearly what has changed and where the problem lies.

**Comment by diegovdc** [comment]
@danielcompton, thanks. 

I tried compilng with `sass --watch path/to/main.scss:path/to/public/css/main.scss`. And can confirm that it works as expected. 

I do not know if works with gulp 3, but it probably does.

I guess it is some kind of optimization in gulp 4. But maybe it is something that `figwheel` should not be concerned about.
