### ISSUE TITLE
Running from a Windows MINGW32 shell uses lowercase drive letter, confuses config checker

### ISSUE THREAD

**Issue by Izzimach** [bhauman/lein-figwheel#73]
I'm not sure I even consider this a real bug, but I'm posting here for the next poor soul that stumbles into this mess caused by Windows file paths.

First of all, running `lein figwheel hello` from a window shell like `cmd.exe` or Powershell works fine. However, when I invoke it from Windows git bash (built with MINGW32) I get the following configuration error:

```
Figwheel Config Error (in project.clj) - your build :output-dir is not in a resources directory.
It should match this pattern: (c:/Users/Gary/Documents/Projects/Github/om-react-pixi/dev-resources|c:/Users/Gary/Documents/Projects/Github/om-react-pixi/resources)/public
```

So it looks like `:resource-paths` is constructed with lowercase drive letters when invoked in git bash. However, the paths generated from `.getCanonicalPath` have uppercase drive letters:

```
user=> (.getCanonicalPath (io/file "."))
"C:\\Users\\Gary\\Documents\\Projects\\Github\\om-react-pixi"
```

Which means that `figwheel-sidecar.config.relativize-resource-paths` won't strip off the leading part of the path string since the drive letters don't match. One path uses an uppercase drive letter while the other path uses a lowercase drive letter. Ugh.

I suppose you could modify `norm-path` to check for this but after poking around in java-land I think using `java.nio.file.Path` would work better at avoiding future headaches. It even has `toAbsolutePath` and `relativize` built in.

**Comment by bhauman** [comment]
Man if you get this working, I'll accept a pull request.  It's very hard
for me to test windows right now.

**Comment by Izzimach** [comment]
Yeah sure, might take a bit since I've not worked on a lein plugin before.

**Comment by bhauman** [comment]
You can do it the simple way.
cd plugin
Change code 
lein install

Then in your project
lein clean
lein figwheel

Repeat as necessary :)

**Comment by Izzimach** [comment]
Let me verify this doesn't break anything on linux (it shouldn't) and I'll generate a PR

**Comment by bhauman** [comment]
Thanks for looking into this.
