### ISSUE TITLE
Figwheel fails to recognize Java version - issues bad warning

### ISSUE THREAD

**Issue by cloojure** [bhauman/lein-figwheel#732]
Running Figwheel with Java 12 produces:

```
> lein figwheel
Figwheel: Cutting some fruit, just a sec ...
Assert failed: Java >= 1.8.0 - Figwheel requires Java 1.8.0 at least. Current version  12
  Please install Java 1.8.0 at least.
  This may only be occuring in the Leiningen (bootstrapping) process but still something to be aware of.
  Especially if this message is immediately followed by an strange stack trace.

```

However `lein` reports the truth:

```
> lein version
Leiningen 2.9.1 on Java 12 Java HotSpot(TM) 64-Bit Server VM

```
Looks like a tweak is needed in Java version parsing.

**Comment by danielcompton** [comment]
Which version of Figwheel are you using? I thought this would have been fixed in https://github.com/bhauman/lein-figwheel/pull/721.

**Comment by cloojure** [comment]
> lein deps :tree |& grep figwheel
 [figwheel-sidecar "0.5.18" :exclusions [[selmer] [org.clojure/clojurescript] [org.clojure/clojure]]]
   [figwheel "0.5.18" :exclusions [[org.clojure/tools.reader]]]

> lein deps :plugin-tree |& grep figwheel
 [lein-figwheel "0.5.18"]

**Comment by bhauman** [comment]
yeah @danielcompton it fails for this case `(compare-semver "12" "1.8.0")`

**Comment by bhauman** [comment]
and `(semver->map "12")` => `{:major nil, :minor nil, :patch nil}` because we are requiring the 3 numbers but the error indicates that his version of java is only supplying `12`

**Comment by danielcompton** [comment]
Thanks, I didn’t expect that case ☺️
