### ISSUE TITLE
High CPU load until first client connected

### ISSUE THREAD

**Issue by mbme** [bhauman/lein-figwheel#74]
lein-figwheel 0.2.2-SNAPSHOT
clojurescript 0.0-2665,  0.0-2727

After running `lein figwheel` leiningen process uses 100% of CPU until browser connected.
Now CPU load stays on 5-10% even if client disconnects.

**Comment by bhauman** [comment]
You are right, fixing it right now.

**Comment by bhauman** [comment]
Alright just redeployed 0.2.2-SNAPSHOT. It fixes the polling eating the CPU.  

I'm running at 3% idle.  Not the best and not the worst.  This is surely the file change polling, this code could be optimized or reverted back to the hand coded method that cljsbuild uses.  I just found file-seq so convenient to use.

**Comment by mbme** [comment]
thank you, works great :+1:

**Comment by bhauman** [comment]
Glad it works!
