### ISSUE TITLE
REPL and line splitting mid-form

### ISSUE THREAD

**Issue by torkus** [bhauman/lein-figwheel#741]
Hi, thanks for figwheel, it's really great.

Is there a way of stopping forms from being split across multiple lines in the REPL when you go back, edit them and press enter?

For example, this form:

```clj
dev:cljs.user=> (prn "foo bar")
"foo bar"
nil
```

if I were to go back and change `prn` to `prn-str` and press enter with the intent to evaluate the form, it splits the line instead:

```clj
dev:cljs.user=> (prn-str
           #_=>  "foo bar")
```

which is inconsistent with how the standard Clojure REPL behaves (and is really infuriating).

**Comment by cldwalker** [comment]
Hi. See https://github.com/bhauman/rebel-readline/issues/101#issuecomment-400018676 for a vim keybindings solution. If you're using the default emacs keybindings, I link to what worked for me

**Comment by torkus** [comment]
this was actually [solved for me on reddit](https://www.reddit.com/r/Clojure/comments/duff5o/terminal_readline_library_for_clojure_dialects/?st=k40grepl&sh=dcf7af64).

the solution was to install the `rlwrap` library. It behaves just like a regular clojure repl now.
