### ISSUE TITLE
Pressing ctrl-D in repl results in: "ClojureScript:cljs.user> ClojureScript:cljs.user> ClojureScript:cljs.user> ..." even with rlwrap.

### ISSUE THREAD

**Issue by chr15m** [bhauman/lein-figwheel#75]
Brilliant software, thanks!

**Comment by chr15m** [comment]
Sorry for the spammy title - did not realised I had pasted so many copies!

**Comment by bhauman** [comment]
Thanks for the report. I'll look into it.

**Comment by bhauman** [comment]
I supplied a patch to fix this ClojureScript repl.

http://dev.clojure.org/jira/browse/CLJS-989

**Comment by glittershark** [comment]
Sure would be nice if they merged that patch :smile:

**Comment by bhauman** [comment]
This is fixed in the latest version of ClojureScript
