### ISSUE TITLE
New snapshot version to Clojars?

### ISSUE THREAD

**Issue by binary132** [bhauman/lein-figwheel#78]
Hi, I'm not sure how to get the latest bugfixed version of your plugin -- I think it needs to be in clojars.

**Comment by mbme** [comment]
just add `lein-figwheel "0.2.2-SNAPSHOT"` as a dependency and lein would automatically retrieve latest version available

**Comment by binary132** [comment]
The `0.2.2-SNAPSHOT` version shown at [clojars.org](https://clojars.org/lein-figwheel/versions/0.2.2-SNAPSHOT) says it was pushed Jan 22...  If I have the latest version, I'm still getting the same bugs.  I'll double check in a few minutes when I'm at my PC.

**Comment by binary132** [comment]
Never mind, maybe the latest version hadn't gone in yet when I'd tried.  Works now.  Thanks!
