### ISSUE TITLE
Windows Volume Label Syntax java.io.IOException

### ISSUE THREAD

**Issue by profbetis** [bhauman/lein-figwheel#79]
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
 at java.io.WinNTFileSystem.canonicalize0 (WinNTFileSystem.java:-2)

To reproduce on Windows 7 (x64):
1. `git clone https://github.com/synapse-garden/dash.git`
2. `lein clean`
3. `lein figwheel test`

figwheel_server.log: http://paste.ubuntu.com/9947110/

**Comment by profbetis** [comment]
Also happens when running `lein cljsbuild once test`

**Comment by binary132** [comment]
```
<DethStryke> bodie_: Yeah, that was the error I was getting with 2727. 2740 working like a dream. :)
```

Seems to be a cljs version issue with Windows.
