### ISSUE TITLE
Incorrect href in inserted stylesheet link tag

### ISSUE THREAD

**Issue by tablatom** [bhauman/lein-figwheel#80]
Live CSS reloading is not working for me.

Setup:
 - I'm using nw.js rather than a regular browser.
 - nw.js is loading the page from the figwheel server at localhost:3449
 - CSS is in resources/public/css
 - I have `:css-dirs ["resources/public/css"]` in my figwheel config.

When Figwheel detects a file, e.g. `style.css` has changed, it removes the following tag:

    <link rel="stylesheet" type="text/css" href="css/style.css">

and then inserts this tag

    <link rel="stylesheet" media="" href="//localhost%3A3449resources/css/style.css?zx=weftsif83jwx">

at which point all my styles are obviously borked.

**Comment by bhauman** [comment]
Can I see your project.clj?

**Comment by tablatom** [comment]
https://gist.github.com/tablatom/29b97cec278065a17032

Thank you : )

**Comment by tablatom** [comment]
I just noticed that in the console, Figwheel is logging

    Figwheel: loaded CSS files.
    ("resources/css/style.css")

That should be `resources/public/css/style.css`

**Comment by bhauman** [comment]
According to your config it should be /css/style.css not resources/css/style.css
What is the path of your css file? and are you on Windows?

**Comment by bhauman** [comment]
Are you using the latest chestnut?

**Comment by tablatom** [comment]
I'm on OS X 10.10.1

From the project root, the css file in question is `resources/public/css/style.css`

I'm not using chestnut at all.

**Comment by bhauman** [comment]
Alrighty, its time for me to add a `:debug` parameter to the figwheel config that will output various debug data that you can send me.

If you could make sure that you are getting the latest `0.2.2-SNAPSHOT` that would be helpful.

The other guess that I would make is that your `:resource-paths` it getting set improperly because of a profile merge.

If you have a `~/.lein/profiles.clj` could you check it to see it it has anything fishy in it.

**Comment by tablatom** [comment]
How would I ensure I have the latest snapshot? I imagine I can simply remove the figwheel related dirs from `~/.m2/repository`. This was the output from running `lein figwheel`:

    $ lein figwheel
    (Retrieving lein-figwheel/lein-figwheel/0.2.2-SNAPSHOT/lein-figwheel-0.2.2-20150122.025744-4.pom from clojars)
    (Retrieving figwheel-sidecar/figwheel-sidecar/0.2.2-SNAPSHOT/figwheel-sidecar-0.2.2-20150130.003542-12.pom from clojars)
    (Retrieving figwheel-sidecar/figwheel-sidecar/0.2.2-SNAPSHOT/figwheel-sidecar-0.2.2-20150130.003542-12.jar from clojars)
    (Retrieving lein-figwheel/lein-figwheel/0.2.2-SNAPSHOT/lein-figwheel-0.2.2-20150122.025744-4.jar from clojars)
    (Retrieving figwheel/figwheel/0.2.2-SNAPSHOT/figwheel-0.2.2-20150128.235059-4.pom from clojars)
    (Retrieving figwheel/figwheel/0.2.2-SNAPSHOT/figwheel-0.2.2-20150128.235059-4.jar from clojars)

I also added `:debug true` to the `:fighwheel` hash in my `project.clj`, but I'm not seeing any new diagnostic output anywhere.

My `~/.lein/profiles.clj` contains

    {:user {:plugins [[lein-ancient "0.6.0"]] }}

Not sure how I missed this before but code reloading is also broken. In the browser console, after "Figwheel: notified of file changes", I see a failed GET request to, e.g.

    http://localhost:3449/resources/out/chisel/commands.js?zx=ogb2msgyuelb

It should be `resources/public/out...`

**Comment by tablatom** [comment]
Correction, the correct URL would be `http://localhost:3449/out/chisel/commands.js` of course.

**Comment by tablatom** [comment]
Correction, the correct URL would be `http://localhost:3449/out/chisel/commands.js` of course.

(oops - no way to undo accidentally closing the issue!)

**Comment by tablatom** [comment]
As a workaround I've created a symlink in my public directory, such that the files are available at the incorrect path that figwheel is using. This has fixed the code reloading problem, but not the CSS, as there  seems to be an additional URL encoding bug with the dynamically added `<link>` tag (`%3A` instead of `:`), as well as a missing `/` (after the port number). The `href` attribute, as mentioned above, is:

    href="//localhost%3A3449resources/css/style.css?..."

**Comment by bhauman** [comment]
Tom I'm really sorry you are having such trouble setting this up.

I haven't added the :debug flag yet I was just asserting that I should definitely do that for situations like this.  

lein-localrepo looks very suspicious. Please try without that.

There is a `:url-rewriter` hook in the client config that should help you deal with these problems. 
https://github.com/bhauman/lein-figwheel#mapping-figwheel-resource-paths-to-your-servers-resource-paths

It just takes a url as string and you can rewrite it to the path that it should be. 

I would be happy to do a screen share to get to the bottom of this.  There is obviously a confluence of things going wrong. Some environmental. Some in naive expectations of figwheel.

I'm willing to bet, that a project generated by `lein new figwheel hello_world` will work.  So there is some assumed expectation on my part that is not meeting an assumed expectation on your part. And I have never tried to use nw.js with figwheel before.

Again, I'm sorry you are having such troubles.

**Comment by bhauman** [comment]
You definitely have me preoccupied with this now.

I just generated a project `lein new figwheel chisel`

I then adopted your project.clj and changed the source directories and the index.html to match up with the project.clj.  So I am running your project.clj unaltered and its all working fine. Now for nw.js .... 

Have also running `lein clean` can be helpful it will delete your compiled clojure and clojurescript.
Also adding this to your project.clj will make sure that `lein clean` deletes your project target files.
```
:clean-targets ^{:protect false} ["resources/public/main.js" "resources/public/out"]
```

OK here is how I can get some debugging data:

LEIN_FAST_TRAMPOLINE=y lein figwheel

There should be an`af724371a7a835c4ee22a84f287e58427749dc64-init.clj` like file in your project root directory.  If you could send me a gist of that file. That would be helpful.

Again I'm open to a screen share.

**Comment by tablatom** [comment]
Thanks so much for being super responsive.

Removing lein-localrepo and `lein clean` have not helped.

Gist is here (formatted a little)

https://gist.github.com/tablatom/2aa8a6b9c91c32e14507

I'll email you about a screen share - I just need to check if I have to run out for a while. Thanks!

If you want to test with nw.js, here is a sample `package.json` to load the app via http instead of a file:

    {
      "name": "Chisel",
      "main": "http://localhost:3449/index.html",
      "node-remote": "http://localhost:3449"
    }

**Comment by bhauman** [comment]
this should be fixed now with the latest release   0.2.3-SNAPSHOT. When you get a chance give it a try.

**Comment by tablatom** [comment]
Code reloading is working properly now. Still having issues with CSS, although they look like nw.js issues rather than figwheel. In devtools I can see a new `<link>` tag added correctly and the old one removed. Sometimes the styling on the page updates correctly and sometimes all the style is lost. If I make a manual edit to the tag (e.g. changing the random string) then the new style appears.

I wanted to try using the url-rewriter to experiment with the href on the generated link tag, to look for a workaround, but things are not behaving as I expect. With some logging, I see that my rewriter function is passed "resources/public/css/style.css" (which I return unchanged), but the actual URL used in the new link tag is something like `http://localhost:3449/css/style.css?zx=RANDOM`

**Comment by bhauman** [comment]
This the expected behavior for url-rewritter for styles.

I know it seems strange but there is a good reason for it.

**Comment by bhauman** [comment]
It sounds like it's working.

Are you using a CSS preprocessor?  It may not be completing?

Or there may be something in your particular  CSS file that nw.js  is choking on?

**Comment by tablatom** [comment]
> Are you using a CSS preprocessor?  It may not be completing?

Great catch : ) I hacked my less-watcher script to compile the file to a temp directory and then mv it into place, and all is now well.

Thanks very much for all your help on this one.
