### ISSUE TITLE
upgrading built-in repl to true nrepl (austin)

### ISSUE THREAD

**Issue by ilazarte** [bhauman/lein-figwheel#81]
I have a template (cljx-start) which integrates cljs/cljx and now reagent and figwheel.  I was unable to load the project in my editors repl (counterclockwise) due to a limitation in the editor but ccw also has a feature to connect to open repls and give you all the repl offers which add its own stuff (syntax highlighting, formatting etc, ccw is pretty cool). 

However, it looks like figwheel only launches a 'local' repl which doesn't give outside editors the ability to connect to it.  Is it possible to somehow use an austin repl with the figwheel session?  Like any lein repl citizen it should respect project.clj :repl-options.

**Comment by bhauman** [comment]
I'm not into doing this right now. But you can create an nrepl connection and set up your own cljs.repl using the current menagerie of tools.  Booting a cljs.repl on top of nrepl is a standard practice. See piggieback and weasel.

**Comment by ilazarte** [comment]
I will give that a shot, thanks!

**Comment by bhauman** [comment]
I recoomend you try this outside of figwheel first just using the figwheel-sidecar lib. Which allows you to set up the env you want.  Then when you get it working, you can show me what you did and we can talk about it :)

**Comment by Gonzih** [comment]
I think it's not just about just having nrepl built in, but also about support from nrepl clients (vim-fireplace, cider etc).

**Comment by bhauman** [comment]
My concern is having a repl experience that works everytime, all the time. Nrepl introduces a lot of complexity for a cljs repl, and the nrepl middleware stack increases that complexity. I'm really tired of having buggy crashing REPLs.

Emacs has inferior lisp mode.  And I'm sure vim has a some kind of shell mode to make it easy to ferry code to the repl from your editor.

I'm not saying I'm unwilling to consider it in the future, if the story changes, but for now, I'm really happy having a stable repl that just works, aren't you?

Embrace the simplicity :)

**Comment by Gonzih** [comment]
Yep, I agree. So far vim+tmux combination works fine for me :)

**Comment by devth** [comment]
My 2 cents on vim: vim+tmux are nice, and I use that for all my non-clj projects, but for clj we have it so much better: fireplace.vim. Being able to `cpr` to make sure my code even compiles is essential. Instead, I'm cmt+tabbing between editor and browser to see if my changes compiled.

**Comment by cichli** [comment]
I've created an example project [here](https://github.com/cichli/figwheel-piggieback-example) that demonstrates how to use sidecar and piggieback together. Just load the core namespace and run `(repl)` to start the REPL up (note that this will block until your browser connects to figwheel).

This is the gist of it:

```clojure
(ns figwheel-piggieback-example.core
  (:require [cljs.env :as env]
            [cemerick.piggieback :as piggieback]
            [figwheel-sidecar.auto-builder :as fig-auto]
            [figwheel-sidecar.core :as fig]
            [figwheel-sidecar.repl :as fig-repl]))

(defonce figwheel-opts
  {:http-server-root "public"
   :server-port 3449})

(defonce figwheel-server
  (fig/start-server figwheel-opts))

(defonce builds
  [{:id "dev"
    :compiler-env (env/default-compiler-env)
    :source-paths ["src/cljs"]
    :compiler {:output-to  "resources/public/js/app.js"
               :output-dir "resources/public/js/out"
               :source-map "resources/public/js/out.js.map"
               :main       "figwheel-piggieback-example.core"
               :asset-path "js/out"}}])

(defonce build (fig-auto/autobuild* {:figwheel-server figwheel-server
                                     :builds builds}))

(defn repl []
  (piggieback/cljs-repl :repl-env (fig-repl/repl-env figwheel-server (first builds))))
```

The main gotcha is to include `:compiler-env` in the build config, so it's shared between the build and the REPL.

@bhauman Austin bundles piggieback, and conditionally uses either `cemerick.piggieback/cljs-repl` or `cljs.repl/repl` dependent on whether it is running in an nREPL environment or not (see [here](https://github.com/cemerick/austin/blob/master/src/clj/cemerick/austin/repls.clj#L48)). Would you consider doing something like this? 

Then the lein plugin and nREPL users could both use the `figwheel-sidecar.auto-builder/run-autobuilder` entry point, making the experience between the two much closer (e.g. the figwheel-specific REPL special functions). This would also mean the plugin doesn't need to run an nREPL server itself - users can provide that separately (via lein repl/CIDER/fireplace/etc.), and run figwheel on top of it.

**Comment by bhauman** [comment]
@cichli I think I will change the api so that you can use what ever cljs repl you want.

**Comment by ilazarte** [comment]
great work!

**Comment by bhauman** [comment]
@cichli alright I just used the piggieback Figwheel combo and it's working pretty darn well. I'm gonna take a stab at it.

**Comment by Gonzih** [comment]
Is there any example of how to integrate piggieback with nrepl that figwheel provides?

**Comment by bhauman** [comment]
https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

If you look at the source for cljs-repl it configures piggieback.

**Comment by Gonzih** [comment]
@bhauman 
thanks, I will use this as a starting point!

**Comment by Gonzih** [comment]
@bhauman 
I think I kind of figured it out, but now I'm a bit confused on how to use this integration with vim-piggieback. Looks like piggieback expects middleware to be loaded in the repl and does repl initialization on its own...

**Comment by bhauman** [comment]
I have never used vim-piggieback.  Um there has to be a way around that.
Also, the landscape is going to change here really soon right? I'm going to
try and have figwheel working with the latest stable nREPL solution that is
coming down the line.
