### ISSUE TITLE
config pattern match is too strict

### ISSUE THREAD

**Issue by yayitswei** [bhauman/lein-figwheel#82]
This error:

```
Figwheel Config Error (in project.clj) - your build :output-dir is not in a resources directory.
It should match this pattern: (dev-resources|resources)/public
```

seems overly conservative. For example, I'm trying to build into `resources/private`, an access-controlled directory.

**Comment by bhauman** [comment]
I totally agree. This is fixed in the next version of figwheel which will be out soon.

**Comment by bhauman** [comment]
The latest release should fix this.  When you get a chance try it out and let me know if its working for you.

**Comment by yayitswei** [comment]
Works! Thanks @bhauman
