### ISSUE TITLE
nrepl support

### ISSUE THREAD

**Issue by Gonzih** [bhauman/lein-figwheel#83]
Hi, I just updated my project to latest figwheel version and it feels very nice to have repl built in! Great job! But what would be better is to also have nrepl support. Is it possible to hook up something like piggieback to figwheel? Thanks.

**Comment by t3chnoboy** [comment]
See https://github.com/bhauman/lein-figwheel/issues/81

**Comment by Gonzih** [comment]
ok, thanks!
