### ISSUE TITLE
:ring-handler only for static files

### ISSUE THREAD

**Issue by bensu** [bhauman/lein-figwheel#84]
Hi Bruce,

Why is the `:ring-handler` option only for static handlers?

I could trace the code back to [this](https://github.com/bhauman/lein-figwheel/blob/8579f73499ed73252823fdfeb857a2e14dadf6f9/sidecar/src/figwheel_sidecar/core.clj#L137) but I don't understand why you made that choice.

Thanks!

**Comment by bhauman** [comment]
It's not only for static handlers. I'm not sure why you're asking this?

**Comment by bensu** [comment]
Oh sorry! I read this from the README:

The inclusion of a static file server allows you to get a decent ClojureScript development environment up and running quickly. For convenience there is a :ring-handler option so you can load a ring handler into the figwheel server.

and then none of my PUT or POST request would get through! That is why I thought it was only static

**Comment by bhauman** [comment]
I am guessing correctly that you were loading your app from the file system, and then trying to make CORS requests to your ring handler embedded in the figwheel server? I didn't think anyone would do that :)  I may as well open up those CORS requests.

**Comment by bensu** [comment]
I was actually loading the app from localhost:3449 but the PUT/POST requests wouldn't go through. It might have a been an error in my code. I have now changed it to use both ring and figwheel so it's no problem. If you are interested in this, I can try to reproduce a minimal version that reproduces the problem and get back to you.

**Comment by bhauman** [comment]
Hmmmmm, if there is a way for you do make a version that doesn't take too
much time that would be great!

But otherwise I'll just open up the CORS requests. :)

On Sun, Feb 8, 2015 at 2:46 PM, Sebastian Bensusan <notifications@github.com

**Comment by bensu** [comment]
I'll come back to you as soon as I get it.

**Comment by bensu** [comment]
Hi Bruce. [Here](https://github.com/bensu/figwheel-ring-handler) I have a minimal ring handler which works for GET requests but fails for POST requests. Use lein fighweel to run it and open the browser console in localhost:3449. You'll see the 200 for GET and 404 for POST. Is this kind of handler supposed to work?

**Comment by bhauman** [comment]
Thanks you for your help with this! Fixed and deployed to 0.2.3-SNAPSHOT
