### ISSUE TITLE
Cannot edit cljs files with figwheel running (Access denied)

### ISSUE THREAD

**Issue by julianjelfs** [bhauman/lein-figwheel#87]
I am finding that trying to run figwheel (initially via a vanilla chestnut installation) on windows 7 64 bit. The first time I edit a cljs file it works but I then cannot edit the file again immediately as I receive the error attached:

![image](https://cloud.githubusercontent.com/assets/86620/6130696/b94a2d76-b13e-11e4-97c4-c526fb5d3996.png)

At the this point the file is being used by the java.exe process and I can't save changes to it. I could well be doing something wrong but if anyone can tell me what I'd be grateful. 

PS -  I tried this on another windows machine as well and experienced the same behaviour.

**Comment by bhauman** [comment]
This is probably because of file polling.  Going to move to a filesystem watch event soon. That should solve this. Sorry, for now a different editor or editor setting is all I can suggest.  But this gives file watch events a higher priority.

**Comment by julianjelfs** [comment]
Oh ok. So you think the editor might make a difference? I was initially trying gVim and had the same issue. I think I also tried notepad++ as well as sublime 3. Nevermind, I shall keep an eye out for an update. Thanks.

**Comment by bhauman** [comment]
Really weird stuff. You are trying a vanilla lein new figwheel hello-world project?

**Comment by bhauman** [comment]
Actually, does `lein cljsbuild auto` work?

**Comment by julianjelfs** [comment]
Ah actually I just tried a plain lein new figwheel and it's working fine on its own. The thing that is not working for me is a plain *chestnut* install when I have figwheel running. So I guess it is some interplay between figwheel, weasel, om etc. Anyway - apparently not a clear cut problem with figwheel so I guess I will close this issue and see if I can work it out. Thanks for the help.
