### ISSUE TITLE
figwheel slow - compiling transitive dependencies?

### ISSUE THREAD

**Issue by tablatom** [bhauman/lein-figwheel#88]
My blissful figwheel workflow has taken a sharp turn for the worse recently with changes taking 20 or 30 seconds to load instead of 1 or 2.

It seems that when I save changes to a file, not only that file but also all those that transitively depend on it are recompiled. I get "notifying browser that file changed" messages for a bunch of files.

I recently upgraded both figwheel and ClojureScript to the latest (0.2.3-SNAPSHOT and 0.0-2814 respectively), so it could well be that this is an issue with ClojureScript and not figwheel.

As well as the long compile time, after the "Successfully compiled ... in ... seconds" message, there is another considerable delay before the files are sent to the browser.

**Comment by bensu** [comment]
Which version did you upgraded from? It probably has to do with [incremental](https://groups.google.com/forum/#!topic/clojurescript/FoiqNV5nunQ) [compilation](https://github.com/clojure/clojurescript/blob/master/changes.md#fixes-4). If you change `ns x`, now ClojureScript recompiles all the namespaces that depend on `x` which would explain a total recompilation if you edit a very "required" ns, i.e. a utility. I don't have a solution, but I'm also looking for one :)

**Comment by swannodette** [comment]
ClojureScript now recompiles dependent namespaces by default. It has also recently exposed a `:recompile-dependents` knob which can be set to disable the new behavior.

**Comment by bensu** [comment]
Thanks! That was exactly what I was looking for. After I play with it, I'll try to document it in the compiler [wiki](https://github.com/clojure/clojurescript/wiki/Compiler-Options).

**Comment by bhauman** [comment]
Setting `:recompile-dependents` to `false` in your `:compile` options will be very helpful if your transitive dependents are taking a long time to compile.

**Comment by tablatom** [comment]
Setting `:recompile-dependents false` has done the job for the compilation step - back down to a second or two (are there any gotchas when this feature is disabled?).

However the long delay between compiling and "notifying browser..." is still there. This seems to also be related to transitive dependencies. After saving a change to a widely required namespace, compilation is quick, there is then a long delay (over a minute in some cases), and finally figwheel notifies the browser about the changed namespace *and* all the (unchanged) dependent namespaces

**Comment by swannodette** [comment]
@tablatom the gotcha is that changes to parent namespaces that would cause errors in dependent namespaces will go unnoticed. The current behavior of the compiler prioritizes correctness - it's a big step towards diminishing corrupted builds and subsequent `lein clean`s - this is a massive time waster in my experience. For figwheel where the short feedback loop is the primary point the advantage is less clear.

**Comment by bhauman** [comment]
tablatom, ah thats because figwheel is looking for changed dependents as well, this should be quick. 

Man I'd love to see the size of the codebase you are working on.

I will have figwheel honor the :recompile-dependents flag as well, I didn't think this was necessary.  

My computation of transitive dependents is memoized but maybe there is a bug in it.  I really need a larger codebase to test this on.  Maybe the CircleCi front end?

@tablatom rest assurred I'm gonna sort this out.

**Comment by bhauman** [comment]
I've just fixed this in master.  Master currently depends on the next release of ClojureScript.

**Comment by bhauman** [comment]
Alright, give fighweel 0.2.4-SNAPSHOT a try, it requires clojurescript 0.0-2843.

It should speed things up for you. Thanks for pointing this out to me.

**Comment by tablatom** [comment]
Works like a charm. Damn it's good to be back. Thanks so much for the rapid help (again!).

FWIW it's not _such_ a big codebase - around 6,000 lines (file lines not code lines). It's in 53 files though, I was slightly surprised to discover (never counted before). I was new to Clojure at the start of this project and was kinda in the Ruby mindset of small classes, one per file. I was pretty surprised when I first saw that clojure.core is just one huge file. As a result my `ns` forms tend to be pretty big.

**Comment by bhauman** [comment]
Yes I'm glad it works!!

**Comment by bhauman** [comment]
Actually, 

If you get a chance, could you do me a favor and set ` :recompile-dependents ` to `true` and tell me if the delay from compile to browser load has improved?  You have a unique code base to test this with.

**Comment by tablatom** [comment]
Yes that delay does seem to have got shorter. In one quick test it also seems to be notifying the browser of a much shorter list of changed files -- many are missing from the full set of dependent files. It's not just the direct dependencies either. I can't see an obvious pattern.

Why is it that figwheel would need to send unchanged files to the browser anyway? I understand dnolen's point about errors going unnoticed, but not the need to re-send those files to the browser.

**Comment by bhauman** [comment]
This is interesting. I'll dig further on the list of dependencies.

Figwheel doesn't "send" the files. Just a list of file names and some meta data. The client can then decide what to load.

Thanks for checking this for me.

**Comment by tablatom** [comment]
The expensive bit seems to be calculating the list, so sending the content vs. sending a list is moot, no?

I'm just wondering in what case the client would need to know about the dependants.

**Comment by bhauman** [comment]
Yeah, this is only done in the case where `:recompile-dependents` is not false.  In this case I have to calculate dependents because those files have potentially changed.

**Comment by tablatom** [comment]
If I've understood correctly, the recompilation of dependents is only valuable for the errors and warnings. The JS emitted would be exactly the same wouldn't it? I may have this wrong, but the dynamic nature of ClojureScript should mean one namespace cannot not rely on compile-time certainties about another.

Not that there is any issue here for me - just trying to learn something : )

**Comment by bhauman** [comment]
The emitted js changes for sure.  But many of these changes are irrelevant like the names of scoped variables. There is something around :static-fns, but you wouldn't set :static-fns to true for a figwheel build.

https://github.com/clojure/clojurescript/wiki/Compiler-Options#static-fns

In optimizations :none the breaking changes are very very rare in my experience.
