### ISSUE TITLE
Lein checkouts

### ISSUE THREAD

**Issue by whodidthis** [bhauman/lein-figwheel#9]
Not sure if possible but would be cool if changes to projects in checkouts would be evaluated too and not need a F5.

**Comment by danielcompton** [comment]
cljsbuild now supports checkouts https://github.com/emezeske/lein-cljsbuild/pull/374#event-383608525. I tried updating figwheel to use the new SNAPSHOT version, but it didn't seem to work. I'm guessing that Figwheel will need some changes to support this?

**Comment by bhauman** [comment]
Figwheel really doesn't use cljsbuild for much anymore.  A change in cljsbuild isn't going to affect Figwheel.  Does the pattern mentioned above not work for you?

**Comment by bhauman** [comment]
When you are auto loading you want to be discerning about what gets autoloaded.

**Comment by danielcompton** [comment]
Ah right, that makes sense then. The pattern above does work, but it would have been nice (but nonessential) for checkouts to be picked up automatically.

**Comment by stumitchell** [comment]
We have be talking about this at our work and have identified this as a tooling pain point.
The trouble with changing the `:source-paths` is that you then need to then remove that path when the checkouts are not there anymore. 
When you use checkouts you don't need to change the `project.clj` file so it would be much better for us it figwheel picked up changes in these files automagically.

**Comment by stumitchell** [comment]
Can you reopen this enhancement so that someone can provide a pr
