### ISSUE TITLE
Ctrl-C to cancel, Ctrl-D to exit

### ISSUE THREAD

**Issue by lambdahands** [bhauman/lein-figwheel#96]
Related to #75, it would be nice if the REPL cancelled commands with `Ctrl-C` and exited with `Ctrl-D` (just as `lein repl` does).

**Comment by bhauman** [comment]
This is a nice to have that would require a disproportionate amount of work.

Not gonna be only the table any time soon.

**Comment by lambdahands** [comment]
Ah, good to know. I can close this out then!

**Comment by venantius** [comment]
I would also love this, if only because I regularly find myself hitting `Ctrl-C` out of habit of so much time on the leiningen REPL and unintentionally killing my Figwheel process.
