### ISSUE TITLE
Stop Figwheel Server

### ISSUE THREAD

**Issue by felipecc** [bhauman/lein-figwheel#98]
I have used the Component Stuart Sierra to make my development environment. Sometimes I need to restart my HTTP server, however when the server restarts I get the message that the port is in use and is not the HTTP server port, but the default port (3349) of Figwheel. Is there a way to stop the Figwheel server?

I'm sorry for bad English.

**Comment by cichli** [comment]
Are you calling `start-server` directly? The return value of that is a function that you can call with no arguments to stop the server.

**Comment by felipecc** [comment]
No, I'm calling as follows:

(lein/-main ["figwheel"])

**Comment by felipecc** [comment]
It would be interesting if the call to the run-server was idempotent in function server the namespace figwheel-sidecar.core
